backend/app/exporters/serializers/ead.rb

When exporting EAD, tag repository image_url with an @id so it has a unique xpath.
see: http://lyralists.lyrasis.org/pipermail/archivesspace_users_group/2015-February/001113.html

tag image_url in ead export

---

backend/app/exporters/serializers/ead.rb

This one might not be as uncontroversial as the last, but I'll suggest it anyway. 
Export the repo.url as a exptr link in addresslines. 
( Is there any better place to put it ? )

add repo.url to addresslines

---

common/advanced_search.rb
common/search_definitions.rb

Just two little changes to advanced search:
* Throw a better error message if a search includes an unrecognized field
* Make system_mtime and last_modified_by searchable via the API

Advanced search fields

---

frontend/app/assets/javascripts/linker.js

Hi @cfitz, @quoideneuf,
This little patch allows for the linker's Browse form to be delivered as a POST request rather than assuming GET. Due to the default 4kB limit on GET request data (Jetty), there are some cases when the form search data can grow quite large, namely when including other linkers as search filters (these deliver both the record's URI and _resolved json to esnure the linker is kept in sync).
The patch is to the linker.js javascript and allows the target form to define the preferred method (POST || GET).
Thanks! Hope you guys are well.
Payten

Allow for a linker's Browse form to be delivered as a POST request 

---

frontend/app/helpers/application_helper.rb

The batch import endpoint seemed to pass through an object ID for its
breadcrumb label, which failed when the HTML sanitizer got called on a
Fixnum.  Coerce the title into a string before sending it along.

Make sure our breadcrumb trail label is always a string.

---

backend/app/controllers/component_add_children.rb
backend/app/model/mixins/tree_nodes.rb
backend/spec/tree_position_spec.rb
frontend/app/assets/javascripts/tree.js.erb

After reviewing the drag/drop code for reordering trees, I noticed a few issues that can cause the ordering to end up a little crazy.  There are a few fixes here:
* When the user selects multiple nodes and drag/drops them, the backend needs to be careful to interpret the target position correctly.  If moving nodes from top to bottom, it needs to apply the moves backwards to get the final ordering right.  Yep.
* The tree_node.rb code was incorrectly sending out the DB's view of the "position" property, which was not the same as the absolute position the frontend was expecting.  Big comment on this and some test cases added.
* The drag/drop code in the JS needs to compensate for the case when one or more nodes is dragged from top to bottom (i.e. where the target index is below the nodes …

Tree ordering fixes

---

backend/app/model/mixins/notes.rb

Hi there,
Just a small change arising from talking to an institution who noticed slow performance when loading one particular record.
When we try to resolve the references in `note_index` records, we do the DB lookup even when the reference hasn't been filled in.  As a result, we're doing an awful lot of pointless queries in cases where there are a large number of `note_index` notes without references.

When resolving note_index linkages, don't waste time looking up NULL records

---

backend/app/converters/lib/xml_sax.rb

I have an EAD record that seems to go into a spin on the regexp check
when imported.  I didn't dig into why that was (the stack trace showed
it stuck deep within JRuby's regex engine) because it seemed easier just
to get rid of the regular expression.
I think this implementation should have the same effect, and it roughly
halved the time taken to import hornstein.xml in my tests.

Remove regexp match on XML source.

---

backend/app/model/ASModel.rb

Hi there,
I've been running a migration from AT and watching the memory usage as it runs, and I noticed memory filling up when importing large trees of records.
After some searching I eventually worked out that the leak was in Sequel itself. There are two model hooks we've never used: `after_commit` and `after_rollback`. You can define them on your `Sequel::Model` subclasses and they'll be called when an object you call `.save` on has been committed by the underlying transaction.
Even if you don't use those hooks, Sequel pushes some empty `after_commit` and `after_rollback` proc objects onto the transaction's own "after" hook. And although those proc objects won't do anything, they create closures that capture the current lexical scope, and that lexical scope includes all of the values …

Set `use_after_commit_rollback` to false on Sequel::Model classes.

---

frontend/app/controllers/application_controller.rb

there's probably a better solution for this but for now this will do it. resource merge errors are causing the templates to break.

quick fix to catch hashed errors that choke the template

---

backend/app/exporters/lib/exporter.rb
backend/spec/export_spec_helper.rb

If a site supplies their own locale files and sets AppConfig[:locale]
to something other than :en exports will fail with an error such as:
(InvalidLocale) :en is not a valid locale
Setting enforce_available_locales to false is an expedient way to not
trip up over any arbitrary user added / configured locales in the exporter.

Do not enforce available locales in exporter

---

backend/app/model/solr.rb
common/config/config-defaults.rb

Retain the default value for `facet.limit` but allow it to be configured according to preference / to combat facet sprawl.
Related to: https://archivesspace.atlassian.net/browse/AR-1146

Configurable facets limit for solr queries

---

public/app/assets/javascripts/application.js
public/app/assets/javascripts/facet.js
public/app/views/layouts/application.html.erb
public/app/views/search/_filter.html.erb
public/config/locales/en.yml

In the public UI (where lengthy facet lists tend to produce a long scroll-y interface i.e. http://sandbox.archivesspace.org:8081/search?type=resource) display up to the first 10 values then offer a "Show more" option (with a subsequent "Show fewer" link).
Related to: https://archivesspace.atlassian.net/browse/AR-1146

Show top 10 facets with link for more

---

frontend/app/views/layouts/application.html.erb

This aligns the content centrally and provides a more flexible base
to build on without having to override application.html.erb in a
plugin.

Make container fluid for main wrapper div

---

backend/app/controllers/component_add_children.rb
backend/app/model/mixins/tree_nodes.rb

I'm looking for a second and third set of eyes.  After the last update, we continued to see re-ordering issues where gaps exist within the position trees.  To address this, I've taken a look at the two files that appear to be most responsible for ordering tree nodes, those being backend/app/controllers/component_add_children and backend/app/model/mixins/tree_nodes.  
I tested this against datasets where I was seeing the component trees falling out of order and at this point, I'm not seeing the problems any longer.  However, I have some questions about if this method is scaleable or if the changes would cause other issues further down the program.
As a secondary -- the current build, we are seeing errors generated when creating new records and creating the component list.  We are seeing …

Proposed changes to address reordering issues

---

backend/app/exporters/serializers/ead.rb

fix for https://archivesspace.atlassian.net/browse/AR-1202 
Finding aid date only exported in EAD if Repo has an image URL

https://archivesspace.atlassian.net/browse/AR-1202

---

backend/app/lib/bootstrap.rb
common/db/migrations/037_generalized_job_table.rb

Sequel 4.x ships with core_extensions turned off by default, so we lost String.to_sequel_blob and thus broke migrations/utils.rb#blobify

#finish turn on Sequel core_extensions

---

frontend/app/assets/javascripts/jobs.show.js

When hitting an error in an import job, the error message has some angle brackets in there and they are misinterpreted as an element:
This little patch adds the log data to a &lt;div&gt; as text so the angle brackets (and other bits and pieces) are escaped accordingly.

Escape log data when appending to the spool

---

frontend/app/assets/stylesheets/archivesspace/form.less
frontend/app/views/reports/index.html.erb

Hi guys,
We've been creating a few of the ArchivesSpace reports and ran into a little issue whereby a report needed to define more than 1 parameter for them to be rendered in the frontend.  This patch allows 1 param to now display nicely.
I've also added the ability for a report `String` param to define an optional enumeration setting.  So when a enumeration type is detected in the frontend and a dropdown list is presented instead of a text field.  
I've also poked in a few new bootstrap 3 classes and some extra padding so it renders nicely.
Hope all is well!
Thanks,
Payten

Fix reports with one param not displaying and support an enumeration parameter

---

backend/app/model/db.rb
common/config/config-defaults.rb

Hi there,
Just a little change to fix an issue that bit us recently.  If you increase the number of indexer threads, it's easy to overwhelm the DB connection pool and have it run out of connections.
The old value of 10 was probably too conservative anyway, so I've doubled it and made the default setting allow an extra two connections for each indexer thread.  Totally unscientific, but I don't think there's any harm in increasing the limit anyway. :microscope:

Increase the number of allowed DB connections and have it grow automatically with the number of indexer threads

---

backend/app/controllers/agent_corporate_entity.rb
backend/app/controllers/agent_family.rb
backend/app/controllers/agent_person.rb
backend/app/controllers/agent_software.rb
backend/app/controllers/subject.rb
backend/app/lib/crud_helpers.rb
backend/app/model/mixins/agent_manager.rb
backend/app/model/subject.rb
backend/app/model/user.rb
backend/spec/controller_conflict_reporting_spec.rb

Hi there,
As a part of getting Yale's data migrated, we noticed that agents and subjects wouldn't remain linked to records when migrating multiple AT databases into a single ArchivesSpace instance.  This happens when the second incoming repository has agents and subjects in common with the first: the migrator tries to create those agents/subjects, but they conflict with the existing ones, fail to create and get skipped.
This change modifies the agent and subject endpoints to return the URI of the conflicting record when this happens.  That way, the AT migrator can be modified to link the incoming records to the already existing agents/subjects at the right moment.
I'm submitting a parallel pull request to the AT migrator for the other half of this, but there's no dependency ordering--the …

When an agent or subject conflict occurs, return the URI of the conflicting record

---

common/db/migrations/047_add_rights_statements_to_agents.rb

Migration 047 was making MySQL unhappy by dropping a column used as an FK and as a member of a uniqueness constraint. This drops the constraints before removing the column.

drop fk and constraint before dropping the column to make mysql happy

---

backend/app/lib/bootstrap.rb
backend/app/model/ASModel.rb

This relates to the fix for issue #143 
It turns out that during very large imports, relationships, agents and other non-ASModel classes get hit heavily enough for this to still cause problems.  I've moved the fix into `bootstrap.rb` to make sure it gets applied everywhere, and that fixes the case I'm seeing.

Disable use_after_commit_rollback globally, not just for ASModel.

---

backend/app/lib/batch_import_runner.rb

Hi there,
We've been working on some custom importers where the converter checks for the existence of records before they are imported.  This patch provides the converter with the same context as the importer, namely the job's repository and the user.  Within this context, the converter can now query the correct repository as it builds the JSONModel for import.
Thanks,
Payten

In the batch importer provide the converter with more context i.e. job's repo and user

---

common/config/config-defaults.rb
indexer/app/lib/indexer_common.rb

Hi there,
A small change here to ensure that the indexer doesn't timeout prematurely when Solr is busy.  Default the timeout to 5 minutes and made it configurable through config.rb too.

Add a larger timeout when talking to Solr (the default was 60 seconds)

---

frontend/app/views/events/_form.html.erb
frontend/app/views/linked_events/_show.html.erb

Hi there,
Just a small bugfix that crops up when you link an event to an accession record that doesn't have a title.  The system blows up when it gets back a nil.  Fixed to use the display_string in preference to the title...
Cheers,
Mark

Cope with records that don't have titles (but do have display_strings)

---

frontend/app/assets/javascripts/subrecord.crud.js

This patch ensures the immediate subrecord-form-list is targeted when initialising the show-all link.
This fixes an issue whereby a nested list within a subrecord has items hidden but the show-all button is disabled and those items cannot be viewed.
To reproduce, add a Rights Statement to an Accession with more than 4 External Documents.  After save, the "Show All" button is displayed on the Rights Statement header and also at the end of the External Documents listing.  The latter causes the page to refresh.
If the subrecord is a one-to-one to the parent record, the Show All button is disabled along with "Add" button (as seen on some plugin specific subrecords - I can't see an example in vanilla ASpace).

Fix show-all button not working for hidden nested subrecords

---

backend/app/lib/AS_fop.rb
stylesheets/as-ead-pdf.xsl

After recently being asked about custom branding for pdf exports I've
tested a number of instances including the ArchivesSpace Sandbox and in
every case I'm seeing, for example:
```
Completed 200 OK in 62.0ms (Views: 0.0ms)
Jul 15, 2015 12:08:13 PM org.apache.fop.events.LoggingEventListener
processEvent
SEVERE: Image not found. URI: archivesspace.small.png. (See position
71:-1)
...
```
Looking at `AS_fop.rb` a workaround was implemented to pickup
`as-helper-functions.xsl`. Applying that same approach for the "icon"
(logo) works around the issue for this as well. Supports user supplied
files / filenames in the stylesheets directory for the icon.

Fix pdf export "image not found"

---

backend/app/model/ASModel_crud.rb
backend/app/model/db.rb
backend/app/model/mixins/relationships.rb
common/db/migrations/057_add_db_indexes.rb

Hey @cfitz,
Here's a bundled up version of the changes we made after reviewing Yale's logs and configuration (in addition to the InnoDB tuning changes).  Give me a yell if I can clarify anything.
:wave:,
Mark
------
Several changes around database performance and error handling:
* Use Sequel's empty_array_ignore_nulls extension to avoid turning
.filter(:somecol => []) into 'WHERE somecol != somecol`.  MySQL does
a full table scan when it sees one of these.
* If a delete request catches a retriable deadlock exception, make
sure we retry the request.
* Force the join on the agent_software table to use the primary key
index.  Since agent_software usually only has one row, the MySQL
optimizer was skipping the index by default.  But when joining
agent_software to the (often very large) …

Incorporate results of Hudson Molonglo performance analysis of Yale's ArchivesSpace Instance

---

README.md
launcher/backup/lib/backup.rb

Add flag to include stored procedures and functions in backup.
This is needed since migration 055 (without it if you dump and
restore then the functions will be missing).
Add to docs for admins managing their own backups.

Dump routines in backup

---

common/locales/enums/en.yml

For collection management processing priority and status.
Issue is viewable at (08/26):
http://sandbox.archivesspace.org/digital_objects/8#tree::digital_object_8

Add missing key, value for default 'none' to enum locales

---

backend/app/controllers/users.rb
backend/spec/controller_user_spec.rb

Hi there,
While chatting with @helrond about session stuff I noticed that there's currently no endpoint to explicitly log out a session.  For the expiring kind they get cleaned up anyway, but for the non-expiring kind there's currently no way of removing those sessions from the database.
I've added and endpoint so that people writing scripts have the option of logging out once they're finished, and there's a small test to go with it.
Mark

New endpoint for logging out a session explicitly

---

indexer/app/lib/periodic_indexer.rb
selenium/spec/collection_management_spec.rb

Records with children from the indexer point of view (such as collection
management records) get special treatment:
https://github.com/archivesspace/archivesspace/blob/ec5762fc9d4b1835181b79c06f69c23e49721047/indexer/app/lib/indexer_common.rb#L557-L569
The child records (if any) are deleted then recreated during the index
process. However the delete step makes the child records available via
the `delete-feed` endpoint, so they are re-deleted after being recreated
when a record is updated =)
This fix filters out the records with children from the delete feed
results, preventing the periodic indexer from acting on them. Without
this fix the updated collection management test fails.

Prevent periodic indexer from gobbling up records with children

---

frontend/app/assets/javascripts/update_monitor.js
frontend/app/views/layouts/application.html.erb

Trigger a redirect to the welcome index action when the user
session has expired during polling. This suppresses the
potentially massive amounts of AccessDeniedException spam
that comes from an expired session in edit mode (which we
see a lot).
If the user had no changes they will be redirected. If the user
had unsaved changes the confirmation navigation alert is
activated. This gives the user a chance to "stay" and attempt
to save their changes after reauthenticating. The alert blocks
polling so it also prevents spam AccessDeniedException messages.

Session expired during edit poll redirect

---

backend/app/exporters/models/marc21.rb

Hi there,
I noticed if a record doesn't have a language set, it throws an exception when you try to export it in MARC format.  Here's a little patch to use the `|||` code to indicate that there's no language coding there.

Modify the MARC model to cope with missing languages

---

common/db/migrations/053_collection_management_redo.rb
common/db/migrations/058_ensure_agent_links_have_agents.rb
common/locales/enums/en.yml

This modifies migration 053 to fall back to using ASpace's agent record when creating Event records from Collection Management records if the last modifying user no longer exists or doesn't have an agent record.
There's still an assumption that the install hasn't had it's ASpace agent record deleted. Perhaps this record should be undeletable?

AR-1320 #finish assign ASpace as the agent in a null agent relationship

---

common/db/migrations/043_add_phone_numbers_to_agent_contact.rb

I think the addresses the issue KU had migrating from 1.2 to 1.3. I chose to just move the extension data into the main telephone field if the former has data and the latter doesn't. ¯_(ツ)_/¯

move telephone_ext to telephone if the latter is nil

---

frontend/app/controllers/classifications_controller.rb
frontend/app/controllers/digital_objects_controller.rb
frontend/app/controllers/resources_controller.rb
selenium/common/webdriver.rb
selenium/spec/trees_spec.rb

there's some odd things that happen sometimes that the JS doesn't like when moving objects around at the top level. Some browsers don't seem to mind...also it seems to matter if the app is packaged or in devserver mode. Uh..this double checks what's being requested to the frontend.

AR-1183 another bug fix for certain conditions on moving things around

---

backend/app/converters/ead_converter.rb

Fix for #326
Since since we're moving ```<langmaterial>``` handling elsewhere, and since ```<langmaterial>``` is the only tag in the (abstract langmaterial materialspec physfacet) list that can legally have a ```<language>``` subtag, we can also clear out the language tag removal code in that block.

[ead import] - fix primary language of material handling

---

backend/app/exporters/serializers/ead.rb
backend/app/exporters/serializers/marc21.rb

Howdy,
As a part of some work with Dartmouth, I've extended the EAD and MARC exporters to give a spot for plugins to add extensions (adding new EAD tags and extra MARC control/data fields).  You can see how I'm using them here:
https://github.com/hudmol/dartmouth_udf_exports/blob/master/backend/lib/ead_user_defined_field_serialize.rb#L5
https://github.com/hudmol/dartmouth_udf_exports/blob/master/backend/lib/marc_user_defined_field_serialize.rb#L54
Does this seem general purpose enough to merge in?
Thanks!
Mark

Add support for extended EAD and MARC exports

---

frontend/app/assets/javascripts/rde.js

In developing the "visible external IDs" feature, which displays a &lt;table&gt; of the record's external IDs on both the readonly and edit screens of the record, we hit a JavaScript error when trying save and apply RDE templates.  This patch is a simple fix to ensure the RDE JavaScript targets the RDE table, instead of the first table in the DOM, which could sometimes be the External IDs table.

Ensure RDE template JavaScript targets the RDE table

---

backend/app/exporters/lib/exporter.rb
backend/app/lib/aspace_i18n.rb
backend/app/lib/bootstrap.rb
common/aspace_i18n_enumeration_support.rb
frontend/app/helpers/aspace_form_helper.rb
frontend/config/initializers/i18n.rb

Here are some changes to I18n translations for enumerations that have come up while working with @jdshaw at Dartmouth.
A couple of changes around this:
* Modified the backend to support the same method for looking up
enumeration values (which might contain dots and other interesting
characters).  Pulled the code that handles this out from the
frontend initializer and into a common spot that both backend and
frontend can use.
* Have the backend load any plugin-supplied I18n yml files.
Previously it was only looking at the distribution defaults.
* Modify aspace_form_helper.rb to use the custom enumeration syntax
when resolving enumeration values.  Ensures that enumeration values
containing dots still get translated correctly.

Enhancements to I18n handling when dealing with enumerations

---

README.md
build/build.xml
build/scripts/checkindex.rb
launcher/scripts/checkindex.bat
launcher/scripts/checkindex.sh

Potentially useful for verifying backups and checking that an index is OK post-rebuild.  I've tested this under Linux & Windows 8:
$ scripts/checkindex.sh $as/build/solr_index/index/
Opening index @ /home/mst/projects/archivesspace/build/solr_index/index/
Segments file=segments_b numSegments=2 version=4.0.0.2 format= userData={commitTimeMSec=1443996386948}
1 of 2: name=_0 docCount=1
codec=Lucene40
compound=false
numFiles=10
size (MB)=0.004
diagnostics = {os=Linux, java.vendor=Oracle Corporation, java.version=1.8.0_31, lucene.version=4.0.0 1394950 - rmuir - 2012-10-06 03:00:40, os.arch=amd64, source=flush, os.version=3.16.0-4-amd64}
no deletions
test: open reader.........OK
test: fields..............OK [16 fields]
test: field norms.........OK [6 fields]
test: terms, freq, prox...OK [41 …

Add a new "checkindex" script for invoking Lucene's CheckIndex tool

---

backend/app/controllers/users.rb

Just a small change to ensure we return a sane 200 response when logging out a session.

Return a 200 HTTP response and an indicator of what happened

---

backend/app/controllers/id_lookup_controller.rb
backend/app/model/idlookup.rb
backend/spec/controller_idlookup_spec.rb
common/asconstants.rb
common/db/migrations/060_index_id_lookup_fields.rb

Hi there,
This is based on some work that Hudmol is doing with Artefactual to help them with their integration between Archivematica and ArchivesSpace.  I've added some new endpoints that will ultimately be used by Rockefeller and Bentley.
I've popped in a few unit tests and have also added some new DB indexes for these columns.  I bumped the migration counter in asconstants.rb too--hopefully that was the right thing to do :)
Thanks,
Mark
-----
This commit adds some new endpoints to be used by the integration
between ArchivesSpace and Archivematica.  They allow you to provide
either a ref_id or a component_id and get back a list of matching
Archival Objects or Digital Object Components.

Add support for new "ID Lookup" endpoints.

---

frontend/app/views/enumerations/_list.html.erb

Avoids problems when the enumeration value contains dots.

Use the hash syntax when translating enumeration values in the listing.

---

backend/app/converters/ead_converter.rb
backend/spec/lib_ead_converter_spec.rb

Refs #328 
unitid content should not be rewritten on import, particularly in ways
that might produce the same value for different unitid values, e.g.
- "this.id" != "this/id"
- "not_the_same" != "not-the-same"
Note that the fix and test are pretty naive - if there is other stuff
depending on the textual structure of id_0, this will cause problems.

Fix for #328 - Removes gsub from unitid handling

---

backend/app/converters/ead_converter.rb
backend/app/exporters/examples/ead/at-tracer.xml
backend/spec/lib_ead_converter_spec.rb

JIRA references: [AR-1134](https://archivesspace.atlassian.net/browse/AR-1134), [AR-1270](https://archivesspace.atlassian.net/browse/AR-1270)
We (at the Bentley Historical Library) wrote up a local fix for these issues, and thought we'd pass it upstream. Happy to refactor / edit if anything seems off!
Previous behavior: given an EAD containing the physdesc below, the ASpace EAD importer would separate the ```<physfacet>``` and ```<dimensions>``` tags into individual ASpace notes, removing them from their intended context within the described extent. It also does not currently account for pre-designated altrenders on physdescs (corresponding to the "portion" attribute of an ASpace extent), instead assuming that all individual extents should be "whole" when imported.
This PR should account …

AR-1134 and AR-1270: account for all physdesc subtags in EAD import

---

build/build.xml

They are now available at:
https://github.com/archivesspace/archivesspace_tomcat

Remove tomcat scripts from build.xml

---

common/locales/enums/en.yml

While I was testing AR-825 I noticed a couple of other translation missing errors. This fixes those minor issues, but I also know this is an area of ongoing discussion. I'm not taking sides on the whole processing status as collection management vs. events discussion... 
Also, "Processed" is already on the list, so I don't really even know if we need "Processing Completed."

adding some translations to event_event_type

---

backend/app/converters/lib/xml_sax.rb

[AR-1421](https://archivesspace.atlassian.net/browse/AR-1421) fix. 
Encoding::InvalidByteSequenceError: ""\xE2"" on US-ASCII

https://archivesspace.atlassian.net/browse/AR-1421

---

backend/app/lib/background_job_queue.rb
backend/app/lib/batch_import_runner.rb
backend/app/lib/find_and_replace_runner.rb
backend/app/lib/job_runner.rb
backend/app/lib/print_to_pdf_runner.rb
backend/app/lib/reports_runner.rb
backend/app/model/job.rb

(I got nerd sniped)
@sdm7g did some analysis on some troubles he'd had with EAD imports and found that importing multiple files would cause an InnoDB lock timeout that would cause the import job to be marked as failed when it had actually succeeded.
Lock timeouts aside, this seemed like a bug, because the job status should really be set to 'completed' in the same transaction that commits the imported records.  I changed the job runner interface to allow jobs to call a `success!` method to mark the job as completed within the current transaction.  I've modified the existing job runners to call this method (although it's not strictly required).
In testing that, I hit the same InnoDB timeout issue when using multiple files.  The job watchdog thread (which just updates the timestamp on the …

Changes to avoid potential deadlocks when importing multiple files

---

backend/app/exporters/serializers/ead.rb
backend/spec/export_ead_spec.rb

Not sure this is the ideal solution, although I think it's probably a niche issue, but the problem being addressed is that handling linebreaks (via handle_linebreaks) with mixed content (that contains linebreaks) can in some cases produce invalid EAD / XML and therefore broken PDF generation.
It might be preferable to pluck out the linebreaks embedded in the mixed content (with a ugly regex?), but then again, it might not depending on local preferences (and there are so many variations on how data is entered and imported), so this approach just leaves the content alone if the generated markup is invalid.

Skip adding p tags when result is invalid markup

---

backend/spec/lib_digital_object_converter_spec.rb

This fixes a test broken by https://github.com/archivesspace/archivesspace/pull/381

tweak digital object converter test to ignore unrelated schema changes

---

backend/app/controllers/search.rb
backend/app/lib/base_search_params.rb

I'd also love to see the `aq` parameter documented in depth; I gleaned a bit from reading the source, but it would be very helpful to have it in the API docs.

API: document query string format

---

backend/app/converters/ead_converter.rb

I just made the following minor updates to the EAD importer:
- notes can be published upon import, unless they're set to internal only in the EAD
- single dates don't need to have their values repeated in the begin and end fields
- finding aid status is imported
I was also going to add an update that forced users to include the audience='external' attribute at the archdesc level in order to publish newly ingested finding aids immediately (line 113), but I commented that out and added the regular behavior back for now.
I'll hopefully dig into a few of the other updates requested here, https://docs.google.com/document/d/1wMGPDSdhfh3FsFZmJ3tngMWtmFNkRUHqwfFcxZp5Txk/edit, next week.

Ead importer updates

---

common/db/migrations/069_remove_childless_instances.rb

If the database is already using the new container model (via the RC, or latest / nightly build, or container management plugin) then instances not related to anything in "container" can be related to something in "sub_container" which trips up this migration. Does this look good?
@cfitz @quoideneuf

Check instance not linked to sub_container

---

frontend/app/assets/stylesheets/archivesspace/top_containers_bulk.less

Changes the tc bulk operations css to work with new version of tablesorter.

Updating CSS to work with new tablesorter

---

public-new/app/assets/javascripts/accordion-table.js

This is a one file, one line fix to handle the "click" event on an accordion widget correctly.  Fixes AR-1501

AR-1501 Allow FireFox users to open accordions

---

public-new/app/views/site/index.html.erb

Removed a duplication of the finding_aid_author token.  Fixes AR-1443

AR-1443 remove duplicate Finding Aid Author

---

public-new/app/controllers/trees_controller.rb

If the archival object had no containers, the trees_controller would throw a
>   [java] NoMethodError (undefined method `[]' for nil:NilClass):
>    [java]   app/controllers/trees_controller.rb:24:in `fetch'
This is because 
`node['containers'].length `
evaluates to **true** when the length == 0.

Handle empty node['containers'] correctly

---

public-new/app/assets/javascripts/records.js
public-new/app/controllers/concerns/tree_apis.rb
public-new/app/controllers/records_controller.rb
public-new/app/views/site/index.html.erb

The breadcrumbs are being created from information that's available through the indexer; I haven't been able to find any objects with [grand]parents that don't have titles, so I'm not sure what to do about the following comment in the story:
> Testing group should comment on how breadcrumb links appear for components that only have a date, no title, in their display string, especially once the inheritance story is delivered.

AR-1494 add breadcrumbs to CONTEXT for objects

---

plugins/aspace-public-formats/backend/controllers/public_formats.rb
plugins/aspace-public-formats/public/controllers/public_formats_controller.rb

Currently the aspace-public-formats plugin passes requests directly to the backend without checking if the record is published or not. It's possible to download all the resource/DO records if this is enabled. 
If a record is published, crawlers ( like Google )  can index the link and it will persist despite the record being unpublished.

security fix for aspace-public-formats plugin

---

backend/app/converters/ead_converter.rb
backend/spec/fixtures/ead_with_extents.xml
backend/spec/lib_ead_converter_spec.rb

Also extends the EAD import unit tests for extents based on provided
test data.

AR-1134 When a physdesc element just has a text child node, use it as a note

---

backend/app/exporters/serializers/ead.rb
backend/spec/export_ead_spec.rb

http://lyralists.lyrasis.org/pipermail/archivesspace_users_group/2016-July/003814.html
Could also try and do something to 1) fix markup problems with Nokogiri doing a to_xml and 2) stick the error messages in an XML comment so people know what to fix in their note content.

try to switch out & into &amp; in EAD export

---

build/build.xml

If a version of solr.war already exists and the solr version is updated (and bootstrapped), solr.war is not updated to the new version. Force it by overwriting (`war destfile="solr.war" update="true"` is not doing it). Adds a negligible ~2s to the build time.

Ensure the right version of solr is packaged

---

solr/schema.xml

Thanks to Mark Triggs:
Newer versions of Solr changed the way norms are implemented, and they
no longer require as much memory in most cases. However, since
ArchivesSpace doesn't really use norms anyway, there's no harm in
disabling them for the "sort_string" field type (used by AR-1027), and
that removes the need to target a specific version of Solr.

Disable norms for sort_string

---

frontend/app/views/archival_objects/_rde_templates.html.erb

Patch adds missing <col> so RDE javascript can calculate the correct table width for archival object rows.  This ensure the actions 'add row' and 'remove row' are visible.
Delivers https://archivesspace.atlassian.net/browse/AR-1424

AR-1424 fix add/remove row actions not visible on AO RDE

---

public/app/views/layouts/application.html.erb

See comments on commit for details. The template that outputs the APP_URL javascript variable in the public-facing interface appears to be using a wrong proxy prefix.

Fixed incorrect APP_URL in public interface template

---

plugins/newrelic/Gemfile

Hi there,
Just a tiny fix to the newrelic plugin to make sure it finds its gem when loading after a clean install.  Yale reported getting exceptions like this, which I could confirm locally:
```
Caused by: 
org.jruby.exceptions.RaiseException: (GemNotFound) Could not find gem 'newrelic_rpm (>= 0) java' in the gems available on this machine.
at RUBY.resolve(/mnt/ssd/tmp/aspace/archivesspace/gems/gems/bundler-1.7.12/lib/bundler/resolver.rb:368)
at RUBY.start(/mnt/ssd/tmp/aspace/archivesspace/gems/gems/bundler-1.7.12/lib/bundler/resolver.rb:166)
at RUBY.resolve(/mnt/ssd/tmp/aspace/archivesspace/gems/gems/bundler-1.7.12/lib/bundler/resolver.rb:129)
at RUBY.resolve(/mnt/ssd/tmp/aspace/archivesspace/gems/gems/bundler-1.7.12/lib/bundler/definition.rb:193)
at …
```

Run the ASpaceGems setup procedure to make sure newrelic can find its gem

---

backend/app/lib/print_to_pdf_runner.rb
backend/spec/model_print_to_pdf_job_spec.rb

The AR-1472 describes only allowing published content to be printed to PDF.   This change adds handling to the PDF job to show a message when a user attempts to print an unpublished resource.  This mimics the same behaviour when exporting EAD XML from an unpublished resource (it returns an empty XML file).  Tests have been updated accordingly.

AR-1472 only published resources can be printed to PDF 

---

backend/app/model/enumeration.rb
backend/spec/controller_enumeration_spec.rb
frontend/app/views/enumerations/_list.html.erb
selenium/spec/enumeration_management_spec.rb

Currently if a enumeration_value is suppressed, it will be deleted if the enumaration is
edited. They will disapear without the user knowing or throw an error if the suppressed
value is in use.
This removed the ability to delete suppressed values, ensuring they will be kept.

Fix auto-deleting supressed enumerations

---

frontend/app/assets/javascripts/header.js

The first row in the advanced search should only offer the 'op' NOT option. The patch fixes the JavaScript used to determine if a new row is indeed the first row so now subsequent rows offer all 'op' options.
Delivers https://archivesspace.atlassian.net/browse/AR-1387

AR-1387 fix advanced search rows not providing correct 'op' options

---

frontend/app/views/resources/_show_inline.html.erb

Oops... I fixed accessions but missed resources.

Don't show an empty classifications box for resources either

---

backend/app/lib/rest.rb

If a caller gives us a scalar when we expected an array of scalars, show
the correct syntax in the error message we return.

Improve endpoint parameter error reporting

---

backend/app/exporters/models/ead.rb
backend/spec/export_ead_spec.rb

So it finds agents in serialize_origination instead of getting a
surpising nil

Add a creators_and_sources method to the @ao class

---

frontend/app/assets/javascripts/rde.js
frontend/app/views/archival_objects/_rde_templates.html.erb

Safari and Firefox where not obeying the CSS width on `<col>` elements so I've changed to it all to use the more widely supported `width` property.
There was also a glitch in Safari whereby the table widths were not be reloaded from the cookie.  To fix I've flip the table's CSS property `table-layout` to `auto` and then back to `fixed` after applying all the widths.  This ensures the table is redrawn by the browser and all the new <col> widths are honoured. 
Delivers https://archivesspace.atlassian.net/browse/AR-1424

AR-1424 fix RDE column widths in all browsers

---

README_RELEASE.md
backend/app/main.rb
build/build.xml
common/asconstants.rb
common/db/db_migrator.rb
docs/user/building-an-archivesspace-release.md

It's pretty common to see test failures in branches due to the hard-coded migration number in ASConstants.  I think we can avoid needing to hard-code it by checking the migration files themselves.

Remove the need for a hard-coded migration number

---

backend/app/converters/ead_converter.rb

Removes useless line continuations from %w construct in importer.

Fixes #574 by removing pythonic nonsense continuations

---

backend/app/model/mixins/map_to_aspace_container.rb
backend/spec/controller_digital_object_spec.rb
backend/spec/export_ead_spec.rb
backend/spec/model_compatibility_spec.rb
backend/spec/model_instance_spec.rb
common/validations.rb

Currently if a digital object is deleted, it leaves behind an orphaned
digital object instance with no DO link (this should be fixed too).
Digital object instances with no digital object get filtered by
Instance.sequel_to_jsonmodel, causing a weird situation where the
database knowns about N instances but the JSON only contains N - 1.
This mismatch upset the container mapping code, which is silly because
it doesn't care about digital object instances anyway.  So, modify that
code to ignore them.
(includes a small fix for the EAD tests which were using digital object
instances without the digital object instance type)

Don't blow up if we hit orphaned digital object instances

---

.gitignore

Super trivial :smile: 
I use it locally pretty often. It would be a good idea to ignore it as we don't want to bundle it:
https://github.com/archivesspace/archivesspace/#download-mysql-connector

Ignore mysql connector [ci skip]

---

launcher/archivesspace.sh

this is required for the postrotate option in log rotate. Adding the restart option to the script removes the need for a helper script to call stop and start, or rebooting the server.

Add restart command to archivesspace.sh

---

backend/app/converters/ead_converter.rb
backend/app/exporters/lib/export_helpers.rb
backend/spec/export_ead_spec.rb
stylesheets/as-ead-pdf.xsl

https://archivesspace.atlassian.net/browse/AR-1614
If date type is 'single', don't attach a unitdate/@type attribute. ( it's neither 'bulk' nor 'inclusive' )
Also export date.certainty as unitdate/@certainty, and pass that thru the to pdf. 
On import: if no @type attribute and only a single value, make model type = 'single' , else 'inclusive' 
( unitdate/@certainty appears to map properly on import. )

Ar 1614 : fix handling of unitdate attributes on EAD & PDF export. 

---

backend/app/exporters/serializers/ead.rb
common/mixed_content_parser.rb

Archon doesn't do the AT feature of p's wrapped in double line breaks. This attempts to fix that.
https://groups.google.com/forum/#!topic/archivesspace/_SeaUbmnVXo

Double line break fix for Archon

---

frontend/app/assets/stylesheets/archivesspace/header.less
frontend/app/views/shared/_header_global.html.erb

This fixes the login for mobile. However, it looks like there's still a lot of other small errors with the responsive template in the ArchivesSpace theme ( like once logged in, the User narbar is not present ) 
But at least now people can login and see something when they get a link....

AR-1287 fixes login form for mobile/responsive

---

frontend/app/assets/javascripts/rde.js
frontend/app/views/shared/_rde.html.erb
frontend/config/locales/en.yml
selenium/spec/rde_templates_spec.rb

Delivers https://archivesspace.atlassian.net/browse/AR-1493 by changing the remove template form interaction to use checkboxes:
Also added a message if there are no template:
And added some locales for a few hardcoded strings.

AR-1493 change remove templates form to use checkboxes instead of buttons

---

frontend/app/assets/stylesheets/archivesspace/rde.less
frontend/app/assets/stylesheets/archivesspace/tables.less

Fixes https://archivesspace.atlassian.net/browse/AR-1296
Problem was due to conflict of background images on the RDE table cell.  Currently the mandatory star is a background image and so is the blue highlight applied for "sticky" columns.  To avoid the conflict, I've changed the required/conditionally-required CSS to apply the background image on the pseudo `:before` element of the cells.

AR-1296 fix RDE sticky styling on required columns

---

frontend/app/assets/javascripts/notes.crud.js

When clicking the "Click to load records" button on a resource record
containing many notes and some instances, the instances section would be
collapsed, never to be seen again.
The code used to initialize the notes section wasn't being properly
scoped, so it was applying to the entire form.  Modified this to only
apply to the notes in question.

AR-1413 Don't inadvertently hide instances

---

common/asutils.rb
frontend/app/controllers/application_controller.rb
frontend/app/controllers/system_info_controller.rb
frontend/app/controllers/users_controller.rb
frontend/app/models/user.rb
frontend/app/views/users/index.html.erb
frontend/config/locales/en.yml
selenium/spec/groups_spec.rb
selenium/spec/user_management_spec.rb
selenium/spec/users_and_auth_spec.rb

Summary:
Reduces the amount of system information available via the UI. Believe
this was added to help support remote installations, but it's including
too much (and I can't see that it's adding much value). As it's not
uncommon to have api keys and such in the environment it's possible to
inadvertently leak sensitive information.
Restricts access to system information so that only the global admin
account has access to it.
Makes it so only the global admin can edit the global admin and other
system accounts (otherwise any 'admin' user can do this by popping in
the path i.e. /users/2/edit).
Prevents any user from becoming the global admin. That account must be
logged into directly, making it the most privileged account in the
system (as it should be).
Prevents group assignment for 'admin' …

Security updates

---

backend/app/converters/lib/marcxml_base_map.rb

Delivers https://archivesspace.atlassian.net/browse/AR-1299
Slight variation on the original #601 PR.  We now simply remove the nested mapping for 610 and 611 fields so they are not duplicated as alternate names for other 610/611 fields in the MarcXML.

AR-1299 remove marcxml rules that add all 610 or 611 names into each generated corporate entity

---

frontend/app/assets/javascripts/subrecord.too_many.js

The root cause of the problems was a function like this:
function initNoteForms($container) {
...
$('.find-something', $container);
... more stuff
}
being called like this:
initNoteForms(function () {
... callback stuff...
})
The intention was for the callback to fire after the note forms were
initialized, but in fact the callback was firing first.
The problem was that $container should have been a JQuery
object (matching some DOM element), but instead it was a callback
function.  That function got passed as the second argument to
JQuery.find, which attempts to wrap it in a JQuery function (in case you
passed a naked DOM element, I guess).  Since this:
$(function () { whatever })
is a synonym for document.onready, the function was immediately
executed, and returned `undefined`.  And since …

AR-1413 Second half of fix for "too many" notes

---

frontend/app/views/file_versions/_image.html.erb
frontend/app/views/file_versions/_show.html.erb

I'm not sure if these are the original issues reported in [AR-1192](https://archivesspace.atlassian.net/browse/AR-1192) but they are seen in the last screenshot on that JIRA issue. ( Maybe original issue was something else. ) 
[1] label "File" is pushed against the right margin. 
[2] "File URI" is listed twice if file version is embeddable.

fix duplicate URI and text misalignment AR-1192 

---

frontend/app/views/external_ids/_show.html.erb

If external ids are a link to external system, display as links in frontend.  
[AR-1648](https://archivesspace.atlassian.net/browse/AR-1648?filter=-8)

display external ids as links in frontend if http(s): URL  [AR-1648]

---

public-new/app/helpers/application_helper.rb

Just a very small thing I came across while working on a new pui plugin. Can override, but seems better contributed ...

Use html_safe for message

---

common/locales/en.yml
frontend/config/locales/en.yml

As the Dates field is no longer deprecated, revises the tooltip to make this clear. Also addresses the immediate issue described in AR-1322, though the longer term implications and need to perhaps address this through the Agents module redo still apply.

AR-1344 update tooltip for non-deprecated Dates field

---

backend/app/model/large_tree.rb
backend/app/model/large_tree_digital_object.rb
backend/spec/common_mixed_content_parser_spec.rb
common/mixed_content_parser.rb
frontend/app/assets/javascripts/tree_renderers.js.erb
public-new/app/assets/javascripts/tree_renderer.js
public-new/app/assets/stylesheets/application.scss
public-new/app/assets/stylesheets/archivesspace/aspace.scss
public-new/app/assets/stylesheets/archivesspace/mixed-content.scss
public-new/app/views/resources/infinite.html.erb
public-new/app/views/shared/_children_tree.html.erb
public-new/config/initializers/assets.rb

Also fixes:
- the `MixedContentParser` was not whitelisting the elements we wished to convert (unit tests added)
- 'null' string in digital object component tree nodes when record didn't have a title (could have a label or date instead).  This was an issue in both the staff and public-new trees.
- 'null' string in archival object tree nodes when record didn't have a title. Due to missing date handling in the public-new tree renderer.
- br element causing newlines in the breadcrumb

AR-1483 better support mixed content in public-new trees

---

launcher/service.bat

ECHO statements for empty lines are incorrect causing "ECHO is off." to be shown in the output. `ECHO.` will cause an empty line to be output instead.

Fix blank line echo statements

---

frontend/app/views/archival_objects/_show_inline.html.erb

There are several JIRA issues relating to `<emph>` tags in title displays.
One issue with Mixed content with emph tags in resource titles has already been  fixed. 
This applies the same fix to archival_objects. 
`<emph>` tags still display in the large tree display. Fixing that prob. requires some javascript. 
Probably something similar required with new pubic collection organization panel.

fix emph on archival_object title display AS-210 and others

---

frontend/app/helpers/application_helper.rb

Fixes this message showing up here, there and everywhere:
```
[java] DEPRECATION WARNING: Method map is deprecated and will be removed in Rails 5.1, as `ActionController::Parameters` no longer inherits from hash. Using this deprecated behavior exposes potential security problems. If you continue to use this method you may be creating a security vulnerability in your app that can be exploited. Instead, consider using one of these documented methods which are not deprecated: http://api.rubyonrails.org/v5.0.1/classes/ActionController/Parameters.html (called from link_to_merge_params at /Users/payten/Development/archivesspace/pui/archivesspace/frontend/app/helpers/application_helper.rb:332)
```

Fix 'Method map is deprecated' warning in frontend

---

backend/app/controllers/component_add_children.rb
backend/spec/controller_component_add_children_spec.rb

The UI doesn't allow this, but the API shouldn't either.

Prevent a situation where a record's ancestor can become its child

---

frontend/app/assets/javascripts/largetree_dragdrop.js.erb
frontend/app/assets/stylesheets/archivesspace/largetree.less
selenium/spec/trees_spec.rb

Adds annotations to the selected rows for drag/drop showing the index of the row within the selection:
And update the drag helper to be a ordered list:

Add annotations to selected rows

---

public-new/app/controllers/resources_controller.rb

Fixes exception:
```
INFO: F, [2017-03-22T10:02:53.029966 #16957] FATAL -- : [d71e9a06-5977-45a2-a49c-6c1c30e0e083] NameError (undefined local variable or method `uri' for #<ResourcesController:0x135fe9d>
```

Fix NameError (undefined local variable or method uri) when SOLR record is missing

---

common/advanced_query_builder.rb
frontend/app/controllers/top_containers_controller.rb

Setting YES or NO to either "Exported to ILS" or "Unassociated containers" in frontend top_container search parameter yields error:
`JSONModel::ValidationException (#<:ValidationException: {:errors=>{"value"=>["Must be a boolean (you provided a String)"]}}>)`
Also note TODO note at top of 
https://github.com/archivesspace/archivesspace/blob/master/public-new/app/lib/advanced_query_builder.rb#L1-L4
However, I see diffs between version in common and version in public-new.
Don't know what's intended here.

booleans need to be booleans, not strings #issue 665

---

frontend/app/assets/javascripts/application.js
frontend/app/assets/javascripts/top_containers.bulk.js

Rails 4 introduced a new version of the "Unobtrusive scripting adapter for jQuery" which now disables form submit elements to help avoid double-click resulting in a double submission of the form. Weeeeee!
So we now have to reenable any ajax form submit buttons proactively (if we're not doing that already!).

Save us from eager disabling of buttons

---

backend/app/model/large_tree.rb
public-new/app/views/shared/_result.html.erb

Fix root title not parsed.
Fix results item breadcrumb ancestor not parsed.

AR-1675 EAD escaping in breadcrumbs / tree

---

frontend/app/assets/javascripts/largetree.js.erb
frontend/app/assets/javascripts/tree.js.erb
frontend/app/views/shared/_largetree.html.erb
frontend/config/locales/en.yml

If the user gets logged out behind the scenes, the next AJAX request
will fail.  Show a helpful message when this happens.

Add extra error handling to tree fetching

---

launcher/scripts/setup-database.bat

archivesspace base directory based upon the dp0 variable (which is the scripts directory) and going up one directory
@jambun Bug in setup-database.bat file

Set required and missing ENV variable ASPACE_LAUNCHER_BASE to the

---

frontend/app/assets/javascripts/tree_renderers.js.erb

Note: No SOLR reindex required for this one, as the staff interface hits the database directly.

AR-1683 expose the classification identifier in the staff interface trees

---

frontend/app/helpers/file_embed_helper.rb
frontend/app/views/file_versions/_file_uri.html.erb

The new behavior is:
* If we're looking at a HTTP/HTTPS url, return a URI object from the
helper and render a hyperlink in the UI.
* Otherwise, leave it alone
Previously there was some code in here to handle Windows
paths (turning them info file URIs), but it's not clear that this
still needed: the resulting file links don't get rendered in any
special way in the UI anyway, and if we wanted to fully support these,
we would need to handle spaces in filenames and other Windows
favorites.
More discussion in #702

Rework file embed helper

---

_yard/templates/default/fulldoc/html/full_list_schema.erb
_yard/templates/default/fulldoc/html/setup.rb
_yard/templates/default/layout/html/setup.rb

yard doc template fixes:
fixes search for schema list, and keeps it from reverting back to class_list after clicking item. 
Maybe there's a better way to do it, but I couldn't figure it out. 
( I did not push rebuilt docs with this patch. That's seems to be something that's usually done right before release. )

fix docs schema search and nav menu

---

backend/app/model/mixins/tree_nodes.rb
backend/spec/model_archival_object_spec.rb

@lmcglohon I think we can wait until post 2.0 for this, but just adding it in.
-------
If you're saving an archival object within Resource A, you shouldn't
be allowed to make it a child of a record in Resource B.  That's
silly.
Fixes #264 (at last!)

Add a consistency check when saving tree nodes

---

common/asutils.rb
common/config/config-defaults.rb

This allows for the plugins directory to be specificed in the
config.rb. If nothing is set, Aspace should use the 'plugins'
directory in the Aspace base.

Add ability to set plugins directory outside aspace base

---

common/config/config-distribution.rb

We would like to have the ability to be able to set the path to the
config.rb file as an env var. This add the ability to set
ASPACE_CONFIG and have it used as the path to the config.rb
file.

Add ability to make path to config.rb an env var

---

common/asutils.rb

If we're asked to dump diagnostics really early during startup, we
might not have our full set of dependencies loaded.  Make sure we have
ASConstants and JSON, since we need those.

Load ASConstants from ASUtils

---

backend/app/converters/lib/marcxml_base_map.rb
backend/spec/lib_marcxml_converter_spec.rb

… from Marc001 as it cannot be used as a unique id when there are multiple agents in the import.
Fixes https://archivesspace.atlassian.net/browse/AR-1643.

AR-1643 remove the MARC XML importer mapping for an agents authority_id

---

reports/accessions/created_accessions_report/created_accessions_report.rb

report because create_date is when it was added to the database, not when it was accessioned.
@jambun

Replaced create_date with accession_date for the created accessions 

---

frontend/app/controllers/application_controller.rb
frontend/app/models/user.rb

These can get quite large for users with a lot of repositories, and
compressing cuts the size down by a half or more.

Compress the 'permissions' cookie value

---

backend/app/controllers/id_lookup_controller.rb

Reported several times on Slack and a bit surprising from an API
standpoint that these weren't there.  Easy to add so here they are.

Expand find-by-id endpoints to include looking up Resource and Digital object records

---

backend/app/converters/lib/marcxml_base_map.rb
backend/app/exporters/examples/marc/at-tracer-marc-1.xml
backend/spec/lib_marcxml_converter_spec.rb

Make MARCXML import handle 610|710 with no $e or $4  to be imported as a 'creator' rather than 'subject' as per the mapping.
Defaults to 'creator' role for 610|710 mappings and adds a test.
Delivers https://archivesspace.atlassian.net/browse/AR-1625

AR-1625 Fix MARCXML importer mishandled 710s

---

public-new/app/models/archival_object.rb
public-new/app/models/record.rb
public-new/app/models/resource.rb

I missed a couple of cases in my first go at this:
- ref tags with attributes other than target
- ref tags in notes on resources, in addition to archival_objects

AR-995 more links

---

backend/app/model/archival_object.rb
backend/app/model/mixins/tree_nodes.rb
backend/app/model/mixins/trees.rb
backend/app/model/resource.rb
common/schemas/resource_ordered_records.rb
public-new/app/controllers/pdf_controller.rb
public-new/app/models/resource_ordered_records.rb

Only items up to 2 levels deep will be shown, and then only items with
an appropriate level of description.

Limit table of contents entries by depth and series

---

frontend/app/assets/stylesheets/archivesspace/toolbar.less
frontend/app/views/accessions/_toolbar.html.erb
frontend/app/views/extent_calculator/_toolbar_button.html.erb
frontend/app/views/shared/_component_toolbar.html.erb
frontend/app/views/shared/_resource_toolbar.html.erb
frontend/config/locales/en.yml
frontend/config/locales/es.yml
frontend/config/locales/fr.yml
selenium/spec/instances_and_containers_spec.rb

We're running out of space for more buttons!  Especially when plugins want to add their own.  I've added a "More" menu to give some of the less frequently used actions a place to live:
accessions: http://tsp.nz/s/a02cad2ded5ac5337252a2e4f4c289a9317aa302.jpg
resources: http://tsp.nz/s/b7842ea640b45849caa59f48b731e7f15eb3a353.jpg
archival objects: http://tsp.nz/s/87901ada3e0004cc9380b94b4f45e69e1f667c40.jpg

Refactor toolbars for accession/resource/archival object to show a "More" menu

---

backend/app/converters/ead_converter.rb
backend/app/exporters/serializers/ead.rb

Additional unitids are made into external_ids if they have a @type (external_id.source = @type)
On export, external_ids are exported as additional unitids with @type=source
https://archivesspace.atlassian.net/browse/AS-99
https://archivesspace.atlassian.net/browse/AR-1542
https://archivesspace.atlassian.net/browse/AR-1268

Handle multiple EAD unitids. First unitid is always primary one.

---

public-new/app/controllers/application_controller.rb
public-new/app/models/record.rb
public-new/app/services/archives_space_client.rb

Keep the ArchivesSpace session in memory and share it between all request threads.
If the session expires, get a new one.

Don't log in on every request

---

common/db/db_migrator.rb
common/db/migrations/064_container_management_warning.rb

Now that the container mapping code is gone, people upgrading from
1.4.2 or prior will need to first upgrade to 1.5.3 to get their
containers migrated.  If we notice someone trying to do this, give
them the lowdown.

Don't allow a direct upgrade from <= 1.4.2 to >= 2.1

---

backend/app/exporters/lib/streaming_xml.rb
backend/app/exporters/models/ead.rb
backend/app/exporters/models/labels.rb
backend/app/exporters/models/mets.rb
backend/app/exporters/models/mods.rb
backend/app/lib/export.rb
backend/app/model/mixins/trees.rb
common/db/migrations/087_reindex_anything_with_instances.rb
indexer/app/lib/indexer_common.rb

Be faster!  :racing_car:
On my dev machine, EAD export of Copland drops from 3 minutes to 40 seconds (assuming it's fully indexed).  Also remove the dependency on resource tree URIs from the various exporters.

Export performance

---

common/db/migrations/033_allow_null_id_1_and_indicators_container_table.rb

Remove the down block for migration 033 as the container table has been dropped and we are unable to recover from that

Fix travis.. again

---

launcher/archivesspace.sh

When deploying ArchivesSpace in my environment, I wanted to use SaltStack to ensure that the archivesspace service was running and to start it if it was stopped. This depended on a status option that provided a relevant exit code. This seemed like it could be useful to others, so I figured I would contribute it.

Adding a status option to the Linux init/launcher script

---

build/build.xml
indexer/app/lib/indexer_common.rb

In investigating indexer timeouts, we came across a few bugs:
- the timeout for indexer HTTP requests to SOLR was 60 seconds instead of the number set via the configuration option `AppConfig[:indexer_solr_timeout_seconds]`
- (development only) The Winstone servlet container, for SOLR, was not being passed the default set of JAVA_OPTS when run as a devserver.   This left Winstone with a minimal memory allocation.

Indexer timeouts

---

backend/app/model/implied_publication_calculator.rb

If a record belonged to an unpublished tree within an unpublished
repository, the tree check would be superseded by the repository check
and throw an error.

Correct implied publication when dealing with unpublished repositories

---

_yard/rakefile.rb
backend/app/controllers/container.rb
backend/app/controllers/location_profile.rb
backend/app/controllers/oai.rb
backend/app/lib/oai/aspace_oai_repository.rb

Two issues here:
* The new OAI controller was assuming that models would be loaded
before it was.  Normally this is true, but YARD turns out to load
controllers without also loading models.  Reworked the controller to
remove the load-time dependency on the models.
* The YARD code was loading controllers in arbitrary order, so I got a
different error to the one Laney saw.  Sort the list of files and
always load them in the same order to avoid these sorts of
surprises.

Fix doc:build target (fixes #834)

---

public/app/controllers/accessions_controller.rb
public/app/controllers/agents_controller.rb
public/app/controllers/classifications_controller.rb
public/app/controllers/concerns/searchable.rb
public/app/controllers/objects_controller.rb
public/app/controllers/resources_controller.rb
public/app/controllers/subjects_controller.rb
public/config/locales/en.yml

My last minute change to avoid putting raw exceptions into flash messages (and overloading the Rails session cookie) messed up the "No Search Results" message.  That message was relying on the exception being displayed to the user, but that no longer happens.
So, I've added a new exception type to allow us to distinguish between the "no results found" case and real search errors.  Now I catch those in the right places and display the message to the user.
I also needed to fix up my "unexpected error" I18N because another 'error' key in that file was taking precedence.

Show "No Search Results" found message

---

common/db/migrations/088_rights_management.rb

Fixes this error `Java::JavaSql::SQLSyntaxErrorException: Columns of type 'BLOB' cannot hold values of type 'CHAR'` caused when creating notes in the rights migration.  This bug only affected derby databases.

ANW-114 fix insert blob error in rights migration on a derby database

---

public/app/assets/javascripts/search.js.erb
public/app/assets/stylesheets/archivesspace/aspace.scss
public/app/controllers/concerns/searchable.rb
public/app/controllers/search_controller.rb
public/app/views/shared/_search.html.erb
public/config/locales/en.yml

So we now get something like this:
And the first row only ever offers 'NOT' as an operator.

AR-1826 clean up public search rows and allow the first row to use the NOT operator

---

public/app/views/shared/_record_innards.html.erb

The majority of the PUI record display is via the `record_innards.html.erb` template.  This change provides a standard way for plugins to append to this template, in both the "upper" section of the page and the accordion "lower" section.

AR-1628 allow record display to be more pluggable

---

public/app/assets/javascripts/search.js.erb
public/app/views/shared/_search.html.erb

AR-1826 expand columns in search form rows to squash any whitespace

---

common/db/migrations/091_enum_default_value_fk.rb

It is possible to delete / merge a controlled value that was set
as a default (particularly where the value is used by multiple
enumerations) and this crashes things hard.
So, leverage the database to ensure default value is set to null
if the value is deleted (which is a good thing regardless).

Set Enumeration default value to null when value deleted

---

backend/app/exporters/models/ead.rb
backend/spec/export_ead_spec.rb
common/db/migrations/092_reindex_anything_with_instances.rb
indexer/app/lib/indexer_common.rb
indexer/app/lib/indexer_common_config.rb

Hi @lmcglohon,
The fix here was pretty small: just needed to resolve container profiles in the indexer, so that the prefetched version (used by the EAD export) had the data it needed.
But I thought I'd address the more general problem of the EAD export implicitly depending on the indexer having resolved certain fields.  In that spirit, I've:
* Pulled the list of EAD resolve fields into a constant
* Pulled the indexer's list of resolved fields (and a few other lists) into a dedicated configuration class
* Written a new unit test to check that all of the resolves required by EAD are satisfied by the indexer's configuration
Hopefully that will avoid bugs like this one in the future.
Cheers,
Mark

AR-1842 Fix issue where EAD export (and OAI) would bomb on top containers with profiles

---

backend/app/controllers/preferences.rb

Issue: https://github.com/archivesspace/archivesspace/issues/879
calls to GET /repositories/:repo_id/preferences/defaults in current master ( v2.1.0-RC ) return "error":"undefined method `defaults_for' for Preference:Class\nDid you mean? defaults"

fix undefined method 'defaults_for' issue #879

---

backend/app/exporters/serializers/ead.rb

EAD: export multiple file versions of a digital object as  daogrp/doaloc  to match how EAD imports work.

EAD Daogrp fix: export multiple file versions as daogrp/daoloc 

---

public/app/controllers/concerns/handle_faceting.rb

Added this note to the JIRA issue:
> This got changed when trying to address overall search performance, since firing up an XML parser for every facet made things slow.
> I've put the XML parsing back in, and hopefully the other improvements we made to avoid doing a parse unless absolutely necessary will avoid too much of a slowdown. We'll have to keep an eye on it, though.

AR-1853 Reintroduce strip mixed content on facets

---

backend/app/converters/ead_converter.rb
backend/app/exporters/serializers/ead.rb

Issue https://github.com/archivesspace/archivesspace/issues/897
Titles were getting lost on roundtripping EAD import/export. 
Added mapping of  file_versions.captions  <-to/from-> (dao|daoloc)/@xlink:title. 
Also another minor change: when digital object titles are inherited from archival object display_strings, strip out the markup. Before this we were getting lots of letters titled  <persname ... /> to <persname ... />

more fixes to EAD export/import: map file_versions.captions <-> (dao|daoloc)/@xlink:title  (issue #879)

---

common/config/config-distribution.rb

the local configuration file to be ignored

Undo Suppress useless already set config messages because is causes

---

common/config/config-defaults.rb

1. Extent should be inherited indirectly, not directly
2. “Language of Materials” section is populated from the “langmaterial” note which doesn’t have any inheritance config by default so it needs one.

Change inheritance defaults based upon request from Mark Custer and Christine di Bella

---

solr/solrconfig.xml

Solr was updated to 4.10.4 awhile but the solrconfig kept the luceneVersion to the
4.0. This is very suboptimal both in terms of perfomrance and amount of
disk space used.
During upgrade, it is important that the old index is deleted and
rebuilt from scratch.

Update the luceneMatchVersion to match with version of Solr

---

backend/app/model/large_tree_resource.rb
frontend/app/assets/javascripts/tree_renderers.js.erb

As per pre-v2.0.0, this change adds the digital object instance type to a column in the resource record's tree view.  Here's the logic from v1.4.2: https://github.com/archivesspace/archivesspace/blob/v1.4.2/frontend/app/views/shared/_tree.html.erb#L124
Delivers https://archivesspace.atlassian.net/browse/ANW-129

ANW-129 display the instance type for both digital object and container instances in the tree view

---

backend/app/lib/oai/mappers/oai_dcterms.rb

if public is running for oai dcterms

ANW-85 include the public url of the record in an identifier tag

---

build/build.xml

Add launcher_rc.rb to the zip file if it exists when a build is created

---

public/config/locales/en.yml
public/config/locales/fr.yml

Newer version of i18n ( 0.8.* ) gem freaks out if you try and interpolate a
variable that isn't set. This seems to be happening with the
'search-limit' label. Assuming that the variable is for the
'search-limiting' label, so this removed the 'limit' variable.
This is related to the issues with #925 / #896

Quit trying to interpolate 'limit' variable in search-limit i18n

---

public/app/views/shared/_result.html.erb

A better fix would be to always generate and add display_string to PUI index, but I'm putting this in as an interim fix. ( We may have accumulated enough bugs to warrant a 2.1.2 bug fix release soon, so this is in the queue if we don't get around to a better fix. ) 
https://archivesspace.atlassian.net/browse/AR-1869

ar-1869: defaults on fetch in case of no title

---

common/db/db_migrator.rb

Fixes #945. Turns out that the setup_database.bat script was trying to get the current version number from a non-existent table - schema_info which caused the setup_database script to fail. So now checking to make sure there are tables prior to setting the current version number. If there are no tables, the current_version variable should be set to 0.

Fix bug in windows install causing failure to setup database when installing with an empty database

---

public/app/views/agents/show.html.erb
public/app/views/shared/_present_list_external_docs.html.erb
public/app/views/shared/_record_innards.html.erb
public/app/views/subjects/show.html.erb

so now there is a present_list for external documents that does not add the prefix to the URL that is used for displaying external documents in the PUI. Fixes https://archivesspace.atlassian.net/browse/ANW-225

URLs for external documents do not need the ASpace application prefix added to them

---

public/app/models/finding_aid_pdf.rb

Make sure the "to be" short title has a regex word char in it and remove left leading newlines or else they become the short title by index selection.

Protect against newline only and newline prefixed fa titles

---

frontend/app/helpers/enumeration_helper.rb

Without this the search string values are unquoted which does not
retrieve the correct results.
BEFORE:
[java] INFO: [collection1] webapp= path=/select params={facet.field=primary_type&facet.field=creators&facet.field=subjects&csv.escape=\&start=0&fq=repository:"/repositories/2"+OR+repository:global&fq=(-types:("pui_only")+AND+*:*)&fq=-exclude_by_default:true&sort=&rows=10&**q=(extent_type_enum_s:(Video-Digital+LTO7)+OR+(processing_total_extent_type_enum_s:(Video-Digital+LTO7)))**&facet.limit=100&csv.header=true&csv.encapsulator="&facet.mincount=0&wt=json&facet=true} hits=0 status=0 QTime=17 
AFTER:
[java] INFO: [collection1] webapp= path=/select params={facet.field=primary_type&facet.field=creators&facet.field=subjects&csv.escape=\&start=0&fq=repository:"/repositories/2"+OR+repository:glo …

Use literal to generate enum aq strings

---

solr/schema.xml

enablePositionIncrements was deprecated in 4.3 and will cause failure on
Solr >= v5 .
https://lucene.apache.org/core/4_10_1/analyzers-common/deprecated-list.html

Remove enablePositionIncrements from schema.xml

---

public/app/views/request_mailer/request_received_email.html.erb

Fixes #964 
url = "#{AppConfig[:public_proxy_url].sub(/\/^/, '')}#{@request.request_uri}"
so don't need app_prefix method around url in this line: 
<strong>URL</strong>: <%= link_to url, url %>
@archivesspace/archivesspace-core-committers Can someone review this for me?

app_prefix function not necessary since the public_proxy_url is already added on the line above

---

backend/app/exporters/serializers/ead3.rb

Without this there's a load order issue between (at least) Mac OS
and Ubuntu. The latter loads ead3.rb before ead.rb and fails.

EAD3Serializer requires EADSerializer so require it first

---

public/app/views/pdf/_archival_object.html.erb

This is a proposed fix for #972.
Note: In `public/app/views/pdf/_archival_object.html.erb`, there are two more occurrences of unescaped HTML, both in the note text field (`<%== note['note_text'] %>`). I'm not sure if unescaped HTML is supposed to be allowed in the note text, so I didn't patch those two occurrences.
Thanks for reviewing this PR.

Fix "Failed to clean XML" in PDF due to raw HTML in archival object

---

build/build.xml

- Makes it possible to run solr cleanup independently
- Ensures all indexer state is cleared out

Make a solr:nuke task and invoke from db:nuke

---

solr/solrconfig.xml

@lmcglohon First pass attempt at fixing https://archivesspace.atlassian.net/browse/AR-1882 and, to a small degree, https://archivesspace.atlassian.net/browse/ANW-201 (admin data not removed from results in PUI, but is lower ranked).
Following fields are boosted (based on local testing):
- primary_type of resource, accession, subject, and the 3 agent types
- four_part_id
- title
Reworking/feedback welcome.

AR-1882 Weight resources and accessions in search relevancy

---

frontend/app/views/shared/_largetree.html.erb

This also fixes https://archivesspace.atlassian.net/browse/ANW-219.

Ensure that if an enumeration value is not available for display, have it display to the value assigned by the user

---

frontend/config/locales/en.yml

Additions to the tooltips for Conditions Governing Access and Use begin and end dates based on confusion indicated by https://archivesspace.atlassian.net/browse/ANW-251.

ANW-251 Tooltip updates

---

backend/app/converters/ead_converter.rb

top container when there isn't already a uri associated with the current barcode in the top containers hash.
I changed the variable names to reflect the content and am now returning the uri for the top container found using the for_barcode method.
@archivesspace/archivesspace-core-committers Can someone review this pull request?

Instead of returning a uri for a top container, the code returns a complete 

---

backend/app/converters/lib/marcxml_base_map.rb
backend/spec/lib_marcxml_converter_spec.rb

- Set authority id from 001 controlfield for agents / subjects
- Sets source and rules for name authority records (limited)
- Create 1 subject record per marc auth record ignoring 4XX fields
The latter update is not "good" just better than the current
behavior of creating 1 subject record for each 4XX variant heading
in an authority record. This is very undesirable as it pollutes the
database with unauthorized form subject headings.
In the future the subject / term data model should be updated to
support authorized vs. unauthorized forms and multiple headings
per subject (the equivalent is already possible for agents).

Update marc auth record import

---

backend/app/model/large_tree.rb

Fixes https://archivesspace.atlassian.net/browse/ANW-238

ANW-238: Since NULL is valid value for publish and suppress columns in the archival_objects table, include it as an option in filters for large trees

---

public/app/views/shared/_result.html.erb

Fixes #1006 
@fordmadox @archivesspace/archivesspace-core-committers

ANW-229: Remove all HTML from the truncated notes so that the results page will render correctly

---

backend/app/views/reports/report.erb

`@report.orientation` is a method, not an attribute: https://github.com/archivesspace/archivesspace/blob/master/backend/app/model/reports/abstract_report.rb#L50
Attempting to set the value returned by `orientation` was generating the error described in ANW-265: https://archivesspace.atlassian.net/browse/ANW-265

fix report orientation bug

---

backend/spec/controller_digital_object_component_spec.rb
backend/spec/factories.rb
backend/spec/model_digital_object_component_spec.rb

The digital object component fixtures changed a bit, which caused some
tests to break. This re-adds the generic DOC fixtures.

Fixes some backend tests that need a specific fixtures

---

public/app/controllers/search_controller.rb

the search params so the next search is not scoped by repository

When magnifying glass pressed to restart search, clear the repo id from

---

common/config/config-defaults.rb
public/app/views/resources/_resource_alltabs.erb
public/app/views/resources/_resource_tab.erb
public/app/views/resources/infinite.html.erb
public/app/views/resources/inventory.html.erb
public/app/views/resources/show.html.erb

PR does the following:
- Fixes issue #1030 
- adds abstraction for a page tab, via partial
- DRYs up tab display on resource/collection overview, detail, and container inventory pages

Fixes add config param to show/hide container inventory on  resource page #1030

---

public/README.md
public/config/initializers/public_new_defaults.rb
public/public/robots.txt

https://archivesspace.atlassian.net/browse/AR-1486
It would be nice to eventually make this more easily configurable, but until we figure out how to do that, lets have a better (open to crawling) default before next release.

by default: allow all robots

---

common/ashttp.rb
common/http_generic_request.rb

There's a JRuby issue ( https://github.com/jruby/jruby/issues/4842 )
that causes IOs to be read into memory if using SSL. This causes big
problems if, for instance, you're using Solr or the backend with an SSL socket.
This adds a patch to chunk the IO manually, rather then just reading the
whole thing in.

Fixes JRuby issue with files being loaded into memory on #copy_stream

---

public/app/assets/stylesheets/archivesspace/aspace.scss
public/app/views/accessions/show.html.erb
public/app/views/agents/show.html.erb
public/app/views/classifications/show.html.erb
public/app/views/containers/show.html.erb
public/app/views/objects/show.html.erb
public/app/views/repositories/show.html.erb
public/app/views/resources/show.html.erb

The fundamental layout isn't consistent for each record type so a record
type class has been added to each record page to make it easier to make
changes that don't fix one thing, break another.

Improve basic alignment for all record types

---

public/app/controllers/concerns/manipulate_node.rb

Ensure mixed content is valid utf8

---

public/app/views/shared/_navigation.html.erb

The logic in public/app/controllers/search_controller.rb is faulty, as it does not remove the repo_id from the base_search_url when reset=true.  I obviate this by explicitly setting the magnifying glass link **/search/reset=true**, rather than relying on the *link_to* syntax, which is dicey.

REALLY fix clicking on the Search(magnif. glass) tab

---

backend/app/exporters/models/labels.rb
backend/spec/controller_exports_spec.rb

This fixes and expands the label export CSV endpoint to use the Top
Container features. This adds more information to the export, with 
the headers being:
-  Repository Name
-   Resource Title
-   Resource Identifier
-   Series Archival Object Title
-   Archival Object Title
-   Container Profile
-   Top Container
-   Top Container Barcode
-   SubContainer 1
-   SubContainer 2
-   Current Location

Fix and expand label export to TSV

---

common/exceptions.rb
public/app/controllers/accessions_controller.rb
public/app/controllers/agents_controller.rb
public/app/controllers/application_controller.rb
public/app/controllers/classifications_controller.rb
public/app/controllers/objects_controller.rb
public/app/controllers/repositories_controller.rb
public/app/controllers/resources_controller.rb
public/app/controllers/subjects_controller.rb
public/app/services/archives_space_client.rb
public/app/views/error/backend_request_failure.html.erb
public/app/views/shared/_pagination.html.erb

Fixes #1090 and adds an error page when the Public UI cannot connect to the backend.
Tries to DRY out the exception rescue bits by moving it to the application controller
You might not see some of these pages in development unless you change the development.rb to
```
config.consider_all_requests_local = false
```

Fix public errors

---

frontend/app/views/accessions/show.html.erb

This PR fixes a bug that we discovered that results in accessions without titles having incomplete breadcrumb trails and HTML header titles. 
We do not assign titles to our accessions, only identifiers, resulting in the bug shown in the attached screenshot. This PR updates the accessions show template to pass a "title" parameter to setup_context using the accession's display string (title if it exists, identifier if not), similar to the [accessions edit template](https://github.com/archivesspace/archivesspace/blob/master/frontend/app/views/accessions/edit.html.erb).

fix accession show title bug

---

stylesheets/as-ead-pdf.xsl

Removes separate date lines for all dates included in series and c-level description, and ensures all are appended to the unittitle.

Remove duplicate dates and add to unittitle line

---

backend/app/lib/oai/aspace_oai_record.rb

In my current failing samples, it is unresolved containers and container profiles that is causing the serializer errors.  
I don't know if it's necessary to resolve everything, but I referred to working code in backend/app/lib/export.rb.
Go ahead and trim that list of resources to be resolved  if you know more specifically what is required. 
( I will look for further failing examples to see if I can find a failure due to agents or subjects. )

ANW-609 unresolved containers was causing errors on OAI getRecord EAD serializer

---

common/config/config-defaults.rb

Neither `:container_management_barcode_length` nor `:container_management_extent_calculator` are documented anywhere in the codebase; this adds basic documentation to `config-default.rb'.
If there's a more appropriate place for this kind of documentation (a README file?), I'll be happy to move it over there instead/in addition.

Added documentation for two container management config options

---

public/app/controllers/resources_controller.rb

We noticed an issue where the default facets array (DEFAULT_RES_FACET_TYPES in public/app/controllers/resources_controller.rb) was being modified and in turn growing in length each time the resources (Collections) view was navigated to if a repository ID was not specified.
At some point the array grows to such a large size that the generated search URL is no longer able to be processed and causes the page to display an error. A service restart would temporarily resolve the issue as it would reset the default facet array.

Dup default facets instead of assigning

---

backend/Gemfile
backend/Gemfile.lock

In previous versions of `saxon-xslt` I included VCR HTTP fixtures
('cassettes') in the files included in the `.gem` package by mistake.
These fixtures have very long file names, which may well have been
causing problems with building on Windows systems, with their
maximum-complete-path-length restriction. Releases 0.7.2.1 and 0.8.2.1
remove the fixtures from the `.gem` package, with no code changes.
This will hopefully fix the Windows build problem @lmcglohon has reported.
(See fidothe/saxon-xslt#17)

Ensure saxon-xslt version >= 0.8.2.1

---

backend/app/controllers/enumeration.rb
backend/spec/controller_enumeration_spec.rb

Currently the update position end-point tries to return the object as
json without calling to_jsonmodel, which just returns the name of the
instance. Call to_jsonmodel and adds test.
Fixes #1163

Return valid updated json_response when updating the position

---

common/locales/en.yml
common/locales/es.yml
common/locales/fr.yml
frontend/app/views/shared/_header_repository.html.erb
frontend/app/views/shared/_header_user.html.erb
frontend/config/locales/en.yml
frontend/config/locales/es.yml
frontend/config/locales/fr.yml

Global Preferences - should appear for system admin permissions only
Repository Preferences - should appear for repository managers and system admins only
User Preference Defaults (should perhaps be renamed to User Preferences to match others) - should appear for all users

Fixes to preferences based upon permissions

---

_yard/API.erb

This PR started as an investigation of this issue: https://github.com/archivesspace/archivesspace/issues/1071
That particular issue was being caused by method checks being written like this:
```ruby
<% if e[:method] == :get %>
```
Methods are returned as an array, so every example in the API docs, regardless of method, was defaulting to the final `<% else %>` block that adds a -d flag regardless of method.  Method checks are now written as:
```ruby
<% if e[:method] == [:get] %>
```
Other changes included in this PR include:
1. Moving code samples to immediately below the heading, in line with the Slate markdown syntax guidelines: https://github.com/lord/slate/wiki/markdown-syntax#formatting-code-annotations-right-column-with-its-explanation-center-column
2. Parsing out endpoint …

Improve API documentation

---

plugins/generate_accession_identifiers/README.md

The plugin name changed slightly at some point, so the suggested config.rb entry needed updating.  Also added a note describing how to set the starting number if desired.

Small README fix for the generate accession identifiers plugin

---

common/locales/enums/en.yml
common/locales/enums/es.yml
common/locales/enums/fr.yml

The `(language).enumerations._note_types.relatedmaterial` locale appears to have been duplicated across all 3 of currently available languages.

Remove Duplicate Enumeration Locale

---

public/app/services/archives_space_client.rb

Also removed commented out code

Add configurable search parameters to search options and remove unused method (get_full_url)

---

plugins/hello_world/README.md

Added an annotated README to the hello_world exemplar plugin as part of Technical Advisory Council Technical Documentation sub-team's work to improve plug-in documentation. The [plug-ins README](https://github.com/archivesspace/tech-docs/blob/master/customization/plugins.md) currently states, "The ArchivesSpace distribution comes with the `hello_world` exemplar plug-in. Please refer to it find out more about how to implement a plug-in." This annotated README will hopefully give new users a better sense of how the plug-in works.
cc: @bobbi-SMR @rshanrath

add README to hello_world plugin

---

public/app/controllers/accessions_controller.rb
public/app/controllers/agents_controller.rb
public/app/controllers/application_controller.rb
public/app/controllers/classifications_controller.rb
public/app/controllers/objects_controller.rb
public/app/controllers/resources_controller.rb
public/app/controllers/subjects_controller.rb

Throwing an incorrect RecordNotFound error when browser back arrow is used
Fixes #1213

Roll back DRY for error handling until it can be refactored. 

---

frontend/app/views/shared/_pagination_summary.html.erb

Looks like a lot but it's actually just re-ordered with a couple of pull-left vs. right updates.

Fix for sort submenu partially off-screen with fluid width

---

common/json_schema_utils.rb

There seems to be some small issues with making a hash like:
Hash[[['key', 'value'], nil, ['anotherkey', 'anothervalue']]]
MRI ruby will actually give an error warning if you do this and the
newer version of jruby will do the same. This simply compacts the array
before it gets passed to Hash[].
i.e:
Hash[[['key', 'value'], nil, ['anotherkey', 'anothervalue']].compact]

Make sure array is compact before using it to create Hash

---

build/build.xml
public/Gemfile
public/Gemfile.lock
public/spec/controllers/accessions_controller_spec.rb
public/spec/features/resources_spec.rb
public/spec/rails_helper.rb
public/spec/spec_helper.rb

This adds Capybara/Selenium tests to the PUI.
The capybara test suite runs with the public:test task.
Tests can be added to the features directory. Included in one to test
for the back button issue that was causing the flash to incorrectly
display that there's a general error.
It is configured to allow for Firefox (default), Chrome, and Headless
Chrome. To use Headless chrome, set an environment variable of
SELENIUM_CHROME. To use regular chrome, set an environment variable of
SELENIUM_HEADY_CHROME.

Add Capybara + Selenium test to PUI

---

selenium/rakefile.rb

Some java versions ( Oracle java 8? ) seem to skip the ensure block when
the rake task is killed. With selenium, this leaves the test server pid
files entact, which will then cause problems on subsequent runs. This
just adds a more clear warning message that the pid files are there and
that the tests might not run correctly.

Add some warning messages about pid files when running Selenium tests

---

.travis.yml

Looks like Travis doesn't support oraclejdk7
https://docs.travis-ci.com/user/reference/trusty/#JVM-(Clojure%2C-Groovy%2C-Java%2C-Scala)-images
Funny tho bc it still runs with a label of "oraclejdk7" ( but if you
look at the log you'll see it's actually running 8. :confused: )

Travis dropped support for oraclejdk7 awhile ago

---

public/app/controllers/classifications_controller.rb
public/app/controllers/digital_objects_controller.rb
public/app/controllers/resources_controller.rb
public/spec/controllers/classifications_controller_spec.rb
public/spec/controllers/digital_objects_controller_spec.rb
public/spec/controllers/resources_controller_spec.rb
public/spec/factories.rb
public/spec/spec_helper.rb

Some of the tree-related actions in the Classification, Digital Object,
and Resources controllers were raising RecordNotFound errors, which
resulted in 500 errors to be returned.
Not sure why these URLs are being called, but this makes sure that
exception is handled by returning a 404 error instead.
Tests included.

Return 404 when no record is found in Tree-releated controller actions

---

backend/app/converters/ead_converter.rb
backend/spec/lib_ead_converter_spec.rb

This PR (and accompanying test) make it so the `@audience` attribute is respected on the `<ead>` element (translating to the `publish` value in a resource) as well as the `<archdesc>`.  It's legal there per standard, and at least one EAD has crossed my transom with `@audience` located thusly.

Fixes #1272 @audience respected on either of <ead>/<archdesc>

---

public/app/views/pdf/_header.html.erb
public/app/views/pdf/_titlepage.html.erb

Updated to use record display string if there is no finding aid title

ANW-310 - for the PUI PDF title page, use record title if there is no finding aid title

---

backend/app/lib/crud_helpers.rb

https://github.com/jeremyevans/sequel/blob/master/lib/sequel/extensions/pagination.rb#L87-L90
Provides db count for record type (don't believe this is conveniently 
exposed any other way).

Return total count in paginated response

---

backend/app/exporters/serializers/ead.rb
backend/spec/export_ead_spec.rb

- daogrp only used if there is more than one visible file version
- 'audience' attribute is set correctly
- dao or daogrp tag nested inside of did tag

ANW-285: unpublished file versions do not appear in EAD export

---

backend/app/exporters/lib/streaming_xml.rb
backend/app/exporters/serializers/ead.rb
backend/spec/export_ead_spec.rb

Handle cases like "two&two" as well as "two & two" correctly,
while handling cases where there is pre-escaped content.

ANW-716: EAD exporter: Escape '&' chars properly

---

frontend/app/views/file_versions/_image.html.erb

A little fix to address a portion of ANW-704.  This adds an alt attribute to images displayed on staff side digital object view records.  The attribute is set to the caption if present, and the digital object title if there is no caption.

Add alt text to staff side file version image

---

.gitignore
backend/spec/model_solr_spec.rb
common/config/config-defaults.rb

Addresses issues discussed in the comments for https://github.com/archivesspace/archivesspace/pull/1128
Changes "op" to "q.op" in default and example solr param config, and updates tests to reflect this change.
https://archivesspace.atlassian.net/browse/ANW-427
https://archivesspace.atlassian.net/browse/ANW-762
Defaults staff-side search (including type aheads) to AND searches.  This change *does not* impact public search.
Passing backend tests, deveserver and built release behave as anticipated.

Change op to q.op for ANW-427

---

frontend/app/assets/javascripts/largetree.js.erb
public/app/assets/javascripts/resizable_sidebar.js
public/vendor/assets/javascripts/largetree.js.erb

For accessibility, the empty buttons and empty link on the collection organization of the PUI need labels. NOTE: This adds labels to those parts only - there is more to be done.
https://archivesspace.atlassian.net/browse/ANW-704
Improves accessibility
- [X ] Bug fix (non-breaking change which fixes an issue)

Add aria labels to empty buttons and empty link in the collection organization section

---

backend/app/exporters/serializers/ead3.rb
backend/spec/export_ead3_spec.rb

Fixes an issue where ampersands were being removed instead of converted, applies proper conversion of un-escaped ampersands in text and in character entities not included in predefined XML entities to ensure validation.

fix and improve handling of ampersands and character entities in EAD3

---

backend/app/exporters/lib/utils.rb
backend/app/exporters/models/marc21.rb
backend/spec/export_marc_spec.rb

Addresses the following bullet points in [ANW-779]:
- Extra "." when there is a extra line/paragraph return at the end of a note field (the exporter interprets the extra return as additional text and thinks it needs to add an ending punctuation mark)
- Unneeded subfield b in corporate entity agent links when used as a subject or creator (a subfield b should only be in the 110, 610, or 710 export when there is a Subordinate Name 1 entry)
https://archivesspace.atlassian.net/browse/ANW-779
Address unintended/undesired consequences stemming from recent MARCXML export improvements.
Automated tests passed (or, when failed, tests updated).  Before and after MARCXML exports show desired fixes.
**Corporate entity** without a subname before PR:
After PR:
**Extra line break** handling before PR: …

ANW-779 MARCXML export updates

---

public/app/assets/javascripts/search.js.erb

Plus Minus buttons for search missing accessibility text
Added labels for accessibility
Tested using WAVE accessibility tool
- [X ] Bug fix (non-breaking change which fixes an issue)

Add label to plus and minus buttons for accessibility

---

backend/app/lib/reports/report_utils.rb
reports/assessments/assessment_list_report/assessment_list_report.rb

Refactor the way the csv format is exported by creating separate columns for formats, conservation issues, and ratings
https://archivesspace.atlassian.net/browse/ANW-766
Returns the assessment record list report back to result before reports refactor
Tested using assessments data provided by ticket submitter

Split out formats, conservation issues, and ratings into individual columns for csv format

---

backend/app/lib/reports/report_utils.rb
reports/assessments/assessment_linked_records_subreport/assessment_linked_records_subreport.rb
reports/assessments/assessment_list_report/assessment_list_report.rb
reports/static/translation_defaults/en.yml
reports/static/translation_defaults/es.yml
reports/static/translation_defaults/fr.yml

Made changes based upon comment from JIRA ticket:
1. The record id (resource_144 etc) seems to the only bit of info missing, which doesn't matter to our current workflows, but might matter to other people?
2. The report is pulling in a field called research value note, and there's actually no place to enter that note, so I'm not sure where that's coming from.
3. The report is pulling in inactive assessments, when the original functionality was designed to exclude inactive records from reports (that's what the inactive button was for).
4. It would be helpful if the assessment attributes (the user-defined fields) were grouped with their sections as they were in the original report.
https://archivesspace.atlassian.net/browse/ANW-766
Using test data, all 5 formats of the Assessment List …

ANW-766 Made improvements/adjustments based upon comments in JIRA ticket

---

backend/app/exporters/models/marc21.rb
backend/spec/export_marc_spec.rb

Continuing to improve/fix MARC export for the 110/610/710s.  
Changes sufield_b from a single subfield containing a concatenation of the two subordinate names into repeatable subfield_b's containing only one subordinate name.  Adjusts end punctuation for subfield's a and b depending on presence of subfield's b and e.
https://archivesspace.atlassian.net/browse/ANW-779
Address bugs in MARC export.
Passed automated tests, and updated tests that failed.  Reviewed MARC exports for compliance with stated mappings.
110 with multiple subnames and subfields:
710 with one subordinate name:
710 with no subordinate names:

Allow multiple subfield b's and correctly punctuate

---

frontend/app/helpers/search_helper.rb
frontend/app/views/search/_context.html.erb

Some staff side searches fail because the context partial was not built to account for a `nil` ancestor.  This changes the fallback value of context_ancestor to `nil` instead of an empty array to avoid a "Something went wrong error" when ancestors = `nil`.
Address error page that is returned when a nil value is present in ancestors.
Ran locally against several different databases and confirmed searches successfully complete.

Address potential for nil ancestors in found in column

---

public/app/controllers/pdf_controller.rb

This skips the token check on the print to pdf form. Since this is not
making database changes or doing any special request with user
information, this check is most likely not needed. This check can cause
issues when using a reverse proxy in some user agents.

Skip verify csrf token check on print to pdf

---

Dockerfile
docker-startup.sh

Use Openjdk slim and multi-stage build for smaller image, less cruft.
Use ArchivesSpace user at runtime (best practice: non root user).
Remove sendmail: anti-pattern and cannot start service as non-root.
N/A
Security and best practice updates for Docker builds.
Local docker builds.
N/A
N/A - not code contribution.

Docker updates:

---

backend/app/model/archival_object.rb
backend/app/model/digital_object_component.rb
backend/app/model/mixins/touch_records.rb
backend/app/model/top_container.rb
backend/spec/mixin_touch_records_spec.rb
backend/spec/spec_helper_methods.rb

Provide a generic mixin that allows a model to define a method to update the `system_mtime` value for one or more related records.
https://github.com/archivesspace/archivesspace/issues/856
Particularly for EAD serialization a resource "full record" is the resource + many of its related records. Updates to some related records do not propagate an update to resources (only those that link via a relationship mixin do currently), which is inconsistent, and makes requesting resources updated "since" or "from" a certain date difficult, requiring a chain of api calls to archival objects, top containers etc. OAI EAD requests are scoped by record type (resource) and therefore updates to archival objects or containers are not factored into results when using dates, which greatly limits the …

Implement a 'touch' functionality to bump related record system_mtime

---

frontend/app/views/events/index.html.erb
frontend/app/views/linked_events/_show.html.erb

Fixes linked record and Events > Browse views to account for event outcomes that are blank/NULL.  Added a ternary in the impacted views to confirm that a `record['outcome']` exists *before* attempting to display the translation for that outcome value in the table.  Additionally, I confirmed by pulling records out via the API that, when an outcome is not present in a record, the outcome key does not exist (e.g. it's just not there, not it's there but is blank).
Partial fix for: https://archivesspace.atlassian.net/browse/ANW-778
An outcome is not a required field for an event record, so the outcome column in the staff UI should not assume that there will always be a value to display.
Backend tests passed looked, inspected visually on a local branch.
Before change:
After change:

Allow event outcome to be blank

---

public/app/views/shared/_search.html.erb
public/config/locales/en.yml

The current header on the `/search?reset=true` search page wasn't easily customized. This changes that with a new locale and a change to the _search.html.erb file.
Trying to change "Search The Archives" was nearly impossible. 
Brought up build locally and tested. The message is unchanged from the original, but it is now easily changed via en.yml
- [x ] New feature (non-breaking change which adds functionality)
- [x ] All new and existing tests passed.

Make search header message configurable

---

backend/app/controllers/id_lookup_controller.rb
backend/app/model/idlookup.rb
backend/spec/controller_idlookup_spec.rb

Addresses bug described in ANW-781.  Response returned from the `repositories/:repo_id/find_by_id/resources` API endpoint now only returns matches from the repository provided.
More work needs to be done to address noted issues with the equivalent endpoints for digital_objects, digital_object_components, and archival_objects.
https://archivesspace.atlassian.net/browse/ANW-781
User identified bug in the `repositories/:repo_id/find_by_id/resources` endpoint.
Existing automated tests passed, and a new relevant test was added.

Ensure response scoped to given repository

---

frontend/app/views/archival_objects/_form_container.html.erb
frontend/app/views/archival_objects/_show_inline.html.erb
frontend/app/views/classification_terms/_form_container.html.erb
frontend/app/views/classification_terms/_show_inline.html.erb
frontend/app/views/classifications/_form_container.html.erb
frontend/app/views/classifications/_show_inline.html.erb
frontend/app/views/digital_object_components/_form_container.html.erb
frontend/app/views/digital_object_components/_show_inline.html.erb
frontend/app/views/digital_objects/_edit_inline.html.erb
frontend/app/views/digital_objects/_show_inline.html.erb
frontend/app/views/resources/_form_container.html.erb
frontend/app/views/resources/_show_inline.html.erb

The Basic Information heading and titles are smushed together and have the wrong font size/type for resources, archival objects, digital objects and classifications.
https://archivesspace.atlassian.net/browse/ANW-798
Tested by navigating to appropriate pages on the staff interface.

ANW-798 fix weird display issues

---

frontend/app/assets/javascripts/largetree_dragdrop.js.erb

When performing a multiselect in tree reorder mode, a misclick shouldn't clear the current selection.
To perform a multiselect in the tree reorder mode, you hold down the command key (on Mac) or control (everywhere else) and select the items you want by clicking their handles.  Clicking anywhere else would normally clear the current selection but, to be tolerant of misclicks, the selection is only cleared if you're not currently holding down the multiselect key.
This all works fine when you're holding the control key, but on Mac (where you hold the command key instead), a misclick will clear the current selection.  This commit unifies the behavior of the control and command keys and pulls the checking logic into a central spot to avoid future issues like this.
I couldn't find anyone …

Tree reorder mode multiselect fix for Mac

---

backend/app/exporters/models/marc21.rb

In order to make individual 7xx fields in marc export, should have iterated over other creators using with_index
Better solution for generating individual 7xx fields when exporting MARC
Existing test to ensure multiple 7xx fields exported passes

rand method used when not necessary

---

backend/app/lib/oai/aspace_oai_repository.rb
backend/spec/model_oai_spec.rb

Previously, ListSets just returned a list of all sets that are defined.
Changes add a check against the repositories defined, such that a set is only included in ListSets results if it is enabled in at least one repository.
https://archivesspace.atlassian.net/browse/ANW-793
This fix is necessary after the ability to turn off OAI for certain sets was added. 
This has been tested by setting all repos to only enable a single set, and then running an OAI ListSets query against it, affirming the correct result.
Also tested setting a repo to allow all sets, and affirming that correct result as well.
Unit test added to model_oai_spec.rb.
- [ x] I have read the **CONTRIBUTING** …

ANW-793: OAI ListSets only returns sets that are included by at least one repo

---

backend/app/model/ASModel.rb
backend/app/model/ASModel_sequel.rb
backend/spec/asmodel_spec.rb

This provides a consistent way to test whether a model is top level - as opposed to nested.
The test is that the model has a corresponding jsonmodel and the
jsonmodel's schema has a uri property.
See above
None
See above
Implemented a unit test
Ran the tests
None

Add a .top_level? method to ASModels

---

backend/app/model/mixins/relationships.rb
backend/spec/model_relationships_spec.rb

Previously these have been anonymous clasees which can make them
tricky to identify when debugging. This change gives each relationship
class a name in the `Relationships` module. For example:
```
Relationships::ResourceSubject
```
Where the first part `Resource` is the name of the model on which
the relationship is defined, and the second part `Subject` is the
name of the defined relationship.
See above
None
See above
Ran the tests - they passed
Provided a test for the change

Give defined relationship classes names.

---

frontend/app/views/site/_footer.html.erb

This asdds a link to the public interface to the footer in the staff interface when you're running on localhost.
This is for ANW-720. 
https://archivesspace.atlassian.net/browse/ANW-720
In the standard application, the public interface footer includes a link back to the staff interface. The staff interface footer should do the same. Links on the staff interface footer should also be blue and underlined like on the PUI side. Basically, we want to have consistency of look and function of the footer on both sides of the application.
Most institutions in production will customize this footer, but this will improve the trial and testing experience.
Ran both source and created a build with the change, footer had links as exepected.
- [x ] New feature (non-breaking change which adds …

ANW-720 Show links between Staff and PUI when using localhost

---

backend/app/lib/oai/aspace_oai_repository.rb
backend/spec/model_oai_spec.rb

Use has_unpublished_ancestor flag in JSON to determine if a record should be included in OAI result set for ListIdentifiers, ListRecords, and GetRecords.
https://archivesspace.atlassian.net/browse/ANW-794
OAI result sets were including entities with unpublished ancestors, which is incorrect behavior.
Tested on development instance by running an OAI ListIdentifier, ListRecord, and GetRecord query on an ArchivalObject. 
Verified that when the AO's root Resource was unpublished, the AO was omitted from all three queries.
Also verified that when AO's root Resource was REpublished, the AO was once again present in all three queries. 
Wrote unit tests for all three cases.

ANW-794: Omit entities from OAI that have unpublished ancestors

---

public/app/controllers/concerns/result_info.rb

ANW-728 - If you somehow manage to accidentally put a space before the http in the "File URI" of a digital object, the PUI chokes and won't display the red icon thinger to link out the digital object to the url.
Adds the `strip` to the `file_uri` so it displays even with a space in the record in the DB
https://archivesspace.atlassian.net/browse/ANW-728
Sometimes someone just drops a space where it shouldn't be, we've all done that. This just cleans that up in the digital object page.
Tested in running source and making changes to a record to include a space and random other things to see if anything broke. Did not break.

Fixes Leading Spaces in File URI Break Links To Digital Objects PUI  

---

common/schemas/abstract_archival_object.rb
common/schemas/archival_object.rb
common/schemas/digital_object.rb
common/schemas/digital_object_component.rb
common/schemas/resource.rb

Minor tweak to clarify that abstract_archival_object is the parent schema for the four major archival record types: resources, archival objects, digital objects, and digital object components.
Also includes small tweak to remove duplicative information from digital object component schema.
It was not obvious by naming convention that this abstract schema applied to the four major record types.
Confirmed no changes were noticeable within the application.

Clarify role of abstract_archival_object schema

---

docs/_site/assets/stylesheets/main.css
docs/assets/stylesheets/main.sass

Change of http to https to load fonts to avoid browser errors.
Change of http to https to load fonts to avoid browser errors.
Chrome and other browsers refuse to load http pages on https sites.

Load fonts from googleapis.como through https

---

indexer/app/lib/fake_solr_timeout_response.rb
indexer/app/lib/indexer_common.rb
indexer/spec/indexer_common_spec.rb

Redo of https://github.com/archivesspace/archivesspace/pull/1420
Sometime Solr will return an error, especially if it's under resourced. This will just log the error and not raise it, which allows the indexer to attempt to complete the index round rather than abort and start from the beginning. 
People can search for SolrIndexingError in the logs for these issues. 
If there's a solr error, the index round will abort. Then the indexer will start from the beginning, then run into another error, and abort. Then the indexer will start from the beginning, then run into another error, and abort. Etc. 
Tests included.
- [] Bug fix (non-breaking change which fixes an issue)

Have indexer log Solr errors, not raise them

---

backend/app/controllers/job.rb
backend/app/lib/job_runners/batch_import_runner.rb
backend/app/lib/job_runners/print_to_pdf_runner.rb
backend/app/model/job.rb
backend/app/model/job_files.rb

When saving the path to job files, only the path relative to the base job files directory gets written to the database. When accessing job files, the absolute path will be created (if it's not already the absolute path) from the stored relative path and the job files directory defined in config.
[ANW-818](https://archivesspace.atlassian.net/browse/ANW-818)
In the table 'job_input_file' the file paths for job files were being stored as absolute file paths rather than as relative paths. This caused problems when the root path for ArchivesSpace changed (i.e. when upgrading).
Tested by running all the different job types and making sure the files could be downloaded and looked correct and that the appropriate relative file path was stored in the database. Also tested that job files from …

ANW-818: Store relative path for job files in stead of absolute

---

backend/app/exporters/serializers/ead.rb
backend/app/exporters/serializers/ead3.rb
backend/spec/export_ead3_spec.rb
backend/spec/export_ead_spec.rb

export label to label attr in physdesc tag for EAD and EAD3 exports for note types:
physdesc
physfacet
dimension
Updated serializer and specs to include value for label for these note types
https://archivesspace.atlassian.net/browse/ANW-150
Missing data is now included in export.
I've updated the unit tests, and tested that the missing data is now present manually for both EAD and EAD3 exports

ANW-150: export label for physdesc notes in EAD

---

common/config/config-defaults.rb
docs/doc/file.configuration.html
docs/user/configuring-archivesspace.md

Found all places where the `:repos` Ruby symbol was mentioned, and replaced it with `:pui_repos`. This was due to a mismatch between documentation and the operation of `Repository.badge_list(repo_code)`.
I spent a few hours looking through documentation and code to try to figure out how to hide the "Record Groups" badge for a repository. I eventually found where the AppConfig settings are used to control that display, and noticed that the documented symbol `:repos` was not actually used anywhere.
I hope that fixing the documentation will help save someone else some time.
Related to this, you can't directly set the configuration properties like:
```rb
AppConfig[:pui_repos]['{repo_code}'][:hide][:counts] = true
```
`AppConfig[:pui_repos]['{repo_code}']` is Nil by default. You instead have …

Fixed references to a symbol that is not used

---

public/app/views/pdf/_archival_object.html.erb
public/app/views/pdf/_resource.html.erb

XMLCLEAN fails when it is fed invalid XML. Anything with an ampersand in a string is not valid XML, so we need to make sure we clean those up before sending anything through xmlclean.
https://archivesspace.atlassian.net/browse/ANW-831
A single & character causes failures like this:
RuntimeError (Failed to clean XML: The reference to entity "ix" must end with the ';' delimiter.):

Fix ampersands in notes to make valid XML

---

common/config/config-defaults.rb
public/app/views/shared/_result.html.erb

This adds a new config.rb variable to change the length of the text on the collection overview page. 
Some sites have very long scope and contents notes because they have 2 or more languages and have a separate note for each language. Those longer notes need to be displayed even if they're longer than the default. 
Ran from source
- [ x] New feature (non-breaking change which adds functionality)
- [x ] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.

Add Option for Abstract Note Length

---

docker-startup.sh

Addresses #1456 
This change causes ArchivesSpace containers to exit if `/archivesspace/scripts/setup-database.sh` fails, allowing Docker to restart the service if the container is running as part of a `docker-compose up` or a `docker stack deploy`.
I am currently substituting this version of the `docker-startup.sh` into my production ArchivesSpace containers. I'll gladly take a crack at adding a test for this to Travis if you feel it is necessary.

Change to Docker startup script

---

public/spec/controllers/application_controller_spec.rb
public/spec/rails_helper.rb

Updating driver locations for public tests per changes in #1410 and updating depreciated public test syntax.
#1410 relocates geckodrivers to `common` which breaks current public tests.  This updates `public/spec/rails_helper.rb` so that is can find those relocated drivers.  Similarly, it updates the syntax of some tests in `application_controller_spec.rb` to remove depreciation warnings.

Update path to drivers and fix depreciations

---

_yard/API.erb
backend/app/lib/rest.rb
backend/spec/documentation_spec.rb
backend/spec/rest_helper_spec.rb

These changes make it possible to add a documentation block (in markdown) and an example in any language supported by Rouge to an Endpoint.
The auto-generated API docs are a useful resource, but are in many cases unhelpful, misleading, or downright inaccurate.  Shell examples are wrong more often than right for endpoints that aren't resources or simple collections of same-type resources.  At the same time, they're the best we have, and replacing them with something better will take time and effort.
This code allows for manual docs to be inserted, while falling back to the existing generated docs.
I added calls to `Endpoint#documentation` and `Endpoint#example` in the spec for the REST helper.

Allow for inline, manual documentation of Endpoints in definition.

---

backend/app/exporters/serializers/ead.rb
backend/app/exporters/serializers/ead3.rb
backend/spec/export_ead3_spec.rb
backend/spec/export_ead_spec.rb
backend/spec/fixtures/oai/responses/getrecord_oai_ead.xml

The agent role 'creator' is now capitalized in the serialize_origination method for EADSerializer and EAD3Serializer.
[ANW-777](https://archivesspace.atlassian.net/browse/ANW-777) Capitalize "Creator" as the default <origination> LABEL value.
In EAD and EAD3 export, the 'creator' agent role maps to the origination/@label attribute in lowercase, which requires users to capitalize this attribute manually in the exported EAD.
I added examples to the EAD and EAD3 spec files to test for capitalization of origination/@label. This also required capitalizing the attribute in one other example ("include the unpublished agent with audience internal when include_unpublished is true") and in the OAI response fixture for EAD. The backend test suite passed.

ANW-777 Capitalize instances of origination/@label for agent role 'creator' in EAD export

---

public/app/views/resources/_finding_aid.html.erb

Updated view in PUI to use translation instead of key value for finding aid status.
https://archivesspace.atlassian.net/browse/ANW-603
Bug fix
Manually verified that correct translation value shows for several different key values for finding aid status.

Update view in PUI to use translation value for finding aid status

---

common/locales/en.yml
common/locales/es.yml
common/locales/fr.yml
common/locales/ja.yml
frontend/config/locales/en.yml
frontend/config/locales/es.yml
frontend/config/locales/fr.yml
frontend/config/locales/ja.yml
public/config/locales/en.yml
public/config/locales/es.yml
public/config/locales/fr.yml
public/config/locales/ja.yml

Changed some terminology for background jobs.
- Changed 'Queue Job' to 'Start Job'
- Changed 'Print to PDF' and 'Print Resource to PDF' to 'Generate PDF'
- Changed 'Reports' to 'Create Report'
- Got rid of unused job type translations in public
[ANW-657](https://archivesspace.atlassian.net/browse/ANW-657)
Makes the functionality of background jobs actions clearer.
Checked that new terminology shows up appropriately in staff interface.

ANW-657 Background Jobs Terminology

---

frontend/app/views/shared/_pagination_summary.html.erb

Gets rid of duplicated record type sort option in the sort dropdown filter for search results
[ANW-749](https://archivesspace.atlassian.net/browse/ANW-749)
The "Record Type" filter was appearing twice in the sort dropdown filter for search results.
Tested that record type now only appears once in the sort dropdown when appropriate.

ANW-749 get rid of duplicate record type sort option

---

frontend/app/assets/javascripts/rde.js

Clicking outside of the rapid data entry modal window will not close the window.  The only way to close the window is by clicking the "X" at the top of the screen.  Change only applies to the RDE modal, not other modals in the application (e.g. search/browse top container from within a resource/accession/ao record).
https://archivesspace.atlassian.net/browse/ANW-391
Make it harder for users to accidentally close the RDE window with wayward clicks that lead to substantial data loss.
Confirmed visually, existing tests pass.

ANW-391: Do not close RDE modal with click outside window

---

public/app/views/pdf/_archival_object.html.erb

Updated PDF template to use the raw record display string, rather than the (now default) HTML escaped form, so that the tags are 1) not visible and 2) available for CSS styling.
[ANW-269](https://archivesspace.atlassian.net/browse/ANW-269) HTML tags are inappropriately generated from the HTML to PDF process for the PUI, but only at the Collection Inventory level.
Fixes problem described in ANW-269. Tags in "Collection Inventory" record display strings were displayed as such, rather than being rendered into the appropriate style by the PDF CSS.
For example, the string: 
`<span class="italic title">Zeniada</span> Notes, 1981`
rendered as
`<span class="italic title">Zeniada</span> Notes, 1981`
rather than
_Zeniada_ Notes, 1981
Generated multiple PDF files that triggered the original error …

ANW-269: Fix finding aid PDF Collection Inventory record display string rendering

---

backend/app/converters/lib/marcxml_base_map.rb
backend/spec/lib_marcxml_converter_spec.rb

Change marcxml_base_map.rb to match to existing lcsh subject source value for LCNAF
When using the LCNAF to bring things in it creates a new value in `enumeration_value` because `AUTH_SUBJECT_SOURCE` is "Library of Congress Subject Headings" instead of lcsh in `/backend/app/converters/lib/marcxml_base_map.rb`. 
Change the full "Library of Congress Subject Headings" to lcsh
```
AUTH_SUBJECT_SOURCE = {
-    'a'=>"Library of Congress Subject Headings",
+    'a'=>"lcsh",
```
https://archivesspace.atlassian.net/browse/ANW-800
I don't feel 100% confident on this one, mostly because I don't know how to thoroughly test things. I know it works in that it uses the existing lcsh and doesn't add a second, which is what we want. I don't know how to test that this change to marcxml_base_map.rb will …

ANW-800 Change marcxml_base_map.rb to match to existing lcsh subject value

---

frontend/app/views/classification_terms/_show_inline.html.erb
frontend/app/views/classifications/_show_inline.html.erb
frontend/app/views/subjects/show.html.erb

500 errors generated when selecting view mode from browse page for subjects:
I, [2019-03-04T09:15:47.309906 #3141]  INFO -- : Completed 500 Internal Server Error in 191ms
F, [2019-03-04T09:15:47.315912 #3141] FATAL -- :   
F, [2019-03-04T09:15:47.317235 #3141] FATAL -- : ActionView::Template::Error (undefined method `[]' for nil:NilClass):
F, [2019-03-04T09:15:47.317933 #3141] FATAL -- :      5:   <%= form.label_with_field "public_url", form.hidden_input("public_url") + "<span class='identifier-display'><span class='identifier-display-part'>#{form.slug_url_field("slug", session[:repo_slug], AppConfig[:repo_slug_in_URL])}</span></span>".html_safe %>
6: <% end %>
7: <% if record_type == @repository %>
8:   <%= form.label_and_textfield "slug", :field_opts => {:readonly => …

Use correct record_types in slug partial display

---

frontend/app/views/jobs/new.html.erb

Eliminates the toolbar and sidebar for background jobs since it doesn't serve much purpose.
Toolbar and sidebar was recently added to jobs form as part of a larger refactor of the jobs form, but it is not really necessary and may be confusing.
Sidebar and toolbar no longer show up on background jobs form
Previous:
Now:

get rid of toolbar and sidebar for background jobs

---

backend/app/exporters/serializers/ead.rb

Currently data is only run through escape_content if <p>s are allowed.  This runs non-p data through escape_content as well.  The EAD3 serializer already does this.
ANW-751
Bug fix
Tested with examples given in ticket
ran backend:test

Fix problem of unescaped ampersands in single-part fields

---

build/build.xml
public/spec/spec_helper.rb

Provides the ability to run select public tests, in a similar way as implemented in the backend.
Allows users to provide a filepath to a public spec and have only that one spec run.  So, for example:
`build/run public:test -Dspec="features/accessibility_spec.rb"`
will run only the tests in `accessibility_spec.rb`.
Also, since individual specs may now be run in isolation, it is possible to reach the end of testing and not have mizuno fire up.  Added a ternary to confirm that mizuno is actually running before attempting to stop it.  
No longer requires the entire public test suite to be run to test one area of the code.
Tested manually.  Can still run all tests with build/run public:test, while also being able to specify single spec files (similar to specifying a single test via the example …

Allow running of individual public specs

---

public/app/helpers/json_helper.rb
public/app/models/record.rb
public/app/views/shared/_multi_notes.html.erb
public/app/views/shared/_record_innards.html.erb

In stead of merging notes of the same type together (with the second heading deemphasized) show notes separately with labels emphasized equally.
[ANW-344](https://archivesspace.atlassian.net/browse/ANW-344)
When multiples of the same note are included in a resource record, the heading for the second iteration of the note appears with less emphasis, so that it looks like a sub note.
Checked in public interface that notes of same type are now equally emphasized.

ANW-344: show separate headings for multiple notes of same type

---

frontend/app/assets/javascripts/mixed_content.js
frontend/app/views/notes/_template.html.erb
frontend/vendor/assets/stylesheets/codemirror/codemirror.less

The note content box now automatically expands to fit the text inside it. Additionally, it expands with enough padding to ensure that the highlight wrap in tag feature always has enough space and shows up.
[ANW-217](https://archivesspace.atlassian.net/browse/ANW-217)
[ANW-260](https://archivesspace.atlassian.net/browse/ANW-260)
It would be more convenient when writing notes to have the text box dynamically expand to fit the content.
The wrap in tag highlighting feature is only usable when highlighting text that appears towards the beginning of a note field. When trying to invoke the feature towards the bottom of a note field with several paragraphs of text, the "wrap with" popup is not visible when highlighting text.
Checked that the note content box resizes appropriately when adding a …

ANW-217 and ANW-260: Note content box

---

frontend/app/views/resources/_sidebar.html.erb

Adds a link to the side navigation bar to the revision statements section for resource records.
[ANW-872](https://archivesspace.atlassian.net/browse/ANW-872)
Revision statements are the only section for resources that does not have a sidebar link. This makes navigation more difficult.
Checked that a link now appears for revision statements both on view and edit and it works appropriately.

ANW-872: add link for revision statements

---

reports/users/user_groups_report/en.yml
reports/users/user_groups_report/es.yml
reports/users/user_groups_report/fr.yml
reports/users/user_groups_report/jp.yml
reports/users/user_groups_report/user_groups_report.rb

Add a user (permission) groups report.
Report lists all users and identifier, name, department, email, telephone, source, is_system_user (bool), is_hidder_user (bool), title, and descriptions of the permission groups they belong to. 
```
{
"id": 1,
"identifier": "admin",
"name": "Administrator",
"department": null,
"email": null,
"telephone": null,
"source": "DBAuth",
"is_system_user": 1,
"is_hidden_user": 0,
"title": null,
"groups": [
{
"description": "Administrators"
}
]
},
```
On PDF and HTML output formats, SYSTEM_USER and/or HIDDEN_USER is appended to the source line if those values are true; otherwise they are not indicated. But boolean values are output for JSON or CSV output. 
Tracking and managing users and their permission group membership. 
This has been in production use …

Add User Groups Report

---

common/config/config-defaults.rb
public/app/controllers/concerns/searchable.rb
public/app/services/archives_space_client.rb
public/spec/controllers/concerns_controller_spec.rb

The solr_params AppConfig values were not being passed into the PUI for searches. This fixes that issue.

Fix to solr params from config.rb file for PUI

---

backend/app/converters/ead_converter.rb
backend/app/exporters/examples/ead/at-tracer.xml
backend/spec/lib_ead_converter_spec.rb

If `<corpname>`, `<famname>`, or `<persname>`'s contain `audience` attributes, respect that attribute.  Default to internal/unpublished if no attribute present.  Also, updated the at-tracer.xml sample to include some attributes in order to add tests to `lib_ead_converter_spec.rb`.
Added tests to `lib_ead_converter_spec.rb`.

Respect audience att on EAD import, add tests

---

common/locales/enums/en.yml
common/locales/enums/es.yml
common/locales/enums/fr.yml
common/locales/enums/ja.yml

Added a translation for note_bibliography which is the default label for bibliography notes in the PUI.
[ANW-824](https://archivesspace.atlassian.net/browse/ANW-824)
Previously, bibliography notes were given no header if a label was not specified.
Checked in public interface that bibliography notes now show up with  a label.

ANW-824: add translation for note_bibliography

---

indexer/app/lib/indexer_common.rb
indexer/app/lib/indexer_common_config.rb
public/app/controllers/agents_controller.rb

Added some fields to the index record for classifications for the creator agent so that the classification will show up in the linked records for that agent both in the staff interface and the PUI. **This will require re-index to take effect.**
[ANW-232](https://archivesspace.atlassian.net/browse/ANW-232)
There's no classification record in the search result page, even when an agent is linked as the creator of this classification. This information should show up somewhere.
Looked to see that classifications now show up in linked records for agents in both the staff and public interface.
Classification with creator:
That creator in SUI:
That creator in PUI:

ANW-232: make classifications show up as linked records for agents

---

backend/app/lib/job_runners/trim_whitespace_runner.rb
common/locales/en.yml
common/locales/es.yml
common/locales/fr.yml
common/locales/ja.yml
common/schemas/trim_whitespace_job.rb
frontend/app/views/jobs/_form.html.erb

Create a background job that cleans up leading and trailing white space in title fields.
[ANW-313](https://archivesspace.atlassian.net/browse/ANW-313)
Whether by human error in data entry or by copying and pasting existing inventories, titles may have leading or trailing white space it would be good to have an automated way to clean up the data. 
Checked that background job finds and corrects all titles with leading or trailing white space for resources, archival objects, accessions, digital objects, and digital object components.

ANW-313: add background job to trim title whitespace

---

public/app/views/shared/_result.html.erb

In stead on only showing the resource title in the link in context, show the resource identifier and title separated by a comma.
[ANW-326](https://archivesspace.atlassian.net/browse/ANW-326)
The resource identifier is not currently shown for archival object search results. This can make it difficult to understand the context of a record.
Tested that the resource identifier now shows up along with the resource title.

ANW-326: show resource identifier for archival objects in search results

---

backend/app/model/assessment.rb

Handle deleting of assessment attribute notes linked to an assessment when deleting the assessment so it does not fail.
[ANW-670](https://archivesspace.atlassian.net/browse/ANW-670)
If there is a note in the ratings section of an assessment record, you get an error when attempting to delete.
Checked that you can now delete an assessment with assessment attribute notes and that it deletes the appropriate attribute notes records from the database.

ANW-670: handle deleting assessment attribute notes when deleting assessment

---

public/app/views/pdf/_archival_object.html.erb
public/app/views/pdf/_resource.html.erb
public/app/views/pdf/_toc.html.erb

PUI PDFs would not generate because the views did not take into consideration that the notes were arrays of hashes
Now I am able to generate a PDF from the PUI

A note is an array of hashes so need to iterate over each hash to get to the data for the PDF

---

frontend/app/helpers/search_helper.rb
frontend/app/views/search/_context.html.erb
frontend/spec/selenium/spec/search_spec.rb
selenium/spec/factories.rb

Under specific circumstances searches can fail when the search results returned contain a suppressed record in the "Found in" column and the user conducting the search does not have permission to view suppressed records.
Added two checks in `search_helper.rb` and the context column partial to avoid nilMethod errors.
Also, copied existing tests from `selenium/search_spec.rb` to newer `frontend/spec/selenium/spec` directory, and added 3 new tests to check context column behavior.
Reported to users group email list by Kevin Clair 4/25/19.
To remedy bug in context column. 
Added three new tests.  All existing and new tests passed.

Handle suppression in found_in column

---

backend/app/lib/slugs/slug_helpers_generate.rb
common/config/config-defaults.rb
frontend/app/views/jobs/_show_templates.html.erb

Do not create human readable URL if there are two backslashes in the data
In the config.rb file, ensure use_human_readable_urls parameter is defaulted to false and move setting of new parameter above the human readable url parameters to make sure it doesn't look like it is part of that
Since generation of slugs is not a repository scoped background job, there is no need to include the current repository in the background job page

More release updates

---

public/app/views/pdf/_archival_object.html.erb
public/app/views/pdf/_resource.html.erb
public/app/views/pdf/_titlepage.html.erb
public/app/views/pdf/_toc.html.erb

Small fix for subnotes that have ampersands. This escapes the &amps and turns them into plain old & when printing to a PDF.
Just a good ol' `.gsub(/&amp;/,'&')`
https://archivesspace.atlassian.net/browse/ANW-822
Printing PDFs with an & in the note or subnote ends up looking bad.

Also escape ampersands on subnotes

---

public/app/controllers/concerns/manipulate_node.rb
public/app/views/pdf/_archival_object.html.erb
public/app/views/pdf/_resource.html.erb
public/app/views/pdf/_titlepage.html.erb
public/app/views/pdf/_toc.html.erb

Fix unintentional issue with handling linebreaks in PUI pdf generation.  Also moves all handling of PUI pdf ampersands to an updated process_mixed_content method.
Fix bug introduced in #902 
1. Updated regex used for ampersands in process_mixed_content.
2. Removed ampersand related gsub's from pui pdf views.
3. Outputs raw content from pui pdf views.
Note: Public tests not run because they are currently failing in master for an unrelated reason.

Allow ampersands and mixed content with linebreaks

---

backend/app/lib/job_runners/generate_slugs_runner.rb

Change up the permissions required for running the slugs generation background job, only allow users with administer_system permissions to run job.

Only allow administer_system users to run background job for slug gen

---

public/app/views/shared/_result.html.erb
public/app/views/shared/_single_note.html.erb
public/spec/controllers/resources_controller_spec.rb
public/spec/factories.rb
public/spec/features/record_innards_spec.rb
public/spec/features/resources_spec.rb
public/spec/spec_helper.rb

Fixes ANW-900.  Respects inheritance settings from AppConfig when displaying scope and contents notes on record pages and search results page.
Added checks for 'is_inherited' to the shared `single_note` and `result` partials.
Also, added new `record_innards` spec with a test to confirm inheritance is/is not conveyed on a resource and archival object page.
Updated 2 existing tests to reflect addition of new resource created in `spec_helper`.
https://archivesspace.atlassian.net/browse/ANW-900
Fixed bug in ANW-900.
Tested manually and added new public test.
Context conveyed on search results page:
Context conveyed on record page:

Show scope note inheritance on record page and search results

---

public/Gemfile
public/Gemfile.lock

Bump Capybara for public tests to 3.15.1 (latest that supports Ruby >= 2.3.0) to clear several deprecation warnings with public tests.
Bump Capybara.  Deprecations discovered while working on #1589 .
Resolves numerous deprecation warnings in public tests.
Tests run without deprecation warnings.
Prior to change:

Update Capybara for public tests

---

backend/app/lib/crud_helpers.rb
common/locales/en.yml
common/locales/es.yml
common/locales/fr.yml
common/locales/ja.yml
frontend/app/views/shared/_form_messages.html.erb

Error messaging when attempting to save duplicate agents included several "translation missings."
* Added `translated` key to errors of the type `conflicting_record` so that the application would not attempt to translate the conflicting record URI.
* Provided a translations for the `conflicting_record` error.
* Pointed to that new translation when the error key was `conflicting_record`.
Remove translation missing messages.
Testing manually, automated tests pass.
Before
After

Missing translation

---

Dockerfile
docker-compose.yml

The Ubuntu base image is bigger (image size ~600mb, so still very reasonable) but should be more consistent for package installation / versions.

Use ubuntu base image

---

backend/app/lib/crud_helpers.rb
common/jsonmodel_i18n_mixin.rb

Additional fix to finish off #1592 .
Explicitly skips attempts to translate error message when that error message has the key `conflicting_record`.
Remove translation missing error from error message received when attempting to create a duplicate agent.
Tested manually, existing tests pass.

Don't attempt to translate URI

---

frontend/app/views/agents/_merge_dropdown.html.erb
frontend/app/views/shared/_event_dropdown.html.erb
frontend/app/views/shared/_merge_dropdown.html.erb
frontend/app/views/shared/_templates.html.erb

Fixes a few staff UI styling issues.
Updated merge dropdown partials (shared and agent merge) to fix spacing issue in dropdown menu.  Also, added btn-default class to event dropdown and shared template buttons to add default button styling.
Tweak staff side UI styling inconsistencies.
All existing tests pass.
Merge dropdown before fix:
Merge dropdown after fix:
Event dropdown before fix:
Event dropdown after fix:

Staff UI tweaks

---

frontend/app/assets/javascripts/ajaxtree.js.erb
frontend/app/controllers/archival_objects_controller.rb
frontend/app/controllers/classification_terms_controller.rb
frontend/app/controllers/digital_object_components_controller.rb
frontend/app/views/archival_objects/_form_container.html.erb
frontend/app/views/classification_terms/_form_container.html.erb
frontend/app/views/digital_object_components/_form_container.html.erb

When adding an archival object, digital object component, or classification term using the 'add sibling' button, the new component will be added directly after the component that was selected when 'add sibling' was initiated rather than at the end of that level.
[ANW-373](https://archivesspace.atlassian.net/browse/ANW-373)
Currently, new siblings are always placed at the bottom of the list of siblings, which can be extremely annoying when trying to insert a new object in a long list.
Checked that new siblings now appear after selected node in view and that they are saved here when the record is saved.

ANW-373: add siblings in tree directly under selected node in stead of at end

---

common/config/config-defaults.rb
common/locales/en.yml
common/locales/es.yml
common/locales/fr.yml
common/locales/ja.yml
public/app/views/shared/_present_list.html.erb

Add the ability to show subject sources along with the subject heading in the PUI if a config option is turned on.
[ANW-253](https://archivesspace.atlassian.net/browse/ANW-253)
There may be subjects with headings that are identical or nearly identical, so in these cases it is necessary to show the subject source in order to distinguish between them.
Checked that the subject sources show up if and only if the config option is turned on.

ANW-253: Show subject source in record's subjects listing

---

backend/app/lib/rest.rb

Fixes #1560 by avoiding alteration of `@prepend_to_autodoc` when no content is passed into the method.

Only set prepend_to_autodoc if writing docs

---

backend/app/exporters/lib/export_helpers.rb
backend/spec/export_ead3_spec.rb
backend/spec/export_ead_spec.rb
backend/spec/fixtures/oai/agents.json
backend/spec/fixtures/oai/resource.json
backend/spec/model_oai_spec.rb

Ensure that the published status of a non-creator agent is respected on EAD export and via oai_ead.
Added a check for published status to `export_helpers.rb`.  Updated existing tests and added 2 new tests to confirm publication status is respected via OAI.  
https://archivesspace.atlassian.net/browse/ANW-906
Bug fix to address lack of published status check for controlaccess agents.
Tested manually (EAD export and OAI GetRecord).  New and existing tests pass.

Respect published status of non-creator agents for EAD

---

backend/app/exporters/models/labels.rb
backend/app/lib/export.rb
backend/app/lib/job_runners/container_labels_runner.rb
backend/spec/export_label_spec.rb
backend/spec/factories.rb
backend/spec/model_container_labels_job_spec.rb
common/locales/en.yml
common/locales/es.yml
common/locales/fr.yml
common/locales/ja.yml
common/schemas/container_labels_job.rb
frontend/app/assets/javascripts/jobs.crud.js
frontend/app/controllers/exports_controller.rb
frontend/app/views/exports/container_labels.html.erb
frontend/app/views/jobs/_form.html.erb
frontend/app/views/jobs/_show_templates.html.erb
frontend/app/views/resources/_toolbar.html.erb

The download container labels functionality can timeout for resources with larger numbers of archival objects. To address this a) refactored the labels code to not hold onto a list of objects by incrementally writing processed rows to tsv, b) for the api, stream the response from the generated tempfile, c) for the ui, pushed the feature to a background job.
https://archivesspace.atlassian.net/projects/ANW/issues/ANW-880?filter=myopenissues
Tested with database containing resources that would timeout using existing download container labels functionality.

Background job for container labels

---

public/app/models/resource.rb
public/app/views/resources/_infinite_item.html.erb

Currently, the PUI doesn't display language of materials information in the linked data in the html source.  This appears to be a simple oversight because the code that is present is looking for the language key in a place where it does not exist (at least not anymore?).  This corrects that.
Currently broken and discovered when preparing to make changes for [ANW-697] and [ANW-382].
Visually inspected.  No existing tests fail.

Pui language

---

common/config/config-defaults.rb
docs/doc/file.configuration.html
docs/user/configuring-archivesspace.md

Issue #1618 describes how a comment in `config-defaults.rb` doesn't align with the actual configuration - while the comment says that Solr backups run at midnight, they run hourly instead.  This error was also present at some points in documentation, which have also been updated.
#1618 
Documentation shouldn't disagree with features, esp. regarding backup scheduling.
Untested (sorry!)

solr_backup_schedule cron schedule fix

---

.travis.yml
public/app/views/resources/_finding_aid.html.erb

Display the translation value (e.g. Describing Archives: A Content Standard) for Finding Aid Description Rules instead of the code (dacs) in the "Finding Aid & Administrative Information" of a PUI Resource record. 
Updated the `resources/finding_aid` template to provide the translation.
https://archivesspace.atlassian.net/browse/ANW-604
Enhanced PUI user experience.

ANW-604 Provide translation for description rules in PUI

---

Dockerfile

The "maintainer" label is being applied during the creation of the `build_release` stage of the container build, instead of the final build stage. This means that the maintainer label has not been distributed with the `archivespace/archivespace` image.
```
austin@debian:archivesspace$ docker image pull archivesspace/archivesspace:2.6.0
2.6.0: Pulling from archivesspace/archivesspace
Digest: sha256:a3c0f3fea4159b5410eff52df5669c86a20f179e7a98c8b2ad252f9bf742fad8
Status: Image is up to date for archivesspace/archivesspace:2.6.0
austin@debian:archivesspace$ docker image inspect archivesspace/archivesspace:2.6.0 -f "{{json .Config.Labels}} {{json .ContainerConfig.Labels}}"
null {}
```
Using Nginx as an example:
```
austin@debian:archivesspace$ docker image pull nginx && docker image inspect …
```

Corrected Maintainer Label

---

common/config/config-defaults.rb
common/config/config-deprecated.rb
common/config/config-distribution.rb

As of release 2.5.2, these settings should be set in the Staff User interface. To change these settings, select Manage OAI-PMH Settings from the System menu in the staff interface. These three settings are at the top of the page in the General Settings section

Removed DEPRECATED OAI Settings

---

public/app/views/pdf/_archival_object.html.erb

Update in response to testing:
- Include control value language of material in PUI PDF if language of material note is not present.

ANW-697: Use same langmaterial logic for AOs in PUI PDF

---

backend/app/exporters/serializers/ead.rb
backend/spec/export_ead_spec.rb

Make sure only specified attributes for specified tags have xlink added on export. The tags specified are: arc, archref, bibref, extptr, extptrloc, extref, extrefloc, linkgrp, ptr, ptrloc, ref, refloc, resource, and title. The specified attributes are: actuate, arcrole, entityref, from, href, id, linktype, parent, role, show, target, title, to, and xpointer.
https://archivesspace.atlassian.net/browse/ANW-669
xlink is required to generate valid EAD exports.

ANW 669 - Add xlink attributes for EAD export

---

common/db/migrations/123_create_lang_materials_schema.rb

The 123 migration was improperly migrating encoded scriptcodes in language of material notes into their own language_and_script records, resulting in indexer errors.
Migrates scriptcodes (which cannot live on their own in resource records) into the same language_and_script records as encoded languages.
https://archivesspace.atlassian.net/browse/ANW-697
Bug encountered when migrating a database with existing scriptcodes.
Manually tested against previously failing database.

ANW-697: Fix scriptcode migration

---

frontend/app/views/digital_object_components/_form_container.html.erb
frontend/app/views/digital_object_components/_rde_templates.html.erb

Updates the digital object component RDE template to account for changes to the language of materials model made in #1666 
Updated RDE template.
Also addressed two unrelated/preexisting issues with the DO RDE template:
- Changed extents section from templating using `archival_object["extents"]` to `digital_object_component["extents"]`
- Fixed styling of resulting digital object component edit form to make Basic Information an <h3> instead of <h2>
Required for full implementation of #1666

ANW-697: Update DO RDE for new languages

---

common/db/migrations/126_cleanup_preferences.rb
common/schemas/defaults.rb

Further cleanup following #1666  This PR removes "language" as a configurable user-defined browse option for resource records.  Also removes the old languages of material note from the note_order preference section.
Prior to fix:

Anw 697 resource browse

---

backend/app/lib/slugs/slug_helpers_eligibility.rb
backend/app/lib/slugs/slug_helpers_generate.rb
backend/app/model/ASModel_sequel.rb
backend/spec/model_repository_spec.rb

Repositories handled as a special case and adding repositories to the BASE_RECORD_TYPES messes up the handling of slug deduplication

Removed Repository from slug BASE_RECORD_TYPES

---

common/db/migrations/126_cleanup_preferences.rb

Small tweak to the 126 migration introduced in #1680 that accounts for the possibility that the defaults JSON object may be lacking a note_order array.
Utilized safe navigation operator when checking for presence of langmaterial in the note_order array.
At least one user experienced issues upgrading their database with the following error:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! !!
!! Database migration error. !!
!! Your upgrade has encountered a problem. !!
!! You must resolve these issues before the database migration can …
```

Accounts for potentially missing note_order array

---

backend/app/model/search.rb
common/config/config-defaults.rb

Added a config option to determine whether to limit the columns in the csv (i.e. option to do it the old way)
[ANW-250](https://archivesspace.atlassian.net/projects/ANW/issues/ANW-250)

Old way CSVs Option: config option not to limit the csv fields

---

indexer/app/lib/pui_indexer.rb

Small optimization for pui indexer tree node deletion. In some cases process can generate large numbers of nodes to delete (400k seen in most extreme case) so batching creates much more reasonable Solr update queries and provides more visibility in the log (vs. appearing to be "hung").

Process tree node deletes in batches

---

backend/spec/export_ead3_spec.rb
backend/spec/export_ead_spec.rb

Fixes EAD export tests that regularly fail by: 
- For EAD 2002 - specifying by id the specific dimension or physfacet content that should be mapped
- For EAD3 skipping the dimensions and physfacet tests with xit (explained below).
According to http://eadiva.com/physdesc/ :
> More importantly, much of [physdesc's] functionality was moved to <physdescstructured> and it was left with only generic elements. It **may not longer contain** `<dimensions>`, `<extent>`, or `<physfacet>`.
Therefore, tests that were mapping dimensions and physfacet to inside of <physdesc> have been skipped since this is not valid EAD3.
To get these tests to stop arbitrarily failing ;-)

Fix or skip regularly failing EAD export tests

---

common/config/config-defaults.rb
public/app/assets/javascripts/smart_staff_links.js
public/app/views/layouts/application.html.erb

The new configuration option is AppConfig[:pui_staff_link_mode] which is defaulted to 'edit' which is what currently happens in the core code base. If it gets changed to 'readonly', it opens the record in the staff interface in readonly/view mode.
https://archivesspace.atlassian.net/browse/ANW-874
If the person pressing on the staff link in the PUI doesn't have permission to edit the record in the staff interface, the link fails.
Manually checked that the mode changes when change value for new configuration option AppConfig[:pui_staff_link_mode]

Add new configuration option for mode the staff link on the PUI opens records in the staff interface

---

frontend/app/views/container_profiles/_listing.html.erb
frontend/app/views/linked_events/_show.html.erb
frontend/app/views/locations/_batch_form.html.erb
frontend/app/views/search/_listing.html.erb
frontend/app/views/top_containers/bulk_operations/_results.html.erb
frontend/app/views/top_containers/bulk_operations/_search_criteria.html.erb
frontend/config/locales/en.yml
frontend/config/locales/es.yml
frontend/config/locales/fr.yml
frontend/config/locales/ja.yml

Minor accessibility improvements for the Manage Top Containers views.  Also, abstracting selecting screen reader only label text out from being hardcoded in the view to utilizing two new locales.
Accessibility weaknesses uncovered while working on ANW-462.
Fixed the errors in red below:

Manage Top Containers accessibility enhancements

---

launcher/launcher.rb

launcher.rb was not correctly interpreting pre-configured AppConfig[:frontend_cookie_secret] and AppConfig[:public_cookie_secret] when they were set in config.rb.
launcher.rb was looking for AppConfig[:frontend_cookie_secret_cookie_secret]/AppConfig[:public_cookie_secret_cookie_secret], creating new secrets in .dat files and using them instead.
[ANW-864](https://archivesspace.atlassian.net/projects/ANW/issues/ANW-864)
I've been working on clustering and more specifically Kubernetes and releasing a Helm chart for ArchivesSpace.  Found that Staff/PUI cookies were not matching when scaling up the frontends.  
Cut a ZIP release with this launcher and started it in normal single-node mode. It created a data/frontend_cookie_secret.dat file and uses it.
Then I pre-set …

[ANW-864] launcher.rb - was looking for AppConfig[:frontend_cookie_secret_cookie_secret]

---

.rubocop.yml
_yard/Gemfile
backend/spec/model_solr_spec.rb
frontend/Gemfile
oai/Gemfile
plugins/newrelic/Gemfile

Corrected test because of rubocop warning (single ] with no initial [). Moving forward, run rubocop on more than just Gemfiles. Also added a few configuration items and excluded the docs directory.

Ran rubocop on all Gemfiles

---

backend/app/controllers/preferences.rb
backend/app/controllers/rde_templates.rb

The `check_permissions` method was defined in `preferences.rb` and `rde_templates.rb` both within the `ArchivesSpaceService` context, which results in the former being overridden.

Deduplicate check permissions for prefs & rde

---

indexer/app/lib/indexer_common.rb

Added some fields to index to make component ids show up in browse view under identifier.
[ANW-216](https://archivesspace.atlassian.net/browse/ANW-216)
From the browse view for resources or digital objects, if you click show components, the identifier column was always blank for the components even if they have a component level identifier.
Checked that component id now shows up in the situation described above.
Not a breaking change but will require a re-index to go into effect

make component ids show up in browse view

---

frontend/app/assets/javascripts/search.js
frontend/app/views/search/_listing.html.erb

Adds a "select all" checkbox to all search listing results similar to that used in Manage Top Containers.  The select all option is only visible to those with permissions that allow multiselect on search pages. 
While ANW-975 only specifically asks for this behavior on the locations search results page, that is managed by the shared search listing partial so this change impacts all search results lists that 1. have a multiselect option, and 2. for users with the permission to multiselect items.
https://archivesspace.atlassian.net/browse/ANW-975
Reduce clicking when wishing to select all items on a page of search results.
All existing tests (including frontend tests) pass.  Visually confirmed as working.

ANW-975: Add select all option to all search listings

---

backend/app/converters/ead_converter.rb

The EAD importer does not currently retain content in the option `@label` attribute.  This PR remedies that.
Updated the `make_single_note` and `make_nested_note` methods to utilize the `@label` attribute if present.
https://archivesspace.atlassian.net/browse/ANW-149 
Manually tested; confirmed all existing tests passed.
EAD with labels:
Notes with labels:

ANW-149: Import @label attribute if present for physdesc note types

---

backend/app/lib/crud_helpers.rb

For `handle_listing` api results apply conventional order (by id ASC) when no order is supplied.
2 issues have been pointed out: a) currently retrieving a list of records can appear unordered (it isn't clear what the default sort method is) b) without an explicit order (required by pagination) the results are non-deterministic and therefore it's possible to get "duplicate' results (where the same record appears in different pages).
Applied via a plugin on a set of sites where problem was identified. Confirmed issue was resolved.

Deterministic order by id unless order provided

---

backend/app/model/mixins/relationships.rb
backend/spec/model_repo_transfers_spec.rb
frontend/app/views/transfer/_transfer_failures.html.erb
frontend/config/locales/en.yml
frontend/config/locales/es.yml
frontend/config/locales/fr.yml
frontend/config/locales/ja.yml

Currently, if a user attempts to transfer a digital object record that has an instance link to a repo-scoped record (e.g. resource or archival object) the DO will transfer, but leaves behind a broken instance relationship.  This results in a number of problems:
- The related record (resource or ao) returns a false Record Not Found error in the interface (even though the record is still in the db);
- The transferred DO is not properly indexed and not searchable in its new repo; and,
- If the user go directly to that DO using it's uri a "server error" is returned.
The only way to resolve this bug is to go back into the database and manually update the DO's repo back to it's original repo.
This PR makes it impossible to transfer a DO that has an instance relationship with another repo-scoped …

ANW-151: Don't allow transfer of DO's linked to repo-scoped records

---

frontend/app/views/digital_objects/_linker.html.erb

When opting to merge digital objects, the linker form provided allows you to select the currently active digital object to merge into (e.g. you can attempt to merge a digital object into itself).  This fix ensures that the currently active record is excluded from the linker form in the same manner that it is done with other major record types (resources, accessions, subjects, etc.).
Added `exclude_ids` to the digital objects linker in the same fashion is used in other major record linkers.
https://archivesspace.atlassian.net/browse/ANW-145 
Do not allow users to attempt to merge digital objects into themselves.
Manually tests; existing tests passing.

ANW-145: Exclude current record from digital object merge

---

frontend/app/views/accessions/edit.html.erb
frontend/app/views/accessions/show.html.erb

Accession display strings containing markup (e.g. <title render="italic">) weren't being properly rendered in the form/show views.  This brings accession records into line with the other major record types and ensures that marked up display strings are italicized/styled inside the <h2>.
Call `clean_mixed_content` on <h2> content as is already done elsewhere (aos, resources, digital objects, etc.).
Visually inspected, automated tests pass.
Prior to fix: 
After fix:

Render marked up display strings in accession show/edit h2s

---

frontend/app/models/mixins/record_children.rb

When creating multipart notes using RDE the main note section is set to published, but the subnote (containing the provided content) is not.  This PR fixes this incongruity by ensuring both values are set to "true" on create (this is the existing behavior for singlepart notes).
Updated the `record_children` mixin to ensure text subnotes are also defaulting to published on create.  Publication defaults set in preference are still respected on record creation outside of RDE, so if the preference checkbox for publish is unchecked, notes (and other subrecords) creating manually/not created inside the RDE will remain unpublished.
https://archivesspace.atlassian.net/browse/ANW-873
Visually inspected and automated tests passing.
Prior to this PR multipart notes created from RDE had both …

ANW-873: Subnotes created from RDE should be published

---

frontend/app/assets/javascripts/agents.browse_merge.js
frontend/app/views/search/_listing.html.erb

The additional of the select_all checkbox in #1726 can potentially have the unintended consequence of reloading a search listing page with individual checkboxes selected but the select_all box unselected.  This forces autocomplete to off for the multiselect column inputs for search listing results to avoid this behavior if the user uses the browser's back button.
This PR sets autocomplete to off for the multiselect inputs.  It also ensures that multiselection will work on agents by including the multiselect js in agents.browse_merge.js (since agents does not natively inclue search.js).
https://archivesspace.atlassian.net/projects/ANW/issues/ANW-975
Tested manually.
Improper behavior prior to this PR.

ANW-975: Update to handle back button

---

frontend/app/helpers/application_helper.rb

Display strings/titles containing markup (e.g. `<title render="italic">`) weren't properly parsed by the `render_token` method, resulting in all content inside tags being dropped altogether.
Calling `clean_mixed_content` on the label attribute passed to `render_token`.
https://archivesspace.atlassian.net/browse/ANW-760
Manually inspected; automated tests pass.
Italicized content is no longer being dropped from the "Active restrictions" table on a top container record.

ANW-760: Don't drop content in title tags inside record linkers

---

backend/app/converters/ead_converter.rb
backend/spec/lib_ead_converter_spec.rb

#992 Related JIRA Ticket or GitHub Issue
[https://archivesspace.atlassian.net/projects/ANW/issues/ANW-152](url)
Tested locally with a number of EADs containing agents with authfilenumbers

ANW-152: Get agent authority_id from @authfilenumber instead of @id

---

backend/app/model/mixins/components_add_children.rb
frontend/app/controllers/archival_objects_controller.rb
frontend/app/controllers/digital_object_components_controller.rb
frontend/app/controllers/digital_objects_controller.rb
frontend/app/controllers/resources_controller.rb

A pass at fixing #1633 
The RDE will show errors related to JSONModel, but it also needs to show
things that pop up when the records are put into the DB. For example,
DO components require unique identifiers. If the RDE hits an issue when
trying to save, this will slightly modify the error message and just
display the message in the RDE error flash.
I tried it out locally. Make a DO, then go into the RDE. Make 2 records with the same identifier. 
You should see the error message and not the "Error with 0 rows..."

Show an error message when the RDE hits a Sequel validation error

---

backend/app/model/db.rb

This modifies the database table UTF-8 check to accept anyt character set starting with 'utf8', so that eg. 'utf8mb4' is accepted.
Fixes #1697 
'utf8' is currently a 3-byte UTF-8 encoding, not capable of storing the Unicode supplementary range.
'utf8mb3' and 'utf8mb4' are also valid names, the former is an alias to 'utf8', the latter is the one people should be using for full Unicode compatibility.
Ran backend:devserver against MariaDB 10.3 and MySQL 5.7, the change made them accept both 'utf8' and 'utf8mb4'.

recognise more utf8 encodings

---

build/build.xml

Solr index and demo database was being deleted every time the frontend devserver was starting up.
That has been moved to its own task solr-db-delete and taken out of the frontend:clean task.
https://archivesspace.atlassian.net/browse/ANW-1005

Remove solr and demo db deletion from frontend:clean ant task

---

backend/app/exporters/serializers/mets.rb
backend/spec/export_mets_spec.rb

This PR addresses two issues in the METS export:
1. Incomplete schema reference to schema location (currently "http://www.loc.gov/standards/mets/mets.xsd"; should be "http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/mets.xsd")
2. Date formatting for CREATEDATE attribute in metsHdr should be ISO 8601 extended, e.g.: 2019-12-17T13:26:34-05:00
https://archivesspace.atlassian.net/browse/ANW-937
Added a test for ISO 8601 compliance to the export_mets_spec and updated the schema location test. Ran backend test suite successfully.

ANW-937: Fixes to METS export

---

backend/app/exporters/serializers/ead.rb

Fix export of language notes containing XML as CDATA in langmaterial elements in EAD 2002.
Add fragments argument to serialize_languages method, as with other serialze_* methods, and the EAD3 version of the same method.
#1721 
Bug fix, see issue.
Tested on development system with test data as per issue. Does not cause any existing backend unit tests to fail.

Fix EAD export of language notes containing XML as CDATA

---

backend/app/model/mixins/relationships.rb

If there were no digital object components, the transfer of a digital object to another repository would go through even though it was attached to an archival object.

Make sure to handle transfer of digital objects without digital object components

---

public/app/views/shared/_record_innards.html.erb

Previously the physical description note appeared twice in the PUI: once in the top (non-collapsible) section and again in the collapsible 'Additional Description' section. Now it only appears in the top section.
[ANW-933](https://archivesspace.atlassian.net/browse/ANW-933)

ANW-933: make phys desc note only appear once

---

public/app/controllers/concerns/result_info.rb
public/app/views/shared/_digital.html.erb

Selects the correct Font-Awesome badge icon according to digital_object_type
digital_object_type is already passed to the view encoded as `dig_obj['material']` for digital_objects, where it is used as part of the caption.  Patch also passes it for digital_instances so that it can work consistently in both views. 
Change to the view selects the appropriate icon according to digital_object_type. 
The view itself  is easy to fix in a local plugin, however the fact that the controller helper functions only work for digital_objects and not digital_object_instances ( which both display the same digital object links ), I would consider a bug which makes it difficult to fix this locally in a plugin. 
Tested locally on a wide variety of digital objects and digital object types. 
These patches were …

select correct badge according to digital_object_type

---

build/build.xml

Maven is requiring https and the repo used for jetty failed security certification
I was able to retrieve required war and jar files

Change maven urls to use https and get jetty jar file from a different repo

---

common/config/config-defaults.rb
frontend/config/initializers/help.rb
frontend/spec/selenium/common.rb

The help pages have been moved to a new application so the AppConfig[:help_topic_prefix] was replaced with AppConfig[:help_topic_base_url] so need to remove AppConfig[:help_topic_prefix].
- [] Breaking change (fix or feature that would cause existing functionality to change)

Remove unnecessary configuration help_topic_prefix due to help pages refactor

---

build/scripts/migrate_db.rb

Added requirement for activesupport/inflector into the migrate_db.rb.
This change was required due to the use of parameterize in [migration #120](https://github.com/archivesspace/archivesspace/blob/21ae42891ca69416742f9f55625590381cb95219/common/db/migrations/120_clean_slugs_for_repositories.rb#L23).
https://github.com/archivesspace/archivesspace/issues/1784
The migrations were run and completed successfully using the parameterize method.

require active_support/inflector in migrations

---

common/db/migrations/130_reindex_linked_records.rb
frontend/app/views/agents/show.html.erb
frontend/app/views/subjects/show.html.erb
indexer/app/lib/indexer_common.rb
solr/schema.xml

When viewing subjects in the staff interface, the "Linked Records" section lists all the resources, archival objects, etc which have been associated with the subject. But when there are duplicate subjects (e.g. same title/term but different sources) both subjects list the same records. The same can happen for agents.
The problems is the "Linked Records" section is rendered by a call to the _search/embedded_ template, which searches the "subjects" Solr index field for records matching the title of the subject. Searching for the subject's URI instead will return accurate results: only the records which have actually been linked to the subject. This requires creating a new Solr index field called "subject_uris" and modifying the indexer to populate it.
The fix for agents is the same except …

ANW-783: Fix linking issues in subject and agent records

---

backend/app/model/solr.rb
backend/spec/model_solr_spec.rb

This fixes issue #1699, so that advanced searches including Boolean NOT performed via the public user interface will return the correct number of hits.
This essentially reverts https://github.com/archivesspace/archivesspace/commit/d4473b71a4ebe8c0f7030ea3869e435584965cb5 which seems to be the cause for Boolean NOT queries returning too few results, see issue #1699 for an analysis. I haven't heard from the original committer, nor been able to work out why that change was made, although one possibility is that it was needed at the time but the subsequent https://github.com/archivesspace/archivesspace/commit/9b2724fc76af9f2f7de2f5d41df1b22b8c9f5383 commit changed the behaviour of Solr.
#1699 
Possibly also https://archivesspace.atlassian.net/browse/ANW-753
This change has been made on our …

Remove code which adds a match-all clause to negated subqueries

---

frontend/app/assets/javascripts/browse_merge.js
frontend/app/views/shared/_templates.html.erb
frontend/config/locales/en.yml
frontend/config/locales/es.yml
frontend/config/locales/fr.yml
frontend/config/locales/ja.yml

This PR adds a confirmation modal to the merge Container Profiles workflow.
This PR builds off the confirm merge Top Containers work from #1756.
1. frontend/app/views/shared/_templates.html.erb
- add `#merge_container_profiles_modal` template
- add `#confirm_merge_container_profiles_modal` template
2. frontend/app/assets/javascripts/browse_merge.js
- add two modal workflow, passing data through the DOM via event listeners
3. frontend/config/locales/{en|es|fr|ja}.yml
- add i18n copy
[ANW-550](https://archivesspace.atlassian.net/browse/ANW-550)
See above

ANW-550 Add confirm modal to merge container profiles workflow

---

public/app/views/shared/_only_facets.html.erb

This change asks search engine crawlers not to follow the links in facets. Such filtered search pages are not information sources themselves, and do not have distinct titles, so I don't think it is desirable for them to appear in search results.
Soon after we launched, we noticed [Amazonbot](https://developer.amazon.com/support/amazonbot) was the first crawler to hit our public user interface. It honours robots.txt instructions but does not support sitemaps, so it just spiders through all the links in the HTML. Unfortunately, that means it spent most of its time trying every combination of facets in the collections list, until it reached some kind of preset limit and shut down. Instead of throwing wave after wave of search results pages at it, this change allows it to crawl to every …

Add "nofollow" rel attribute to links in facets/filters in PUI

---

frontend/app/assets/javascripts/notes.crud.js
frontend/app/views/notes/_template.html.erb

Creating a language note now only requires one click to load the template.
[ANW-927](https://archivesspace.atlassian.net/browse/ANW-927)
Creating a language note requires multiple clicks even though only one note is possible from this area.
Language note type is selected and template is loaded as soon as you click add note.

ANW-927: make process for creating language notes more efficient

---

frontend/app/assets/javascripts/rde.js

This PR solves ANW-1048 and ANW-1052 by decreasing the scope of the work in #1705 from the global `populateColumnSelector` to the local `initColumnShowHideWidget` in the Rapid Data Entry modal.
1. [ANW-1048](https://archivesspace.atlassian.net/browse/ANW-1048)
2. [ANW-1052](https://archivesspace.atlassian.net/browse/ANW-1052)
Tested against the problems cited in both tickets listed above.
See above.

ANW-1048 and ANW-1052 required column fix

---

backend/app/model/mixins/tree_nodes.rb
backend/spec/tree_position_spec.rb

When editing an archival object, a database constraint violation of the "uniq_ao_pos" index in the "archival_object" table may occur when saving the object, giving an error message similar to the following in the GUI:
```
translation missing: - translation missing: validation_errors.database_integrity_constraint_conflict_javacommysqljdbcexceptionsjdbc4mysqlintegrityconstraintviolationexceptionduplicate_entryroot@/repositories/2/resources/1608-500for_keyuniq_ao_pos
```
While the error message is superficially similar to that described in  AR-1326: DB Constraint Violation for transferred Archival Object positionsAccepted (https://archivesspace.atlassian.net/browse/AR-1326), the fundamental cause is different, as it occurs in ArchivesSpace v2.7.0.
As indicated in James Bullen's April 5, 2017 …

ANW-1020. uniq_ao_pos index constraint violation fix

---

frontend/app/assets/javascripts/utils.js

#1762 accidentally removed the "X" that allows users to close a number of ArchivesSpace alerts by placing the <a> inside of a screen reader only class.  This removes that addition and uses javascript to add an aria-label to the link for accessibility purposes.
Confirmed visually that the X returned, utilized ChromeVox and Wave plugin to confirm that the aria-label is being presented to screen reader users.  Broken Selenium tests that alerted me to this regression are now passing.
X's missing in 2.7.1:
X to close back on alerts:

Ensure alert popups retain "X" to close, but with screen reader labels

---

frontend/app/models/search_result_data.rb
frontend/config/locales/en.yml
indexer/app/lib/indexer_common.rb
public/app/controllers/concerns/handle_faceting.rb
public/app/controllers/objects_controller.rb
public/app/controllers/resources_controller.rb
public/app/controllers/search_controller.rb
public/app/views/shared/_only_facets.html.erb
public/config/locales/en.yml
solr/schema.xml

Enhancement to add a language of materials facet which allows users to filter resources and archival objects by their language of materials.
- New "langcode" Solr field
- New indexer hook to populate that field from the values of language of materials drop-downs. It does not index any additional languages which might be recorded inside language notes (as the language codes used, if any, would not be guaranteed to be ISO-639/2)
- Modifications to PUI to display facet in search and browsing resources and digital objects
- Similar modifications to staff interface
https://archivesspace.atlassian.net/browse/ANW-1018
This is based on modifications made to our production system, which have been in use for six months. But that is running a pre-2.7.0 version of ArchivesSpace. This pull request is …

ANW-1018: Add language facet

---

backend/app/controllers/enumeration.rb
backend/app/lib/exceptions.rb
backend/app/model/enumeration.rb
backend/spec/model_enumeration_spec.rb

- Referenced the possibility of 404 in the `/config/enumerations/migration` endpoint
- Added an `EnumerationMigrationFailed` exception for getting error messages from failed enumeration migrations.
- Swapped the original `"Can't transfer from a read-only enumeration value"` error so it uses the new exception class, so users can see the reason for a failed migration instead of `"Access denied"`.
- Added an exception for cases where a request attempts to merge values in a not-editable enumeration.
- Added an exception for cases where `old_value` does not refer to an existing value.
#1167 
```python
import aspace
client = aspace.client.ASpaceClient(auto_auth=False)
client.authenticate()
client.enumerations.get(2)['editable']
client.enumerations.get(2)['values']
client.enumerations.merge(2, …
```

Improvements to Enumeration Model Migrate

---

frontend/app/assets/stylesheets/archivesspace/common.less
frontend/app/views/welcome/index.html.erb

This PR provides a minor spacing bump to ensure the "Welcome to ArchivesSpace" heading next to the login panel on the front end welcome view doesn't wrap on smaller desktop viewports.
[ANW-953](https://archivesspace.atlassian.net/browse/ANW-953?focusedCommentId=36843&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-36843)
See above

ANW-953 heading tweak

---

backend/app/model/mixins/relationships.rb
backend/spec/controller_merge_request_spec.rb

Small adjustments following 3/18 call:
- Add a `next if` to relationships mixin to remove one indent;
- Add check to confirm desired subject remains linked in the subject merge request spec.

Small refactor to relationships mixin; update subject merge test

---

public/app/models/finding_aid_pdf.rb

This is a very small change to pass the resource record data structure to the template which renders the footer of PDFs generated by the public user interface (completely unrelated to PDFs generated via XSL-FO by the backend.)
This has no effect in stock ArchivesSpace, but makes it easier for plug-in writers to customize the end of the PDFs (e.g. to add indexes or revision statements to end of PDFs.)
None
Makes no functional difference itself so nothing to test.
N/A

Pass resource record to PUI PDF footer template

---

backend/app/model/mixins/relationships.rb

Fixes bug discovered by @cdibella wherein duplicates are not identified and deleted when there are multiple pre-existing relationships prior to record merge.

Address merging items with multiple existing relationships

---

common/config/config-defaults.rb
public/app/views/objects/show.html.erb
public/app/views/resources/infinite.html.erb
public/app/views/resources/show.html.erb
public/app/views/shared/_search_collection_form.html.erb

It is a common customization to add the search-in-collection form to the sidebar on archival object pages. At the Bodleian we have [done it](https://archives.bodleian.ox.ac.uk/repositories/2/archival_objects/113), Yale [do it](https://archives.yale.edu/repositories/6/archival_objects/2621367), and Harvard [do it](https://hollisarchives.lib.harvard.edu/repositories/24/archival_objects/387951). But we've each had to implement it by overriding templates, which is a maintenance issue when it comes time to upgrade to a new ArchivesSpace release. This pull request makes it an option in the config file. And also to add the same form to the collection organization view (which we may be the only ones [to do](https://archives.bodleian.ox.ac.uk/repositories/2/resources/2157/collection_organization).) …

Make displaying search-in-collection form configurable option in other contexts

---

frontend/app/views/accessions/_toolbar.html.erb
frontend/app/views/agents/_toolbar.html.erb
frontend/app/views/shared/_component_toolbar.html.erb
frontend/app/views/shared/_resource_toolbar.html.erb
frontend/app/views/shared/_view_published_button.html.erb

This pull request has two aims:
- Move the code to render the 'View Published' toolbar button to its own shared template. This has the benefits of reducing repetition in the code (replacing multiple lines in the templates for resources, accessions, and agents with a single render call in each) and make it easier for plug-ins to override the behaviour of this button.
- Add the 'View Published' toolbar button to archival objects and digital objects components. Because those can be nested, within other records, an additional check is ensures the button is not displayed if they have an unpublished ancestor.
Each is in a separate commit, so if it was a design choice not to have view published buttons on archival objects then that can be reverted. But it seems like an obvious improvement, and …

Modify the view published button in the staff interface toolbar

---

backend/app/lib/crud_helpers.rb
backend/app/model/mixins/agent_manager.rb
backend/spec/controller_agent_software_spec.rb
backend/spec/controller_conflict_reporting_spec.rb
backend/spec/factories.rb
backend/spec/model_agent_software_spec.rb
common/locales/en.yml
common/locales/es.yml
common/locales/fr.yml
common/locales/ja.yml

Returns the correct conflicting record uri when a user attempts to post an agent record with an authority ID that conflicts with an existing authority ID.
Adds the following to fix the bug described in ANW-292:
- A conditional check in `crud_helpers` to determine if the conflict stems from an authority id or other piece of metadata (e.g. conflicting name);
- Add a new method to `agent_manager` to find a conflicting record based on authority id, as the existing method used to find conflicting records relies on the agent_sha1 which doesn't take into account the value of the authority id.
This fix also required changes to the factory for `agent_software` as it was the only mock agent type that was being created without an authority_id.  Changing this factory also required a few updates to …

ANW-292: Correct conflicting record error on authority id collision

---

backend/spec/model_solr_spec.rb
indexer/app/lib/large_tree_doc_indexer.rb
public/app/controllers/concerns/searchable.rb

ANW-806-pui-and-search
These changes allow solr_params to apply to PUI as they do for SUI.
- Remove duplicate publish from q param (it's in fq)
- Remove types pui from q (types pui covered by publish true)

ANW-806-pui-and-search

---

.github/workflows/backend.yml
.github/workflows/frontend.yml
.github/workflows/public.yml
build/run
common/test_utils.rb
frontend/spec/selenium/spec/resources_spec.rb
frontend/spec/selenium/spec_helper.rb
frontend/spec/spec_helper.rb
public/spec/spec_helper.rb

Support use of `ASPACE_TEST_DB_URL` for the frontend and public tests.
Update workflows to use MySQL for the sui and pui.

Enable mysql for ui tests

---

solr/solrconfig.xml

Turn on Luke request handler so features in the Solr web interface like analysis and term info in the schema browser will work. This makes it easier to diagnose search issues and for developers to experiment with things like alternative tokenizers, stemming, etc. It has no effect on the ArchivesSpace application.
None.
But this is the sort of issue it might help with: http://lyralists.lyrasis.org/pipermail/archivesspace_users_group/2020-April/007531.html
We've had this enabled on all our Solr servers, used by ArchivesSpace and other systems, for years. I am not aware of any security or stability issues with having it enabled.

Enable Luke request handler

---

public/app/controllers/concerns/searchable.rb
public/app/models/search.rb
public/app/views/shared/_facets.html.erb
public/app/views/shared/_search_collection_form.html.erb

This is primarily a fix for date filter parameters not being included in the base URL used by onward links in search results pages. This causes the following bugs:
- Date filters being lost after the first page of results
- Date filters being lost when another filter is applied
Also, while testing those, I found and fixed the following minor display issues:
- An extra close-ul tag causes invalid HTML and inconsistent indenting in the remove-filter links
- When you apply facets, then remove them all, the "Filtered by" heading remains
- Setting a date range in the search-in-collection form works, but there is no way to remove/edit the date range on the results page.
#1610 
https://archivesspace.atlassian.net/browse/ANW-893
https://archivesspace.atlassian.net/browse/ANW-664
Tested on a …

Date filter fixes

---

backend/app/exporters/serializers/ead.rb
backend/app/exporters/serializers/ead3.rb
backend/spec/export_ead3_spec.rb
backend/spec/export_ead_spec.rb

This pull request changes three things:
1. Fixes invalid EAD2002 caused by output of `xlink:audience` attributes when exporting something with digital objects.
2. Attempts to change the logic of when to output an `audience` attribute for digital objects discussed in ANW-805.
3. While adding tests for the above, I noticed the EAD3 exported was invalid when digital objects are linked to a resource, due to the exporter continuing to place `dao` in `archdesc` (which was fine in EAD2002 but wrong in EAD3.)
Regarding number 2 above, here is the new logic implemented described in detail:
- If a digital object is _unpublished_, the exported `dao` or `daogrp`
element gets an `audience` attribute of "internal".
- Any file versions within an _unpublished_ digital object get an
`audience` attribute …

ANW-805: Change logic for when dao/daogrp/daolink get "internal" audience attributes

---

frontend/app/assets/stylesheets/archivesspace/tables.less
frontend/app/assets/stylesheets/archivesspace/top_containers_bulk.less
frontend/app/controllers/search_controller.rb
frontend/app/helpers/search_helper.rb
frontend/app/models/search.rb
frontend/app/views/agents/show.html.erb
frontend/app/views/locations/show.html.erb
frontend/app/views/search/_embedded.html.erb
frontend/app/views/search/_listing.html.erb
frontend/app/views/search/_results.html.erb
frontend/app/views/top_containers/bulk_operations/_results.html.erb
frontend/config/locales/en.yml
frontend/spec/controllers/search_controller_spec.rb
frontend/spec/selenium/spec/events_spec.rb
frontend/spec/spec_helper.rb
indexer/app/lib/indexer_common.rb

Implementation of generalized table configuration as described in #1843, as well as specific  implementation of enhancements to the linked records table on the LocationController#show page that exercise the implementation.  Some additional solr fields on top_container objects were required to implement the desired improvements to the table.
`SearchController#do_search` now takes additional arguments which set display variables and allow for specification of extra columns.  A hash of procs usable as "formatters" is provided, so that output of these columns can be customized.  A number of solr fields are added to support specifically sorting top_containers via indicator, display string, and barcode (there is a combined_indicator field as well, which was provided for a previous …

Generalized table improvements to core

---

backend/app/model/archival_object.rb
backend/app/model/digital_object_component.rb
backend/spec/model_archival_object_spec.rb
backend/spec/model_digital_object_component_spec.rb
common/db/migrations/132_update_display_string.rb
common/locales/en.yml
common/locales/es.yml
common/locales/fr.yml
common/locales/ja.yml

Adds all available dates to the headings of archival object and digital object component records in the staff side and, if published, public side interfaces.
Modifies the archival object and digital object component models to include all dates in the autogenerated record display string.  Because this behavior only happens on create or update from JSON, changes to these models only impacts newly created/updated archival components, therefore migration 132 has also been added to identify and, via information stored in the database, recreate these display strings to address previously created archival components.  Additionally, behavior has been added to prepend dates with a date_type of bulk with "bulk: " in the new record headings.  Translations were also added for this prepended bulk …

ANW-172: Add all dates to ao and do records h2

---

frontend/app/views/assessments/_form.html.erb
frontend/vendor/assets/stylesheets/bootstrap/variables.less

Rearranged existing code to ensure link/hint text about adding additional assessment attributes is visible to users with appropriate permissions even when no additional attributes have been added yet.  On the **edit** page for assessments one of the two should be provided:
- For users with permission to create/update assessment attributes, a link to manage the additional attributes for this repository;
- For users with permission to view the edit form for assessment records, but lacking permission to add/update assessment attributes, hint text should be provided.
Also updated the font color of `text-muted` (used for the above hint text) from light gray to gray to pass color contrast checks.   
https://archivesspace.atlassian.net/browse/ANW-257
Visually inspected, existing tests passed. …

ANW-257: Add hint to adding Assessment Attributes

---

public/app/views/shared/_skipnav.html.erb

Removes skip links from PUI show pages where `#toggleRefineSearch` and `#searchresults` anchors are not present.
On show pages where an `@search` variable is present (record types that may have linked records including agents, subjects, and classifications), search-related skip links were being added based on the check for `@search` on line 4 of `public/app/views/shared/_skipnav.html.erb`.  This change skips all show pages (aside from repositories, where an embedded search is still present) so that skip links with missing anchors aren't generated for agents, subjects, and classifications pages.
Accessibility errors corrected according to WAVE plugin.  Existing public tests passing.
Currently broken skip links:
Links removed:

Remove skip links from show pages

---

backend/app/model/large_tree_resource.rb
backend/app/model/mixins/resource_trees.rb
backend/app/model/top_container.rb
common/db/migrations/133_add_barcodes_to_sub_container.rb
common/schemas/sub_container.rb
common/schemas/top_container.rb
frontend/app/controllers/top_containers_controller.rb
frontend/app/views/sub_containers/_show.html.erb
frontend/app/views/sub_containers/_template.html.erb
frontend/config/locales/en.yml
frontend/spec/selenium/spec/instances_and_containers_spec.rb
indexer/app/lib/indexer_common.rb

This adds a barcode to subcontainers. It is able to be searched for in both the general search, and on the top containers page using the keyword and barcode fields. It is optional, turning on/off using an AppConfig option. Previous PR received comments to remove AppConfig options and to add Selenium test from @mark-cooper . These comments have been addressed.
Manual testing of up/down migrations, addition/subtraction of barcodes, and searching for barcodes in all abovementioned fields.
A Selenium test covers adding a subcontainer barcode and searching for it from the Top Containers page.

Add subcontainer barcodes with test

---

backend/app/model/solr.rb
backend/spec/model_archival_object_spec.rb
backend/spec/model_solr_spec.rb
frontend/app/models/search.rb
frontend/spec/selenium/spec/instances_and_containers_spec.rb

The merged PR for #1699 to improve PUI search disabled the match all
clause for "purely negative expression groups" (arguing that Solr does
support such a search without the clause appended). However typeahead
search at least fails with the clause removed.
This PR retains the improved PUI search and fixes the typeahead behavior
by moving the negated types fq param from the advanced search query to a
separate param.
Here's a gist with debug queries:
https://gist.github.com/mark-cooper/63e7fdec57c9cf60211054ee041e3454

Fix for broken typeahead search, resolves #1835

---

backend/app/controllers/classification_term.rb
backend/app/model/classification_term.rb
backend/spec/controller_classification_spec.rb

Resolves #1384 by routing the `/repositories/:repo_id/classification_terms/:id/parent` endpoint through the same `set_parent_and_position` method used in other ordered hierarchy type records (e.g. archival objects, digital object components, etc.).  It appears that implementation of the `/parent` endpoint was never fully implemented for classification terms leading to a longstanding bug as described in #1384.
Also, since the existing `update_position_only` method appeared to do nothing/not be used elsewhere in the classification_terms universe, it has been removed.  (Seems like this method was probably initially copied from the enumerations controlled, but never really finished.)
https://github.com/archivesspace/archivesspace/issues/1384
Backend tests passing and one new test added.  API …

Issue #1384: Use correct method for classification_terms/parent endpoint

---

backend/app/controllers/exports.rb
backend/app/lib/export.rb

Resolves #1877 by adding `image_for_pdf` to `generate_pdf_from_ead`.
This change makes it possible to generate PDFs via the `/repositories/:repo_id/resource_descriptions/:id.pdf` endpoint.
https://github.com/archivesspace/archivesspace/pull/1480
Existing tests pass; API returns PDF as anticipated.

Issue #1877: Fix PDF generation via API

---

frontend/app/controllers/top_containers_controller.rb
indexer/app/lib/indexer_common.rb
solr/schema.xml

This improves both the accuracy of results and sorting order in the top container typeahead. See attached screenshots for comparison of old behavior vs new behavior.
Manual testing, and passes all current tests, including the ones recently added based around the top container typeahead.
Previous Behavior:
Current Behavior:
(Not sure whether to call this a bug fix or a new feature- more of an improvement on existing functionality)

Top container typeahead improvements

---

frontend/app/assets/javascripts/top_containers.bulk.js

This change improves the sorting of the indicator column when viewing the results of a search for top containers. It especially improves results on mixed alphabetical + numeric indicators, and no longer sorts by string length.
Manual testing, and this passes the indicator sort test that already exists in the "searches containers and performs bulk operations" block.
old behavior:
new behavior:

Improvements to top container indicator column sort

---

public/config/locales/en.yml
public/config/locales/es.yml
public/config/locales/fr.yml

Values for created and modified are listed twice in the search_results section of the public locales file. This is unnecessary and interferes with using automated translation software to parse the file. For some reason these weren't duplicated in the Japanese file, so there are only updates to the English, French, and Spanish files here.

removing two duplicate values in the public locales file

---

frontend/app/controllers/top_containers_controller.rb
frontend/app/views/top_containers/bulk_operations/_search_criteria.html.erb
frontend/config/locales/en.yml
frontend/config/locales/es.yml
frontend/config/locales/fr.yml
frontend/config/locales/ja.yml
indexer/app/lib/indexer_common.rb

This change adds a new select box "Has Location" on the Manage Top Containers search page. The new search field has_location returns true if a Top Container has one or more locations.
The Solr wildcard index *u_sbool is being used to index the value. The markup is consistent with existing code and all translations have been provided for the input label and select options text.
ARCSPC-907 in Harvard Library JIRA
Tested manually in multiple browsers by using the new select box on the Manage Top Containers search page. Also tested adding and removing a location from a top container and making sure the indexer updates the has_location value correctly.

Add Has Location to Top Container search page

---

indexer/app/lib/indexer_common_config.rb
indexer/spec/indexer_common_spec.rb

It is a corporate agent used to display repository contact info in the pui.

Allow repository contact to be indexed

---

indexer/app/main.rb

Make the indexer honor `AppConfig[:indexer_log_level]` instead of `AppConfig[:backend_log_level]`, allowing for the separate configuration of log levels for these two components.
Fixes #1692 
Edited the compose file to add `APPCONFIG_INDEXER_LOG_LEVEL` and `APPCONFIG_BACKEND_LOG_LEVEL` in various configurations and observed that the container log output now matches the levels set for both individually.

use indexer_log_level instead of backend_log_level

---

build/build.xml

Minor update to `build.xml` to ensure that the integration.tmp directory is deleted following frontend selenium test runs.  This mimics existing behavior in `backend:integration`, `public:test`, and `frontened:test`.
Failing to delete the `integration.tmp` directory leads to false test failures/stale index data.
Confirmed directory is deleted from `build/` following testing; tests pass as expected.

Delete integration.tmp following selenium tests

---

plugins/lcnaf/frontend/routes.rb
plugins/lcnaf/frontend/spec/lcnaf_client_spec.rb

Minor updates to the embedded lcnaf plugin to keep this version and https://github.com/archivesspace-plugins/lcnaf in sync
-Opted to preserve the external plugins routes file.
- Updated spec locations so they can be run with `build/run plugin:frontend:test`
- Fixed regularly failing second page test so that it's not pinned to a specific search result
- Fixed regex in spec to account for valid lcnaf identifiers that may have more than a single alpha character at the start of the identifier

Minor changes to routes and spec in response to syncing plugin versions

---

frontend/app/assets/javascripts/browse_merge.js
frontend/app/views/shared/_multiselect.html.erb
frontend/spec/selenium/spec/container_profiles_spec.rb

Refactoring done as part of #1913 resulted in the display strings being inadvertently removed from the container profile merge selection modal.  This fix re-adds the display string to the data attributes of the select all buttons in `shared/_multiselect.html.erb` and narrows the scoping of the results list in `browse_merge.js` so that it doesn't inadvertently provide a blank radio button for the header element. 
This also includes a first pass at adding some container profile selenium tests (previously there were none), including a test to confirm the above bug no longer persists.
Issue identified during internal release candidate testing.
Existing tests pass, new tests added.
Existing bug:
Fix:

Fix container profile merge modal to re-add display strings

---

common/config/preference_defaults.rb
common/config/search_browse_column_config.rb
common/locales/en.yml
common/locales/es.yml
common/locales/fr.yml
common/locales/ja.yml
frontend/config/locales/en.yml
frontend/config/locales/es.yml
frontend/config/locales/fr.yml
frontend/config/locales/ja.yml

Set the default sort for the jobs index page to `time_submitted`.
Also, add new required translations for `time_submitted` sort value, and also fix #1879 oversight of not providing translations for the core-shipped background job container labels job parameters that are now listed in the index's job_data column.
Fix stemming from initial internal 2.8.0RC testing.
Existing tests passed.

Change the default sort of jobs index to time_submitted

---

frontend/app/views/top_containers/bulk_operations/_location_linker.html.erb

#1913 requires browse to go through the generic `search_controller` instead of record-type-specific controllers.  This changes the `location_linker` used by top_containers to follow that new model.
Resolves bug introduced by #1913.
Discovered during initial internal 2.8.0RC testing.
Prior to fix a locations browse from top containers shows no results:
Following fix:

Use correct search controller from top container location browse

---

frontend/app/assets/javascripts/search.js
frontend/spec/selenium/spec/accessions_spec.rb

Style changes implemented in #1913 resulted in the `select_all` box adding an object for the header row of the index table to the `selected_records` array that is used for batch deleting records.  This change narrows the scope of the `selected_records` selection to the table data cells only, and alters an existing test (in `accessions_spec`) to use the select all button.
Allows for record deletion across record types when using the `select_all` checkbox.
Issue identified during internal 2.8.0 release candidate testing.
Error on current master:

Fix select_all deletion

---

backend/app/model/search.rb
backend/app/model/solr.rb
indexer/app/lib/indexer_common.rb
indexer/app/lib/large_tree_doc_indexer.rb
indexer/app/lib/pui_indexer.rb
public/app/helpers/view_helper.rb
public/app/models/finding_aid_pdf.rb
public/app/models/record.rb
public/app/services/archives_space_client.rb
public/app/views/resources/_infinite_item.html.erb
public/app/views/shared/_idbadge.html.erb
solr/schema-6.6.xml
solr/schema.xml

Add fq for types pui to all pui searches, this eliminates duplicates results
with record types using inheritance (i.e. where there are 2 published records
but only 1 with type pui, commonly this applies to archival objects).
Add types pui to tree and scroll docs so the pui can continue to access them.
This is required for the Collection Organization functionality to work.
Update all record types to include a uri. This is for consistency and also
so that the records_for_uris method can always search by uri except when
using a pui id (in that case use the id field as before). This is also
required for Collection Organization as it uses both forms (id and uri).
Cleanup unused cm_uri for Collection Management.

Updates for pui search

---

frontend/app/assets/javascripts/mixed_content.js

This PR adds a save function to the CodeMirror-controlled notes textarea triggered by an onChange event to ensure that updated note content is saved even when the change does not result in a change in cursor position (e.g. when using the delete key, or any other forward changing key combo like ctrl+delete or alt+delete).
Add save to all onChange events.  Fuller description of CodeMirror events here: https://codemirror.net/doc/manual.html#events. (Note: though this is the manual for a much newer release, the onChange event binding does not seem to have changed much.)
Also, this CodeMirror bug report helped me suss out/track down this issue:  https://github.com/codemirror/CodeMirror/issues/73. ArchivesSpace's `mixed_content.js` does currently call a save function on the else of …

ANW-138: Save changes that don't involve cursor activity

---

frontend/app/helpers/search_helper.rb
frontend/spec/selenium/spec/accessions_spec.rb

Changes from #1913 resulted in the second level sort from browse pages being present, but never actually working/sticking/successfully resorting the results.  This seems to stem from the sort variable in `build_search_params` being unaware of the existing first level sort on browse index pages.  This change adds that existing sort from `@search_data.sorted?` to that variable.
Also added a simple test to `accessions_spec`.
Discovered during internal testing of #1925 
Now, selecting an option for the second level sort on browse pages will actually do something other than reload the same page:

Ensure sort_2 works from browse pages

---

backend/app/model/mixins/relationships.rb

When merging top containers from the Manage Top Containers area (functionality added with #1764 ), relationships and associated/dependent records are reindexed post-merge, but the surviving top container target itself is not.  Since the top container document in the index stores information about attached collections (e.g. `collection_display_string_u_sstr`, `collection_identifier_stored_u_sstr`, etc.) failing to trigger a reindex of the target/surviving top container results in necessary information about newly related records being absent in the index.  From the user perspective, this means that a user who searches for an attached resource/accession on Manage Top Containers will be presented with inaccurate results.
While, at present, this bug only impacts top containers, the reindex of …

ANW-462 cont: Reindex target post merge

---

frontend/app/views/top_containers/bulk_operations/_bulk_action_templates.html.erb
frontend/app/views/top_containers/bulk_operations/_results.html.erb
indexer/app/lib/indexer_common.rb

Top containers may be linked to multiple locations (and this all works properly at the db layer), however the index never stores more than one location.  This implements a fix in `indexer_common` that adds all linked locations to the top_container solr record.  This also includes associated UI fixes to account for the fact there may now be more than one location present in the Manage Top Containers results table and on the Bulk Update Locations (Multiple) table.
Changes to `indexer_common` to ensure all locations are attached to a top_container.
Issue discovered during v2.8.0-RC1 testing.
Confirmed changes to index as necessary; all existing tests pass.
Multiple locations listed on the Manage Top Containers result page:

Ensure that top_container records index all linked locations

---

_yard/API.erb
backend/app/lib/rest.rb

Adds deprecation warnings to API docs!
See above, that's really all it is!
#1949 
I built the docs and they were not busticated!

Deprecation notice in API docs

---

CONTRIBUTING
README.md
common/db/db_migrator.rb
docs/_includes/sidebar.html
plugins/hello_world/README.md

High level attempt to fix broken links on existing docs sidebar that resulted from reorganization within the tech-docs repo; remove references to `archivesspace.github.io/archivesspace` and replace with references to `archivesspace.github.io/tech-docs site`.

Update docs sidebar and begin redirects to tech_docs page

---

frontend/app/assets/stylesheets/archivesspace/token-input.less
frontend/app/controllers/accessions_controller.rb
frontend/app/controllers/archival_objects_controller.rb
frontend/app/controllers/resources_controller.rb
frontend/app/views/container_locations/_show_only_token.html.erb
frontend/app/views/sub_containers/_show.html.erb
frontend/app/views/top_containers/_linker.html.erb

This adds a non-editable tag to top containers on edit and view pages for resources, archival objects, and accessions. The tag displays the location and functions as a link to the location's page.
Manual testing.

Display location when viewing container instance

---

frontend/app/assets/javascripts/linker.js

This PR adds id prefixes to linker-rendered records in record edit views and Top Container search view in staff UI. Doing so provides greater context to staff about records that can often have the same display string but different ids.
- [ANW-631](https://archivesspace.atlassian.net/browse/ANW-631)
- [ANW-700](https://archivesspace.atlassian.net/browse/ANW-700)

ANW-631 and ANW-700 add id prefixes to linker records

---

frontend/app/assets/javascripts/jquery.tokeninput.js
frontend/app/assets/stylesheets/archivesspace/rde.less
frontend/app/views/archival_objects/_rde_templates.html.erb

This PR enables scrolling on the linker dropdown when the linker is positioned at the bottom of the viewport (which happens when the linker is at the bottom of a modal form) ([ANW-897](https://archivesspace.atlassian.net/browse/ANW-897)).
⚠️ This PR overrides the Token Input jquery plugin file directly ⚠️
While editing 3rd party files is icky, I feel it is ok in this case since the plugin has been unmaintained for 6 years, and [the repo is archived](https://github.com/loopj/jquery-tokeninput) in read only mode. It's safe to assume there won't be anymore updates to this plugin.
This PR also overrides the jquery.kiketable.colsizable plugin's CSS to enable linker scroll in the Rapid Data Entry form (which is required after
the changes mentioned above) …

ANW-347 and ANW-897 Better linker dropdown

---

frontend/app/assets/javascripts/top_containers.bulk.js
frontend/app/controllers/repositories_controller.rb
frontend/app/controllers/top_containers_controller.rb
frontend/app/views/top_containers/bulk_operations/_collection_accession_linker.erb
frontend/app/views/top_containers/bulk_operations/_collection_resource_linker.erb
frontend/app/views/top_containers/bulk_operations/_container_profile_linker.html.erb
frontend/app/views/top_containers/bulk_operations/_location_linker.html.erb
frontend/spec/selenium/spec/instances_and_containers_spec.rb

This addition adds sticky search functionality to the Top Containers search. After executing a search and leaving the search page, your search will repopulate upon revisiting the search page and automatically get the search's results. 
This has been both manually tested, and a Selenium test covers the feature.

Top Container Sticky Search

---

public/app/assets/javascripts/print.js
public/app/controllers/pdf_controller.rb

This PR resets the PUI print-to-pdf button after it's clicked. It also removes an unneeded function whose callback never ran due to httponly cookies.
[ANW-1053](https://archivesspace.atlassian.net/browse/ANW-1053)
In browser testing.
See above.

ANW-1053 Reset PUI print button

---

backend/app/converters/ead_converter.rb

Adds a `?` quantifier to stop the `.*` part of the regular expression pattern, which matches barcodes, from being greedy and overriding the part of the pattern intended to match spaces. This prevents trailing spaces from being regarded as part of the barcode.
This, in turn, avoids the EAD importer failing when multiple container elements have the same barcode in their label attributes, but with an extra space. See the related JIRA ticket.
Also changed ` *` to `\s*` so other forms of whitespace (tabs, newlines) are also not included at the start or end of the barcode.
https://archivesspace.atlassian.net/browse/ANW-1089
Tested on a development system using a real EAD file which was failing on our production system.
N/A

ANW-1089: Fix regex for extracting barcodes from label attributes in containers in EAD importer

---

scripts/tasks/release_notes.rb

Back of house update to `release_notes` task to find and call out deprecated endpoints in release notes.  This is currently setup to find all deprecations and state that the endpoints will be removed on or after 1 year from the date on which the release notes are generated.  As such, this section will still require some manual cleanup for previously deprecated endpoints that are still around in that 1 year grace period.  At the very least, this gets something in place so that we won't forget to call them out when writing up the release notes.
Also added a heading and to-do section for noting configuration changes and new migrations, though some of this could be automated in the future as well.
After running the task, the following is returned:
```
__TODO: add config changes and migrations …
```

Update the release notes task to highlight deprecated endpoints

---

plugins/lcnaf/frontend/assets/lcnaf.js
plugins/lcnaf/frontend/controllers/lcnaf_controller.rb
plugins/lcnaf/frontend/locales/en.yml
plugins/lcnaf/frontend/locales/fr.yml
plugins/lcnaf/frontend/models/opensearcher.rb
plugins/lcnaf/frontend/spec/lcnaf_client_spec.rb
plugins/lcnaf/frontend/views/lcnaf/index.html.erb

This plugin was checking for a 200 status code and throwing an exception for anything other than a 200. id.loc.gov now throws a 301 for http://id.loc.gov redirecting to https://id.loc.gov. While we can (and have) updated the hardcoded search links in `lcnaf_controller`, we can't handle the fact that the entry uri's returned by that search also point to now 301'd uris (e.g. http://id.loc.gov/authorities/names/n86828140.marcxml.xml). Just to get things working again, I've added a check for 301/Net::HTTPMovedPermanently before the check for anything other than 200/Net::HTTPOK.
Also, quickly provided better user feedback in the Search Error modal since the Internal Server Error that was getting thrown there was unlikely to ever by helpful to anyone. This can/should be improved upon in the …

Update to account for id.loc.gov moving from http to https

---

frontend/spec/selenium/spec/events_spec.rb

Continuing work to improve Selenium test suite.  Prior to this change, `events_spec.rb` could not run successfully independent of other tests as it depended on the existence of an admin user that is not created within the `events_spec` itself.  This minor change utilizes the agent created in the before block of the events tests, instead of the admin agent provided by other/prior tests.
To enable all selenium tests to be pass at the file level at minimum (if not yet at the context or individual example level).

Ensure all selenium tests can run independently

---

frontend/app/assets/javascripts/linker.js
frontend/spec/selenium/spec/resources_spec.rb

This change prepopulates the Top Container search modal with results for the current resource when opening the modal from a Resource or Archival Object page.
Selenium test covers the feature.
View upon opening the modal:

Search Prepopulation for Current Resource in Top Container Modal

---

backend/app/controllers/search.rb

During work on #1923 the non-standard and duplicative `search/subjects` endpoint was discovered.  As part of #1923, the only use of `search/subjects` in the codebase (in `frontend/app/controllers/subjects_controller.rb`) was refactored to use the general `/repositories/#{session[:repo_id]}/search` endpoint instead.  As such, `search/subjects` should be considered deprecated and removed in future releases.
This (tiny) PR notes this deprecation in the search controller.

Continuation of #1923 to deprecate search/subjects endpoint

---

frontend/app/assets/javascripts/update_monitor.js

Includes one commit from the larger #1896 authored by @marktriggs and funded by Queensland State Archives.
- ed1377fa6ba8f64a793992defff6bad8100ece69: Don't duplicate "Errors and warnings" sidebar entry
If another user has saved a record that you have open for editing,
each iteration of the "update monitor" would add a new sidebar entry,
so you'd end up amassing a lot of them...
Prevents duplicate errors and warnings sidebar.
Visually confirmed fix.  Only one error/warning sidebar entry is visible for each error/warning present on the page, and more errors/warnings sections aren't added to the sidebar as you remain on the edit page.

Don't duplicate "Errors and warnings" sidebar entry

---

frontend/app/views/agents/_form.html.erb
frontend/app/views/agents/show.html.erb
frontend/spec/selenium/spec/assessments_spec.rb

Includes three commits from the larger #1896 written by @payten and funded by Queensland State Archives.
- 9de3b837c579596b085f25fa050067590f3986df: Only show Linked Assessment Reviewer/Surveyed By on agent_person records
- 586097be5973472a50d2b1eb6412f950c8618d93: Ensure plugin sections are displayed at the end of agents readonly page
- dc769d5ddcda7fcd10c8dad404f25b1f931c47c2: Agents don't link to external_ids, so the form is not required
Also includes two new tests in `assessments_spec.rb` to add test coverage for 9de3b837c579596b085f25fa050067590f3986df.
Includes modifications to the staff-side agents form/show templates, including:
- Only adding a linked assessment reviewer/surveyor subrecords to the show pages for agent_persons (other agent types - corporate entities, families, and …

Agent form enhancements

---

common/config/search_browse_column_config.rb

Adds last modified and created date as default sort options for accessions, resources, digital objects, and search. I'm not sure if it would be better to address this along with future preferences work instead of merging this, but it seemed like a simple change to me.
Changes to the common SearchAndBrowseColumnConfig to add default sort options for last modified and created date. Uses the existing functionality. 
N/A, default sorting by last modified date was just a feature we wanted. Save the extra clicks to show which records were most recently update, which I find I do constantly.
Tested the new options with real world data for resources, accessions, digital objects, and the search results pages. When you select preferences, they are stored in the database, so if you, say set resources …

adds last modified and created date as default sort options

---

common/aspace_i18n.rb
frontend/app/helpers/aspace_form_helper.rb
frontend/app/views/container_locations/_show.html.erb
frontend/app/views/dates/_template.html.erb
frontend/app/views/locations/show.html.erb
frontend/app/views/shared/_largetree.html.erb
frontend/app/views/user_defined/_show.html.erb
frontend/config/locales/en.yml

Includes seven commits from the larger #1896 funded by Queensland State Archives and written by:
- @jambun
- @marktriggs
- 76ef79d650413dc73aafae8d0f9c60a7b58091af: Use the form template for user_defined fields
- a894eb63b39e059ca6794f85dce3e0870b4b810d: Fix a bug where the transfer dropdown is closed when the linker modal is closed
- cae9e05b81a1648ea575a9cb75809c4063f90b7d: Report a useful stacktrace if generating JS templates fails
- 0e8f31aac12cadc2b97fa6ff8c30226691cb282e: ensure all components respect AppConfig[:locale]
- 1d03cf9c9d938d97f85955518731c40e50011a88: Fix small layout issue with "Location" in top_container/show
- 6405369a1972bebac216c73b7af52c732c3bf285:  Layout fix: show audit info at the bottom of basic information
- 095a89df4b0b13cb3b6182c229d1d1fb7210ce08: Add I18n …

Hm qsa 090220 mc

---

backend/app/controllers/enumeration.rb
backend/app/model/enumeration.rb
backend/spec/rest_enumerations_spec.rb
common/config/config-defaults.rb
frontend/app/controllers/enumerations_controller.rb
frontend/app/views/accessions/_toolbar.html.erb
frontend/app/views/agents/_toolbar.html.erb
frontend/app/views/enumerations/index.html.erb
frontend/app/views/shared/_component_toolbar.html.erb
frontend/app/views/shared/_resource_toolbar.html.erb
frontend/config/locales/en.yml
frontend/config/routes.rb

Includes two commits from the larger #1896 funded by Queensland State Archives and written by:
- @jambun
- @payten
- 52c17d1c27e41affd75e76019adba62011d85b40: Only render View Published toolbar action if AppConfig[:show_view_published]
- 9078049affaf29a10331369570dc201c6d7a38d0: Add the ability to download a CSV of all enumerations with their values
There are a couple of small updates applied to the above commits:
- Use existing appconfig setting to determine visibility of view published (rather than a new one)
- Added position and readonly columns to enumeration csv export
- Exported csv filename does not include spaces
Manually, and test added for csv export endpoint.

Hm qsa 091520 mc

---

backend/app/controllers/merge_request.rb
backend/app/lib/rest.rb
backend/app/model/mixins/relationships.rb
backend/spec/rest_merge_request_spec.rb

Fixes ANW-1116 by restoring replace functionality to detailed agent merges.  
Skips the step of saving the updated target record in the relationships mixin that was added with #1939 .  Since the detailed merge can result in changes to the target record, attempting to resave the record in the relationships mixin will throw a `"The record you tried to update has been modified since you fetched it."` error.
Also introduces a more robust `merged_response` to rest.rb to provide greater/more consistent feedback about the merge activity completed via the API.  New REST tests make use of this `merged_response`.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1116
Existing tests pass, new REST tests added.

ANW-1116: Don't update merge target for agent merges

---

backend/app/model/location.rb
common/config/search_browse_column_config.rb
frontend/app/controllers/locations_controller.rb
frontend/app/models/search.rb
frontend/app/models/search_result_data.rb
frontend/app/views/locations/show.html.erb
frontend/app/views/search/_filter.html.erb
frontend/config/locales/en.yml
indexer/app/lib/indexer_common.rb

On the Browse Locations results page, this creates a facet by the Location record Repository field to make it easier for a staff user to limit their view to desired records.  Also adds a 'None' option for the Repository.  
This allows a broader faceting option for the Locations.
This has been manually tested.  
- [ x] New feature (non-breaking change which adds functionality)
- [x ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.

Browse location by repository facet

---

common/config/config-defaults.rb
public/app/views/cite/_modal_tabbed.html.erb
public/config/locales/en.yml
public/config/locales/es.yml
public/config/locales/fr.yml
public/config/locales/ja.yml
public/spec/features/cite_spec.rb

Extends #1941 by implementing the following:
- Makes default active Citation tab configurable with the addition of a new `AppConfig[:pui_active_citation_tab_item]` config option;
- Removes hardcoded English language labels/headings from the citation modal and employs translations instead; and,
- Adds 3 new citation modal tests to the public test suite.
https://archivesspace.atlassian.net/projects/ANW/issues/ANW-921
Manually tested, existing tests pass, new tests added.

ANW-921: Make citation tab configurable, use translations

---

_yard/API.erb

Just a small change to the API docs to encourage people to not allow public access to the API endpoint.

Adds recommendation to restrict API access

---

common/db/migrations/137_reindex_locations.rb
frontend/app/models/search.rb
frontend/app/models/search_result_data.rb
frontend/app/views/search/_filter.html.erb
frontend/spec/selenium/spec/locations_spec.rb

Continuation of #1889 to add/update the following:
- Add migration to reindex all locations due to owner repo additions;
- Adds two new Selenium tests;
- Adds additional check to `search.rb` after witnessing a lot of doubling up of blank facet queries (e.g. `http://localhost:3000/locations?q=-owner_repo_display_string_u_ssort%3A%2A&-owner_repo_display_string_u_ssort%3A%2A&-owner_repo_display_string_u_ssort%3A%2A&sort=title_sort+asc`)
- Moved `query_array` creation to `_filter.html.erb` and modified the searches there to allow individual addition/removal of a blank owner repo "filter" and/or a normal text query;
- Updated `facet_label_for_query` to resolve the fact that "normal" filter text queries weren't displaying a full label and changing the blank repo query label a bit to make it …

Continuation of #1889 to add migration, test, label changes

---

public/app/lib/xml_cleaner.rb

Fix for ANW-1111. The  PUI Print to PDF Fails if `&`  is Immediately Followed by a Capital Letter. This just changes the line.match to match UPPER and lower case letters. 
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1111

ANW-1111 Fixes PUI Print to PDF Fails if &  Followed by a Capital Letter

---

frontend/config/locales/en.yml
frontend/config/locales/es.yml
frontend/config/locales/fr.yml
frontend/config/locales/ja.yml

A facet for language (langcode) was added via https://github.com/archivesspace/archivesspace/pull/1792 and additional translations for the staff interface were added via https://github.com/archivesspace/archivesspace/pull/1827. Although the facet still works, the translations appear to have been removed prior to 2.8.0. This adds them back in, though in different place(s) from the original pull requests. (I'm putting this in draft in case my solution is way off base.)
https://archivesspace.atlassian.net/browse/ANW-1125

Add langcode value+translation back into yml files

---

frontend/app/controllers/locations_controller.rb
frontend/app/views/locations/_form.html.erb
frontend/spec/selenium/spec/locations_spec.rb

The disabled input means params are not sent to the controller, so
the data is lost on update. Instead, if a temporary location flag
is submitted, check for a value in the params or for a pre-existing
value in the location record. Also ensure that when a temporary
location is selected the flag is checked.
https://archivesspace.atlassian.net/browse/ANW-851
Manual UI wrangling and updated location specs.

ANW-851: Fix temporary location lost on update

---

backend/app/converters/lib/marcxml_base_map.rb
backend/spec/lib_marcxml_converter_spec.rb

This change fixes an issue with processing data in the MARC 544 field during MARCXML import. Previously, on import, the value of indicator 1 was prepended to the data in the note text, and subfield d (title) was ignored. This change removes the value of indicator 1 from the note text, and includes subfield d.
https://archivesspace.atlassian.net/browse/ANW-750
Backend unit tests (build/run backend:test) passed on Windows Subsystem for Linux (Ubuntu 18.04)

ANW-750: Update MARCXML 544 field import

---

backend/app/converters/ead_converter.rb
backend/spec/lib_ead_converter_spec.rb

Solves problem of EAD importer failing to import <controlaccess><title>
ANW-903
Tested by importing several EADs.  Works as expected.

ANW-903 Fixes EAD uniform title import

---

common/locales/en.yml

Cleans up the image_url_tooltip wording so it's more clear what that thing does.

Branding Image URL tooltip wording change

---

common/config/config-defaults.rb
frontend/app/views/site/_branding.html.erb
public/app/views/shared/_header.html.erb

Upstream changes introduced via the Rails upgrade (5.0.x to 5.2.x) included in #1953  resulted in the loss of alt text for the logo image on the staff interface.  Previously, Rails' `image_tag` method would fallback to using a filename as the source of automatically generated alt tags, however that behavior was removed in Rails 5.2 as it doesn't actually generate useful alt text in most cases.  See: https://github.com/rails/rails/commit/9a74c7b99bf0ac901f86bb38372a68e157cf9c73 .
Moving forward we'll have to explicitly include alt text in `_branding.html.erb` (or explicitly define blank alt text if the image is purely for decorative purposes).
I've also added an `AppConfig` controlled alt text to the PUI to attempt to keep the staff/PUI behavior the same, however I'm happy to reconsider …

ANW-1126: Add alt text to logo images in staff and PUI

---

frontend/app/views/shared/_header_repository.html.erb

Bulk import background jobs should only be triggered from resource records, so it can be skipped in the top level create dropdown.
Found via user testing of #1980 
Visually confirmed fix.

Hide bulk import from create dropdown menu

---

backend/app/model/digital_object_component.rb

Resolves ANW-1130 and returns the ability to save a digital object component that only includes a date.
Follows the standard used in `backend/app/model/archival_object.rb` and sets the display string as `""` instead of `nil` when there is no title or label for a digital object component.
https://archivesspace.atlassian.net/browse/ANW-1130
Manually confirms that digital object components without titles or labels can be saved.

ANW-1130: Don't error when a dig obj comp only has a date

---

frontend/app/assets/javascripts/linker.js

Continuation of #1906 to also prefix digital object typeaheads with the digital object identifier.
https://archivesspace.atlassian.net/browse/ANW-631
Visually confirmed that typeahead is prepended with identifiers of all types.

ANW-631 cont'd: Also include the doid in a digital object typeahead

---

backend/app/converters/ead_converter.rb

Stop trying to map DAO titles to the much smaller caption field
[ANW-757](https://archivesspace.atlassian.net/browse/ANW-757)
Imported test file with dao titles > 255 characters. Imports no longer break.

ANW-757: Stop mapping dao titles to captions

---

frontend/app/assets/javascripts/bulk_import.js.erb
frontend/app/assets/stylesheets/archivesspace/buttons.less
frontend/app/views/resources/_bulk_import_form.html.erb

In response to feedback from #1980 , this PR adds more dramatic color changes/styling while toggling the job type buttons in the bulk import modal (see screen capture below).
I also addressed the following:
- Changed the forms filename `<span>` into a `<label>` to provide an adequate label for the filename input; and, 
- Updated the class/js for the modal success form to improve stylistic consistency/greater color contrast on the "Close" button after successfully queuing up a bulk import job (see screenshot).
Feedback received post #1980 
New color/style on job type toggle:
Fixed this faint/poor contrast "Close" button on the success modal:

Style improvements for bulk import modal
