archivesspace/archivesspace

- common/db/migrations/036_make_location_temporary_enum_editable.rb
- common/locales/en.yml
- frontend/app/assets/javascripts/locations.batch.js
- frontend/app/assets/javascripts/locations.crud.js
- frontend/app/assets/javascripts/locations.index.js
- frontend/app/assets/javascripts/resources.crud.js.erb
- frontend/app/controllers/locations_controller.rb
- frontend/app/helpers/aspace_form_helper.rb
- frontend/app/views/container_locations/_template.html.erb
- frontend/app/views/locations/_form.html.erb
- frontend/app/views/locations/_form_batch.html.erb
- frontend/app/views/locations/batch.html.erb
- frontend/app/views/locations/index.html.erb
- selenium/common.rb
- selenium/spec/selenium_spec.rb
This is a PR that includes several commits relating to sprint 1 ( 2015 )
> Sprint 1 PR

- selenium/spec/selenium_spec.rb
- selenium/spec/spec_helper.rb
This will hopefully fix the Selenium::WebDriver::Error::StaleElementReferenceError. Also includes a tweak for Solr when running against a standalone backend.
> Tweak selenium once more

- backend/app/model/db.rb
- common/config/config-defaults.rb
Just a little debugging tool that would have been handy to have recently :)
> Introduce a new AppConfig[:db_debug_log] option to log all SQL.

- backend/app/controllers/resource.rb
- common/locales/en.yml
- frontend/app/assets/javascripts/jobs.crud.js
- frontend/app/controllers/resources_controller.rb
- selenium/spec/selenium_spec.rb
https://archivesspace.atlassian.net/browse/AR-979?focusedCommentId=13028&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13028
> Find and replace adjustments

- plugins/lcnaf/frontend/controllers/lcnaf_controller.rb
> update the LCNAF plugin for new jobs API

- frontend/app/controllers/search_controller.rb
- frontend/app/helpers/search_helper.rb
- frontend/app/views/accessions/_linker.html.erb
- frontend/app/views/dates/_template.html.erb
- frontend/app/views/resources/_linker.html.erb
- frontend/app/views/search/_listing.html.erb
- frontend/config/locales/en.yml
- indexer/app/lib/indexer_common.rb
> Accession indexing

- common/locales/enums/en.yml
Then if / when added by site to controlled value list translation is already in place:
http://www.loc.gov/marc/relators/relaterm.html
> Add more codes from MARC Code List for Relators

- backend/app/exporters/models/mods.rb
The name map MODS export contained an error.
> Fixing error in MODS name export

- common/db/migrations/041_position_suppress_enum_values.rb
@cfitz - didn't test this too thoroughly so please review
> make sure enumeration positions get updated

- frontend/app/assets/javascripts/form.js
- frontend/app/assets/javascripts/utils.js
Fixes:
1. the ctrl-s issue reported by windows users
2. the missing scrollbar after the shortcuts help modal is closed
> AR-1065 #finish #2ndattempt

- .gitignore
- common/locales/enums/es.yml
- common/locales/es.yml
- frontend/config/locales/es.yml
- frontend/config/locales/help/es.yml
- locales.sh
- public/config/locales/es.yml
Includes script to see diff between `version` and `master`:
```
./locales.sh [$CURRENT_RELEASE_VERSION]
```
Produces diff between `master` and version specified (or
v1.2.0 by default which can be incremented in the locales 
script with each release).
> Spanish translations for ArchivesSpace up to 1.2.0.

- common/locales/en.yml
- common/schemas/defaults.rb
- frontend/app/assets/javascripts/application.js
- frontend/app/assets/javascripts/jobs.crud.js
- frontend/app/assets/javascripts/notes.crud.js
- frontend/app/assets/javascripts/preferences.js
- frontend/app/assets/javascripts/tree.js.erb
- frontend/app/assets/javascripts/utils.js
- frontend/app/controllers/utils_controller.rb
- frontend/app/views/defaults/_template.html.erb
- frontend/app/views/notes/_form.html.erb
- frontend/bower.json
- frontend/config/locales/en.yml
- frontend/config/routes.rb
- frontend/vendor/assets/javascripts/Sortable.js
No tests written for this yet - I intend to come back around to those once I've restructured the selenium specs successfully.
> AR-946 #finish sort notes by preferred order per repo

- common/locales/enums/es.yml
- common/locales/es.yml
- frontend/config/locales/es.yml
- frontend/config/locales/help/es.yml
- locales.sh
Spanish language updates for v1.3.0 courtesy of @luismart at FJM.
> Updated es locales for v1.3.0

- frontend/app/assets/javascripts/tree.js.erb
- selenium/spec/trees_spec.rb
Commented a line, tests pass...
¯\_(ツ)_/¯
> tweak tests and take out a node refresh call

- backend/app/exporters/lib/export_helpers.rb
- backend/spec/export_ead_spec.rb
Subjects with those term types are not getting serialized in the EAD.
> Use comma for OR in controlaccess case statement

- backend/app/exporters/serializers/ead.rb
Previous PR: https://github.com/archivesspace/archivesspace/pull/271
> EAD p serializer fix take two: regex

- backend/app/model/reports/jasper_report.rb
- plugins/lcnaf/frontend/assets/lcnaf.js
- plugins/lcnaf/frontend/controllers/lcnaf_controller.rb
- plugins/lcnaf/frontend/models/opensearcher.rb
- plugins/lcnaf/frontend/routes.rb
- plugins/lcnaf/frontend/views/lcnaf/index.html.erb
squashed commits and rebased before pull request. 
Also fixed it so multiple selected imports work properly.
> LCNAF and LCSH imports from id.loc.gov  fixed in lcnaf plugin. 

- frontend/app/views/accessions/_toolbar.html.erb
- frontend/app/views/agents/_toolbar.html.erb
- frontend/app/views/classifications/_toolbar.html.erb
- frontend/app/views/events/_toolbar.html.erb
- frontend/app/views/events/edit.html.erb
- frontend/app/views/events/show.html.erb
- frontend/app/views/groups/_toolbar.html.erb
- frontend/app/views/locations/_toolbar.html.erb
- frontend/app/views/repositories/_toolbar.html.erb
- frontend/app/views/shared/_component_toolbar.html.erb
- frontend/app/views/shared/_resource_toolbar.html.erb
- frontend/app/views/subjects/_toolbar.html.erb
- frontend/app/views/users/_toolbar.html.erb
- frontend/config/locales/en.yml
REBASE: https://github.com/archivesspace/archivesspace/pull/246
Add appropriate title for record during delete confirmation.
> AR-1132 Add record titles to delete confirmation

- backend/app/model/event.rb
- frontend/app/views/events/_form.html.erb
- frontend/app/views/locations/_form.html.erb
- frontend/app/views/locations/show.html.erb
- frontend/app/views/subjects/show.html.erb
Rebase of https://github.com/archivesspace/archivesspace/pull/247
> Missing frontend plugin hooks

- common/locales/enums/es.yml
- common/locales/es.yml
- frontend/config/locales/es.yml
Signed-off-by: luismart <l.martinezuribe@gmail.com>
[mark.c.cooper@outlook.com: some whitespace and indentation cleanup]
Signed-off-by: Mark Cooper <mark.c.cooper@outlook.com>
All credit goes to @luismart =)
> update of spanish translations

- backend/app/converters/lib/xml_sax.rb
Fixes errors in EAD import -- see #332
> possible fix for #332

- backend/app/converters/lib/marcxml_base_map.rb
- backend/spec/lib_marcxml_converter_spec.rb
> adding authority_id pulled from controlfield 001

- frontend/app/assets/javascripts/utils.js
- frontend/app/views/top_containers/bulk_operations/_search_criteria.html.erb
- frontend/app/views/top_containers/index.html.erb
Seems like a few more linkers needed to be initialized inline: https://github.com/archivesspace/archivesspace/issues/334
> Top container manager fixes

- backend/app/model/name_person.rb
- backend/spec/model_agent_person_spec.rb
Fix for https://github.com/archivesspace/archivesspace/issues/268
> ensure that sort names don't begin with a space

- indexer/app/lib/indexer_common.rb
These are just some edits to what appear to be some cut and paste mishaps.
> Cleanup some redundancies and odd code placement in indexer

- frontend/app/controllers/users_controller.rb
Users who can manage users can create them =)
> AR-1417 Disable allow_user_registration prevents user creation within frontend

- indexer/app/lib/periodic_indexer.rb
@quoideneuf  what do you think?
> AR-1415 #finish attempt to fix indexer

- public-new/app/assets/javascripts/application.js
- public-new/app/assets/javascripts/records.js
- public-new/app/assets/javascripts/router.js
- public-new/app/assets/javascripts/searching.js
- public-new/app/assets/javascripts/utils.js
- public-new/app/assets/stylesheets/archivesspace/aspace.scss
- public-new/app/assets/stylesheets/archivesspace/typography.scss
- public-new/app/controllers/records_controller.rb
- public-new/app/views/site/index.html.erb
- public-new/bower.json
- public-new/config/routes.rb
- public-new/jasmine/my.conf.js
- public-new/jasmine/record_model_spec.js
- public-new/vendor/assets/javascripts/lodash-inflection/lodash-inflection.js
- solr/schema.xml
> New public interface

- backend/app/exporters/lib/export_helpers.rb
- backend/app/exporters/serializers/ead.rb
- backend/spec/export_ead_spec.rb
- backend/spec/factories.rb
- backend/spec/model_agent_person_spec.rb
Rebase of https://github.com/archivesspace/archivesspace/pull/427
> Alexduryee master

- backend/app/model/search.rb
fixes #455 
Yeah, for some reason i was pulling the total pages from the request params and not the response.
> set the total pages based on the response not the request, dummy.

- common/locales/en.yml
advanced_search -> test -> identifier
> adding an enumeration value

- backend/spec/lib_ead_converter_spec.rb
Rebased: https://github.com/archivesspace/archivesspace/pull/466
by @quoideneuf
> Fix conflict

- public-new/app/views/site/index.html.erb
Per Mark's comment:  I added the header element "Additional Information", and changed the "Additional Description" accordion header to "Notes"
> AR-1498 Add header to accordion

- common/locales/enums/es.yml
- common/locales/es.yml
- frontend/config/locales/es.yml
Thanks to @luismart
Note: these are not available in the v1.5.1 release package. You
will need to create a custom build or use another method to get
access to the updated locales for v1.5.1.
> Update Spanish translations circa v1.5.1

- indexer/app/lib/indexer_common.rb
- selenium/spec/search_spec.rb
Fixes http://lyralists.lyrasis.org/pipermail/archivesspace_users_group/2016-August/003843.html and adds tests.
> fixing fullrecord indexer

- backend/app/model/mixins/notes.rb
@cfitz @pobocks @sdm7g
If you're at all interested and can spare a minute to peek at this it would be much appreciated =)
I've been looking into a reindexing issues with v1.5.1. What I've found is that (given default config values) there's a timeout issue querying note_persistent_id when there are many associated values. The queries look like:
```
SELECT * FROM `note_persistent_id` WHERE ((`parent_id` = 6620) AND (`parent_type` = 'resource') AND (`persistent_id` = 'des00010c01233')) LIMIT 1
```
https://github.com/archivesspace/archivesspace/blob/master/backend/app/model/mixins/notes.rb#L193-L195
When that is being done many (thousands of) times over it's possible to hit the solr timeout (which can be raised, but not satisfactorily).
So my approach is to "cache" the query result per parent …
> Resolve note pids faster

- public/app/controllers/search_controller.rb
> Adds a line to sanitize filter_term param in the old old public ui

- backend/app/converters/ead_converter.rb
Note that this still handles checking audience on a bespoke basis:
audience checks must still be built into any case where EAD content is
being turned into a model that can take a publish attribute.
> Fixes #534 - adds a number of missing @audience checks.

- backend/app/exporters/serializers/ead.rb
- backend/app/lib/print_to_pdf_runner.rb
- backend/spec/export_ead_spec.rb
- backend/spec/model_print_to_pdf_job_spec.rb
- common/locales/en.yml
- common/schemas/print_to_pdf_job.rb
- frontend/app/controllers/jobs_controller.rb
- frontend/app/views/jobs/_form.html.erb
- frontend/app/views/jobs/_show_templates.html.erb
- frontend/app/views/resources/_toolbar.html.erb
Further things based on breaking news on AR-1472.
For review!
> AR-1472 extend PDF export

- common/schemas/boolean_field_query.rb
- common/schemas/date_field_query.rb
Delivers https://archivesspace.atlassian.net/browse/AR-1582
> AR-1582 update date and boolean advanced queries to support NOT

- frontend/app/views/shared/_header_repository.html.erb
Show it to users with:
manage_container_record
Not:
manage_repository
> AR-1559 Show the manage top containers link to the right users

- frontend/app/assets/stylesheets/archivesspace/tree.less
@payten Just a tiny fix here when you've got a second...
> Fix the cropped "Loading" message box on trees

- backend/app/controllers/batch_import.rb
- backend/app/exporters/lib/export_helpers.rb
- backend/app/exporters/models/ead.rb
- backend/app/lib/cycle_finder.rb
- backend/app/lib/dependency_set.rb
- backend/app/lib/nested_record_resolver.rb
- backend/app/lib/notifications.rb
- backend/app/lib/streaming_import.rb
- backend/app/lib/streaming_json_reader.rb
- backend/app/lib/uri_resolver.rb
- backend/app/main.rb
- backend/app/model/ASModel_crud.rb
- backend/app/model/db.rb
- backend/app/model/mixins/agent_manager.rb
- backend/app/model/mixins/agent_names.rb
- backend/app/model/mixins/implied_publication.rb
- backend/app/model/mixins/relationships.rb
- backend/spec/lib_uri_resolver_spec.rb
- backend/spec/model_implied_publication_spec.rb
Incorporating a small back catalog of performance improvements we put together as a part of doing migration work.
> Hudmol performance improvements

- .gitignore
- build/BUILD_README.md
- supervisord/README.md
- supervisord/api.conf
- supervisord/archivesspace.conf
Entirely optional, for developer convenience only.
> Add supervisord configuration files for development [ci skip]

- indexer/app/lib/periodic_indexer.rb
> Make the periodic indexer more robust against disks filling up

- backend/app/controllers/exports.rb
- backend/app/lib/export.rb
https://archivesspace.atlassian.net/browse/AR-1533
removes anything other than 0-9, A-Z, "." , or "_" from filename. 
Also adds a UTC timestamp to the filename.
> AR-1533 remove any funny chars from export filename and add a timestamp

- build/build.xml
adds some hoooks to build.xml for plugin testing.
> allow travis builds to run from plugin directory

- backend/app/exporters/serializers/ead.rb
- backend/spec/export_ead_spec.rb
Delivers https://archivesspace.atlassian.net/browse/AR-1562.
> AR-1562 exclude suppressed components from EAD export

- backend/app/model/large_tree_resource.rb
- frontend/app/assets/javascripts/tree_renderers.js.erb
- frontend/app/assets/javascripts/tree_toolbar.js.erb
If this seems to be on the right track, I'll do the same for the digital object and classification trees.
> I18n the tree summary text and pull back all containers for these summaries

- backend/app/model/advanced_query_string.rb
- backend/app/model/solr.rb
- backend/spec/model_solr_spec.rb
- common/advanced_query_builder.rb
- common/schemas/boolean_field_query.rb
- common/schemas/date_field_query.rb
- common/schemas/field_query.rb
- common/validations.rb
- frontend/app/assets/javascripts/header.js
- frontend/app/assets/javascripts/utils.js
- frontend/app/controllers/application_controller.rb
- frontend/app/controllers/search_controller.rb
- frontend/app/helpers/search_helper.rb
- frontend/app/views/shared/_advanced_search.html.erb
- frontend/config/locales/en.yml
Delivers:
AR-1570
AR-1571
AR-1572
> Support empty value searching

- public-new/app/models/record.rb
- public-new/app/views/shared/_record_innards.html.erb
Delivers https://archivesspace.atlassian.net/browse/AR-1630
> AR-1630 show any linked classifications in a Record Group accordion

- indexer/app/lib/indexer_common.rb
- public-new/Gemfile.lock
- public-new/app/controllers/search_controller.rb
- public-new/app/models/concerns/tree_nodes.rb
- public-new/app/views/shared/_result.html.erb
- solr/schema.xml
Delivers https://archivesspace.atlassian.net/browse/AR-1675
> AR-1675 Index the ancestor URIs and resolve them to show a  search result breadcrumb

- backend/app/main.rb
- build/build.xml
- common/archivesspace_thread_dump.rb
- frontend/config/initializers/init_thread_dump.rb
- indexer/app/main.rb
- public-new/config/initializers/init_thread_dump.rb
- public/config/initializers/init_thread_dump.rb
A new facility for generating human-readable thread dumps.  Also a small fix for Solr in dev mode.
> Thread dump

- common/locales/en.yml
- frontend/app/assets/javascripts/largetree.js.erb
- frontend/app/assets/javascripts/largetree_dragdrop.js.erb
- frontend/app/assets/javascripts/tree_toolbar.js.erb
Added this message:
Tips on wording?
Also, to make it clearer what is cut and what is the selected node (also the paste target), I clear the highlighted rows upon cutting:
> Add message upon invalid move

- public-new/app/controllers/accessions_controller.rb
- public-new/app/controllers/agents_controller.rb
- public-new/app/controllers/classifications_controller.rb
- public-new/app/controllers/containers_controller.rb
- public-new/app/controllers/objects_controller.rb
- public-new/app/controllers/repositories_controller.rb
- public-new/app/controllers/subjects_controller.rb
- public-new/app/models/concerns/tree_nodes.rb
e.g. linked records to a container: http://pui.hudmol.com/repositories/3/top_containers/68
> AR-1675 ensure ancestors and repository are resolved for any inline searches

- public-new/app/controllers/resources_controller.rb
Fixes https://archivesspace.atlassian.net/browse/AR-1675
> AR-1675 resolve ancestors on the resource search so breadcrumbs show

- README_HTTPS.md
> 583 - Add RequestHeader to forward https protocol into ArchivesSpace

- frontend/app/assets/javascripts/accessions.show.js
... so the button actually does something!
> AR-1503 load extent_calculator.js in accessions show

- backend/app/controllers/collection_management.rb
- backend/app/model/ASModel_crud.rb
- backend/app/model/collection_management.rb
- backend/app/model/large_tree_classification.rb
- backend/spec/model_collection_management_spec.rb
- common/db/migrations/084_reindex_collection_management_records.rb
- common/jsonmodel.rb
- common/schemas/collection_management.rb
- frontend/app/assets/stylesheets/archivesspace/tables.less
- frontend/app/models/resolver.rb
- indexer/app/lib/indexer_common.rb
- indexer/app/lib/periodic_indexer.rb
- indexer/app/lib/pui_indexer.rb
- public/app/views/records/_components.html.erb
- public/config/locales/en.yml
- public/config/locales/es.yml
- solr/schema.xml
Plus also add an error handler if the tree fails to load.  And also avoid blank trees when the tree SOLR records are eagerly deleted by the periodic indexer.
> AR-1683 Add identifier to classification tree in PUI

- plugins/lcnaf/frontend/models/http_request.rb
- plugins/lcnaf/frontend/models/opensearcher.rb
- plugins/lcnaf/frontend/models/srusearcher.rb
Abort the connection after 5 seconds and retry.
> Deal with transient stalls from LOC API

- common/aspace_logger.rb
- common/locales/en.yml
- frontend/app/controllers/system_info_controller.rb
- frontend/app/views/notes/_template.html.erb
- frontend/app/views/search/_filter.html.erb
- frontend/app/views/shared/_event_dropdown.html.erb
- frontend/config/application.rb
- frontend/config/initializers/i18n.rb
@marktriggs doesn't look like a PR was created for this...
> Patches from review

- launcher/archivesspace.sh
This allow in the .sh script to set a pidfile as an env variable
( ASPACE_PIDFILE )
> Add ability to set the PIDFILE as an env variable

- common/config/config-defaults.rb
Provide a little more guidance on system configuration (based on experience helping people figure this stuff out)
> Reorder the default configuration file

- frontend/app/assets/javascripts/tree_renderers.js.erb
- frontend/app/assets/stylesheets/archivesspace/common.less
- frontend/app/controllers/archival_objects_controller.rb
- frontend/app/controllers/digital_object_components_controller.rb
- frontend/app/controllers/digital_objects_controller.rb
- frontend/app/controllers/resources_controller.rb
- frontend/app/views/archival_objects/_form_container.html.erb
- frontend/app/views/digital_object_components/_form_container.html.erb
- frontend/app/views/digital_object_components/_show_inline.html.erb
- frontend/app/views/digital_objects/_edit_inline.html.erb
- frontend/app/views/digital_objects/_show_inline.html.erb
- frontend/config/initializers/i18n.rb
Delivers https://archivesspace.atlassian.net/browse/AR-1695
> AR-1695 parse mixed content in resource/digital object trees, headings and messages

- README_RELEASE.md
> Update Release MD file so that the correct version number will be in the footers of the documentation

- public-new/app/controllers/pdf_controller.rb
- public-new/app/views/pdf/_archival_object.html.erb
- public-new/app/views/pdf/_footer.html.erb
- public-new/app/views/pdf/_header.html.erb
- public-new/app/views/pdf/_resource.html.erb
- public-new/app/views/pdf/_toc.html.erb
- public-new/config/locales/en.yml
Namely:
* Expand the table of contents to include links to the major
sections and note types.
* Indent the Collection Inventory records according to their depth
in the record tree.  Show some nice lines to indicate how deep you
are.
* Apply I18n where needed
> Betterment of PDF generation!

- backend/app/exporters/lib/export_helpers.rb
- backend/app/exporters/serializers/ead.rb
https://github.com/archivesspace/archivesspace/issues/754
> include unitdate @era, @calendar attribs in export

- .travis.yml
Per https://github.com/travis-ci/travis-ci/issues/5227
> Force a shorter host name so travis doesn't barf

- backend/app/controllers/date_calculator.rb
- backend/app/model/date_calculator.rb
- backend/spec/controller_date_calculator_spec.rb
- backend/spec/model_date_calculator_spec.rb
- frontend/app/assets/javascripts/date_calculator.js.erb
- frontend/app/assets/javascripts/resources.crud.js.erb
- frontend/app/assets/javascripts/resources.show.js.erb
- frontend/app/controllers/date_calculator_controller.rb
- frontend/app/views/date_calculator/_no_object.html.erb
- frontend/app/views/date_calculator/_results.html.erb
- frontend/app/views/date_calculator/_template.html.erb
- frontend/app/views/date_calculator/_toolbar_button.html.erb
- frontend/app/views/shared/_component_toolbar.html.erb
- frontend/app/views/shared/_resource_toolbar.html.erb
- frontend/config/locales/en.yml
- frontend/config/routes.rb
… accessible via the backend API and frontend toolbar menu.
> Implement the date calculator for resource and components

- backend/app/model/mixins/tree_nodes.rb
- backend/spec/model_publish_spec.rb
> Take into account suppressed ancestors when calculating has_unpublished_ancestor

- public-new/app/models/resource.rb
- public-new/app/views/layouts/application.html.erb
- public-new/app/views/shared/_metadata.html.erb
Currently only resources are supported.
> AR-1484 Include json-ld in the head for supported record types

- .travis.yml
@mark-cooper Please review and merge this.
> Remove notification of travis builds to IRC channel since we are getting rid of the channel at the end of May 2017

- indexer/app/lib/indexer_common.rb
- public-new/app/helpers/record_helper.rb
- public-new/app/models/agent_corporate_entity.rb
- public-new/app/models/agent_family.rb
- public-new/app/models/agent_person.rb
- public-new/app/models/resource.rb
adding json-ld to people and a little fix for resources
> AR-1484 semantically rich metadata

- public-new/app/controllers/agents_controller.rb
- public-new/app/controllers/subjects_controller.rb
> AR-1750 no repo facet in subjects and names

- backend/app/lib/export.rb
Need to resolve reference to container profile to avoid the
dreaded "undefined method `[]' for nil:NilClass".
> Fix ead export with container profile

- public-new/app/models/record.rb
- public-new/app/views/shared/_idbadge.html.erb
> AR-1792 other level in badges

- public-new/app/helpers/json_helper.rb
…ype. also add a br for more separation - sigh
> AR-1798 repeated notes should display

- public/app/views/pdf/_archival_object.html.erb
- public/app/views/pdf/_digital_object_links.html.erb
- public/app/views/pdf/_resource.html.erb
Pulled the common bits into a partial to remove duplication.
> AR-1471 Don't show thumbnail links as digital objects

- build/build.xml
- frontend/config/application.rb
- public/README.md
- public/config/application.rb
Hi @lmcglohon,
I've updated the public interface's README to better reflect the state of reality :)  While documenting the locales stuff I realized what was there doesn't really make sense for the ArchivesSpace distribution, so I've also updated the location of the locale files so people can override them if needed.
Cheers,
Mark
> PUI readme and locale overrides

- UPGRADING_2.1.0.md
> Documentation for upgrading to version 2.1.0

- public/config/application.rb
Thanks @sdm7g! Here is the fix, I believe.
Fixes #883
> Fix locale for PUI

- public/app/views/pdf/_archival_object.html.erb
- public/app/views/pdf/_resource.html.erb
- public/app/views/pdf/_toc.html.erb
(I fat-fingered and momentarily pushed this to master before reverting it about 10 seconds later.  Apologies!)
> AR-1852 If a note has a label, display it in preference to the note type

- backend/app/converters/ead_converter.rb
Since indexentry children are generally all describing the same entity,
parse the entry into a fragment, and construct a single item from the
contents of the children.
Refer to https://archivesspace.atlassian.net/browse/ANW-167 for details of issue.
> Improvement to indexentry handling. Refer #873

- common/config/config-distribution.rb
Reverts archivesspace/archivesspace#907
> Revert "Undo Suppress useless already set config messages because is causes"

- backend/app/converters/ead_converter.rb
This should fix the problem with indexentry erroring out.
> blocks passed to `with` must take args

- public/app/models/record.rb
- public/app/views/shared/_record_innards.html.erb
Delivers https://archivesspace.atlassian.net/browse/AR-1801
> AR-1801 fix top container title showing hash rather than string

- backend/app/model/mixins/notes.rb
Analysis of database usage on a large dataset exposed an issue in the notes mixin whereby "empty" queries were being generated by Sequel and not optimised in any way by MySQL.  This resulted in performance degradations for datasets with large numbers of notes.
It is likely this was introduced with the rights statement changes wherein the notes subrecord was linked to a nested record for the first time (previously always linked to top level records).  And this is the scenario in which these empty notes queries are created.
> Improve general performance by ensuring the notes mixin no longer runs "empty" SELECT queries against the notes tables

- common/config/config-defaults.rb
- public/app/assets/stylesheets/archivesspace/aspace.scss
- public/app/controllers/search_controller.rb
- public/app/views/layouts/application.html.erb
- public/app/views/search/search_results.html.erb
- public/app/views/shared/_navigation.html.erb
- public/app/views/shared/_search.html.erb
- public/app/views/shared/_skipnav.html.erb
- public/config/locales/en.yml
Delivers:
* https://archivesspace.atlassian.net/browse/AR-1741
* https://archivesspace.atlassian.net/browse/AR-1742
* https://archivesspace.atlassian.net/browse/AR-1743
> PUI skipnav and search changes

- frontend/app/assets/javascripts/ajaxtree.js.erb
Delivers https://archivesspace.atlassian.net/browse/ANW-132
> ANW-132 ensure current node is visible in tree pane after save

- backend/app/converters/accession_converter.rb
Reverts archivesspace/archivesspace#931
None of the telephone fields are being populated from the accession csv importer so more needs to be done to fix this issue.
> Revert "ANW-90 make the accession importer respect the changed model for tele…"

- public/config/locales/en.yml
- public/config/locales/fr.yml
Reverts archivesspace/archivesspace#938
@cfitz This needs to be more thought out as far as how to handle this issue.
> Revert "Quit trying to interpolate 'limit' variable in search-limit i18n"

- common/aspace-rails/asset_path_rewriter.rb
> Ensure asset paths in public CSS files are rewritten to include the prefix

- README.md
- backend/app/controllers/exports.rb
- backend/app/exporters/lib/exporter.rb
- backend/app/exporters/lib/utils.rb
- backend/app/exporters/models/ead.rb
- backend/app/exporters/serializers/ead3.rb
- backend/app/lib/export.rb
- backend/spec/export_ead3_spec.rb
- backend/spec/exporter_spec.rb
- backend/spec/factories.rb
- build/solr_home/collection1/conf/_rest_managed.json
- frontend/app/assets/javascripts/export_dropdown.js.erb
- frontend/app/controllers/exports_controller.rb
- frontend/app/views/resources/_toolbar.html.erb
- frontend/config/locales/en.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
- public/vendor/assets/javascripts/largetree.js.erb
add ead3 param to js
clone EADSerializer as EAD3Serialier and pass opts to use it when selected
add spec for ASpaceExporter
udpate readme with log
added xml-model for rng schema
begin work on control
add exporter spec and mod repo factory:
more control work
even more work on control subelements
more control
control complete all specs passing
update readme
work on did subelements
update readme
update readme
work on dates
serialize_dates complete
finish did notes and fix date specs
more notes
done with controlaccess
update README
final integration of code components common to 2002 schema serializer
update readme
bug fixes
add conversion of extref in mixed content - closes #1
add strip_attribute_namespace_prefixes - fixes #2
convert @type to @localtype in mixed contet - fixes #3
wrap text …
> add EAD3 export serializer and updates to supporting files

- .gitignore
- common/config/config-defaults.rb
- public/app/helpers/application_helper.rb
- public/app/helpers/requests_helper.rb
- public/app/mailers/request_mailer.rb
- public/app/models/accession.rb
- public/app/models/concerns/resource_request_items.rb
- public/app/models/digital_object.rb
- public/app/models/request_item.rb
- public/app/views/shared/_request_page_action.html.erb
Add support for using a repository's email address for requests.
> Use and prefer repo defined email for requests

- .gitignore
- common/config/config-defaults.rb
- public/app/helpers/application_helper.rb
- public/app/helpers/requests_helper.rb
- public/app/mailers/request_mailer.rb
- public/app/models/accession.rb
- public/app/models/concerns/resource_request_items.rb
- public/app/models/digital_object.rb
- public/app/models/request_item.rb
- public/app/views/shared/_request_page_action.html.erb
Add support for using a repository's email address for requests.
> Add support for using a repository's email address for requests.

- backend/app/exporters/serializers/ead3.rb
[JIRA ar-1868](https://archivesspace.atlassian.net/browse/AR-1868) applied to ead3 serializer and additional EAD3 bug fixes: Issue #975
> Ar 1868 ead3

- frontend/app/controllers/resolver_controller.rb
> respond to autoselect_repo param for readonly same as edit

- backend/app/lib/job_runners/print_to_pdf_runner.rb
Fixes https://archivesspace.atlassian.net/browse/AR-1883.
> Add new container pieces to the staff interface print to PDF method

- CUSTOMIZING_THEMING.md
Just a few notes on public vs private and where stuff goes
> some clarifications

- launcher/archivesspace.sh
> Fix PIDFILE variable name within status function

- common/db/migrations/094_add_description.rb
- common/locales/en.yml
- common/schemas/repository.rb
- frontend/app/views/repositories/_form_container.html.erb
- public/app/controllers/concerns/result_info.rb
- public/app/views/repositories/_full_repo.html.erb
- public/config/locales/en.yml
https://archivesspace.atlassian.net/browse/AR-1907
> Add description field to repository record and display in pui

- common/multipart_buffer_setter.rb
- frontend/config.ru
- frontend/config/application.rb
chrome driver implementation from Chris Fitzpatrick - https://github.com/cfitz/archivesspace/tree/chromedriver
@cfitz
> Alternative method for fixing rack issue 1075 for preparation of adding

- public/app/controllers/concerns/searchable.rb
I added the escaping of reserved characters in the query string so that the brackets are handled. However, it means that it will return results for a search that is and is not bracketed (or has one of the reserved characters in the string). For example, searching for book, [book] or "[book]" will return the same results.
> ANW-231: Added the use of escaping reserved characters in a search query

- frontend/app/views/digital_object_components/defaults.html.erb
for the default value web page. Also, Digital Object Component was displaying on the page twice so I removed the extra `<h2>` tag from the defaults main page.
@cdibella @archivesspace/archivesspace-core-committers
> ANW-197: Was using digital_object instead of digital_object_component as data

- frontend/app/controllers/classification_terms_controller.rb
- frontend/app/views/classification_terms/_form_container.html.erb
- frontend/app/views/classification_terms/_linker.html.erb
- frontend/app/views/classification_terms/_record_linker.html.erb
- frontend/app/views/classification_terms/_show.html.erb
- frontend/app/views/classification_terms/_show_inline.html.erb
- frontend/app/views/classification_terms/_template.html.erb
- frontend/app/views/classification_terms/defaults.html.erb
- frontend/config/locales/en.yml
Fixes https://archivesspace.atlassian.net/browse/ANW-233
@maderikra 
> ANW-233: Ensure that linked records both display and stay linked with classification terms

- backend/app/model/repository.rb
> Add ability to print to PDF for users in the repository-archivist standard group

- frontend/app/views/shared/_header_user.html.erb
Repository Manager group now has the options of managing Controlled Value Lists, Container Profiles, and Location Profiles.
@cdibella @archivesspace/archivesspace-core-committers
> ANW-200: Correct display of appropriate options based upon permissions

- indexer/spec/indexer_common_config_spec.rb
- indexer/spec/indexer_common_spec.rb
> Update indexer tests to accommodate changes for assessments module and

- public/app/views/welcome/show.html.erb
- public/config/locales/en.yml
Recommended by PUI Enhancement group:
http://cherryhill.github.io/aspace_pui/01landing.html
(click Keyword, last item is "Identifier")
> Add identifier to field options.

- public/app/assets/stylesheets/archivesspace/aspace.scss
- public/app/views/layouts/application.html.erb
- public/app/views/shared/_footer.html.erb
- public/app/views/shared/_navigation.html.erb
- Use fluid more consistently
- Better alignment of main sections
- Restore the missing footer items
This can all be overidden as usual.
> Minimal changes to fix basic layout:

- backend/app/converters/lib/marcxml_base_map.rb
- backend/app/exporters/examples/marc/authority_john_davis.xml
- backend/app/exporters/examples/marc/gf2014026450.xml
- backend/spec/lib_marcxml_converter_spec.rb
- common/locales/enums/en.yml
Populate bioghist note from 678
Name order set directly in name_map
Set source lcgft for genre/form
Trim punctuation in name field values
> Updates to marc agents / subjects import

- public/app/assets/stylesheets/archivesspace/aspace.scss
- public/app/views/resources/show.html.erb
- public/app/views/search/search_results.html.erb
- public/app/views/shared/_facets.html.erb
- public/app/views/shared/_sorter.html.erb
Some margin for expand all
Give sort selection more space to reduce wrapping effect
Filter / Collection form saner alignment irrespective of width
> Small pui tidyups

- public/app/views/shared/_digital.html.erb
is no thumbnail image into a standard href
Also fixed indentation so I could do the refactor.
> Fix digital object link issue by converting the button form when there

- public/app/controllers/concerns/result_info.rb
- public/app/views/shared/_digital.html.erb
> Use correct field for setting caption

- frontend/app/assets/stylesheets/archivesspace/header.less
- frontend/app/views/shared/_header_global.html.erb
This prevents that from happening.
Related to: https://archivesspace.atlassian.net/browse/AR-1287
> On smaller width screens the global navbar disappears completely =(

- backend/app/exporters/models/ead.rb
but the lock_version is not. For EAD export, the assumption was that equal lock_versions in the database and index means that the index record is up-to-date. However, the position in the index is not updated until the record is indexed. This change ensures that the correct position is used in the EAD export.
> When tree nodes are re-ordered, the position in the database is updated

- reports/digital_objects/digital_object_list_table_report/digital_object_list_table_report.rb
> this should be repository scoped

- reports/accessions/created_accessions_report/created_accessions_report.rb
Same issue and fix as (closed) #1109
> another report that should have been repository scoped

- frontend/app/views/layouts/application.html.erb
curious if a bit of mimicry could fix this issue for the staff interface - please review to see if it makes sense for this file
> add lang attribute to html tag for staff interface

- backend/app/exporters/models/mods.rb
- backend/app/exporters/serializers/mods.rb
- backend/spec/export_mods_spec.rb
ANW-289 Make MODS exporter utilize subject term type
> ANW-289_mods_exporter_subject_fields

- public/Gemfile
> Temporary fix until the code is updated for lastet font-awesome gem #1131 

- clustering/CLUSTERING_README.md
- launcher/archivesspace.bat
- launcher/archivesspace.sh
- launcher/service.bat
> Update Java version documentation to current required versions

- backend/app/lib/oai/mappers/oai_dc.rb
- backend/spec/model_oai_spec.rb
- backend/spec/oai_helper.rb
- backend/spec/oai_mappers_spec.rb
Bugfix for ANW-321: Conditions Governing Access and Conditions Governing Use are now mapped to <dc:rights>.
> Bugfix for ANW-321: Conditions Governing Access and Conditions

- common/locales/en.yml
Small change to generalize the date expression tooltip.
> ANW-602 generalize date expression tooltip

- public/README.md
https://github.com/archivesspace/archivesspace/issues/1189
> Correct link to config-defaults.rb file

- common/db/migrations/098_remove_bulk_inclusive_events.rb
- common/locales/en.yml
- common/locales/es.yml
- common/locales/fr.yml
- frontend/app/views/dates/_template.html.erb
- frontend/app/views/events/_form.html.erb
Note that this involves db migration 098, and so does #1141 .  Since I don't know whether both or none or one PR will be accepted and, if both accepted, in what order, I've left them both 098, but whichever PR gets accepted second will need to be modified making the db migration 099.
> ANW-354 Remove bulk and inclusive date types from event records

- frontend/app/assets/javascripts/largetree.js.erb
- public/vendor/assets/javascripts/largetree.js.erb
See https://archivesspace.atlassian.net/browse/ANW-680
Note that I updated both versions of the file, despite the message within the frontend version about being the "canonical" version.  At least when using a dev version of ASpace, I had to update both files to get the updated results in the staff interface and the PUI.
> fix for hover text and HTML output

- public/app/models/resource.rb
See https://archivesspace.atlassian.net/browse/ANW-677
> ANW-677: json-ld language fix

- public/app/controllers/accessions_controller.rb
- public/app/controllers/agents_controller.rb
- public/app/controllers/classifications_controller.rb
- public/app/controllers/objects_controller.rb
- public/app/controllers/repositories_controller.rb
- public/app/controllers/resources_controller.rb
- public/app/controllers/subjects_controller.rb
@cfitz @pobocks solution to replace https://github.com/archivesspace/archivesspace/pull/1160
> Replace deprecated skip_before_filter with the appropriate skip_before_action method

- backend/spec/model_solr_spec.rb
- common/config/config-defaults.rb
Also updated tests to new expect syntax
> Set default search operator to AND in AppConfig

- build/build.xml
update to jruby-9.1.17.0    https://github.com/archivesspace/archivesspace/issues/1224
> update jruby: issue #1224

- common/config/config-distribution.rb
Use redacted form of db url (as it is elsewhere).
Protect keys and values containing sensitive terms. Erring on side of
caution to avoid leaking info via ui / api.
> Some security updates for dumped settings:

- backend/app/exporters/models/marc21.rb
- backend/spec/export_marc_spec.rb
MARCXML export: update 041 field with correct ind2 and subfield $2
> MARCXML export: update 041 field with correct ind2 and subfield $2

- frontend/app/helpers/search_helper.rb
- frontend/app/views/digital_objects/index.html.erb
- frontend/app/views/resources/index.html.erb
- frontend/app/views/search/_context.html.erb
- frontend/app/views/search/_listing.html.erb
- frontend/app/views/search/_results.html.erb
- frontend/config/locales/en.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
@lmcglohon, @cdibella - First draft ready for review/testing.  I think I covered all the angles we discussed.  A close review of the new methods in search_helper would be especially helpful!
> ANW-566 search results in context

- frontend/app/views/layouts/application.html.erb
- frontend/app/views/shared/_header_global.html.erb
- frontend/app/views/shared/_header_repository.html.erb
- frontend/app/views/site/_branding.html.erb
- frontend/app/views/site/_footer.html.erb
Layout update as used by demo, test, sandbox.
> Use fluid containers for staff ui (more screen real estate)

- frontend/app/helpers/search_helper.rb
- frontend/app/views/search/_context.html.erb
> Remove identifier from context string

- frontend/config/initializers/javalibs.rb
This file is old and is not doing anything and can be removed.
> Remove a weird old file from initializers

- README_TUNING.md
- launcher/archivesspace.bat
- launcher/archivesspace.sh
This adds some options that i've used to make optimize JVM for jruby.
Reduces the memory usage.
> Adding some GC opts to optimize jruby

- backend/app/converters/lib/marcxml_base_map.rb
- backend/spec/lib_marcxml_converter_spec.rb
Fix for https://archivesspace.atlassian.net/browse/ANW-713
> ANW-713: Remove literal "Indicator 1" from notes

- common/config/config-defaults.rb
It now == AppConfig[:public_proxy_url]
> Updating default value for AppConfig[:ark_url_prefix]

- public/app/views/pdf/_archival_object.html.erb
- public/app/views/pdf/_header.html.erb
Attempts at some changes to basic formatting on the PUI PDF until the process for it can be reviewed and possibly changed to make it in line with the staff PDF.
> ANW-258 - some small stylistic changes to PUI PDF

- Dockerfile
https://github.com/docker/hub-feedback/issues/508
Attempt lookup branch or match tag for version.
> Source branch not available in Docker Hub w/o hooks.

- backend/app/controllers/resource.rb
@cdibella @lmcglohon - Updated as we discussed this morning!
> Update API description for top_containers.

- frontend/app/views/top_containers/bulk_operations/_results.html.erb
column added to top container results table
> ANW-541: Add container type column to top container results table

- README.md
I'm afraid this wasn't really clear.
> Clean up MySQL Backups How-To Area A Bit

- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/issue-template.md
Create an issue template for bugs, enhancements, and new features
> Update issue templates

- frontend/app/assets/stylesheets/themes/default/default.less
- public/app/assets/stylesheets/archivesspace/aspace.scss
Also removed sidebars from print view on frontend
> Removed pagination and hrefs from print view to clean up printing results

- frontend/Gemfile
- frontend/Gemfile.lock
Reverts archivesspace/archivesspace#1341
Need to examine staff UI implications
> Revert "#1177 Remove less-rails-boostrap"

- Dockerfile
- README_DOCKER.md
- docker-compose.yml
Uses wget for Docker status health check.
n/a
Sets health check status correctly.
Build, run, review status.
> Use already installed wget for docker health check

- frontend/app/helpers/application_helper.rb
- frontend/app/views/locations/show.html.erb
Display record URI with audit info
Add URI to info included in audit info (creation and modification user/date) with each record, and add display_audit_info helper to show template for locations. Modify audit info formatting slightly to accommodate addition.
NA
Facilitates integrations by providing record URI which can then be used to identify the ArchivesSpace record in another system and enable communication with the AS API
Ran existing front-end tests with no failure. Verified that record views display URI with audit info
- [X ] New feature (non-breaking change which adds functionality)
- [X ] My code follows the code style of this project.
- [X ] I have read the **CONTRIBUTING** document.
- [X ] All new and existing tests passed.
> add uri to audit info and add audit info to locations show

- frontend/app/views/locations/index.html.erb
Changed the permission to "update_location_record"
issue #1351  
Because batch editing is limited to only system adminstrators, rather than repository managers/others with the ability to edit locations.
I tested it by running a local copy and verifying that a repository manager could edit locations.
Note: I omitted regression tests because, well, the browser-based tests are an ongoing issue right now, and this is very, very low-risk.
> Fixes #1351 by making checkboxes coherent with edit permissions

- backend/app/views/reports/report_content.erb
Adds alt text to the logo image included report header.
https://archivesspace.atlassian.net/browse/ANW-704
Continue to resolve accessibility issues.
> Add alt text to report logo

- README_HTTPS.md
- [x ] New feature (non-breaking change which adds functionality)
- [ x] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
> Add a note about optionally setting secure cookie headers to Apache

- frontend/vendor/assets/javascripts/bootstrap-combobox.js
Accessibility changes made for ANW-702 for the comboboxes negatively impacted the extents and language comboboxes so the changes need to be removed until a better solution is determined.
Manually tested with local build
> Revert accessibility changes for comboboxes

- public/app/assets/stylesheets/archivesspace/colors.scss
Adjust existing default colors to improve contrast ratios.  Spreadsheet documenting changes attached to https://archivesspace.atlassian.net/browse/ANW-370
https://archivesspace.atlassian.net/browse/ANW-356
https://archivesspace.atlassian.net/browse/ANW-370
Pass contrast checks.
Visually inspected.
Homepage before PR:
Homepage after PR:
Subjects listing before PR:<img width="1132" alt="old_subjects" src="https://user-images.githubusercontent.com/15144646/49452955-2c0aa500-f7b0-11e8-9901-ebc1f6e3805b.png">
Subjects listing after PR:
> Improve color contrast

- backend/app/lib/oai/aspace_oai_repository.rb
- backend/spec/model_oai_spec.rb
Reverts archivesspace/archivesspace#1407
> Revert "ANW-794: Omit entities from OAI that have unpublished ancestors"

- frontend/app/helpers/aspace_form_helper.rb
Fixes unintended bug wherein the event date/time dropdown does not function.
Revert buggy form helper change from #1417 
Bug fix for event records.
Visually inspected.
Before PR:
After PR:
> Fix event date dropdown

- frontend/app/views/oai_config/edit.html.erb
Repository URI used for editing OAI settings doesn't not take into consideration a prefixed or proxied server
https://archivesspace.atlassian.net/browse/ANW-674
See testing comments in JIRA ticket
> Add prefix information to repository URI for correct URL for Edit OAI Settings button

- frontend/app/views/agents/_merge_dropdown.html.erb
- frontend/config/locales/en.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
- frontend/config/locales/ja.yml
Provide mechanism for configuring text on agent merge modal window button
> Add translation for Agent merge specific button

- frontend/app/assets/javascripts/agents.browse_merge.js
- frontend/app/assets/javascripts/agents.index.js
Ensure that the target agent for the merge is the first selected instead of the first agent in the sorted display in the UI
> Grab first selected agent to make it the target agent for a merge

- frontend/app/views/agents/_merge_selector.html.erb
- frontend/app/views/agents/index.html.erb
- frontend/app/views/external_documents/_template_merge_target.html.erb
> Remove merge button from agents browse and fix external documents for merging

- common/config/config-defaults.rb
This was included in this PR (https://github.com/archivesspace/archivesspace/pull/1360) but somehow got removed prior to creating release v2.5.2
https://archivesspace.atlassian.net/browse/ANW-267
> Add path_to_java configuration for PDF generation on Windows

- public/app/views/layouts/application.html.erb
Missing favicon in Public User Interface
> Include Favicon in Public User Interface

- common/locales/es.yml
- common/locales/ja.yml
- frontend/config/locales/es.yml
- frontend/config/locales/ja.yml
- public/config/locales/es.yml
- public/config/locales/ja.yml
All locales files should have the same key/values pairs
> Add slugs to Spanish and Japanese locales files along with note that translations are courtesy of Google translate

- frontend/app/helpers/application_helper.rb
Minor update to my previous PR that added the URI to the audit info. This update puts the value inside a readonly input field to make it easier for users to select the value for copy/paste.
NA
We've found that users are having difficulty accurately selecting the full URI before copying. This change enables easy selection via triple-click in most browsers.
Tested UI in local instance
- [ X ] New feature (non-breaking change which adds functionality)
> put URI value inside input for easier selection

- backend/app/lib/username.rb
- common/locales/en.yml
- common/locales/es.yml
- common/locales/fr.yml
- common/locales/ja.yml
- frontend/app/controllers/users_controller.rb
Allow @ character in usernames and use form validation to ensure valid username.
- allow usernames to contain @ character
- update username tooltip to specify allowed characters
- validate username before submitting form so it shows a meaningful error message
[ANW-92](https://archivesspace.atlassian.net/browse/ANW-92)
Many users want or expect to be able to use @ symbols in their usernames, most typically so they can use their email address as their username.
Tested that a user can be created with a username that includes @ and that when the username contains an invalid character or is missing an appropriate and meaningful error message is shown.
> ANW-92 : Allow @ in usernames

- launcher/plugin_gems/initialize-plugin.bat
> determine which bundler version to use

- backend/app/lib/slugs/slug_helpers_generate_by_name.rb
- backend/app/model/accession.rb
- backend/app/model/agent_corporate_entity.rb
- backend/app/model/agent_family.rb
- backend/app/model/agent_person.rb
- backend/app/model/agent_software.rb
- backend/app/model/archival_object.rb
- backend/app/model/classification.rb
- backend/app/model/classification_term.rb
- backend/app/model/digital_object.rb
- backend/app/model/digital_object_component.rb
- backend/app/model/repository.rb
- backend/app/model/resource.rb
- backend/app/model/subject.rb
- frontend/app/controllers/archival_objects_controller.rb
- frontend/app/controllers/classification_terms_controller.rb
- frontend/app/controllers/classifications_controller.rb
- frontend/app/controllers/digital_object_components_controller.rb
- frontend/app/controllers/digital_objects_controller.rb
- frontend/app/controllers/repositories_controller.rb
- frontend/app/controllers/resources_controller.rb
- frontend/app/controllers/subjects_controller.rb
- frontend/app/views/shared/_slug.html.erb
Ongoing work for ANW-617: Refactoring and bug fixes
Fixes for 500 errors in views
Flash message for all entity types when is_slug_auto turned off due to empty slug
Refactored auto_generator in models
https://archivesspace.atlassian.net/projects/ANW/issues/ANW-617?filter=myopenissues
Manual testing
> ANW-617 - Fixes and refactoring 

- common/locales/en.yml
- common/locales/es.yml
- common/locales/fr.yml
- common/locales/ja.yml
Added a sentence suggested by Kevin Clair in the comments to ANW-345. I did in all four languages currently represented by our locales files, though the Japanese one is solely Google Translate and could use a check by a fluent speaker/reader.
ANW-345
To hopefully clear up some confusion about behavior in the Collection Management sub-record.
> ANW-345 - small addition to the processing total extent tooltip

- public/config/routes.rb
Reorder of the routes file caused incorrect routes to be used for top containers
Top containers would not diplay in the PUI
Manually
> Move top container route above slugged object routes otherwise the slugged object routes are matching for top containers and causing errors

- Dockerfile
> Add build-essential for Docker builds

- backend/app/converters/location_converter.rb
- backend/app/exporters/examples/location/aspace_location_import_template.csv
- backend/spec/lib_location_converter_spec.rb
- common/locales/en.yml
- common/locales/es.yml
- common/locales/fr.yml
- common/locales/ja.yml
Add Locations import from CSV.
Sample import spreadsheet provided and tests follow importer conventions.
> Add location csv import

- public/app/controllers/objects_controller.rb
- public/config/routes.rb
These were routes that weren't being used in the application.
> Remove unused request_showing method and routes from PUI

- public/app/views/shared/_print_page_action.html.erb
I think it was just renamed from `fa-file-pdf-o` to `fa-file-pdf` in FA 5.
> Fixes a croken Font Awesome PDF icon on PUI

- docs/doc/RecordHelper.html
- public/app/helpers/record_helper.rb
- public/app/views/repositories/_badge.html.erb
- public/app/views/shared/_digital.html.erb
> Fixes a broken Font Awesome file icon on PUI

- docs/doc/RecordHelper.html
- public/app/helpers/record_helper.rb
- public/app/views/repositories/_badge.html.erb
> Fixes a broken Font Awesome text icon on PUI

- public/app/views/repositories/_badge.html.erb
> Fixes a broken Font Awesome agent icon on PUI

- public/app/views/shared/_record_innards.html.erb
Added label for scope and contents note.
[ANW-296](https://archivesspace.atlassian.net/browse/ANW-296)
The scope and contents note should have a label in the PUI because it is the only finding aid element without one.
scope and contents note now shows up with appropriate label in PUI
> ANW-296: add label for scope and contents note

- _yard/API.erb
- backend/app/controllers/container.rb
> Bugfix in API.erb, used non-printing eval for shell example

- backend/app/converters/ead_converter.rb
Provide the appropriate (non-default) argument to insert_into_subnotes
ANW-223
Bug fix
Tested with sample file in JIRA as well as a couple of extra EADs with chronlists.
build/run backend:test
- [x ] All new and existing tests passed.
> Fix for duplicate chronlist import

- public/app/helpers/record_helper.rb
Missed the archival object icon when updated the font awesome gem
Visually made sure the icon showed up
> Update font awesome icon for archival objects

- plugins/jobs_example/README.md
- plugins/jobs_example/frontend/assets/javascripts/slow_nothing.js
- plugins/jobs_example/frontend/locales/en.yml
- plugins/jobs_example/frontend/locales/fr.yml
- plugins/jobs_example/frontend/views/slow_nothing_job/_form.html.erb
Make sample background job clearer and more robust in order to make it easier to add a background job plugin as well as update existing job plugins to work with upcoming release.
There have been changes to the background jobs code that may impact job plugins people have created.
> update sample job to reflect changes to background jobs

- frontend/app/views/shared/_breadcrumb.html.erb
- public/app/views/pdf/_archival_object.html.erb
- public/app/views/pdf/_resource.html.erb
- public/app/views/pdf/_titlepage.html.erb
- public/app/views/pdf/_toc.html.erb
This covers the 4 remaining  Ampersand JIRAs
ANW-822 and ANW-316, were small fixes not related to each other or others
ANW-831 is the big one that causes the big fails, putting an "&" in many places causes PDFs to fail
ANW-858 is fixed here as well, that was pretty much the same thing.
Here are all those ampersands tickets:
https://archivesspace.atlassian.net/browse/ANW-858 (fixed here)
https://archivesspace.atlassian.net/browse/ANW-831 (fixed here)
https://archivesspace.atlassian.net/browse/ANW-823 (fixed in another PR)
https://archivesspace.atlassian.net/browse/ANW-822 (fixed here)
https://archivesspace.atlassian.net/browse/ANW-751 (fixed in another PR)
https://archivesspace.atlassian.net/browse/ANW-316 (fixed here)
> Fixes For Ampersands in PUI PDFs

- common/locales/en.yml
- common/locales/es.yml
- common/locales/fr.yml
- common/locales/ja.yml
Added tooltips for the three fields related to HRUs.
More ANW-617 refinements
Consistency with tooltips for all other fields.
- [ x] New feature (non-breaking change which adds functionality)
> added tooltips for three fields related to HRUs

- backend/app/lib/job_runners/generate_slugs_runner.rb
- backend/app/lib/slugs/slug_helpers_generate.rb
- common/locales/en.yml
- common/locales/es.yml
- common/locales/fr.yml
- common/locales/ja.yml
- frontend/app/controllers/accessions_controller.rb
- frontend/app/controllers/agents_controller.rb
- frontend/app/controllers/archival_objects_controller.rb
- frontend/app/controllers/classification_terms_controller.rb
- frontend/app/controllers/classifications_controller.rb
- frontend/app/controllers/digital_object_components_controller.rb
- frontend/app/controllers/digital_objects_controller.rb
- frontend/app/controllers/repositories_controller.rb
- frontend/app/controllers/resources_controller.rb
- frontend/app/controllers/subjects_controller.rb
- frontend/app/views/shared/_slug.html.erb
If the data in a field being used to generate a slug has two slashes (//) in it, assume it contains a URL and do not use that data to generate a slug
Remove tags in data being used to generate a slug
Make the autogenerate slug disabled message a warning after the success message instead of a part of the success message and rewrite of the warning messages
Use correct record type in logging message
Make Public URL an actionable link in edit mode
Visually
> Small updates for the next release

- frontend/app/assets/javascripts/jobs.crud.js
> Enable file uploads using Safari

- common/locales/en.yml
> Make auto-generate slug label capital case like everything else

- Dockerfile
Build failed on the RC and this should fix that.
> Use available source branch for Docker builds

- backend/app/exporters/models/marc21.rb
MARC export for 7xx was changed from translation to enumeration
https://archivesspace.atlassian.net/browse/ANW-896
> MARC Export 7xx  relator should be the three letter code

- backend/app/exporters/serializers/ead.rb
- backend/spec/export_marc_spec.rb
- backend/spec/export_spec_helper.rb
> Fix ead export

- common/db/migrations/122_create_lang_materials_schema.rb
> Refactor 122 migration

- backend/app/lib/oai/mappers/oai_mods.rb
Removes two duplicated case statements from the OAI MODS export mappings.
Removes unnecessary/duplicative code.
> Remove duplicate case statements

- frontend/app/controllers/top_containers_controller.rb
- frontend/app/views/shared/_header_repository.html.erb
- frontend/app/views/top_containers/bulk_operations/_toolbar.html.erb
View-only option for manage top containers.
https://archivesspace.atlassian.net/browse/ANW-280
Manual ui tests.
> Allow read user to view & search for top containers

- common/db/migrations/121_add_scripts_update_finding_aid_language.rb
Update migration 121 to catch exceptions for unparseable notes or notes without the required attributes. Provide more detailed logging of the migration activity.
Successfully upgraded database that was failing the migration.
> Catch exceptions and log activity

- .travis.yml
- build/build.xml
From Mark Triggs, improvements to dist builds (https://github.com/hudmol/archivesspace/commit/00a201f1b34d65505a8ac43ff20f07d0903f39ce)
Updated travis tests to not use Java 7 and created new matrix for running tests in less than 50 minutes - a travis limit
Faster build times and improved travis testing
> Improve build and travis tests

- solr/solrconfig.xml
Refs #1636 - decomposes bq into multiple parameters as per https://lucene.apache.org/solr/guide/7_4/the-dismax-query-parser.html#bq-boost-query-parameter
#1636 
Tested on my local, QA, and production Solr instances.
> Separate terms in default bq

- common/config/config-defaults.rb
Better clarity for Staff Only option and removed unnecessary example
Better clarity for Staff Only option and removed unnecessary example to make these less confusing.
- [ x] My change requires a change to the documentation.
>  Small pui-related config changes

- public/app/views/pdf/_digital_object_links.html.erb
Addresses https://archivesspace.atlassian.net/projects/ANW/issues/ANW-909
There is no check present in the `_digital_object_links.html.erb` partial to confirm digital objects are published before adding in these instance links in the PDF.  This corrects that.
https://archivesspace.atlassian.net/projects/ANW/issues/ANW-909
Removes unpublished content from public PDF.
Manually tested, existing tests passed.  Note: There aren't currently any tests for the public-side PDF, and this doesn't add any.
Before fix:
After fix:
> ANW-909 Don't show unpublished DOs in PDF

- backend/app/model/solr.rb
- backend/spec/model_solr_spec.rb
Extension of previous PR: #1637
> Ref #1636 - updated handling of params on backend

- backend/app/controllers/search.rb
- backend/app/model/search.rb
- backend/app/model/solr.rb
- frontend/app/controllers/application_controller.rb
- frontend/app/views/accessions/index.html.erb
- frontend/app/views/agents/index.html.erb
- frontend/app/views/classifications/index.html.erb
- frontend/app/views/digital_objects/index.html.erb
- frontend/app/views/events/index.html.erb
- frontend/app/views/locations/index.html.erb
- frontend/app/views/resources/index.html.erb
- frontend/app/views/search/_results.html.erb
- frontend/app/views/subjects/index.html.erb
The CSV export functionality exports more fields than expected. This makes it so only the fields in the display are included in the export.
https://archivesspace.atlassian.net/browse/ANW-250
> ANW-250 only show fields that show up in view in csv

- Dockerfile
Disclaimer about use of repo Docker config.
> Program Team / Committer docker disclaimer

- common/db/migrations/123_create_lang_materials_schema.rb
Resolves migration error relating to inline scriptcodes in language of material notes.  Also improves migration logging.
https://archivesspace.atlassian.net/browse/ANW-697
Migrations containing scriptcode attributes of <language> tags in a langmaterial note were failing.  This resolves that.
Tested against multiple databases, including those with scriptcodes inside language of materials notes.
> ANW-697: Update migration for scriptcode error; improve logging

- public/app/controllers/concerns/searchable.rb
Testing with Human Readable URLs turned on revealed the need to be more explicit checking variable types when sanitizing parameters
> Need to be more explicit about the parameter variable types that get sanitized

- frontend/config/locales/en.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
es yml file was not loading
Changed the locales config to all four languages: en, es, fr, and ja and made sure the translations loaded
> Remove BOM from es.yml file and remove extra translations for creators

- docker-compose.yml
Just updates to the docker compose file for testing all the servers together (including external Solr).
> Docker updates

- scripts/pull_tech_docs.rb
The tech docs working group noticed we were getting an error when we would try to run build/run doc:build because the tech-docs repo would not allow us to connect with the git@github.com syntax. When we switched to using https://github.com/archivesspace/tech-docs.git it worked. So, submitting this to fix that issue
I don't think this has a ticket but I could be wrong.
This change allows people not on the tech-docs repo to build the docs without encountering that error.
I ran this and it worked, as did others in the group. We are both running locally on macs. It shouldn't affect any where else in the code since it is just a url change essentially.
- [ x] I have read the …
> Fixing Tech Docs Pull

- frontend/app/views/container_profiles/_linker.html.erb
- frontend/app/views/location_profiles/_linker.html.erb
- frontend/app/views/shared/_templates.html.erb
Update feature branch for ANW-550.
> Re-genericize and fix facets in linkers

- backend/app/model/top_container.rb
- backend/spec/model_managed_container_spec.rb
- frontend/app/assets/javascripts/top_containers.bulk.js
- frontend/app/views/top_containers/bulk_operations/_bulk_action_success.html.erb
- frontend/app/views/top_containers/bulk_operations/_bulk_action_templates.html.erb
- frontend/config/locales/en.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
- frontend/config/locales/ja.yml
When using the bulk update options for top containers, bulk updating to empty values (e.g. leaving the text or selection fields empty) does remove these values from the records in the database.  However, in the case of locations (either bulk updating single or multiple locations) while the database is updated, the top container record is not reindexed so results in the manage top containers screen do not reflect the reality of the database.  This resolves that issue and ensures that all changes made with bulk update location(s) trigger a reindex.
Updated `backend/app/model/top_container.rb` to ensure `update_mtime_for_ids` is run even when an empty `location_uri` is provided.
Also, to complement this work:
- updated .yml files updated to add clarifying text noting that providing empty …
> Bulk update empty

- _yard/API.erb
- backend/app/controllers/container.rb
- backend/app/controllers/enumeration.rb
Small update to the API docs, including:
- providing shell and python examples for `/config/enumerations/migration` endpoint (courtesy of Alicia Detelich)
- tweaking language/examples in authentication section, including adding examples of how to store a session key as an environmental variable
- added some line breaks to existing examples
- removed some weak/minimizing language
shell example:
python example:
session key example:
> Add/update API docs

- backend/spec/rde_template_fix_spec.rb
- common/db/migrations/127_rde_templates_fix.rb
- common/db/migrations/utils.rb
Updates references to 'colLang' to 'colLanguage' & 'colScript'.
https://archivesspace.atlassian.net/projects/ANW/issues/ANW-964?filter=myopenissues&orderby=priority%20DESC
> Fix for RDE templates created pre v2.7

- frontend/Gemfile
- frontend/Gemfile.lock
- frontend/app/helpers/search_helper.rb
- frontend/config/environments/test.rb
- frontend/spec/controllers/search_controller_spec.rb
- frontend/spec/factories.rb
- frontend/spec/spec_helper.rb
This pull request is waiting on https://github.com/archivesspace/archivesspace/pull/1702 to be merged into master so the new test architecture can be used to test performance.
When the search results are displayed or updated based upon filters, if the record has an ancestor, the ancestor title is retrieved to add to the view. The code was pulling the record twice which was making the display page load slowly. The change pulls the record only once and then uses the result based upon further logic making the page display faster.
> Improve performance by getting the json once instead of twice

- common/db/migrations/128_reindex_archival_objects_digital_object_components.rb
This is a continuation of #1716 to cause the required reindex of records without requiring a complete reindex.
https://archivesspace.atlassian.net/browse/ANW-216
> Reindex archival objects and digital object components so that component IDs show up in browse view

- common/config/config-defaults.rb
- frontend/app/views/assessment_attributes/edit.html.erb
- frontend/app/views/assessments/_form.html.erb
- frontend/config/help.yml
- frontend/config/initializers/help.rb
> Help pages

- clustering/files/archivesspace/config/config.rb
> Add default data_directory parameter for clustering configuration

- backend/app/model/db.rb
> Use boolean true and not string true

- backend/app/lib/job_runners/generate_slugs_runner.rb
- backend/app/lib/slugs/slug_helpers_generate.rb
- backend/spec/model_accession_spec.rb
- backend/spec/model_resource_spec.rb
- backend/spec/spec_slugs_helper.rb
- common/db/migrations/120_clean_slugs_for_repositories.rb
Slugs have invalid characters
#1725 
Automated tests and manually
> Clean up slugs to make sure they create a valid URL

- backend/spec/model_restriction_spec.rb
Restriction date was set to 2020-01-01
Ran test and it passed
> Change date to farther in the future

- backend/app/exporters/lib/export_helpers.rb
- backend/app/exporters/models/marc21.rb
- backend/app/exporters/serializers/ead.rb
- backend/app/exporters/serializers/ead3.rb
#1552 
Manually exported MARC, EAD, and EAD3
> Fix MARC, EAD, EAD3 exports when linked to software agent as subject

- backend/app/lib/oai/mappers/oai_mods.rb
Solution included in issue
#1687
> add xsi declaration

- frontend/app/views/locations/_sidebar_batch.html.erb
The URLs for the sidebar links did not include proxies so added it in.
> Make sure to account for proxy urls in locations sidebar

- common/config/config-defaults.rb
- frontend/app/views/site/_footer.html.erb
Update default feedback link in staff-side footer due to archivesspace.org website changes.
Updated link in _footer.erb and config-defaults.
Also updated _footer.erb to comply with standard of only using double quotes in .erb files when used for interpolation.
https://archivesspace.atlassian.net/browse/ANW-1004
Confirmed link updated.
> ANW-1004: Update default feedback link

- frontend/app/views/top_containers/bulk_operations/_bulk_action_templates.html.erb
> Add outline/styling to 8 bulk action template cancel buttons

- frontend/app/assets/javascripts/utils.js
- frontend/app/assets/stylesheets/archivesspace/form.less
- frontend/app/assets/stylesheets/archivesspace/help.less
- frontend/app/assets/stylesheets/archivesspace/sidebar.less
- frontend/app/assets/stylesheets/themes/default/default.less
- frontend/app/views/agents/_linker.html.erb
- frontend/app/views/agents/name_forms/_agent_family.html.erb
- frontend/app/views/agents/name_forms/_agent_software.html.erb
- frontend/app/views/assessments/_agent_linker.html.erb
- frontend/app/views/assessments/_form.html.erb
- frontend/app/views/assessments/_records_linker.html.erb
- frontend/app/views/classification_terms/_record_linker.html.erb
- frontend/app/views/classifications/_record_linker.html.erb
- frontend/app/views/events/_record_linker.html.erb
- frontend/app/views/location_profiles/_linker.html.erb
- frontend/app/views/repositories/_linker.html.erb
- frontend/app/views/shared/_header_global.html.erb
- frontend/app/views/shared/_header_repository.html.erb
- frontend/app/views/shared/_linker.html.erb
- frontend/app/views/shared/_login.html.erb
- frontend/vendor/assets/stylesheets/bootstrap/variables.less
- public/app/views/shared/_facets.html.erb
- public/app/views/shared/_request_form.html.erb
- public/app/views/shared/_skipnav.html.erb
Fixed more accessibility issues for the PUI and SUI
https://archivesspace.atlassian.net/browse/ANW-954
Tested using the WAVE tool
> ANW-954: Improve accessibility

- backend/spec/controller_archival_object_spec.rb
- backend/spec/controller_repository_spec.rb
- backend/spec/controller_resource_spec.rb
- backend/spec/export_dc_spec.rb
- backend/spec/export_eac_spec.rb
- backend/spec/export_marc_spec.rb
- backend/spec/export_mets_spec.rb
- backend/spec/export_mods_spec.rb
- backend/spec/export_spec_helper.rb
- backend/spec/factories.rb
- backend/spec/model_generate_arks_job_spec.rb
- backend/spec/model_generate_slugs_job_spec.rb
- backend/spec/model_oai_spec.rb
- backend/spec/model_repository_spec.rb
- backend/spec/model_subject_spec.rb
Renamed factory so the API docs will generate correctly.
#1770 
Looked at `endpoint_examples.json` and built docs locally and verified that the factory-produced value showed up in relevant routes.
> Fixes #1770 by changing factory name

- common/locales/en.yml
Attempt to reduce confusion about what the different preferences do. Changing just in English as a start.
> Slight wording changes related to preferences

- frontend/app/helpers/search_helper.rb
The modal for adding linked records was not showing up because of a problem in add_linker_column where arguments were in the wrong order.
Checked that linker modal now shows up correctly and can be used to link records.
> fix bug causing linker not to show up

- frontend/app/helpers/search_helper.rb
Reverts archivesspace/archivesspace#1785
> Revert "fix bug causing linker not to show up"

- frontend/app/views/top_containers/bulk_operations/_bulk_action_templates.html.erb
> Unintentional revert of changes during rebase

- common/locales/es.yml
- common/locales/fr.yml
- common/locales/ja.yml
- frontend/app/views/jobs/_form.html.erb
- frontend/app/views/jobs/_toolbar.html.erb
- frontend/app/views/jobs/index.html.erb
- frontend/app/views/jobs/new.html.erb
- frontend/app/views/jobs/show.html.erb
- frontend/app/views/shared/_header_global.html.erb
- frontend/app/views/shared/_header_repository.html.erb
- frontend/config/locales/en.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
- frontend/config/locales/ja.yml
- public/app/views/shared/_navigation.html.erb
- public/config/locales/en.yml
- public/config/locales/es.yml
- public/config/locales/fr.yml
- public/config/locales/ja.yml
Ran yml file checker on release candidate and found inconsistencies across different languages
> Make sure translations contained in all yml files, add some translations, and correct reference to non-existing translations

- supervisord/api.conf
- supervisord/archivesspace.conf
- supervisord/backend.conf
Developer only updates to the supervisord config files for running the dev servers.
> Supervisord conf updates for python 3.x

- backend/app/model/mixins/relationships.rb
> ANW-462: refactor relationships models

- build/run
- common/test_utils.rb
- frontend/app/assets/stylesheets/archivesspace/form.less
Frontend Selenium will run again.
> Fix for "Retrying include_theme_css".

- backend/app/model/mixins/agent_manager.rb
- backend/spec/model_agent_person_spec.rb
Howdy,
Today I noticed a small but long-standing bug that allows agents to get into a weird state as a result of combining duplicate names.  Gory details and a fix below!
The incoming list of agent names is processed to remove duplicates prior to being saved, so a set like this:
names: [{primary_name: "hello", authorized: true, is_display_name: true},
{primary_name: "duplicate", authorized: false, is_display_name: false},
{primary_name: "duplicate", authorized: false, is_display_name: false}]
Is collapsed to:
names: [{primary_name: "hello", authorized: true, is_display_name: true},
{primary_name: "duplicate", authorized: false, is_display_name: false}]
This can cause problems if you see input like this:
names: [{primary_name: "hello", authorized: true,  is_display_name: false}, …
> Always keep the display name when deduplicating non-authorized names

- backend/app/model/mixins/reindex_top_containers.rb
- backend/spec/controller_enumeration_spec.rb
- backend/spec/model_enumeration_spec.rb
- backend/spec/model_relationships_spec.rb
Some additional code cleanup and updates to backend tests to fix failures when running with MySQL. Still need to resolve managed container spec failures to be reviewed in context of: https://github.com/archivesspace/archivesspace/pull/1764
> MySQL backend tests updated cont.

- backend/app/model/mixins/relationships.rb
- backend/spec/controller_merge_request_spec.rb
- frontend/spec/selenium/spec/instances_and_containers_spec.rb
Updating/adding frontend and backend tests.
> Additional frontend and backend container merge tests

- backend/spec/controller_merge_request_spec.rb
Test update to replicate situation fixed with commit b933311546f4e2092f86045cba3a87ef43ba051b .
> Update test to account for multiple relationships

- common/aspace_i18n.rb
- common/config/preference_defaults.rb
- common/jsonmodel.rb
- common/locales/en.yml
- common/locales/es.yml
- common/locales/fr.yml
- common/locales/ja.yml
- common/schemas/defaults.rb
- frontend/app/controllers/application_controller.rb
- frontend/app/helpers/application_helper.rb
- frontend/app/views/defaults/_template.html.erb
- frontend/config/application.rb
Allow language selection for staff UI (frontend app) using preferences.
> Option for preferences to set locale

- .github/workflows/backend.yml
- .github/workflows/frontend.yml
- .github/workflows/indexer.yml
- .github/workflows/public.yml
Enable github actions to run tests with workflow per app.
> Add github actions to run tests with mysql

- public/app/views/containers/show.html.erb
- public/config/locales/en.yml
- public/config/locales/es.yml
- public/config/locales/fr.yml
- public/config/locales/ja.yml
https://archivesspace.atlassian.net/browse/ANW-867
> Change PUI container display page search results title ANW-867

- frontend/public/404.html
- frontend/public/422.html
- frontend/public/500.html
- public/public/404.html
- public/public/422.html
- public/public/500.html
Minor first-pass changes to improve color contrast (staff only) and add a document language to the static error pages for staff and public interfaces.  
Improve color contrast on staff-side error pages.  Add doc language for both staff and PUI error pages.
Accessibility errors corrected according to WAVE plugin. Existing tests passing.
Previous staff side 500 error page:
New staff side 500 error page:
> Minor changes to staff and public side error pages

- frontend/app/helpers/application_helper.rb
- frontend/app/views/assessment_attributes/edit.html.erb
- frontend/app/views/groups/_form.html.erb
- frontend/config/locales/en.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
- frontend/config/locales/ja.yml
- frontend/vendor/assets/stylesheets/bootstrap/forms.less
Addressing several accessibility errors unearthed by sitewide staff-side accessibility scans.
Fixes the following:
- Missing input labels in the audit trail sections of staffside view records for URIs and ARKs;
- Added aria-labels to magnifying glass icons/links on the assessment attributes record page;
- Added screen reader text to the plus buttons on the assessment attributes record page;
- Added form labels to the checkboxes on the manage groups page;
- Added a fieldset/legend to the inputs on the manage groups page; and,
- Updated translations files and stylesheets as needed to complement the above work.
Accessibility errors corrected according to WAVE plugin.
Labels added to view/show audit section:
Added labels/link text to assessment attributes:
Added form labels to manage groups:
> Add missing form labels, fix empty links, add aria-labels, add fieldset

- frontend/app/assets/javascripts/tree_renderers.js.erb
- public/app/assets/javascripts/tree_renderer.js.erb
This PR adds all dates to the archival objects tree subrecord view, including with 'bulk' prepended when appropriate, in both staff and public interfaces.
[ANW-172](https://archivesspace.atlassian.net/browse/ANW-172)
See above
> ANW-172 Show all sub record dates in tree

- backend/app/controllers/accession.rb
- backend/app/controllers/resource.rb
Resolves #1875 wherein the /repositories/:repo_id/resources/:id/top_containers API endpoint throws an error when there are attached digital object instances. 
#1875
> Issue #1875: Account for digital object instances

- README.md
Added a brief description and link to information about ArchivesSpace membership.
> Membership

- frontend/app/views/top_containers/show.html.erb
In the Top Container View display the Container Type above the Indicator, to match the Edit page
ARCSPC-666 in Harvard Jira
Tested Manually by displaying in Top Container Display
- [x ] New feature (non-breaking change which adds functionality)
> Put Type above Indicator, top container view

- frontend/config/locales/en.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
- frontend/config/locales/ja.yml
- scripts/tasks/check.rb
Just a bit of cleanup and making the output for the locales task easier to read.
> Update output for check locales and remove some duplicate keys [ci skip]

- _yard/API.erb
- backend/app/controllers/location_profile.rb
- backend/app/controllers/search.rb
- backend/app/controllers/update_feed.rb
- backend/app/lib/rest.rb
Resolves #393 by adding a new `paged` flag for paginated responses that don't get passed through `handle_listing`.
Removes `.paginated` from all paginated endpoints that don't pass through `handle_listing` and replaces them with a new `.paged` method.  This provides better error responses via the API (e.g. users will not be told to provide `all_ids` or an `id_set` parameter when those parameters do not actually work).  Also minimally updated `API.erb` for better API documentation as well.
https://github.com/archivesspace/archivesspace/issues/393 
Existing tests pass.  API docs build appropriately.  API error responses improved.
Error prior to change:
Error after change:
Updated API docs:
> Issue #393: Only use pagingation for calls going through handle_listing

- frontend/app/assets/javascripts/notes.crud.js
- frontend/spec/selenium/spec/agents_spec.rb
- frontend/spec/selenium/spec/notes_spec.rb
https://github.com/archivesspace/archivesspace/issues/1894
> Anw 635 list subnotes fix

- common/locales/en.yml
- common/locales/es.yml
- common/locales/fr.yml
- common/locales/ja.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
- frontend/config/locales/ja.yml
- public/config/locales/es.yml
- public/config/locales/fr.yml
- public/config/locales/ja.yml
Update translations for v2.8.0 per output of `bundle exec rake check:locales`
Adding Spanish, French, and Japanese translations (from Google Translate).
Discovered during release candidate process.
> Update translations for v2.8.0

- reports/assessments/assessment_rating_report/en.yml
- reports/assessments/assessment_rating_report/es.yml
- reports/assessments/assessment_rating_report/fr.yml
- reports/assessments/assessment_rating_report/ja.yml
At least one rating value must be selected to successfully complete this report. Some users are confused about this and the error messaging is not clear. This is an attempt to clear that up, and add missing translations for other languages while we're at it.
> Brief additional guidance for assessment rating report

- build/build.xml
Update to match documentation provided at: https://github.com/archivesspace/tech-docs/pull/89
> Download rack versioned jar

- public/app/assets/javascripts/cite.js
- public/app/models/archival_object.rb
- public/app/models/digital_object.rb
- public/app/models/resource.rb
- public/app/views/cite/_modal_tabbed.html.erb
- public/app/views/cite/show.html.erb
- public/app/views/shared/_modal_actions.html.erb
This is a slight refactor of #1830 which was merged, but only into a [feature branch](https://github.com/archivesspace/archivesspace/tree/ANW-921) not master.
Updates include:
- Rebase to sync the code base prior to this feature branch with the current state of master
- Refactor some of the code duplication out of 2/3 of the models that call the citation modal (`public/app/models/resource.rb` and `public/app/models/digital_object.rb`, not `public/app/models/archival_object.rb`)
[ANW-921](https://archivesspace.atlassian.net/browse/ANW-921)
See #1830
> ANW-921 Rebase code base and refactor and some related models

- common/config/config-defaults.rb
- public/config/initializers/public_new_defaults.rb
- public/config/locales/en.yml
- public/config/locales/es.yml
- public/config/locales/fr.yml
- public/config/locales/ja.yml
No bookbag/bookmark feature was ever fully implemented in the v2.x+ PUI, so this small pull requests removes unused code related to that unimplemented function.
> Removes code related to unimplemented bookbag feature

- Rakefile
- scripts/tasks/release_notes.rb
Updates relnotes generation to last used (this is just for the record, process is expected to change for the next release).
> Brief form for relnotes

- public/app/controllers/concerns/result_info.rb
Account for more permutations of how records pass through. Attempt
to use display string, then title, fallback on locale.
> PUI fix caption

- frontend/app/views/resources/_toolbar.html.erb
Bug fix to #1964 - sync initial URL to checkbox state
> Bug fix to #1964 - sync initial URL to checkbox state

- frontend/app/controllers/accessions_controller.rb
- frontend/app/controllers/agents_controller.rb
- frontend/app/controllers/assessments_controller.rb
- frontend/app/controllers/classifications_controller.rb
- frontend/app/controllers/container_profiles_controller.rb
- frontend/app/controllers/digital_objects_controller.rb
- frontend/app/controllers/events_controller.rb
- frontend/app/controllers/locations_controller.rb
- frontend/app/controllers/resources_controller.rb
- frontend/app/controllers/search_controller.rb
- frontend/app/controllers/subjects_controller.rb
- frontend/app/helpers/export_helper.rb
- frontend/app/models/search.rb
- frontend/app/views/assessments/index.html.erb
Includes one commit from the larger #1896 written by @payten and funded by Queensland State Archives.
- b62d09f: CSV bugfixes for search filters.  If the user has narrowed their search results using filters, the
"Download CSV" export should also apply those filters.
Also extends the above by:
- adding a filename prefix for all exports;
- using translations for all filename prefixes; and, 
- extending the export csv option to assessments (the method has long been present in the controller, but a button was never provided in the view).
When using the "Download CSV" button from browse/search pages on the staff UI any applied filters should be respected by the csv export.
Existing tests pass, manually confirmed behavior.
> Filter csv export

- frontend/app/assets/javascripts/subrecord.crud.js
- frontend/app/assets/javascripts/subrecord.too_many.js
- frontend/app/views/shared/_templates.html.erb
Includes two commits from the larger #1896 written by @payten and funded by Queensland State Archives.
- 487e2ba65131a6ebe7e0998ce35a4f15a88f21ed: Focus the first VISIBLE form element after adding a new nested subrecord form
- ffc1fbbb2f7ec931ae6f5a06569db67a4e0cf598: Show count of hidden subrecords via too_many_subrecords_template
Includes modifications to the staff-side subrecord javascript and forms, including:
- Focus the first VISIBLE form element after adding a new nested subrecord form since some subrecord forms have hidden form elements; and, 
- Adding the count of hidden subrecords via the too_many_subrecords_template.
Existing tests pass, manually confirmed behavior.
ffc1fbbb2f7ec931ae6f5a06569db67a4e0cf598 adds the count of hidden subrecords in parens at the end of the …
> Subrecord enhancements

- launcher/backup/lib/backup.rb
Probably mainly of interest to @mark-cooper  :)
Some combination of rubyzip & JRuby's JZlibDeflate cause two problems
when backing up Solr indexes whose segments files are
large (multi-GB):
* The script consumes a lot of heap space--seemingly in proportion
to the size of the files being backed up
* The process of creating the zip file fails with:
java.lang.ArrayIndexOutOfBoundsException: null
This seems to happen when files being backed up approach 4GB, so
seems likely to be an 32-bit integer overflow in JRuby's deflate
code.
This PR switches the backup script to use the builtin Java zip
libraries, being careful to limit the amount of memory used.  I've
verified that it handles 4GB files correctly.
> Modify backup.rb to handle large files

- scripts/tasks/release_notes.rb
Includes changes to the `release_notes` task, including the following:
- credits authors of all commits, not just the last author in a merge commit; and, 
- add some additional handling to catch anw numbers entered like `anw 1021` instead of strictly `ANW-1021` when adding links to JIRA.
The first change may necessitate some additional cleanup on the backend as all commits will now be credited in the "Community Contributions" sections (including separate commits like "oops" or rebases), but it comes with the benefit that all individuals working in a feature branch will be credited for their work and enables crediting authors when their work is cherry-picked and pull requested by others.
> Update release notes to credit all commit authors, not just the last

- public/config/locales/es.yml
The Spanish translation file for the public interface was almost 95+% English. To improve on this I brought over all the already translated enums from common file and used various tools in Weblate to get suggestions for most of the rest. I matched translations from other files in ArchivesSpace when I could.
I validated the yml file.
> Spanish translations for the public interface

- frontend/app/assets/javascripts/enumerations.index.js
- frontend/app/views/enumerations/_list.html.erb
- frontend/app/views/enumerations/_merge.html.erb
The Suppress button in the Manage Controlled Value Lists area was a different color than everywhere else in the application. This bugged me.
https://archivesspace.atlassian.net/browse/ANW-1016
- [ x] My change requires a change to the documentation. - screenshot for a configurable value list/merging values in a configurable value list will need to change in the user manual/training workbook
> ANW-1016 - Suppress button color consistency

- public/config/locales/fr.yml
A few small changes for items still in English. Did not touch enums that are also in English in the enums file.
> Small update to French translations for PUI

- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
A few recently added items had English translations in the French and Spanish files.
> Adds a few Spanish and French translations

- common/config/config-distribution.rb
- common/spec/appconfig_spec.rb
Cleanup and extend support for additional types. Add tests.
> Update AppConfig from env options

- frontend/app/controllers/archival_objects_controller.rb
- frontend/app/controllers/classification_terms_controller.rb
- frontend/app/controllers/jobs_controller.rb
Remove methods that do not exist from `set_access_control` in various controllers.
Cleanup work identified by Laney McGlohon during larger permissions review.
https://archivesspace.atlassian.net/browse/ANW-992
Existing tests pass.
> ANW-992: Remove missing methods from set_access_control

- frontend/spec/selenium/spec/bulk_import_spec.rb
Sometimes more than the default 200 retries are needed before the background job completes its run, the page releoads, and the "refresh" button becomes clickable.  After experimenting with a few wait options (none of which particularly liked our `find_element` method), this seems like the simplest path forward that's most in compliance with other existing tests.  At the least, it will stop random failures from popping up just due to timing issues.
Confirmed that even if the initial round of 200 retries fails, a new cycle of retries begins and, once the page is fully refreshed, tests will pass.
> Bulk import tests need to be a bit more patient

- public/app/controllers/concerns/handle_faceting.rb
The filter facet for container type on a resource's inventory page was not using translation values.  Now it does.
https://archivesspace.atlassian.net/browse/ANW-1129
Visually confirmed.
> ANW-1129: Use translations for PUI container type filter

- backend/app/lib/nested_record_resolver.rb
- backend/app/model/backend_enum_source.rb
- backend/app/model/mixins/dynamic_enums.rb
- backend/app/model/mixins/relationships.rb
- backend/app/model/mixins/tree_nodes.rb
- backend/spec/controller_enumeration_spec.rb
- common/aspace_i18n_enumeration_support.rb
- common/json_schema_utils.rb
- common/spec/lib/factory_bot_helpers.rb
- frontend/app/assets/javascripts/subrecord.collapsible.js
- frontend/app/helpers/aspace_form_helper.rb
- frontend/app/views/agents/_form.html.erb
- frontend/app/views/agents/_form_required.html.erb
- frontend/app/views/groups/edit.html.erb
- frontend/app/views/notes/_template.html.erb
- frontend/app/views/shared/_form_messages.html.erb
- frontend/app/views/shared/_subrecord_form.html.erb
- frontend/config/initializers/i18n.rb
- frontend/spec/selenium/spec/subjects_spec.rb
Includes seven commits from the larger #1896 funded by Queensland State Archives and written by:
- @marktriggs
- 6cf976ca7c31ea1545e1325652677e9160d37492: Improve performance of frontend forms
- 033275a1c60511e20c5631e50ee29e04af3badf8: I18n caching
- 542db73453deb3fa0ef1c96cace5fab71c7a8a3c: Improve enumeration value caching
- c7dbf5d4c8c373a772f40a7dc651f43670935a2b: Early skip over empty nested records
- c3cc859fe65f235f5ba8fe32ba9b21a728905c8e: Reduce number of queries used for fetching relationships
- 1768915ed5e5432023bacc8723963309c6875b31: Faster version of drop_empty_elements
- ccc74666543eaa8b7eb9f1bbf87e42ca9a1eb4ed: Calculate AO positions by using a method that is faster for batches
A collection of performance enhancements primarily targeting the staff user interface.
Before / …
> Hm qsa 092820 mc

- frontend/app/views/jobs/index.html.erb
Continuation of #2015 to also hide the `Load via Spreadsheet` option from the Jobs toolbar.
> Continuation of #2015 to hide Load Spreadsheet

- backend/spec/lib_bulk_import_bulk_import_mixins_spec.rb
- backend/spec/lib_bulk_import_bulk_mixins_spec.rb
- backend/spec/lib_bulk_import_lang_handler_spec.rb
- backend/spec/lib_bulk_import_notes_handler_spec.rb
- common/locales/en.yml
There were a number of inconsistencies in case for the locales for the bulk importer plus one misspelling of dear old "ArchivesSpace." This fixes those up. More work is likely needed to improve some of the error messages but will be considered separately.
> Minor fix-ups to bulk import locales

- backend/app/lib/bulk_import/agent_handler.rb
- backend/app/lib/bulk_import/bulk_import_parser.rb
- backend/app/lib/bulk_import/digital_object_handler.rb
- backend/app/lib/bulk_import/import_digital_objects.rb
- backend/spec/lib_bulk_import_agent_handler_spec.rb
Updated error message for files with no data
Made thumbnail and url optional for digital objects
Relator no longer required for a linked agent
> Bulk import tweaks

- frontend/app/controllers/preferences_controller.rb
- frontend/app/views/preferences/_toolbar.html.erb
- frontend/config/locales/en.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
- frontend/config/locales/ja.yml
- frontend/config/routes.rb
- frontend/spec/selenium/spec/user_preferences_spec.rb
Provides a UI-based way to reset preferences to application defaults.
https://archivesspace.atlassian.net/browse/ANW-1017
Reset button:
Reset confirmation modal:
Success message:
> ANW-1017: Reset preference defaults

- backend/app/exporters/serializers/ead.rb
Minor addition to #2013 to use translation value for "script" instead of hardcoding script.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-969
> ANW-969: Minor tweak to #2013 use translation in EAD2002 export

- public/Gemfile
> Allow public plugins to use gems

- frontend/config/locales/en.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
- frontend/config/locales/ja.yml
Very minor change to translations to respond to feedback left on #2039 .  (The other translation changes requested there are pre-existing behavior/not related to #2039 work, so should be discussed separately.)
> Minor tweak to #2039 translation

- common/locales/en.yml
- common/locales/es.yml
- common/locales/fr.yml
- common/locales/ja.yml
Updating `common` translations for the v2.8.1 release.
> Updating non-English translations for v2.8.1

- frontend/app/views/repositories/transfer.html.erb
> Fix up repository transfer form

- public/config/locales/en.yml
- public/config/locales/es.yml
- public/config/locales/fr.yml
- public/config/locales/ja.yml
A few more translation updates for v2.8.1.
Typo in Spanish translations and remove (again) translations related to #1960
> Additional PUI translations for 2.8.1

- README.md
Just happened to notice our build status badge says failing.  That doesn't look so great.  It's still pointing at Travis, but the time has probably come to point it to the GH Actions status. 
This should also update the status badge on the YARD docs next time they are built (v3.0.0 release).
> Update build status from Travis to GH Actions

- common/jsonmodel_type.rb
- common/schemas/abstract_agent.rb
- common/schemas/agent_person.rb
- common/spec/jsonmodel_spec.rb
- frontend/app/controllers/agents_controller.rb
- frontend/app/helpers/application_helper.rb
- frontend/app/views/agents/_form.html.erb
- frontend/app/views/agents/_sidebar.html.erb
@avatar382 this got a bit long so thought would be better as a PR than a diff. I believe it's equivalent to your code, so should be merge-able if you want to do that. Otherwise you can use it as a set of suggestions.
Main thing is a bit of cleanup for determining full mode, and starting a process for finding properties from schemas (using tags) so we don't always have to include long lists of fields inline.
> Bit of consolidation

- backend/app/controllers/agent_corporate_entity.rb
- backend/app/controllers/agent_family.rb
- backend/app/controllers/agent_person.rb
- backend/app/controllers/agent_software.rb
- backend/spec/controller_agent_corporate_entity_spec.rb
- backend/spec/controller_agent_family_spec.rb
- backend/spec/controller_agent_person_spec.rb
- backend/spec/controller_agent_software_spec.rb
- frontend/app/controllers/agents_controller.rb
- frontend/app/views/agents/_toolbar.html.erb
- frontend/config/locales/en.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
- frontend/config/locales/ja.yml
- frontend/config/routes.rb
Provides a "Publish All" option to agent records.
> Add 'Publish All' to agents

- common/locales/enums/en.yml
- frontend/app/assets/javascripts/agents.crud.js
- frontend/app/views/agent_places/_template.html.erb
Expand subject linkers upon adding an agent_function, agent_occupation, agent_place, or agent_topic subrecord.
Also flip/flops the placement of the linker and role dropdown selector in the agent_place form.
> Expand subject linker by default

- backend/app/model/agent_function.rb
- backend/app/model/agent_occupation.rb
- backend/app/model/agent_place.rb
- backend/app/model/agent_resource.rb
- backend/app/model/agent_topic.rb
- backend/app/model/implied_publication_calculator.rb
- backend/app/model/mixins/agent_manager.rb
- backend/spec/export_dc_spec.rb
- backend/spec/export_eac_spec.rb
- backend/spec/export_ead3_spec.rb
- backend/spec/export_ead_spec.rb
- backend/spec/export_marc_auth_agent_spec.rb
- backend/spec/export_marc_spec.rb
- backend/spec/export_mets_spec.rb
- backend/spec/export_mods_spec.rb
- backend/spec/export_spec_helper.rb
- backend/spec/mixin_touch_records_spec.rb
- backend/spec/model_oai_spec.rb
Ensure that linked subject records are updated when the agent record they are linked to is modified.  This is necessary, first and foremost, to ensure that proper implied publication status is maintained on linked subject records.
This PR also includes a number of unrelated changes to `backend/spec`, particularly in the various export tests.  While adding needed tests to `mixin_touch_records_spec.rb` it was discovered that a thread was being opened in `export_spec_helper.rb` that was interfering with tests outside of the scope of exports.  To get the new touch records tests to reliably pass, some refactoring had to be done to the export tests/spec helper.
> Update linked subjects when agent is saved

- backend/app/converters/lib/eac_base_map.rb
- backend/app/exporters/serializers/eac.rb
- backend/spec/lib_eac_converter_spec.rb
- common/db/migrations/139_add_new_agents_enums.rb
- common/db/migrations/140_create_new_agents_tables.rb
- common/db/migrations/141_update_existing_tables_for_agents.rb
- common/locales/en.yml
- common/locales/enums/en.yml
- common/schemas/abstract_name.rb
- common/schemas/abstract_parallel_name.rb
- frontend/app/views/agents/name_forms/_agent_corporate_entity.html.erb
- frontend/app/views/agents/name_forms/_agent_corporate_entity_merge.html.erb
- frontend/app/views/agents/name_forms/_agent_corporate_entity_merge_target.html.erb
- frontend/app/views/agents/name_forms/_agent_corporate_entity_required.html.erb
- frontend/app/views/agents/name_forms/_agent_family.html.erb
- frontend/app/views/agents/name_forms/_agent_family_merge.html.erb
- frontend/app/views/agents/name_forms/_agent_family_merge_target.html.erb
- frontend/app/views/agents/name_forms/_agent_family_required.html.erb
- frontend/app/views/agents/name_forms/_agent_person.html.erb
- frontend/app/views/agents/name_forms/_agent_person_merge.html.erb
- frontend/app/views/agents/name_forms/_agent_person_merge_target.html.erb
- frontend/app/views/agents/name_forms/_agent_person_required.html.erb
- frontend/app/views/agents/name_forms/_agent_software.html.erb
- frontend/app/views/agents/name_forms/_agent_software_merge.html.erb
- frontend/app/views/agents/name_forms/_agent_software_merge_target.html.erb
- frontend/app/views/agents/name_forms/_agent_software_required.html.erb
…ecords
The field for transliteration was confused for romanization, this adds the correct enumeration and updates all database and schema references to match, as well as making the necessary updates to exports.
This is needed to match the spec.
Some in browser testing, backend tests and frontend tests
> Fix conflation of romanization and transliteration in agent names

- backend/app/controllers/exports.rb
- backend/app/exporters/models/marc_auth.rb
- backend/app/exporters/serializers/marc_auth.rb
- backend/spec/export_marc_auth_agent_spec.rb
- backend/spec/export_spec_helper.rb
- frontend/app/controllers/exports_controller.rb
> ANW-429 Exports update 1

- reports/accessions/accession_inventory_report/accession_inventory_report.rb
> Don't limit report to just repo 2

- launcher/launcher.rb
tiny correctness fix to not initialize the same variable twice
observed launcher still working
> call o.e.jetty.server.Server.new only once

- plugins/generate_accession_identifiers/frontend/routes.rb
> generate_accession_identifiers does not handle prefxes

- Gemfile
- Gemfile.lock
- Rakefile
- scripts/tasks/release_notes.rb
> Use github api for release notes [ci skip]

- backend/app/model/assessment.rb
- common/db/migrations/139_add_external_documents_to_assessments.rb
- common/schemas/assessment.rb
- frontend/Gemfile
- frontend/Gemfile.lock
- frontend/app/views/assessments/_form.html.erb
- frontend/app/views/assessments/_sidebar.html.erb
- frontend/config/environments/development.rb
- frontend/spec/selenium/spec/assessments_spec.rb
This adds External Documents to the Assessment Model. 
[ANW-1015](https://archivesspace.atlassian.net/browse/ANW-1015)
Spec has been added
New feature (non-breaking change which adds functionality)
> Adds External Documents to Assessment

- frontend/Gemfile
- frontend/Gemfile.lock
- frontend/app/assets/javascripts/top_containers.bulk.js
- frontend/app/controllers/top_containers_controller.rb
- frontend/app/views/top_containers/bulk_operations/_toolbar.html.erb
- frontend/config/environments/development.rb
Adds the ability to export Top Containers to a CSV file
[ANW-695](https://archivesspace.atlassian.net/browse/ANW-695)
New feature (non-breaking change which adds functionality)
> Top Container CSV Export

- backend/app/converters/lib/eac_base_map.rb
- backend/app/exporters/examples/eac/xmleac.xml
- backend/spec/lib_eac_converter_spec.rb
- common/db/migrations/140_create_new_agents_tables.rb
Addresses first-round testing issues related to EAC imports, including:
- <languageDeclaration><language> @scriptCode not imported when there is a script tag with a scriptcode attribute present;
- "No descriptive note specified" note being generated when <source><descriptiveNote> not present;
- <nameEntry> that includes `, yyyy-yyyy` syntax no longer being copied into name form dates field;
- name order default for persons now indirect;
- "Default label" generic label not being generated for notes without labels;
- <biogHist> line spacing and <p></p>s being cleaned during import;
- <biogHist><citation> elements now import to Citation subrecord;
- <biogHist> chronlists now create a chronlist (lists and outlines still dumped into note_text);
- <languageUsed> elements not inside a …
> ANW-429 EAC import enhancements

- backend/app/exporters/models/eac.rb
- backend/app/exporters/serializers/eac.rb
- backend/spec/controller_exports_spec.rb
- backend/spec/custom_matchers.rb
- backend/spec/export_eac_spec.rb
> EAC export updates

- backend/app/lib/oai/aspace_oai_repository.rb
This fixes an issue with subjects in RI not being resolved for OAI.
All of the PUI resolves RI indexer config is included so the RI
behavior should now be equivalent between OAI and PUI indexer.
https://archivesspace.atlassian.net/browse/ANW-1121
Reviewed OAI responses. Existing tests pass.
> Update OAI Provider resolve list

- backend/app/model/mixins/sort_name_processor.rb
- backend/spec/model_agent_corporate_entity_spec.rb
- backend/spec/model_agent_family_spec.rb
- backend/spec/model_structured_date_spec.rb
- frontend/app/helpers/aspace_form_helper.rb
- frontend/app/views/agent_functions/_show.html.erb
- frontend/app/views/agent_occupations/_show.html.erb
- frontend/app/views/agent_places/_show.html.erb
- frontend/app/views/agent_topics/_show.html.erb
Adds tweaks/fixes to staff interface as discovered by testers.
Unit tests updated.
> Staff interface tweaks + fixes

- Dockerfile
- docker-compose.yml
- solr/Dockerfile
- solr/schema-8.8.xml
- solr/solrconfig-8.8.xml
- Update Ubuntu base image
- Use the MySQL 8 connector (works with 5.7)
- Add netbase resolves (https://github.com/jruby/jruby/issues/3955)
- Remove New Relic init for local test env (maintained in external repo)
- Use MySQL 8
- Update Solr build files and use 8.8
> Updates for the Docker environment:

- backend/app/model/reports/register_custom_fields.rb
- reports/custom/language_subreport.rb
objects, digital objects and digital object components and add language as a sub record
> [ANW-1184] Remove language as a custom field for resources, archival 

- backend/app/converters/lib/marcxml_auth_agent_base_map.rb
Resubmission of #2139 
Small updates to related agents MARC import maps to account for 511 tag (conference proceedings).
Extended 111/411 name maps to 511 as well.  Ensure related agents are created from 511.
Discovered during import map updates.
> ANW-429 account for conference proceedings

- frontend/app/assets/javascripts/custom_report_templates.crud.js
- frontend/app/views/custom_report_templates/_form.html.erb
Update to remove check/uncheck from "narrow by?" checkboxes
> ANW-1076 check/uncheck for display checkboxes only

- frontend/app/assets/javascripts/custom_report_templates.crud.js
- frontend/app/controllers/application_controller.rb
- frontend/app/controllers/custom_report_templates_controller.rb
- frontend/app/views/custom_report_templates/_form.html.erb
- frontend/config/locales/en.yml
- frontend/config/locales/fr.yml
- frontend/config/locales/ja.yml
ANW-1076 - only select and un-select display checkboxes because narrow by checkboxes need additional input
ANW-1073 - use existing handle_crud method to make copy and add copy method translations
> ANW 1073 and ANW 1076 Improvements

- frontend/app/assets/javascripts/custom_report_templates.crud.js
- frontend/app/assets/stylesheets/archivesspace/buttons.less
- frontend/app/views/custom_report_templates/_listing.html.erb
- frontend/app/views/custom_report_templates/_toolbar.html.erb
Made check all button green and color toggles when pressed
Made copy button plain button
> Additional button enhancements

- backend/app/controllers/exports.rb
Mark software eac export endpoints for future deletion.
https://archivesspace.atlassian.net/browse/ANW-1233
> ANW-1233: Deprecate EAC export endpoints for software agents

- common/locales/en.yml
- frontend/config/locales/en.yml
Updating some translation values
N/A
> Updating Translation values (EN)

- common/selenium/backend_client_mixin.rb
- frontend/spec/selenium/spec/agents_spec.rb
- frontend/spec/selenium/spec_helper.rb
Remove some code pertaining to a standalone indexer during selenium runs,  which was stranded a while back and likely never used. Also revert some selenium hooks that rewrite the user's config file. Finally, tweak an agent test to more aggressively index.
> Minor selenium cleanup

- backend/app/exporters/serializers/eac.rb
https://archivesspace.atlassian.net/browse/ANW-1230
> ANW-1230 Fix eac citation subnote export

- Dockerfile
> Add shared-mime-info (required since mimemagic 0.3.8)

- frontend/app/assets/stylesheets/archivesspace/buttons.less
- frontend/app/views/custom_report_templates/_listing.html.erb
- frontend/app/views/custom_report_templates/_toolbar.html.erb
Fixed button colors and placement
> Update colors and placement of buttons

- common/db/migrations/143_migrate_agent_date_data_to_structured_dates.rb
This prevents crashing with standard config / resources using larger databases (1m+ dates).
> Prevent OOM error by batching date records (migration 143)

- reports/static/translation_defaults/en.yml
- reports/static/translation_defaults/es.yml
- reports/static/translation_defaults/fr.yml
Forgot Language translation for new subreport
> ANW-1184 add missing translation

- backend/app/converters/lib/marcxml_auth_agent_base_map.rb
- backend/spec/lib_marcxml_auth_agent_converter_spec.rb
Test should pass now. It probably needs a review though by someone more familiar with the spec.
> fix xpaths when searching around the parent document

- backend/app/exporters/examples/marc/marcxml_collection_with_multiple_records.xml
- backend/spec/lib_marcxml_auth_agent_converter_spec.rb
Updates to xpath and tests to confirm that collections of marc auth records don't scramble data improperly across agent records
https://archivesspace.atlassian.net/browse/ANW-1238
> ANW-1238 marc auth collection

- public/app/models/archival_object.rb
I'm not sure how this slipped by...but in any case here it is again.
> fix errant merge conflict

- common/locales/en.yml
Update translation values for agent relationship types
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1234
Manual testing to ensure relationship type translations appearing correctly
> ANW-1234: Update translation values for agent relationship types

- common/locales/en.yml
- frontend/app/views/agents/_linker.html.erb
- frontend/app/views/related_agents/_template.html.erb
Adding tooltips to related agents subform
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1231
Manual testing to ensure tooltips appear correctly
> ANW-1231: Add tooltip for related agents fields

- common/locales/enums/es.yml
- common/locales/enums/fr.yml
- common/locales/enums/ja.yml
- common/locales/es.yml
- common/locales/fr.yml
- common/locales/ja.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
- frontend/config/locales/help/es.yml
- frontend/config/locales/help/fr.yml
- frontend/config/locales/help/ja.yml
- frontend/config/locales/ja.yml
- public/config/locales/es.yml
- public/config/locales/fr.yml
- public/config/locales/ja.yml
he agents work added many English translations that need to be translated to other languages.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1261
Manual testing by changing the locale and looking for missing translation errors.
> ANW-1261: Update translation files for foreign languages

- frontend/app/views/agents/_form.html.erb
- frontend/app/views/agents/_merge_selector.html.erb
- frontend/app/views/agents/required.html.erb
- frontend/app/views/related_agents/_form.html.erb
- frontend/config/help.yml
Updating help links for new ASpace 3.0 work.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1199
Manual testing verifying links
> ANW-1199: Updating help links

- backend/app/converters/lib/marcxml_auth_agent_base_map.rb
Source and rules are no longer required, so the importer should not set defaults to 'local' on import.
https://archivesspace.atlassian.net/browse/ANW-1267
> ANW-1267 Remove default source and rules from MARCXML Auth Importer

- frontend/app/assets/javascripts/top_containers.bulk.js
- frontend/app/controllers/top_containers_controller.rb
- frontend/app/views/top_containers/bulk_operations/_toolbar.html.erb
- frontend/spec/selenium/spec/instances_and_containers_spec.rb
> ANW-695: Apply stored search params to download CSV for top containers

- frontend/app/views/agents/_form.html.erb
- frontend/config/help.yml
- frontend/config/locales/help/en.yml
Updating tooltip labels for help links
https://archivesspace.atlassian.net/browse/ANW-1269
> ANW-1269: Updating tooltip labels for help links

- frontend/app/assets/javascripts/notes.crud.js
- frontend/app/assets/stylesheets/archivesspace/form.less
- frontend/app/views/notes/_template.html.erb
- frontend/config/locales/en.yml
The subform for note outlines works, but it's confusing and easy to break. This adds some CSS and JS tweaks to improve user experience.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1037
> ANW-1037: UI tweaks for note_outline subform

- public/app/views/pdf/_digital_object_links.html.erb
> ANW-1212 Exclude unpublished file versions from PUI PDF output

- public/app/controllers/repositories_controller.rb
- public/app/views/repositories/_badge.html.erb
- public/spec/factories.rb
- public/spec/features/repositories_spec.rb
- public/spec/spec_helper.rb
> ANW-211 PUI record badge should only show archival objects

- common/db/migrations/146_tc_link_cleanup.rb
Very minor change to the logging output of migration 146 to avoid displaying advice on cleaning up "Lost and Found" top containers to users whose databases didn't have any corrupt container links in the first place.
> ANW-1253 cont'd - migration 146 logging cleanup

- public/app/models/digital_object.rb
- public/spec/features/digital_objects_spec.rb
- public/spec/spec_helper.rb
> ANW-1207: Digital Object suppress link to unpublished accessions

- common/locales/en.yml
- reports/static/translation_defaults/en.yml
- reports/static/translation_defaults/es.yml
- reports/static/translation_defaults/fr.yml
> ANW-1184 Fixes for the moving of languages to a subreport

- public/app/assets/stylesheets/archivesspace/mixed-content.scss
CSS fix for correctly styling bold tag in mixed note content in the PUI
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-963
> ANW-963: CSS fix for correctly styling bold tag in mixed note content in the PUI

- public/app/assets/stylesheets/archivesspace/aspace.scss
CSS fixes for small mobile devices (up to 480px width)
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1029
Manual in-browser testing (mobile device emulation)
> ANW-1029: CSS fixes for small mobile devices (up to 480 px width)

- frontend/app/helpers/search_helper.rb
Adding edit button to index listing for event records in frontend
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-856
Manual testing in browser
> ANW-856: Adding edit button to index listing for event records in frontend

- backend/app/controllers/subject.rb
This is just #2084 minus the changes to the `docs` directory.  
See #2084
> Update to #2084 subjects API documentation

- backend/app/converters/lib/marcxml_bib_base_map.rb
- backend/app/exporters/examples/marc/at-tracer-marc-1.xml
- backend/spec/lib_marcxml_bib_converter_spec.rb
Change to MARCXML bib map to map 520 with an ind1='2' to a scope and contents note, instead of a general (odd) note.  Also includes more robust testing of the various bits of 520 import logic already in the code.
https://archivesspace.atlassian.net/browse/ANW-1074
> ANW-1074 MARCXML import 520 ind1="2" to scopecontent

- common/db/migrations/147_migrate_notes_and_reindex_agents.rb
1. trigger reindex for all agent records
2. migrate note_agent_rights_statemtent to note_general_context
https://archivesspace.atlassian.net/browse/ANW-1281
manual testing
> touch agent records for reindex and migrate note_rights content

- backend/app/model/reports/register_custom_fields.rb
Make sure finding aid language and script are included in custom reports and attached to correct enum
[ANW-1271](https://archivesspace.atlassian.net/browse/ANW-1271)
> [ANW-1271] Make finding aid language and script enums with the correct enum name for lookup when generating reports

- frontend/app/views/repositories/_form_container.html.erb
- frontend/app/views/repositories/_toolbar.html.erb
Stumbled on these while working on #2253 and it annoyed me enough I decided to fix it.  A few small changes explained in details in the JIRA.
https://archivesspace.atlassian.net/browse/ANW-1289
Toolbar before:
Toolbar after:
Contact details before:
Contact details after:
> ANW-1289 Updates to manage repositories form

- common/locales/en.yml
- frontend/app/views/custom_report_templates/show.html.erb
The completion of the view mode for custom reports
> [ANW-1275] Views completed

- backend/app/lib/crud_helpers.rb
- backend/app/lib/rest.rb
- backend/spec/controller_rest_spec.rb
> Enable sorting of paginated results

- backend/app/exporters/models/ead.rb
- backend/app/exporters/serializers/ead3.rb
- backend/spec/export_ead3_spec.rb
- backend/spec/export_ead_spec.rb
- backend/spec/factories.rb
- backend/spec/spec_helper.rb
Resolves #1584 
#1584
EAD2002 with fax, business number with extension, and number with no number type:
EAD3 with fax, business number with extension, and number with no number type:
> Issue #1584 Update EAD export for telephones subrecord

- frontend/spec/selenium/spec/default_values_spec.rb
- frontend/spec/selenium/spec/trees_spec.rb
As discussed in May21 sprint review, pend these tests until we can resolve the frequent failure.
All too many times
> pend two tests that fail frequently

- common/locales/en.yml
- common/locales/es.yml
- common/locales/fr.yml
- common/locales/ja.yml
- frontend/app/controllers/users_controller.rb
- frontend/app/helpers/users_helper.rb
- frontend/app/views/users/index.html.erb
> ANW-891: Add more fields and sort to the users table

- Dockerfile
> Add git for broader plugin support

- common/locales/en.yml
- common/locales/es.yml
- common/locales/fr.yml
- common/locales/ja.yml
The error message given when data does not match the regex defined in the schema is jargon. Renamed so that it's more user friendly.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1082
> ANW-1013: Update error message for regex mismatch to be more user friendly

- frontend/app/assets/javascripts/tree_toolbar.js.erb
Adding context sensitive help link in an easily visible place next to button
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1164
> ANW-1164: Context-sensitive help link for load via spreadsheet

- frontend/app/views/preferences/edit.html.erb
- frontend/config/help.yml
Updating context sensitive help links for preference pages.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1149
> ANW-1149: updating help links for preferences pages

- frontend/app/assets/stylesheets/archivesspace/submenu.less
On small phone screens, some menus go off the left and are not visible. This improves the situation by right aligning the menu. 
In some cases, the menus can go off to the right instead, but this still seems like an improvement and it would take a major rework to eliminate all of these menu issues with such small screens.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-158
In browser testing with mobile device emulation
> ANW-158: Bugfix for menus going off screen to the left on very small screens

- public/app/assets/stylesheets/archivesspace/aspace.scss
Previous fix for phone sized screens was not completely effective on larger phones
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1029
In browser testing with mobile device emulation
> ANW-1029: Extending PUI interface fixes to tablet sized screens

- frontend/vendor/assets/stylesheets/bootstrap/variables.less
- public/app/assets/stylesheets/archivesspace/colors.scss
Minor changes to address color contrast issues in non-text elements, including:
- Darkening the bounding box around focused elements (this applies to both the PUI and the SUI):
- Making the contrast between the active tabs/pills in the PUI meet a 3:1 ratio: 
https://archivesspace.atlassian.net/browse/ANW-1332
> ANW-1332 Adjust color contrast for non-text elements

- frontend/vendor/assets/stylesheets/bootstrap/variables.less
Darkens the active breadcrumb text in the staff ui breadcrumb bar to provide better color contrast (approximately 6:1 contrast ratio):
https://archivesspace.atlassian.net/browse/ANW-1330
> ANW-1330 Darken active breadcrumb text in SUI

- public/Gemfile
- public/Gemfile.lock
- public/app/assets/javascripts/request.js
- public/app/views/repositories/_badge.html.erb
- public/app/views/resources/infinite.html.erb
- public/spec/features/accessibility_spec.rb
- public/spec/spec_helper.rb
Addresses instances of duplicated id's on individual resource pages in the PUI.  Also adds `axe-core-rspec` and an initial test to confirm no duplicate ids are present.
https://archivesspace.atlassian.net/browse/ANW-1315
> ANW-1315 Don't duplicate ids in PUI

- frontend/app/assets/javascripts/largetree.js.erb
- frontend/app/assets/javascripts/tree_renderers.js.erb
- public/app/assets/javascripts/tree_renderer.js.erb
- public/app/views/shared/_search.html.erb
- public/config/locales/en.yml
- public/config/locales/es.yml
- public/config/locales/fr.yml
- public/config/locales/ja.yml
Improves descriptive labels provided in the PUI search filter dropdown and PUI record page sidebar/tree (which is copied from the frontend).
https://archivesspace.atlassian.net/browse/ANW-1313
> ANW-1313 Provide more descriptive labels in PUI record sidebar, search

- backend/app/exporters/lib/exporter.rb
- backend/app/exporters/models/ead.rb
- backend/app/exporters/serializers/eac.rb
- backend/app/exporters/serializers/ead.rb
- backend/app/exporters/serializers/ead3.rb
- backend/spec/export_eac_spec.rb
- backend/spec/export_ead3_spec.rb
- backend/spec/export_ead_spec.rb
- backend/spec/factories.rb
- backend/spec/model_metadata_rights_declaration_spec.rb
- common/db/migrations/148_metadata_rights_statement_enum.rb
- common/locales/en.yml
- common/locales/enums/en.yml
- common/schemas/metadata_rights_declaration.rb
- frontend/app/views/agents/_form_required.html.erb
- frontend/app/views/metadata_rights_declarations/_show_fields.html.erb
- frontend/app/views/metadata_rights_declarations/_template.html.erb
- frontend/app/views/resources/_sidebar.html.erb
- frontend/config/locales/en.yml
- public/app/views/agents/show.html.erb
- public/app/views/shared/_metadata_rights_declarations.html.erb
- public/app/views/shared/_record_innards.html.erb
- public/config/locales/en.yml
Revisions to metadata rights declaration per https://archivesspace.atlassian.net/browse/ANW-1282
> ANW-1282: metadata rights declaration revisions2

- backend/app/controllers/archival_object.rb
- common/locales/en.yml
- frontend/app/assets/javascripts/jobs.crud.js
- frontend/app/controllers/archival_objects_controller.rb
- frontend/app/controllers/resources_controller.rb
- frontend/app/views/jobs/_form.html.erb
- frontend/app/views/resources/_linker.html.erb
- frontend/config/routes.rb
This PR adds some minor functionality to the find and replace job, chiefly the ability to find and replace in portions of a resource tree (by selecting an archival object instead of a resource as a base record). It also stops `lang_material` models from being selected, since they were causing two "Language" entries to appear in the list.
I believe these changes have broad applicability, as requested by Christine in JIRA, but I won't be offended if others disagree!
https://archivesspace.atlassian.net/browse/ANW-1310
Local testing, backend and frontend test suites run
> ANW-1310: minor enhancements to the find and replace job

- backend/spec/lib_ead_converter_spec.rb
- backend/spec/model_archival_object_spec.rb
- common/db/migrations/154_default_otherlevel.rb
- common/validations.rb
Update to #2054 based on comments left there.
> Enforce other level value field when level is otherlevel

- frontend/app/assets/stylesheets/archivesspace/rde.less
This PR overwrites Bootstrap to add a sticky table header to the RDE form on scroll.
[ANW-919](https://archivesspace.atlassian.net/browse/ANW-919)
Visual cross browser tests.
See above.
> ANW-919 Add sticky table header to RDE form

- indexer/app/lib/indexer_common.rb
- public/app/controllers/accessions_controller.rb
- public/app/models/accession.rb
- public/app/views/accessions/_related_accessions.html.erb
- public/app/views/resources/_related_accessions.html.erb
- public/config/locales/en.yml
- public/config/locales/es.yml
- public/config/locales/fr.yml
- public/config/locales/ja.yml
- public/spec/controllers/resources_controller_spec.rb
- public/spec/features/classifications_spec.rb
- public/spec/features/resources_spec.rb
- public/spec/spec_helper.rb
Corrects an issue introduced via #2238 that broke the ability to view resources with related accessions in the PUI.
https://archivesspace.atlassian.net/browse/ANW-667
> ANW-667 Fixes to use index for display

- common/locales/enums/en.yml
- common/locales/enums/es.yml
- common/locales/enums/fr.yml
- common/locales/enums/ja.yml
Translation missing error appears when leaving container type blank on a top container in PUI
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1176
> ANW-1176: adding missing translation in PUI

- common/db/migrations/143_migrate_agent_date_data_to_structured_dates.rb
I messed up and forgot to rename the expression processing method in the migration .
> fixup! add date expression parsing to migration 143

- frontend/spec/features/accessibility_spec.rb
- frontend/vendor/assets/javascripts/bootstrap-datepicker.js
Resolves conflicts with master, replacement for:
https://github.com/archivesspace/archivesspace/pull/2341
> ANW-1348 resolved

- common/config/config-defaults.rb
- public/spec/features/accessibility_spec.rb
Adding accessibility test
https://archivesspace.atlassian.net/browse/ANW-1358
Manual and in browser testing
> ANW-1358: Updating alt text for main logo; adding accessibility test

- common/spec/lib/factory_bot_helpers.rb
- public/app/views/shared/_display_notes.html.erb
- public/app/views/subjects/show.html.erb
- public/spec/factories.rb
- public/spec/features/agents_spec.rb
- public/spec/features/subjects_spec.rb
- public/spec/spec_helper.rb
Show pages for subjects in the PUI are not working due to a call out to the `display_notes` partial.  Subjects don't and have never had notes, so this is unnecessary.  I'm not sure what happened upstream to reveal this bug, but this will fix it. 
Additionally, upon further digging, it appears that `display_notes` partial isn't used anywhere else either, so I've fully removed it.  Additional partials were also being called in subjects that, again, are never relevant in the context of subjects and the data they can hold, so I've also removed those (dates, component_id, and ref_id).
When writing tests to support this work I also noticed that the PUI tests weren't using the shared factories in `common/spec/lib/factory_bot_helpers.rb` leading to the proliferation of duplicate or near duplicate …
> ANW-1361 Fix PUI subjects show page, PUI factories updates

- frontend/app/assets/javascripts/add_event_dropdown.js
- frontend/app/assets/javascripts/jquery.tokeninput.js
- frontend/app/assets/javascripts/linker.js
- frontend/app/assets/javascripts/merge_dropdown.js.erb
- frontend/app/assets/javascripts/transfer_dropdown.js.erb
- frontend/app/views/resources/_linker.html.erb
- frontend/app/views/shared/_event_dropdown.html.erb
- frontend/app/views/shared/_merge_dropdown.html.erb
- frontend/app/views/shared/_resource_toolbar.html.erb
- frontend/app/views/shared/_transfer_dropdown.html.erb
- frontend/config/locales/en.yml
- frontend/spec/features/accessibility_spec.rb
- frontend/spec/selenium/spec/instances_and_containers_spec.rb
- frontend/spec/selenium/spec/merge_and_transfer_spec.rb
About half the issues for ANW-1326.
> ANW-1326 work in progress: resource toolbar roles and aria attributes

- frontend/config/locales/help/en.yml
- frontend/config/locales/help/es.yml
- frontend/config/locales/help/fr.yml
- frontend/config/locales/help/ja.yml
Updating tooltip values for help links added in ANW-1149
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1149
> ANW-1149: Updating tooltip for help icon on preferences page

- frontend/spec/features/accessibility_spec.rb
Hopefully this will resolve some of the problems this test is having on Github Actions.
N/A
I added a setTimeout to the date field initializer, then tweaked the test until  10 runs all passed. I could not replicate the errors with login, but hopefully the within block will help selenium find the form fields more easily.
> attempt to resolve random CI failures in accessibility tests

- frontend/app/views/agent_contact_details/_show.html.erb
> ANW-442: show preferred contact badge in agent view mode

- frontend/app/views/digital_objects/_show_inline.html.erb
Previous implementation of this feature was missing this.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-501
> ANW-501: Adding classification subrecord to digital object show page

- public/app/views/request_mailer/request_received_staff_email.html.erb
Resubmit to pass tests: https://github.com/archivesspace/archivesspace/pull/2358
> ANW 1379: Washu library technology services fix staff email template

- backend/app/model/archival_object.rb
- backend/spec/model_archival_object_spec.rb
- public/app/models/record.rb
- public/spec/factories.rb
- public/spec/features/resources_spec.rb
> ANW-861 reverts rebase

- backend/app/model/advanced_query_string.rb
- backend/spec/model_advanced_query_string_spec.rb
- common/advanced_query_builder.rb
- frontend/app/assets/javascripts/header.js
- frontend/app/views/shared/_advanced_search.html.erb
- frontend/spec/factories.rb
- frontend/spec/features/advanced_search_dates_spec.rb
- frontend/spec/spec_helper.rb
Reposting https://github.com/archivesspace/archivesspace/pull/2369
> Anw 573 advanced search date copy 2

- .yamllint
- common/locales/enums/en.yml
- common/locales/enums/es.yml
- common/locales/enums/fr.yml
- common/locales/enums/ja.yml
Combination underlying file cleanup/linting, as well as initial updates from Weblate, only targeting `common/locales/enums`.  The diff is huge here, but it's nearly all white space/ordering changes stemming from the Weblate setup process, I promise! ;-)
I have temporarily switched off the Weblate enums component until this is merged into the core code.  Then I'll point that component to the master branch, and turn it back on.
I've added some very basic configurations to `.yamllint`, but as of now running this linter is still manual (e.g. `yamllint .`) and/or up to your editor of choice.  We can investigate adding this into CI if we'd like.
> Enumerations translations updates and start linter implementation

- backend/app/model/db.rb
Just aiming to clarify the logic that decides whether a transaction should be retried given an exception, but with one small change.
If a Java-level exception makes it to the top of a `DB.open` call, Sequel wraps it in a `Sequel::DatabaseError` and rethrows.  This can create pretty unhelpful error messages, because `is_retriable_exception` was only expecting to see JDBC exceptions.  When that happens, you get something like:
Error: #<NoMethodError: undefined method `getSQLState'; for java.lang.NullPointerException:Java::JavaLang::NullPointerException>
So, in addition to making the control flow a little more explicit, this change also skips checking `getSQLState` on other exception types.  They'll get re-raised without the confusing `NoMethodError`.
> Refactor is_retriable_exception logic

- backend/app/controllers/component_add_children.rb
These are additions to the API documentation. They provide shell examples for adding archival object children to resources and other archival children.
Provides examples to the API documentation where there previously were none.
I ran all tests included in the repository specs. The changes passed all tests, including the documentation tests.
- My first submission in this repository. I'm a data migration specialist with Lyrasis
> added API examples for component add children

- .yamllint
- public/config/initializers/public_new_defaults.rb
- public/config/locales/en.yml
While digging into the errors reported in Weblate for the public translations, I noted that a lot of unused translations crept into the public yml file (likely the result of long ago copy/pasting from the frontend translations).  This PR is a conservative first effort at doing some cleanup, including:
- extending yamllint to cover `public`;
- correcting style and syntax errors raised by yamllint; and,
- removing obviously unused translations from public.
> Public locales cleanup

- build/scripts/export_config.rb
https://archivesspace.atlassian.net/browse/ANW-1404
https://archivesspace.atlassian.net/browse/ANW-1405
> ANW-1404 and ANW-1405 Remove config options

- frontend/app/assets/javascripts/tree_toolbar.js.erb
- frontend/app/assets/stylesheets/archivesspace/form.less
- frontend/app/views/shared/_templates.html.erb
- frontend/config/help.yml
- frontend/config/locales/help/en.yml
Add tooltip, Refactor JS code so that link and tooltip title come from the same YAML files as all others
> ANW-1164: Refactor & Tooltip for CSV help icon, 

- frontend/app/views/custom_report_templates/show.html.erb
> Fix view custom report templates with no subreports

- COPYING
Based on recent changes to the Partners group and involvement going forward
University of Illinois Urbana-Champaign is no longer a Partner as of July 1, 2021, and this revised statement reflects responsibility for ArchivesSpace going forward. The change has been approved by all three of the Founding Partners.
> update copyright statement

- frontend/app/assets/javascripts/custom_report_templates.crud.js
- frontend/app/views/custom_report_templates/_toolbar.html.erb
- frontend/config/locales/en.yml
- frontend/spec/features/custom_report_spec.rb
Ensure the "Check/Uncheck All" button in the custom reports template toolbar:
1. Uses translations, and;
2. Provides a meaningful label depending on context.
Also adds an initial frontend custom reports template test.
https://archivesspace.atlassian.net/browse/ANW-1304
> ANW-1304 Custom reports check/uncheck changes

- frontend/app/assets/javascripts/largetree.js.erb
- frontend/app/assets/javascripts/largetree_dragdrop.js.erb
Updates the selector for the parent node of a drag drop target in reorder mode
The nesting for the tree has changed slightly. Levels are now wrapped in an extra div that needs to be accounted for in the selector statements.
https://archivesspace.atlassian.net/browse/ANW-1435
Local testing with local data.
Mac O/S running against MariaDB. I don't believe these changes affect any other sections.
> ANW-1435 Reorder Mode Insert Before/After

- _yard/API.erb
- backend/app/lib/rest.rb
Adds a "Permissions" section to the API documentation that denotes what, if any, permissions are required to use the endpoint.
https://archivesspace.atlassian.net/browse/ANW-1294
No permissions needed:
Permissions required:
> ANW-1294 Indicate required permissions for endpoints in API docs

- frontend/app/assets/javascripts/largetree.js.erb
Fixes selector statement to correctly select the entire set of waypoints necessary to collapse a set of child nodes in the tree
Fixes ANW-1443
https://archivesspace.atlassian.net/browse/ANW-1443
Local testing with data supplied in bug report.
Mac OS, MariaDB
I don't believe this change affects any other sections of the application.
> Fix Selector to Correctly Collapse Nodes for ANW-1443

- backend/app/controllers/classification.rb
- backend/app/controllers/digital_object.rb
- backend/app/controllers/resource.rb
- backend/app/controllers/tree_docs.rb
Updates `/root` endpoint API documentation as requested in the JIRA ticket.
https://archivesspace.atlassian.net/browse/ANW-1292
> ANW-1292 Clarify /root API endpoints

- backend/app/model/ancestor_listing.rb
- backend/app/model/digital_object_component.rb
- backend/spec/model_inheritance_spec.rb
- common/schemas/digital_object_component.rb
Adds the ancestor list to the digital object component schema -- which is already included in the archival object schema for future developer use and refactoring.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-701
> ANW-701: include ancestor listing in digital object components

- package-lock.json
This PR updates outdated dependencies in the front end lint system.
> chore: Update front end linting npm dependencies

- backend/app/converters/lib/marcxml_bib_base_map.rb
- backend/spec/lib_marcxml_bib_converter_spec.rb
Support mapping for Conference Meeting boolean for x11's in the MARC importer
https://archivesspace.atlassian.net/browse/ANW-1411
> ANW-1411: Support mapping for Conference Meeting boolean for x11's in the MARC importer

- frontend/app/views/bulk_import_templates/_listing.html.erb
- frontend/app/views/bulk_import_templates/index.html.erb
- frontend/config/help.yml
- frontend/config/locales/en.yml
Adds a description column to the bulk_template download page, explanatory text, and a link to the help center.
> ANW-1460 add help text and link for bulk template downloads

- frontend/app/controllers/agents_controller.rb
- frontend/spec/features/agent_software_spec.rb
> ANW-1463: Fix agent software merge

- common/locales/en.yml
> ANW-1465: Update locales for custom report templates

- frontend/app/views/resources/_sidebar.html.erb
> ANW-1469: Update metadata rights declaration sidebar position

- backend/app/model/enumeration.rb
- frontend/app/views/enumerations/_list.html.erb
- frontend/spec/selenium/spec/enumeration_management_spec.rb
when there is a value in the enumeration that is suppressed
bugfix
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1148
> ANW-1148: bugfix for not being able to set an enumeration default

- backend/app/controllers/agent_corporate_entity.rb
- backend/app/controllers/agent_family.rb
- backend/app/controllers/agent_person.rb
- backend/app/controllers/agent_software.rb
- backend/app/controllers/enumeration.rb
This PR is to update API documentation with additional examples. These examples include "Publish <agent> and all its sub-records" and "Get an Enumeration by Name".
Documentation for existing API calls.
I ran `./build/run rubocop -D correct=true` in order to catch any potential linter issues.
> Added API shell examples for agents publish and get enumeration by name

- backend/app/lib/slugs/slug_helpers_generate.rb
- backend/spec/model_resource_spec.rb
- backend/spec/spec_slugs_helper.rb
Bugfix for 500 errors in the PUI when UTF-8 chars make their way into slugs
https://archivesspace.atlassian.net/browse/ANW-1201
> ANW-1201: bugfix for UTF-8 chars in slugs breaking the PUI

- frontend/app/assets/stylesheets/archivesspace/top_containers_bulk.less
- frontend/app/views/top_containers/bulk_operations/_bulk_action_templates.html.erb
Bug fixes
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-164
> ANW-164: fix visual bug in top container bulk operations

- common/config/config-defaults.rb
- frontend/app/views/site/_branding.html.erb
- public/app/views/shared/_header.html.erb
Enhancement
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-857
> ANW-857: Adding a config.rb option for header logo and alt-text in frontend

- frontend/app/views/agents/_sidebar.html.erb
- frontend/config/locales/en.yml
Increasing usability by adding appropriate links
https://archivesspace.atlassian.net/browse/ANW-1434
> ANW-1434: adding sidebar links for events and linked via rights statement to events show

- frontend/app/assets/javascripts/extent_calculator.js
- frontend/spec/selenium/spec/resources_spec.rb
Bugfix
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1244
> ANW-1244: bugfix for extent calculator adding result to wrong subrecord

- frontend/config/locales/en.yml
> dedupe global_preferences locale key

- backend/app/model/enumeration.rb
- backend/spec/model_enumeration_spec.rb
> ANW-807 make sure suppressed enum values don't block added values

- backend/app/controllers/users.rb
- backend/spec/controller_user_spec.rb
- frontend/app/controllers/users_controller.rb
- frontend/app/views/shared/_header_user.html.erb
- frontend/app/views/users/_form.html.erb
- frontend/app/views/users/edit_self.html.erb
- frontend/config/locales/en.yml
- frontend/config/routes.rb
- frontend/spec/selenium/spec/user_management_spec.rb
- frontend/spec/selenium/spec/users_and_auth_spec.rb
Adds support for users to update their own accounts
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-534
in browser and unit testing
> ANW-534: Add support for users to update their own accounts

- frontend/config/locales/en.yml
bugfix for translation missing error
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1487
> ANW-1487: bugfix for translation missing error

- backend/app/exporters/lib/export_helpers.rb
- backend/app/exporters/serializers/ead.rb
- backend/app/exporters/serializers/ead3.rb
Bugfix for include unpublished flag not being handled properly
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1276
manual testing
> ANW-1276: bugfix for include_unpublished flag not passed to ead agent export

- backend/app/controllers/container.rb
- backend/app/model/top_container.rb
- backend/spec/model_managed_container_spec.rb
- frontend/app/assets/javascripts/top_containers.bulk.js
- frontend/app/controllers/top_containers_controller.rb
- frontend/app/views/top_containers/bulk_operations/_bulk_action_templates.html.erb
- frontend/app/views/top_containers/bulk_operations/_toolbar.html.erb
- frontend/config/locales/en.yml
- frontend/config/routes.rb
- frontend/spec/selenium/spec/instances_and_containers_spec.rb
Add support to bulk update indicators, as is currently done with barcodes.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-445
manul in browser testing and unit testing
> ANW-445: adding feature to allow bulk update for indicators

- frontend/app/controllers/enumerations_controller.rb
- frontend/app/views/enumerations/_delete.html.erb
- frontend/app/views/enumerations/_list.html.erb
- frontend/spec/selenium/spec/enumeration_management_spec.rb
allow suppressed enum values to be deleted in one step
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1165
> ANW-1165: allow suppressed enum values to be deleted in one step

- frontend/app/assets/stylesheets/archivesspace/top_containers_bulk.less
- frontend/app/views/top_containers/bulk_operations/_bulk_action_templates.html.erb
- frontend/app/views/top_containers/bulk_operations/_container_profile_linker.html.erb
Added create option to linker in update container profiles
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-164
> ANW-164: adding "create" option to linker in "update container profiles" option

- frontend/app/assets/stylesheets/archivesspace/submenu.less
Menus in the front end were off screen at phone and tablet sizes. This fixes this so that the menus are functional at these screen sizes.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1374
> ANW-1374: Fix menu display for phone and tablet screen sizes

- frontend/app/views/preferences/edit.html.erb
- frontend/app/views/shared/_header_user.html.erb
- frontend/config/locales/en.yml
- frontend/spec/selenium/spec/user_preferences_spec.rb
…s glocal preferences
Clarifying confusing global preferences
https://archivesspace.atlassian.net/browse/ANW-1396
unit and in browser testing
> ANW-1396: global preferences

- backend/app/exporters/serializers/ead.rb
- backend/app/exporters/serializers/ead3.rb
- backend/spec/export_ead_spec.rb
Bugfix
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1268
> ANW-1268: bugfix for invalid EAD created when top_container.type left blank

- frontend/config/locales/en.yml
Changed the name to more closely resemble name of similar bulk operations.
> Small rename to new indicator container bulk operation

- package-lock.json
This PR patches a npm subdependency via `npm audit fix`.
> Chore: Patch npm dependency vulnerability

- backend/app/main.rb
- build/build.xml
- common/asutils.rb
- frontend/config/application.rb
- public/Gemfile
- public/Gemfile.lock
- public/config/application.rb
Enable for backend & public
Load pry aliases
> Some dev related pry updates

- frontend/app/views/jobs/report_partials/_customreporttemplate.html.erb
List custom report templates alphabetically in the reports area
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1494
> ANW-1494: List custom report templates alphabetically in the reports area

- backend/app/exporters/models/marc21.rb
- backend/spec/export_marc_spec.rb
- common/config/config-defaults.rb
include PUI link in MARC export
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1071
> ANW-1071: include PUI link in MARC export

- common/locales/en.yml
- frontend/app/views/preferences/edit.html.erb
- frontend/config/locales/en.yml
- frontend/spec/selenium/spec/default_values_spec.rb
- frontend/spec/selenium/spec/record_lifecycle_spec.rb
- frontend/spec/selenium/spec/user_preferences_spec.rb
Update copy for preferences menu and page for clarity
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1396
> ANW-1396: Update copy for preferences menu and page for clarity

- common/config/search_browse_column_config.rb
Adding changes suggested by review for ANW-1360 in PR #2697 
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1360
> Updates to ANW-1360: Search and Browse ID column needed, i.e. Agents and Subjects

- backend/app/exporters/models/marc21.rb
Rework:  output a second 856 with PUI link only if distinct from ead_loc
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1071
> ANW-1071: output a second 856 with PUI link only if distinct from ead_loc

- frontend/app/views/jobs/report_partials/_customreporttemplate.html.erb
Rework for 1494: make sort case insentitive
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1494
> ANW-1494: make custom report template sort case insensitive

- build/build.xml
> Fix public / staff app url link in footer for dev

- frontend/app/models/archival_object.rb
- frontend/app/models/resource.rb
- frontend/spec/controllers/resources_controller_spec.rb
> ANW-725: retain any default value notes when spawning

- public/app/assets/javascripts/print.js
- public/app/assets/stylesheets/application.scss
- public/app/assets/stylesheets/archivesspace/aspace.scss
- public/app/assets/stylesheets/archivesspace/print.css
- public/app/views/search/search_results.html.erb
This PR solves [ANW-950](https://archivesspace.atlassian.net/browse/ANW-950) by improving the PUI print styles, adding some print event js behavior, and updating markup.
Manual cross-browser testing.
Print preview screenshots taken from Firefox at 100% scale, not stretched to fit width.
> ANW-950: Improve PUI print styles

- frontend/app/assets/javascripts/header.js
- frontend/app/assets/javascripts/utils.js
- frontend/app/assets/stylesheets/archivesspace.less
- frontend/app/assets/stylesheets/archivesspace/datepicker.less
- frontend/app/helpers/aspace_form_helper.rb
- frontend/app/views/jobs/_form.html.erb
- frontend/app/views/reports/index.html.erb
- frontend/app/views/shared/_advanced_search.html.erb
- frontend/config/locales/de.yml
- frontend/config/locales/en.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
- frontend/config/locales/ja.yml
- frontend/spec/features/accessibility_spec.rb
This PR closes [ANW-170](https://archivesspace.atlassian.net/browse/ANW-170) and [ANW-490](https://archivesspace.atlassian.net/browse/ANW-490) by making the datepicker opt-in by leveraging the calendar icon to the right of each date input as a datepicker toggle switch.
> ANW-170, ANW-490: Make datepickers opt-in

- backend/app/exporters/models/marc21.rb
- backend/spec/export_marc_spec.rb
include primary agent_record_identifier in MARC export subfield $0
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1414
> ANW-1414: include primary agent_record_identifier in MARC export subfield $0

- .devcontainer/Dockerfile
- .devcontainer/README.md
- .devcontainer/aliases
- .devcontainer/build_and_push
- .devcontainer/build_local
- .devcontainer/devcontainer.json
- .devcontainer/setup
- .solargraph.yml
Fix Mariadb package / commands
Preload mysql db fixtures database
Build multiarch images and push to Docker hub
Use prebuilt image for containers
Remove secrets (was weird)
Still on the fence: pre-bootstrapping
> Updates to devcontainer experiment

- public/app/models/record.rb
- public/app/views/shared/_agents_list.html.erb
- public/app/views/shared/_record_innards.html.erb
- public/app/views/shared/_subjects_list.html.erb
- public/spec/controllers/resources_controller_spec.rb
- public/spec/controllers/search_controller_spec.rb
- public/spec/features/record_innards_spec.rb
- public/spec/features/resources_spec.rb
- public/spec/features/subjects_spec.rb
- public/spec/spec_helper.rb
display subjects list in PUI sorted by first term type
display agents related as subjects in related names section
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-339
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-300
Screenshots (if appropriate):
> ANW-339, ANW-300: display subjects list in PUI sorted by first term type, display agents related as subjects in related names section

- backend/app/exporters/models/marc21.rb
- backend/spec/export_marc_spec.rb
export bibliography notes in MARCXML to 581 tag
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1350
> ANW-1350: export bibliography notes in MARCXML to 581 tag

- frontend/app/views/revision_statements/_template.html.erb
publish flags for revision statements respect user preferences
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1084
manual testing
> ANW-1084: publish flags for revision statements respect user preferences

- public/app/models/record.rb
Date labels were inconsistently applied in the PUI, this fixes them so they're always shown 
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-956
> ANW-956: Always display date label in PUI

- backend/app/model/large_tree.rb
- frontend/app/assets/javascripts/tree_renderers.js.erb
- frontend/spec/selenium/spec/trees_spec.rb
[ANW-942](https://archivesspace.atlassian.net/browse/ANW-942)
> ANW-942: Display suppressed status in large tree

- frontend/config/locales/en.yml
Adding missing translation
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1608
> ANW-1608: adding missing translation

- backend/app/model/enumeration_value.rb
- backend/spec/model_enumeration_spec.rb
- common/db/migrations/168_enum_values_strip_ws.rb
https://archivesspace.atlassian.net/browse/ANW-632
Backend test added. Reviewed db migration. Manually tested in UI.
> ANW-632: remove leading/trailing whitespaces from enumeration values

- frontend/app/models/default_values.rb
- frontend/spec/features/default_values_spec.rb
Return nil on RecordNotFound when retrieving default values
https://archivesspace.atlassian.net/browse/ANW-1617
> ANW-1617: resolve cannot create default values

- frontend/config/locales/en.yml
Adding missing translations
https://archivesspace.atlassian.net/browse/ANW-1608
> ANW-1608: adding missing translations

- public/app/views/containers/show.html.erb
Adds restricted display to show page for top containers on PUI
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1549?filter=myopenissues
> ANW-1549: displays restricted status on container show page in PUI

- frontend/config/locales/en.yml
Updating translations
https://archivesspace.atlassian.net/browse/ANW-1612
Manual, in browser testing
> ANW-1612: update translations

- backend/app/model/digital_object.rb
- backend/spec/model_digital_object_spec.rb
- common/schemas/digital_object.rb
- indexer/app/lib/indexer_common.rb
- public/app/controllers/resources_controller.rb
- public/app/views/resources/_resource_alltabs.erb
- public/app/views/resources/_resource_tab.erb
- public/app/views/resources/digitized.html.erb
- public/config/locales/en.yml
- public/config/routes.rb
- public/spec/features/resources_spec.rb
Add digital object tab, view all d.objects assoc. with resource.
https://archivesspace.atlassian.net/browse/ANW-1206
Builds on (review first):
https://github.com/archivesspace/archivesspace/pull/2844
> Anw 1206 digitized tab

- frontend/config/help.yml
adding links to help documentation for classification record links
https://archivesspace.atlassian.net/browse/ANW-1472
manual in-browser testing
> ANW-1472: adding links to help documentation for classification record links

- backend/app/lib/bulk_import/bulk_import_parser.rb
- common/locales/en.yml
improve invalid UTF-8 error message on spreadsheet import
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1257
> ANW-1257: improve invalid UTF-8 error message on spreadsheet import

- backend/app/converters/lib/marcxml_bib_base_map.rb
- backend/spec/examples/marc/american-communist-82.xml
- backend/spec/examples/marc/american-communist-92.xml
- backend/spec/examples/marc/american-communist-all-call.xml
- backend/spec/lib_marcxml_bib_converter_spec.rb
import marc call numbers as record identifiers
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-440
> ANW-440: import marc call numbers as record identifiers

- backend/app/exporters/models/marc21.rb
change primary identifier order to more closely match MARC spec
https://archivesspace.atlassian.net/browse/ANW-1414
- [ x I have authority to submit this code.
> ANW-1414: change primary identifier order to more closely match MARC spec

- common/config/preference_defaults.rb
- common/locales/en.yml
- common/locales/ja.yml
- common/schemas/defaults.rb
- frontend/app/controllers/digital_objects_controller.rb
- frontend/app/helpers/digital_object_helper.rb
- frontend/app/views/defaults/_template.html.erb
- frontend/app/views/digital_objects/_linker.html.erb
- frontend/spec/features/spawning_spec.rb
Adds support for copying certain fields from the current Resource or Accession when creating and linking a new digital object when enabled via a new preference, as described in https://archivesspace.atlassian.net/browse/ANW-1615
> ANW-1615 support copying description fields and notes from base record when linking a new digital object

- public/app/views/shared/_record_innards.html.erb
reorder subrecord display order
https://archivesspace.atlassian.net/browse/ANW-300
> ANW-300: reorder subrecord display in view

- frontend/app/views/top_containers/bulk_operations/_results.html.erb
- frontend/app/views/top_containers/show.html.erb
- frontend/spec/selenium/spec/instances_and_containers_spec.rb
Rework for ANW-1488, make sure note is visible where appropriate on the view and results pages.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1488
> ANW-1488: display top_container internal note on show view and results page

- backend/app/converters/lib/marcxml_bib_base_map.rb
- backend/spec/examples/marc/american-communist-82.xml
- backend/spec/examples/marc/american-communist-92.xml
- backend/spec/examples/marc/american-communist-all-call.xml
- backend/spec/examples/marc/at-tracer-marc-2.xml
- backend/spec/examples/marc/at-tracer-marc-3.xml
- backend/spec/examples/marc/at-tracer-marc-4.xml
- backend/spec/lib_marcxml_bib_accession_converter_spec.rb
- backend/spec/lib_marcxml_bib_converter_spec.rb
Improve processing of MARCXML 300 field extent processing
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1260
> ANW-1260: MARCXML import: update 300 processing for extents

- backend/app/model/ASModel_crud.rb
- backend/app/model/ASModel_scoping.rb
- backend/app/model/event.rb
- backend/app/model/group.rb
- backend/app/model/preference.rb
Prevent most repository-scoped records from being created in the global repo
> resolves https://github.com/archivesspace/archivesspace/issues/1848

- backend/app/lib/oai/aspace_oai_record.rb
Use correct export method for oai marc with archival objects
https://archivesspace.atlassian.net/browse/ANW-1643
> ANW-1643 fix oai marc error

- frontend/config/help.yml
adding context-sensitive help for metadata rights dec
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1471
> ANW-1471: adding context-sensitive help for metadata rights dec

- plugins/lcnaf/frontend/assets/lcnaf.js
Fixes a browser JS bug caused by URI strings as values in data attributes.
> ANW-1609 quote data attributes that contain URI values

- public/app/helpers/json_helper.rb
- public/app/models/record.rb
- public/app/views/shared/_result.html.erb
- public/spec/features/agents_spec.rb
Update PUI parse_date to support structured dates.
https://archivesspace.atlassian.net/browse/ANW-1625
> ANW-1625: PUI fix agents

- frontend/config/locales/help/en.yml
adding tooltip translations
https://archivesspace.atlassian.net/browse/ANW-1471
[ANW-1471]: https://archivesspace.atlassian.net/browse/ANW-1471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-1471: adding tooltip translations

- frontend/config/locales/en.yml
Adding missing translation
https://archivesspace.atlassian.net/browse/ANW-1612
[ANW-1612]: https://archivesspace.atlassian.net/browse/ANW-1612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> adding missing translation

- backend/app/exporters/models/marc21.rb
fix for $0 ordering for corporate agents in MARCXML exports
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1414
manual testing
[ANW-1414]: https://archivesspace.atlassian.net/browse/ANW-1414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-1414: fix for $0 ordering for corporate agents in MARCXML exports

- public/app/views/resources/_resource_alltabs.erb
> ANW-1206: hide dobj pil if no linked dobj instances

- backend/app/exporters/models/marc21.rb
Fixing inconsistent subfield ordering in MARC export
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1414
Manual testing
> ANW-1414: subfield ordering fix

- public/config/locales/en.yml
Adding missing translation
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1662
Manual testing
> ANW-1662: adding missing translation

- common/db/migrations/170_make_date_label_existence_readonly.rb
Replaces https://github.com/archivesspace/archivesspace/pull/2873
> GH-2833 ensure date_label enumeration has an 'existence' value

- stylesheets/as-ead-pdf.xsl
Applied fix for table markup breaking PDF generation
https://archivesspace.atlassian.net/browse/ANW-1648
manual testing
Table as appears in PDF:
Note as appears in Resource record:
> ANW-1648: Applied fix for table markup breaking PDF generation

- frontend/app/views/accessions/_form.html.erb
- frontend/app/views/archival_objects/_form_container.html.erb
- frontend/app/views/digital_object_components/_form_container.html.erb
- frontend/app/views/digital_objects/_form_container.html.erb
- frontend/app/views/resources/_form_container.html.erb
- frontend/spec/features/default_values_spec.rb
- frontend/spec/features/spawning_spec.rb
- frontend/spec/selenium/spec/accessions_spec.rb
- frontend/spec/selenium/spec/classifications_spec.rb
- frontend/spec/selenium/spec/collection_management_spec.rb
- frontend/spec/selenium/spec/digital_objects_spec.rb
- frontend/spec/selenium/spec/enumeration_management_spec.rb
- frontend/spec/selenium/spec/notes_spec.rb
- frontend/spec/selenium/spec/rde_spec.rb
- frontend/spec/selenium/spec/resources_spec.rb
- frontend/spec/selenium/spec/trees_spec.rb
This is but a copy of https://github.com/archivesspace/archivesspace/pull/2803 with an added commit to fix broken selenium tests.
> ANW-1666 mixed content in titles

- frontend/config/locales/en.yml
Discovered by a tester. They're Location Profiles not Locations Profiles.
> correcting typo

- backend/app/model/mixins/representative_file_version.rb
- backend/spec/mixin_representative_file_version_spec.rb
Rewrite the parts of the mixin that search resource trees for representative digital objects and digital object trees for representative file versions. Perviously we tried to 'cheat' by using a single query, but that was not fit to purpose due to both selection and order criteria not reflecting the nuances of the spec. This means that we now have more expensive calculations to make, so we will probably want to add some guardrails like a controller parameter for resolving representatives (since only the indexer really needs the property as of now) and / or a config setting for how many nodes to search through.
> A rewrite of the representative file version mixin 

- backend/app/model/mixins/representative_file_version.rb
Changes how representative digital object is found in resource tree, using hash tables similar to:
https://github.com/archivesspace/archivesspace/blob/master/backend/app/model/mixins/trees.rb#L188-L240
Significantly reduces response time for trees where the winning object is positioned far down in the ordered tree.
> Another Pass at Searching Resource Tree for Representative

- backend/app/model/archival_object.rb
- backend/app/model/mixins/representative_file_version.rb
- backend/spec/mixin_representative_file_version_spec.rb
…m an unpublished Archival Object
https://archivesspace.atlassian.net/browse/ANW-1708
> ANW-1708 A Resource's Representative File Version should not come from an unpublished Archival Object

- COPYING
- README.md
Needed to update the links to our license due to change on the destination site's side.
> Updating broken links

- backend/app/model/external_document.rb
- backend/app/model/file_version.rb
- backend/app/model/mixins/notes.rb
- backend/app/model/note.rb
- backend/app/model/revision_statement.rb
See https://github.com/archivesspace/archivesspace/issues/2935
> Gh 2935 publishable mixin cleanup

- common/config/config-defaults.rb
There was a typo in a comment. I updated it to be extent.
Hasn't been tested because it is a comment change.
> Update typo in config-defaults.rb

- backend/app/exporters/serializers/ead.rb
- backend/app/exporters/serializers/ead3.rb
include physoc note labels in all EAD and PDF exports
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1450
> ANW-1450: include physoc note labels in all EAD and PDF exports

- frontend/app/assets/javascripts/largetree_dragdrop.js.erb
- frontend/app/assets/javascripts/tree_renderers.js.erb
- frontend/app/assets/javascripts/tree_toolbar.js.erb
- frontend/app/assets/stylesheets/archivesspace/toolbar.less
- frontend/config/locales/en.yml
- frontend/spec/selenium/common/tree_helper.rb
- frontend/spec/selenium/spec/digital_objects_spec.rb
[ANW-625](https://archivesspace.atlassian.net/browse/ANW-625): Refactor the UI for asking the user "how do you want to handle dropping your dragged selection", from a post-drop modal to a pre-drag radio input selection with a default choice.
Features of the new radio input buttons include:
- built from semantic HTML, and therefore are more accessible and operate slightly differently under the hood than other buttons while remaining visually and functionally consistent with the other toolbar buttons
- make use of the browser's local storage to remember the user's most recent selection
**NOTE** that this change requires updating the docs here, https://archivesspace.atlassian.net/wiki/spaces/ArchivesSpaceUserManual/pages/894140803/Reordering+Components+in+Resources+and+Digital+Objects+as+of+v …
> ANW-625: Refactor staff drag and drop modal as toolbar buttons

- docker-startup.sh
Support for copying robots.txt
Delete the deploy pkg tmp folder
Using a test deployment and confirming that the robots.txt file is correct and the tmp folder is no longer around.
> Update docker startup script

- public/app/views/welcome/show.html.erb
Fixes a copy/paste error. 'record' object does not exist in this context.
Fixes an earlier pull request that had a copy/paste error.
Local Testing
> Plugin addition to PUI welcome - fix

- public/app/views/pdf/_resource.html.erb
Porting over support for displaying physloc notes in PUI PDFs from ANW-258 branch
https://archivesspace.atlassian.net/browse/ANW-1450
manual testing
> ANW-1450: porting over physloc work in PUI PDF from ANW-258 branch

- .devcontainer/Dockerfile
- .devcontainer/setup
> Devcontainer: install gems directly as final step

- frontend/config/locales/de.yml
- frontend/config/locales/en.yml
Taking out some language that was hedging ArchivesSpace's bets on how the reset would work.
> Small edit to password reset directions

- backend/app/exporters/serializers/ead.rb
- backend/app/exporters/serializers/ead3.rb
- backend/spec/export_ead_spec.rb
- common/db/migrations/174_add_is_finding_aid_status_published.rb
- common/locales/en.yml
- common/schemas/resource.rb
- frontend/app/views/resources/_form_container.html.erb
- public/app/views/pdf/_resource.html.erb
- public/app/views/resources/_finding_aid.html.erb
- public/spec/features/resources_spec.rb
- public/spec/spec_helper.rb
Added a publish flag for finding aid status for resource record, implemented it in PUI and EAD exports
https://archivesspace.atlassian.net/browse/ANW-312
> ANW-312: Publish flag for finding aid status

- frontend/app/views/linked_agents/_template.html.erb
Fixes bug where choosing primary agent didn't stick.
https://archivesspace.atlassian.net/browse/ANW-504
> ANW-504: fix for primary agent link not getting selected; css bug

- backend/app/controllers/id_lookup_controller.rb
- backend/spec/controller_idlookup_spec.rb
Analogous to `[:GET] /repositories/:repo_id/find_by_id/archival_objects` but, rather than accepting `ref_id` or `component_id` parameters to query the `archival_object` table on those columns, instead this queries the `top_container` table on the `indicator` or `barcode` columns.
I would find this very useful in my own API scripts. The `[:GET] /repositories/:repo_id/top_containers/search` endpoint already exists, but that returns Solr search results, which have to be parsed and a second call made to retrieve the JSON representation of the top container itself.
https://archivesspace.atlassian.net/browse/ANW-1800
```python
>>> from asnake.client import ASnakeClient
>>> client = ASnakeClient(baseurl="http://localhost:4567", username="admin", password="admin")
>>> client.authorize()
>>> …
```
> ANW-1800: Add a "find_by_id" API endpoint for top containers

- common/locales/en.yml
updating label name on Location form
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-852
> ANW-852: updating label name on Location form

- frontend/app/views/top_containers/bulk_operations/_collection_accession_linker.erb
- frontend/app/views/top_containers/bulk_operations/_collection_resource_linker.erb
Looks like a couple of these got mixed up in PR #2709
> fixes a couple of misreferenced translations

- frontend/config/locales/en.yml
Changed one word in the subject import template description based on a hosted customer's observation
None
- [X ] My code follows the code style of this project.
- [X ] I have read the **CONTRIBUTING** document.
- [ X] I have authority to submit this code.
My first ever PR, but just a typo, so fingers crossed.
> Typo in en.yml

- common/config/config-defaults.rb
> updated link to new solr docs URL

- public/app/controllers/repositories_controller.rb
The PUI agents listing includes agent records with the `pui_agent_family` type, but the badge for them in the repository page ("Names" in English) was not including that type in its count. This adds the type to the list of counts that are fetched, and a special case for adding it in to the `pui_agent` count for display.
> ANW-1693 include family agents in PUI agent badge count

- backend/app/converters/lib/marcxml_bib_base_map.rb
- backend/app/exporters/models/marc21.rb
- backend/app/exporters/serializers/marc_auth.rb
- backend/spec/export_marc_spec.rb
- backend/spec/lib_marcxml_bib_converter_spec.rb
Adding MARC import and export support
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-504
> ANW-504: Adding MARC import and export support

- .github/workflows/frontend.yml
- .github/workflows/public.yml
- common/db/db_migrator.rb
- frontend/spec/features/representative_file_version_spec.rb
- frontend/spec/features/resource_tree_spec.rb
- frontend/spec/features/spawning_spec.rb
- frontend/spec/selenium/spec/merge_and_transfer_spec.rb
https://archivesspace.atlassian.net/browse/ANW-1895
> fixes / improvements for our flakky frontend specs

- frontend/app/views/notes/_form.html.erb
https://archivesspace.atlassian.net/browse/ANW-1875
> ANW-1875 remove add contact note button in repository show view

- frontend/config/locales/de.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
- frontend/config/locales/ja.yml
Adds the remaining translations for the Make Primary tooltip.
https://archivesspace.atlassian.net/browse/ANW-1878
> ANW-1878 - Add other languages for Make Primary tooltip

- frontend/config/locales/de.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
- frontend/config/locales/ja.yml
Further changes for the other languages on this tooltip and label. I noticed some edits were needed once this was merged.
https://archivesspace.atlassian.net/browse/ANW-1878
> ANW-1878 - make primary tooltip adjustments

- frontend/spec/features/datepicker_plugin_spec.rb
Run it without any failures on CI 50 times with Java 8: 
https://github.com/archivesspace/archivesspace/actions/runs/8008001902/job/21873410601
And another 50 times with Java 11:
https://github.com/archivesspace/archivesspace/actions/runs/8008001902/job/21873411232
> Fix datepicker plugin spec

- .devcontainer/Dockerfile
- .devcontainer/build_and_push
- .devcontainer/build_local
- .github/workflows/accessibility.yml
- .github/workflows/backend.yml
- .github/workflows/frontend.yml
- .github/workflows/public.yml
- backend/app/model/solr.rb
- backend/spec/model_solr_spec.rb
- solr/Dockerfile
- solr/solrconfig.xml
Bump Docker solr to v9.4.1.
Use LATEST for lucenematchversion to avoid having to specify it (and to track latest during development).
Disable checksum verification for solrconfig.
https://archivesspace.atlassian.net/browse/ANW-1851
> Solr updates

- frontend/spec/controllers/jobs_controller_spec.rb
https://archivesspace.atlassian.net/browse/ANW-1969
> ANW-1969 fix datepicker plugin spec

- frontend/spec/controllers/digital_objects_controller_spec.rb
- frontend/spec/factories.rb
- frontend/spec/features/spawning_spec.rb
Rewrites feature tests for DO spawning as controller tests, which should improve execution speed and reliability.
> ANW-1884 rewrite DO spawn spec as controller tests

- stylesheets/as-ead-pdf.xsl
Fixes to Staff PDF
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1849
Manual testing
> ANW-1849: Fixes to Staff PDF

- frontend/spec/features/typeahead_search_spec.rb
> fix capybara typeahead search spec

- frontend/app/views/linked_agents/_show.html.erb
- public/config/locales/en.yml
Adding labels so primary agents can be easily distinguished
https://archivesspace.atlassian.net/browse/ANW-504
manual testing
> ANW-504: adding labels to primary agent links in frontend and PUI show views

- plugins/custom-pui-pdf-font/README.md
> Small typo fix for PUI PDF font plugin

- stylesheets/as-ead-pdf.xsl
https://archivesspace.atlassian.net/browse/ANW-1992
> ANW-1992 scale image on staff generated pdf to fit

- frontend/spec/features/permissions_spec.rb
> fix flaky permissions spec

- common/config/config-aliases.rb
> fix email_perform_deliveries config alias

- .github/workflows/accessibility.yml
- .github/workflows/all_specs_dispatch.yml
- .github/workflows/backend.yml
- .github/workflows/codescan.yml
- .github/workflows/common-frontend.yml
- .github/workflows/frontend.yml
- .github/workflows/indexer.yml
- .github/workflows/public.yml
Manually triggering a workflow only works on the master branch, so we first need to merge this PR in order to really be able to test it: https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
https://archivesspace.atlassian.net/browse/ANW-2012
> Manually trigger specs on CI

- .github/actions/bootstrap/action.yml
- frontend/spec/aspace_helper.rb
- frontend/spec/features/accessibility_spec.rb
- frontend/spec/features/agent_software_spec.rb
Had to manually trigger a CI run for all tests on this PR:
https://github.com/archivesspace/archivesspace/actions/runs/9034734501/job/24827997301
> Fix frontent ci

- .github/workflows/frontend.yml
- frontend/spec/features/digital_objects_rde_spec.rb
- frontend/spec/features/rde_spec.rb
> Fix rde spec

- .github/workflows/common-frontend.yml
> updated aws ami

- frontend/spec/features/collection_management_spec.rb
- frontend/spec/features/custom_report_spec.rb
> Fix more specs

- .github/workflows/all_specs_dispatch.yml
- .github/workflows/common-frontend.yml
- .github/workflows/frontend.yml
This will allow us to manually trigger running the CI for a specific group of frontend specs. Unfortunately the manual triggering of actions only can happen for workflows already in master, so we can only test this after it is merged.
> add a choice dropdown to choose to manually dispatch a specific workflow

- .github/workflows/common-frontend.yml
Avoid the need to create a PR every time we want to update the AWS AMI used by github runners. As a better practice use repository variables instead.
> aws conf variables

- frontend/spec/features/groups_spec.rb
This seems to avoid issues locally.
> logout at end of each example in groups spec

- frontend/app/views/archival_objects/_form_container.html.erb
- frontend/app/views/digital_object_components/_form_container.html.erb
> ANW-2041 Fix component publish checkbox layout

- common/locales/de.yml
This is a fork of #3180 which included multiple new-line-only changes. This PR removes the white space changes. This PR was necessary because I couldn't push to the original branch.
> Gh 3180 german translations alt

- frontend/config/locales/de.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
- frontend/config/locales/ja.yml
Apply changes to en.yml from 
https://github.com/archivesspace/archivesspace/pull/3203/files#diff-49cfcba79865708f2da7a6af19b370464ebebf9ccbc819a849098c422090a041
to all locales
> Sync locales

- backend/app/model/spreadsheet_builder.rb
- backend/spec/model_spreadsheet_builder_spec.rb
Add spreadsheet builder model for bulk update
Testing with unit tests
> Add spreadsheet builder model and specs

- backend/app/lib/job_runners/resource_duplicate_runner.rb
- backend/app/lib/resource/duplicate.rb
- backend/spec/lib_resource_duplicate_spec.rb
- backend/spec/spec_helper.rb
- common/locales/de.yml
- common/locales/en.yml
- common/locales/es.yml
- common/locales/fr.yml
- common/locales/ja.yml
- common/schemas/resource_duplicate_job.rb
- common/spec/lib/factory_bot_helpers.rb
- frontend/app/controllers/exports_controller.rb
- frontend/app/controllers/resources_controller.rb
- frontend/app/views/exports/resource_duplicate.html.erb
- frontend/app/views/shared/_resource_toolbar.html.erb
- frontend/config/locales/de.yml
- frontend/config/locales/en.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
- frontend/config/locales/ja.yml
- frontend/config/routes.rb
- frontend/spec/features/resources_spec.rb
[ANW-1757]
[ANW-1757]: https://archivesspace.atlassian.net/browse/ANW-1757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-1757 Duplicate resource record

- backend/app/exporters/serializers/ead.rb
- backend/spec/fixtures/oai/responses/getrecord_oai_ead.xml
- stylesheets/as-ead-pdf.xsl
[ANW-1651]
[ANW-1651]: https://archivesspace.atlassian.net/browse/ANW-1651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-1651 Agent relator translations on staff pdf

- backend/app/lib/csv_template_generator.rb
Fix bug reported here: https://archivesspace.atlassian.net/browse/ANW-1428?focusedCommentId=39615
[ANW-1428]
[ANW-1428]: https://archivesspace.atlassian.net/browse/ANW-1428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-1428 fix prefilled do import template path

- backend/app/lib/csv_template_generator.rb
I tried to fix this with: https://github.com/archivesspace/archivesspace/pull/3225 but that solution does not work on test.archivesspace.org. 
I think this one will be better.
[ANW-1428]
[ANW-1428]: https://archivesspace.atlassian.net/browse/ANW-1428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-1428 Fix digital object template path

- backend/app/exporters/serializers/ead.rb
- backend/spec/lib_as_fop_spec.rb
- stylesheets/as-ead-pdf.xsl
[ANW-1982]
[ANW-1982]: https://archivesspace.atlassian.net/browse/ANW-1982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-1982 Remove commas and periods from EAD langmaterial

- backend/app/model/solr.rb
- public/app/models/record.rb
- public/app/models/solr_results.rb
- public/app/services/archives_space_client.rb
- public/app/views/shared/_result.html.erb
- public/config/locales/de.yml
- public/config/locales/en.yml
- public/config/locales/es.yml
- public/config/locales/fr.yml
- public/config/locales/ja.yml
- public/config/locales/pt.yml
- public/spec/controllers/search_controller_spec.rb
- public/spec/features/search_spec.rb
[ANW-363]
[ANW-363]: https://archivesspace.atlassian.net/browse/ANW-363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-363 Public search highlighting

- backend/app/exporters/serializers/ead.rb
- backend/app/lib/job_runners/print_to_pdf_runner.rb
- backend/spec/fixtures/oai/responses/getrecord_oai_ead.xml
- backend/spec/fixtures/oai/responses/getrecord_oai_ead_without_uris.xml
https://archivesspace.atlassian.net/browse/ANW-1651?focusedCommentId=39654
> ANW 1651 agent relator translations on staff pdf

- frontend/app/assets/stylesheets/archivesspace/form.scss
- frontend/app/views/digital_object_components/_new_inline.html.erb
- frontend/app/views/locations/_sidebar_batch.html.erb
- frontend/app/views/locations/batch.html.erb
- frontend/app/views/shared/_sidebar.html.erb
Fix minor layout issues from the Softserv upgrades in the staff sidebar and new child form action buttons.
> ANW-2102: Fix minor staff softserv layout issues

- frontend/app/views/layouts/application.html.erb
[ANW-2098]
[ANW-2098]: https://archivesspace.atlassian.net/browse/ANW-2098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2098 Fix html output on plugin header

- public/app/views/layouts/application.html.erb
[ANW-2098]
[ANW-2098]: https://archivesspace.atlassian.net/browse/ANW-2098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2098 Fix html output on public plugin header

- Dockerfile
- scripts/build_release
[ANW-2108]
[ANW-2108]: https://archivesspace.atlassian.net/browse/ANW-2108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2108 show git commit hash in UI footer

- frontend/app/controllers/archival_objects_controller.rb
- frontend/spec/features/trees_spec.rb
[ANW-1964]
[ANW-1964]: https://archivesspace.atlassian.net/browse/ANW-1964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-1964 duplicate archival object without instances

- .github/workflows/all_specs_dispatch.yml
[ANW-2110]
[ANW-2110]: https://archivesspace.atlassian.net/browse/ANW-2110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2110 trigger all specs on java 17

- frontend/app/views/bulk_archival_object_updater/download_form.html.erb
[ANW-2080]
[ANW-2080]: https://archivesspace.atlassian.net/browse/ANW-2080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2080 Fix dropdowns on generate bulk archival object spreadsheet form

- frontend/app/views/top_containers/bulk_operations/_search_criteria.html.erb
This PR fixes Softserv layout bugs on the top containers search form at /top_containers.
[ANW-1985](https://archivesspace.atlassian.net/browse/ANW-1985)
[ANW-1985]: https://archivesspace.atlassian.net/browse/ANW-1985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-1985: Fix the top containers search form layout bugs

- Dev.dockerfile
- Dockerfile
- build/build.xml
- frontend/Gemfile
- frontend/Gemfile.lock
- launcher/archivesspace.bat
- launcher/archivesspace.sh
- public/Gemfile
- public/Gemfile.lock
- public/config/application.rb
- public/config/environments/production.rb
[ANW-2110]
[ANW-2110]: https://archivesspace.atlassian.net/browse/ANW-2110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Anw 2110 add support for java 17

- frontend/app/views/location_profiles/edit.html.erb
- frontend/app/views/location_profiles/new.html.erb
- frontend/app/views/location_profiles/show.html.erb
> ANW-2126 Fix location profile badge and layouts

- Dockerfile
- Gemfile.lock
- backend/Gemfile
- backend/Gemfile.lock
> Fix jdbc issue

- build/build.xml
This fixes the jdbc issue of our Docker builds
> bundle backend without development and build groups

- Dockerfile
> revert upgrade of ubuntu version in Dockerfile

- backend/spec/lib_as_fop_spec.rb
- stylesheets/as-ead-pdf.xsl
[ANW-2044]
[ANW-2044]: https://archivesspace.atlassian.net/browse/ANW-2044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2044 Staff PDF archival object component unique identifier

- .github/workflows/accessibility.yml
- .github/workflows/all_specs_dispatch.yml
- .github/workflows/backend.yml
- .github/workflows/codescan.yml
- .github/workflows/common-frontend.yml
- .github/workflows/frontend.yml
- .github/workflows/indexer.yml
- .github/workflows/public.yml
- frontend/spec/aspace_helper.rb
- frontend/spec/rails_helper.rb
- public/spec/rails_helper.rb
[ANW-2129]
[ANW-2129]: https://archivesspace.atlassian.net/browse/ANW-2129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2129 run public capybara specs on chrome and get browser and driver logs

- .github/workflows/accessibility.yml
- .github/workflows/all_specs_dispatch.yml
- .github/workflows/frontend.yml
> fix github actions CI dispatching

- frontend/app/views/jobs/_form.html.erb
This PR fixes some common minor Softserv form label + value field layouts.
[ANW-2147](https://archivesspace.atlassian.net/browse/ANW-2147)
[ANW-2147]: https://archivesspace.atlassian.net/browse/ANW-2147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2147: Fix report label and value layouts

- .github/workflows/accessibility.yml
- .github/workflows/all_specs_dispatch.yml
- .github/workflows/common-frontend.yml
- .github/workflows/frontend.yml
- .github/workflows/public.yml
- frontend/spec/aspace_helper.rb
> ensure we are logged out before trying to login

- .github/workflows/accessibility.yml
> upload ci-logs when accessiblity ci workflow fails

- backend/app/converters/ead_converter.rb
- backend/spec/examples/ead/ead-dao-test.xml
- backend/spec/examples/ead/vmi.xml
- backend/spec/fixtures/ead_with_extents.xml
- backend/spec/lib_ead_converter_spec.rb
[ANW-243]
[ANW-243]: https://archivesspace.atlassian.net/browse/ANW-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-243 Verify date type on EAD import

- backend/app/converters/ead_converter.rb
- backend/spec/examples/ead/ead-dao-test.xml
- backend/spec/examples/ead/vmi.xml
- backend/spec/fixtures/ead_with_extents.xml
- backend/spec/lib_as_fop_spec.rb
- backend/spec/lib_ead_converter_spec.rb
- frontend/app/assets/stylesheets/themes/default/default.scss
- frontend/app/views/agents/show.html.erb
- frontend/app/views/extent_calculator/_show_calculation.html.erb
- frontend/app/views/jobs/_form.html.erb
- frontend/app/views/jobs/_job_records.html.erb
- frontend/app/views/linked_agents/_show.html.erb
- frontend/app/views/search/_title_cell.html.erb
- frontend/app/views/shared/_header_repository.html.erb
- frontend/app/views/shared/_header_user.html.erb
- public/app/views/pdf/_archival_object.html.erb
- public/spec/models/finding_aid_pdf_spec.rb
- stylesheets/as-ead-pdf.xsl
Cherry picked changes from master branch on:
[ANW-2087]
[ANW-2044]
[ANW-243]
[ANW-2147]
[ANW-2148]
[ANW-2149]
[ANW-2084]
[ANW-2087]: https://archivesspace.atlassian.net/browse/ANW-2087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ANW-2044]: https://archivesspace.atlassian.net/browse/ANW-2044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ANW-243]: https://archivesspace.atlassian.net/browse/ANW-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ANW-2147]: https://archivesspace.atlassian.net/browse/ANW-2147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ANW-2148]: …
> Merge fixes from master

- backend/spec/model_location_profile_spec.rb
- common/validations.rb
[ANW-1880]
[ANW-1880]: https://archivesspace.atlassian.net/browse/ANW-1880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-1880 Update location profile dimensions validation

- frontend/spec/aspace_helper.rb
> ensure jQuery.active is defined before checking its return value

- public/Gemfile
See also https://github.com/archivesspace/tech-docs/pull/191
[ANW-2159]
[ANW-2159]: https://archivesspace.atlassian.net/browse/ANW-2159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2159 remove javascript runtime dependency from pui

- README.md
Updating the link for user documentation to go to information about accessing the Help Center
> Update user docs link

- public/app/controllers/application_controller.rb
- public/app/controllers/concerns/manipulate_node.rb
- public/app/models/record.rb
- public/app/views/pdf/_archival_object.html.erb
- public/spec/models/finding_aid_pdf_spec.rb
[ANW-2010]
[ANW-2010]: https://archivesspace.atlassian.net/browse/ANW-2010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2010 fix ampersands with semicolons in public PDF

- public/app/models/record.rb
- public/spec/features/classifications_spec.rb
- public/spec/features/resources_spec.rb
[ANW-2163]
[ANW-2163]: https://archivesspace.atlassian.net/browse/ANW-2163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2163 Remove repository and classification uri from highlighting

- README.md
- build/build.xml
- frontend/spec/aspace_helper.rb
- oai/app/main.rb
- oai/config/warble.rb
- oai/config/web.xml
- public/Gemfile
> Cherry pick fixes from master

- frontend/spec/features/bulk_import_spec.rb
This is the second of a chain of two PRs (see also: https://github.com/archivesspace/archivesspace/pull/3349)
> Fix frontend bulk import spec

- .github/workflows/common-frontend.yml
- .github/workflows/frontend.yml
- frontend/spec/features/bulk_import_spec.rb
Use github workers for our frontend specs to avoid the issue: https://github.com/orgs/community/discussions/44322
This should be merged to master after https://github.com/archivesspace/archivesspace/pull/3350 is merged into it so that all specs pass.
> use github runners for ci 

- backend/app/converters/ead_converter.rb
- backend/spec/lib_ead_converter_spec.rb
[ANW-243] [ANW-2182]
[ANW-243]: https://archivesspace.atlassian.net/browse/ANW-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ANW-2182]: https://archivesspace.atlassian.net/browse/ANW-2182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-243 Fix date types on EAD import

- .github/workflows/common-frontend.yml
- .github/workflows/frontend.yml
- frontend/spec/aspace_helper.rb
- frontend/spec/features/accessibility_spec.rb
- frontend/spec/features/datepicker_plugin_spec.rb
- frontend/spec/features/default_values_spec.rb
- frontend/spec/features/events_spec.rb
- frontend/spec/features/merge_and_transfer_spec.rb
- frontend/spec/features/resources_spec.rb
- frontend/spec/rails_helper.rb
> Fix Ci feature specs

- common/jsonmodel_i18n_mixin.rb
- frontend/spec/features/subjects_spec.rb
[ANW-1442]
[ANW-1442]: https://archivesspace.atlassian.net/browse/ANW-1442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-1442 Prepend frontend proxy URL in subject conflict error message

- public/app/controllers/pdf_controller.rb
- public/spec/features/resources_spec.rb
- public/spec/rails_helper.rb
[ANW-2087] see comment https://archivesspace.atlassian.net/browse/ANW-2087?focusedCommentId=40560
[ANW-2087]: https://archivesspace.atlassian.net/browse/ANW-2087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2087 Public PDF download clean filename

- backend/app/lib/job_runners/ns2_remover_runner.rb
[ANW-2186]
[ANW-2186]: https://archivesspace.atlassian.net/browse/ANW-2186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2186 add logging

- frontend/spec/aspace_helper.rb
> Avoid Selenium::WebDriver::Error::JavascriptError: ReferenceError: jQuery is not defined on our ci

- frontend/config/routes.rb
The route was removed here: https://github.com/archivesspace/archivesspace/commit/4c9ebfaf147ea93f53af5bac2d184febc5493448#diff-159f705e5b95933188ff14104166f25d5aca357c96ceb70982f9254892a43694L115
[ANW-2137]
[ANW-2137]: https://archivesspace.atlassian.net/browse/ANW-2137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2137 Fix resource record default route

- frontend/app/views/top_containers/show.html.erb
- frontend/spec/features/agents_spec.rb
- frontend/spec/features/resources_spec.rb
[ANW-2203]
[ANW-2203]: https://archivesspace.atlassian.net/browse/ANW-2203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2203 Fix top container with restriction view

- frontend/app/views/top_containers/show.html.erb
- frontend/spec/features/agents_spec.rb
- frontend/spec/features/resources_spec.rb
> Cherry pick latest changes

- public/app/views/digital_objects/_linked_instances.html.erb
- public/spec/features/digital_objects_spec.rb
[ANW-2089]
[ANW-2089]: https://archivesspace.atlassian.net/browse/ANW-2089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2089 fix breadcrumbs of digital objects containing mixed content

- backend/app/model/search.rb
- backend/spec/model_search_spec.rb
- frontend/app/assets/javascripts/digital_object_spawning.js.erb
- frontend/app/helpers/jobs_helper.rb
- frontend/app/views/bulk_archival_object_updater_job/_form.html.erb
- frontend/app/views/jobs/_job_records.html.erb
- frontend/spec/features/resources_spec.rb
- public/app/views/digital_objects/_linked_instances.html.erb
- public/spec/features/digital_objects_spec.rb
> Merge latest from master

- common/locales/en.yml
- common/locales/es.yml
- frontend/config/locales/es.yml
This commit was/is incomplete:
https://github.com/archivesspace/archivesspace/commit/f95e6a6b2ef435d55eaa2eb5d1b9b5660c0e66f2#diff-3443581a78ba31861d1e38948ea10ef1a0b326835ccbf935e1ba39ba78361fe7R3017
It only has EN and DE
This PR adds the missings for ES.
> Fix missing locales

- public/app/models/record.rb
- public/app/views/shared/_record_innards.html.erb
- public/config/locales/de.yml
- public/config/locales/en.yml
- public/config/locales/es.yml
- public/config/locales/fr.yml
- public/config/locales/ja.yml
- public/spec/features/record_innards_spec.rb
- public/spec/spec_helper.rb
Adds "partial/whole extend" literal on PUI collection overview page
https://archivesspace.atlassian.net/browse/ANW-1505
> ANW-1505: Adding partial/whole extend in PUI

- Gemfile
- Gemfile.lock
Needed in the release notes process
> update git gem

- scripts/tasks/doc.thor
- scripts/tasks/release_notes.rb
> Fix release notes generation

- frontend/config/locales/es.yml
> remove duplicate translation keys

- frontend/app/assets/javascripts/utils.js
- scripts/tasks/doc.thor
- scripts/tasks/release_notes.rb
> Merge from master

- scripts/tasks/doc.thor
> add debug messages in release notes building

- frontend/config/locales/de.yml
- frontend/config/locales/en.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
- frontend/config/locales/ja.yml
> Fix merge terminology in locales (for master branch)

- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
> fix merge terminology locales on release-v4.0.x branch

- .github/workflows/release.yml
- scripts/tasks/doc.thor
use github token during release release notes building, get complete git history and add debug messages
> fix release notes building

- public/app/views/shared/_digital.html.erb
- public/config/locales/de.yml
- public/config/locales/en.yml
- public/config/locales/es.yml
- public/config/locales/fr.yml
- public/config/locales/ja.yml
- public/config/locales/pt.yml
- public/spec/features/record_digital_materials_spec.rb
Singluar and Plural on digital objects of a resource for the PUI
https://archivesspace.atlassian.net/browse/ANW-1773
Singular
Plural
- [] New feature (non-breaking change which adds functionality)
> ANW-1773: Singluar and Plural on PUI digital objects

- public/config/locales/de.yml
- public/config/locales/en.yml
- public/config/locales/es.yml
- public/config/locales/fr.yml
- public/config/locales/ja.yml
- public/config/locales/pt.yml
- public/spec/features/resources_spec.rb
Relabel PDF icon on PUI
https://archivesspace.atlassian.net/browse/ANW-972
> ANW-972: Change label of pdf icon in PUI

- frontend/config/locales/de.yml
- frontend/config/locales/en.yml
- frontend/config/locales/es.yml
- frontend/config/locales/fr.yml
- frontend/config/locales/ja.yml
These are some small changes to the description of what some of the selections are at the bottom of the bulk updater download page, based on a suggestion from a user.
> Updated locales for bulk update page

- common/config/config-defaults.rb
- frontend/app/controllers/application_controller.rb
- frontend/app/models/user.rb
- frontend/config/environments/production.rb
- frontend/config/initializers/session_store.rb
- public/config/environments/production.rb
- public/config/initializers/session_store.rb
Applies to Rails production env.
> Use AppConfig for rails force_ssl to secure cookies etc.

- frontend/spec/features/advanced_search_dates_spec.rb
> ANW-2031 advanced search dates spec fix

- backend/app/lib/job_runners/resource_duplicate_runner.rb
- frontend/app/views/jobs/_show_templates.html.erb
- frontend/spec/features/jobs_spec.rb
- frontend/spec/features/resources_spec.rb
[ANW-2230]
[ANW-2230]: https://archivesspace.atlassian.net/browse/ANW-2230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2230 hide resource duplicate job from job creation menu in SUI

- frontend/spec/features/accessions_spec.rb
- frontend/spec/features/advanced_search_dates_spec.rb
- frontend/spec/features/archival_objects_spec.rb
- frontend/spec/features/collection_management_spec.rb
- frontend/spec/features/enumeration_management_spec.rb
- frontend/spec/features/groups_spec.rb
- frontend/spec/features/locations_batch_spec.rb
- frontend/spec/features/merge_and_transfer_spec.rb
> ANW-2031 re-enable feature specs

- frontend/app/views/shared/_rde.html.erb
See also: https://github.com/archivesspace/e2e-tests/pull/53/files#diff-d6777af1e71c2c8364425710fe0df56274b5f9c02912bfd71fce012a1908171aR36-R44
> fix for property of fill column on rde

- .github/workflows/frontend.yml
> add more groups of frontend feature specs to increase parallelism

- frontend/spec/aspace_helper.rb
- frontend/spec/features/advanced_search_dates_spec.rb
- frontend/spec/features/notes_spec.rb
> ANW-2031 re-enable and fix notes spec

- frontend/spec/aspace_helper.rb
- frontend/spec/features/advanced_search_dates_spec.rb
- frontend/spec/features/notes_spec.rb
- frontend/spec/features/resources_spec.rb
> ANW-2031 re-enable resources specs

- .github/workflows/public.yml
- public/app/models/record.rb
[ANW-2236]
[ANW-2236]: https://archivesspace.atlassian.net/browse/ANW-2236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2236 remove redundant field from solr highlighting

- frontend/app/assets/javascripts/top_containers.bulk.js
- frontend/app/views/top_containers/bulk_operations/_bulk_action_templates.html.erb
- frontend/spec/features/top_containers_spec.rb
> ANW-2031 re-enable top containers spec

- frontend/spec/features/digital_objects_spec.rb
- frontend/spec/features/notes_spec.rb
- frontend/spec/features/system_information_spec.rb
- frontend/spec/features/typeahead_search_spec.rb
- frontend/spec/features/user_management_spec.rb
> ANW-2031 fix and re-enable feature specs

- frontend/app/controllers/agents_controller.rb
- frontend/spec/features/agents_spec.rb
- frontend/spec/features/enumeration_management_spec.rb
[ANW-2247]
[ANW-2247]: https://archivesspace.atlassian.net/browse/ANW-2247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2247 fix publish and delete agents success messages

- build/build.xml
- frontend/spec/aspace_helper.rb
- frontend/spec/features/accessibility_spec.rb
- frontend/spec/features/agents_spec.rb
- frontend/spec/features/digital_objects_spec.rb
- frontend/spec/features/events_spec.rb
- frontend/spec/features/merge_and_transfer_spec.rb
- frontend/spec/features/notes_spec.rb
- frontend/spec/features/rde_spec.rb
- frontend/spec/features/rde_templates_spec.rb
- frontend/spec/features/resources_spec.rb
- frontend/spec/features/top_containers_spec.rb
- frontend/spec/rails_helper.rb
> ANW-2031 improve spec efficiency

- backend/app/converters/lib/marcxml_bib_base_map.rb
- backend/spec/examples/marc/at-tracer-marc-1.xml
- backend/spec/examples/marc/sj2021054178.marcxml.xml
- backend/spec/lib_marcxml_bib_converter_spec.rb
- common/locales/enums/en.yml
Updates MARCXML imports to use subject source codes, rather than full (potentially space-containing) subject source translations.
As described in [ANW-2245](https://archivesspace.atlassian.net/browse/ANW-2245), the current behavior (importing full phrases such as "Medical Subject Headings") has the following negative consequences:
- potentially duplicates existing controled values;
- creates inconsistencies across sources (lcsh has already [been updated](https://github.com/archivesspace/archivesspace/pull/1467) to use a code, not translation);
- potentially breaks EAD2002 exports because source attributes cannot contain spaces.
https://archivesspace.atlassian.net/browse/ANW-2245
Existing automated tests pass; manually tested.
[ANW-2245]: …
> ANW-2245 ensure imported subjects are valid on EAD export

- Gemfile.lock
- common/locales/de.yml
- common/locales/en.yml
- common/locales/es.yml
- frontend/config/locales/de.yml
- scripts/tasks/check.rb
[ANW-2264]
[ANW-2264]: https://archivesspace.atlassian.net/browse/ANW-2264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2264 fix missing locales report and yml files

- public/app/controllers/pdf_controller.rb
- public/app/views/shared/_print_page_action.html.erb
- public/config/initializers/public_new_defaults.rb
- public/spec/features/resources_spec.rb
PDF download icon on PUI collection views
https://archivesspace.atlassian.net/browse/ANW-773
> ANW-773: Adding PDF download button on collection views

- frontend/app/views/accession_links/_accession_linker.html.erb
- frontend/spec/features/archival_objects_spec.rb
As described in [ANW-2270](https://archivesspace.atlassian.net/browse/ANW-2270), accession links will be removed on resave if they number more than 5 (and are thus initially hidden)
Updates the linker template for accession links to provide `prelinker` classed input fields and updates the id for each linker form. Adds additional feature spec for archival object accession links.
[ANW-2270](https://archivesspace.atlassian.net/browse/ANW-2270)
Local Testing under 4.0.
[ANW-2270]: https://archivesspace.atlassian.net/browse/ANW-2270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ANW-2270]: https://archivesspace.atlassian.net/browse/ANW-2270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> potential fix for ANW-2270

- build/build.xml
- docker-compose-prod.yml
[ANW-2269]
[ANW-2269]: https://archivesspace.atlassian.net/browse/ANW-2269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2269 add locales and plugins to docker conf package

- backend/Gemfile
- backend/app/converters/lib/marcxml_auth_agent_base_map.rb
- backend/spec/examples/marc/authority_john_davis.xml
- backend/spec/lib_marcxml_auth_agent_converter_spec.rb
- build/build.xml
[ANW-2232]
[ANW-2232]: https://archivesspace.atlassian.net/browse/ANW-2232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2232 import all repetitions of repeatable marcxml datafields

- frontend/app/assets/javascripts/InfiniteTree.js
- frontend/app/assets/javascripts/InfiniteTreeFetch.js
- frontend/app/assets/javascripts/InfiniteTreeMarkup.js
- frontend/app/assets/javascripts/MixedContent.js
- frontend/app/assets/javascripts/MixedContentHelper.js
- frontend/app/assets/javascripts/tree_renderers.js.erb
- frontend/app/assets/stylesheets/archivesspace/infinite-tree.scss
- frontend/app/views/shared/_infinite_tree.html.erb
This PR is mostly used for adding the visual diff to the historical record.
This PR upgrades the frontend's InfiniteTree markup to use the new `<ol>` tree via the recent work on [ANW-2559](#3472).
> ANW-2311: Upgrade frontend InfiniteTree markup

- build/build.xml
- docker-compose-prod.yml
See also https://github.com/databacker/mysql-backup/pull/62/files
[ANW-2278]
[ANW-2278]: https://archivesspace.atlassian.net/browse/ANW-2278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2278 fix docker backups

- frontend/app/helpers/export_helper.rb
- frontend/spec/helpers/export_helper_spec.rb
[ANW-2274]
[ANW-2274]: https://archivesspace.atlassian.net/browse/ANW-2274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2274 fix csv encoding

- public/app/models/record.rb
- public/app/models/solr_results.rb
- public/app/views/shared/_result.html.erb
- public/spec/controllers/search_controller_spec.rb
[ANW-2280]
[ANW-2280]: https://archivesspace.atlassian.net/browse/ANW-2280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2280 Fix translation missing errors in search results highlighting

- common/locales/enums/de.yml
- common/locales/enums/en.yml
- common/locales/enums/es.yml
- common/locales/enums/fr.yml
- common/locales/enums/ja.yml
- public/app/helpers/json_helper.rb
- Add a new label for "Acquisition" for date_label
- Provide a fallback in case the date_label is missing
https://archivesspace.atlassian.net/browse/ANW-2029
> ANW-2029: Missing translation for date label

- build/build.xml
- common/spec/lib/factory_bot_helpers.rb
- frontend/Gemfile.lock
- frontend/spec/aspace_helper.rb
- public/Gemfile.lock
- public/app/views/shared/_result.html.erb
- public/config/locales/de.yml
- public/config/locales/en.yml
- public/config/locales/es.yml
- public/config/locales/fr.yml
- public/config/locales/ja.yml
- public/config/locales/pt.yml
- public/spec/features/search_spec.rb
[ANW-2280]
[ANW-2280]: https://archivesspace.atlassian.net/browse/ANW-2280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2280 add search results highlighting on PUI

- public/app/controllers/repositories_controller.rb
- public/app/views/repositories/_repository.html.erb
- public/spec/controllers/repositories_controller_spec.rb
Add an "About" preview section in PUI repos list if description exists
https://archivesspace.atlassian.net/browse/ANW-1610
Create a repo with a description and navigate to the repositories list in PUI
> ANW-1610: About field on repos list

- frontend/config/help.yml
Looks like the link was going to the wrong place, so this changes to the right one.
> fix bulk updater help link

- frontend/app/controllers/bulk_import_templates_controller.rb
Just a small change to improve error handling when the user requests a template that doesn't exist.
> Improve handling of non-existent import template

- .github/workflows/frontend.yml
- frontend/spec/controllers/preferences_controller_spec.rb
> re-enable frontend model and controller specs

- backend/app/model/mixins/relationships.rb
- backend/spec/controller_merge_request_spec.rb
- frontend/app/controllers/agents_controller.rb
This is a rewrite of https://github.com/archivesspace/archivesspace/pull/3340 moving the solution from the SUI to the backend, so that it works when merging agents using the API as well.
[ANW-2064]
[ANW-2064]: https://archivesspace.atlassian.net/browse/ANW-2064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Linked agent role lost from records when merging agents

- frontend/spec/features/notes_spec.rb
- frontend/spec/features/representative_file_version_spec.rb
- frontend/spec/features/resource_tree_spec.rb
- frontend/spec/features/restricted_properties_spec.rb
> ANW-2031 fix and re-enable disabled feature specs

- public/app/assets/stylesheets/archivesspace/bootstrap-overrides.scss
- public/app/views/shared/_note_content.html.erb
This PR fixes [ANW-2344](https://archivesspace.atlassian.net/browse/ANW-2344) which reports on Softserv-related formatting issues with PUI bioghist and bibliographic notes display.
[ANW-2344]: https://archivesspace.atlassian.net/browse/ANW-2344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2344 Fix PUI notes displays and Softserv blockquote styles

- frontend/app/views/search/_filter.html.erb
- frontend/spec/features/mixed_content_in_title_fields_spec.rb
- public/app/views/agents/_name.html.erb
- public/app/views/agents/_related_agents.html.erb
- public/app/views/agents/show.html.erb
- public/app/views/shared/_agents_list.html.erb
- public/app/views/shared/_header.html.erb
- public/spec/features/mixed_content_in_title_fields_spec.rb
This PR finishes up [ANW-2353](https://archivesspace.atlassian.net/browse/ANW-2353) with:
- a fix for the frontend search filter that was discovered after previous PRs in this ticket thread, including updating the frontend spec
- multiple fixes for the public app, and including a comprehensive spec
- #3509 
- #3534 
- #3537 
[ANW-2353]: https://archivesspace.atlassian.net/browse/ANW-2353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2353 Fix more mixed content in display of record titles

- Gemfile.lock
- _yard/Gemfile.lock
- backend/Gemfile.lock
- indexer/Gemfile.lock
- public/Gemfile.lock
> Remove duplicate gem versions

- .github/workflows/accessibility.yml
- .github/workflows/all_specs_dispatch.yml
- .github/workflows/backend.yml
- .github/workflows/codescan.yml
- .github/workflows/common-frontend.yml
- .github/workflows/frontend.yml
- .github/workflows/indexer.yml
- .github/workflows/public.yml
- .github/workflows/release.yml
- .github/workflows/stats.yml
- Rakefile
- backend/app/main.rb
- backend/spec/spec_helper.rb
- build/build.xml
- common/aspace_coverage.rb
- common/spec/jsonmodel_spec.rb
- common/validations.rb
- frontend/config/application.rb
- frontend/spec/aspace_helper.rb
- frontend/spec/spec_helper.rb
- indexer/Gemfile
- indexer/Gemfile.lock
- indexer/app/lib/fake_solr_timeout_response.rb
- indexer/app/lib/realtime_indexer.rb
- indexer/app/main.rb
- indexer/spec/spec_helper.rb
- public/config/environments/test.rb
- public/spec/spec_helper.rb
[ANW-2276]
[ANW-2276]: https://archivesspace.atlassian.net/browse/ANW-2276?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2276 fix test coverage reports, integrate coveralls

- docker-compose-prod.yml
[ANW-2383]
See also: https://github.com/archivesspace/tech-docs/pull/241/files
And: https://github.com/archivesspace/archivesspace/issues/3563
[ANW-2383]: https://archivesspace.atlassian.net/browse/ANW-2383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2383: update Solr command to use solr-precreate with custom config path

- public/spec/factories.rb
- public/spec/spec_helper.rb
> Fix public specs

- backend/spec/model_deletion_spec.rb
- backend/spec/sample_record_set.dat
Convert dataset json and update model lookups to handle multiple titles change
> ANW-2380 deletion spec and dataset updates

- common/locales/en.yml
- frontend/app/controllers/resources_controller.rb
- frontend/spec/features/resources_spec.rb
> fixes for frontend resources spec

- backend/spec/controller_digital_object_component_spec.rb
> ANW-2380 digital object component controller spec

- .github/workflows/all_specs_dispatch.yml
- .github/workflows/common-e2e-tests.yml
- .github/workflows/e2e-tests.yml
> Add e2e tests workflow

- frontend/spec/features/resources_spec.rb
> remove duplicate test for bulk archival object spreadsheet generation

- frontend/app/controllers/archival_objects_controller.rb
- frontend/app/views/resources/_form_container.html.erb
- frontend/spec/factories.rb
- frontend/spec/features/add_as_you_go_spec.rb
- frontend/spec/features/archival_objects_spec.rb
- frontend/spec/features/assessments_spec.rb
- frontend/spec/features/classifications_spec.rb
- frontend/spec/features/digital_objects_rde_spec.rb
- frontend/spec/features/events_spec.rb
- frontend/spec/features/jobs_spec.rb
- frontend/spec/features/merge_and_transfer_spec.rb
- frontend/spec/features/notes_spec.rb
- frontend/spec/features/rde_spec.rb
- frontend/spec/features/rde_templates_spec.rb
- frontend/spec/features/resources_spec.rb
- frontend/spec/features/typeahead_search_spec.rb
> Frontend spec fixes

- frontend/app/views/custom_report_templates/index.html.erb
- frontend/config/help.yml
- frontend/config/locales/help/en.yml
It looks like a more generic help link on this page was not updated to make it specific to custom report templates.
https://archivesspace.atlassian.net/browse/ANW-2393
> ANW-2393: Correcting some issues with the context-sensitive help for custom report templates

- .env.docker.prod
- build/build.xml
- build/scripts/export_config.rb
[ANW-2401]
[ANW-2401]: https://archivesspace.atlassian.net/browse/ANW-2401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2401 remove config overrides from docker env to avoid confusion

- .github/workflows/build-docker-images.yml
[ANW-2406]
[ANW-2406]: https://archivesspace.atlassian.net/browse/ANW-2406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2406 use docker metadata action to generate docker tags

- .github/workflows/build-docker-images.yml
[ANW-2406]
[ANW-2406]: https://archivesspace.atlassian.net/browse/ANW-2406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2406 build separate metadata for each image type

- docker-compose-prod.yml
https://stackoverflow.com/questions/65612411/forcing-docker-to-use-linux-amd64-platform-by-default-on-macos
https://docs.docker.com/build/building/multi-platform/
[ANW-2426]
[ANW-2426]: https://archivesspace.atlassian.net/browse/ANW-2426?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add platform directive to avoid no matching manifest docker error on mac

- indexer/app/lib/indexer_common.rb
- public/spec/features/search_spec.rb
- public/spec/rails_helper.rb
[ANW-2441]
[ANW-2441]: https://archivesspace.atlassian.net/browse/ANW-2441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2441 fix sorting by finding aid filing title

- frontend/app/assets/javascripts/InfiniteTree.js
- frontend/app/assets/javascripts/InfiniteTreeI18n.js
- frontend/app/assets/javascripts/InfiniteTreeMarkup.js
- frontend/app/assets/javascripts/tree_renderers.js.erb
- frontend/app/assets/stylesheets/archivesspace/infinite-tree.scss
- frontend/app/views/shared/_infinite_tree.html.erb
- frontend/config/environments/development.rb
- frontend/config/environments/production.rb
- frontend/config/environments/test.rb
[ANW-2322](https://archivesspace.atlassian.net/browse/ANW-2322)
[ANW-2322]: https://archivesspace.atlassian.net/browse/ANW-2322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ANW-2322: Add remaining columns to the Infinite Tree for resources

- backend/app/controllers/job.rb
Adds additional documentation to the `jobs_with_files` endpoint
https://github.com/archivesspace/archivesspace/issues/3671
> add documentation for jobs_with_files endpoint

- backend/app/model/mixins/trees.rb
- frontend/app/controllers/bulk_archival_object_updater_controller.rb
- frontend/app/controllers/digital_objects_controller.rb
- frontend/app/controllers/jobs_controller.rb
- frontend/app/controllers/resources_controller.rb
- frontend/app/views/jobs/_job_records.html.erb
- frontend/app/views/resources/_form_container.html.erb
- frontend/spec/features/archival_objects_spec.rb
- frontend/spec/features/resources_spec.rb
update "Trees" backend mixin for multiple titles
update bulk archival object updater controller to pass dropdown menu example in resources_spec
update archival objects spec
> various spec updates

- common/db/migrations/142_update_existing_tables_for_agents.rb
```
archivesspace  | I, [2025-09-09T15:26:30.684657 #13]  INFO -- : Begin applying migration version 142, direction: up
archivesspace  |
archivesspace  |     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
archivesspace  |     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
archivesspace  |     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
archivesspace  |     !!                                                                                                !!
archivesspace  |     !!                                      Database migration error.                                 !!
archivesspace  |     !! …
```
> migration 142 fails without securerandom

- solr/Dockerfile
> Start testing Solr v9.9.0

- common/multiple_titles_helper.rb
- frontend/app/controllers/archival_objects_controller.rb
- frontend/app/controllers/resources_controller.rb
Updates various controller actions to handle multiple title selection so that the client-side linker stuff will have access to the proper title.
> Linker updates
