frontend/app/views/jobs/_show_templates.html.erb, frontend/app/views/jobs/show.html.erb
Following feedback from #1980, have implemented the following:
- Don't display "Files" section with downloadable files/reports when a job is queued or running (this applies globally for all import job types);
- Bulk import jobs were using the default/fallback form template, and not the bulk import job template with bulk import specific form fields -- now they are; and,
- Fixed a long-standing style thing that has bothered me wherein the `#files` section of a completed job was styled the same as the drag and drop `#files` div in a file upload form.
Only show "Download Report" when job is complete.  Show bulk import job specific "Basic Information" info:
=> Don't show files unless job complete, show bulk_import form fields

frontend/app/assets/javascripts/collection_management_records.crud.js
The js that does the calculation for total processing hours for collection management sub-records is hard coded for resources only. This PR makes that calculation apply to accessions and digital objects (and pretty much any other object in future).
None. Discovered in regression testing for 2.8.1
Local testing in browser. Mac O/S with MySQL.
=> Update Total Processing Hours for Collection Management CRUD js

frontend/app/views/agents/_form_required.html.erb
Fixes a 500 error due to incorrect assignment in frontend/app/views/agents/_form_required.html.erb line 21. Error can currently be reproduced by attempting access any of /agents/agent_person/required, /agents/agent_family/required, etc.
None. Discovered during regression testing for 2.8.1.
In-browser testing of local build: Mac O/S running against MySQL DB. Also: all agent frontend tests were run against new change.
N/A
=> Fixes Agent required fields view

backend/app/lib/bulk_import/agent_handler.rb
The call to *stored*, the method used to see if an agent has previously been processed (and its information stored locally had an incorrectly created parameter.
This solves the problem of, once an agent of a particular type (person, corporate, family) is created, it is applied as the agent for any subsequent archival objects that have an arbitrary agent of the same type.
- [X ] Bug fix (non-breaking change which fixes an issue)
- [ X] My code follows the code style of this project.
- [ X] I have read the **CONTRIBUTING** document.
=> Fix to agent handler assigning wrong agents

backend/app/lib/bulk_import/bulk_import_mixins.rb
The bulk importer allows for creation of date_type enumeration values. This creates all sorts of havoc in the frontend. This is a quick patch to prevent that specific issue, but does not fix the validation problems in general. Nor does it prevent the importer from creating an object from a row with this issue. It will continue to discard that section of the row. IE if the date type is not in the list of enumeration values already present, that date section of the row will be discarded and no date subrecord will be created.
https://github.com/archivesspace/archivesspace/issues/2035
Local testing, including manual import and backend tests.
=> Prevent bulk import from creating date types

common/config/search_browse_column_config.rb, common/locales/en.yml, common/locales/es.yml, common/locales/fr.yml, common/locales/ja.yml, frontend/app/helpers/search_helper.rb, frontend/app/views/defaults/_template.html.erb, frontend/app/views/preferences/_sidebar.html.erb, frontend/app/views/preferences/edit.html.erb, frontend/app/views/search/_langcode_cell.html.erb, frontend/app/views/shared/_sidebar_entry.html.erb, frontend/config/locales/en.yml, frontend/config/locales/es.yml, frontend/config/locales/fr.yml, frontend/config/locales/ja.yml
Extends existing search/browse preference column behavior in the following ways:
- Browse/search columns preferences may be set in the UI for all 18 record types currently in `search_browse_column_config.rb`;
- Language of Materials columns may now be added for the following record types in the UI: resources, archival objects, digital objects, digital object components, and multi/search.;
- Given the addition of 14 new record types to the UI, a new sidebar has been added to the user/repo/global preferences page, with browse columns sorted alphabetically by translated key.  Also, note order has been moved nearer the top, a heading has been provided for the browse columns section, and a new `subentry` local has been added to `sidebar_entry` to make it somewhat easier to nest sub-subheadings …
=> ANW-1099, ANW-776, ANW-1008: Search/browse column improvements

common/config/config-aliases.rb, common/config/config-defaults.rb, common/config/config-distribution.rb
This is in addition to the existing alias option.
Deprecate bulk import frontend config settings for upload. They
are not used now that the bulk import runs as a background job.
Checked deprecated config settings are reported on startup.
=> Provide a direct method to deprecate a config property.

backend/app/lib/bulk_import/bulk_import_mixins.rb, backend/app/lib/bulk_import/lang_handler.rb, backend/app/lib/bulk_import/notes_handler.rb, common/locales/en.yml
Update date type messaging. Date will not be processed if type
is not recognized.
Makes error messaging consistent with: https://github.com/archivesspace/archivesspace/pull/2037
=> No escape on note exception message

backend/app/exporters/serializers/ead.rb, common/locales/en.yml
Fix for ANW-969, exporting an EAD2002 <langusage> note based on find_aid_language if there's no finding_aid_language_note
The JIRA calls for exporting <script> as well, but EAD2002 doesn't have a script tag.
[ANW-969](https://archivesspace.atlassian.net/browse/ANW-969)
Tried several exports, with and without finding aid language note
=> ANW-969: Export <langusage> from finding aid language if no note

frontend/app/views/classification_terms/_record_linker.html.erb, frontend/app/views/classifications/_record_linker.html.erb, frontend/app/views/events/_record_linker.html.erb
Seems like this one has been around for a long while, but the Linked Records sections on Events, Classifications, and Classification Terms edit pages don't have the same styling applied to them as other instances of Linked Records sections elsewhere in the application (likely because these are less frequently used record types in general).  This change just mimics the classes/html used elsewhere in the application to fix the existing ugly/broken-looking styling.
I also did a little indentation/code style cleanup since I was already in there... 
Incidentally discovered during pre-v2.8.1-RC testing.
Looks good :-)
Before this PR:
Proposed changes:
=> Improve styling of event and classifications record linkers

common/config/search_browse_column_config.rb, common/db/migrations/138_reindex_collection_management.rb, frontend/app/models/search.rb, indexer/app/lib/indexer_common.rb
Add title_sort to CM record, it was missing because CM records
are indexed as extra documents (reindex of CM records required).
Update parent_title to use title_sort. Don't need to change use
of parent_title as CM record titles are all the same anyway.
Update frontend search to find sort_by when available in config.
This will work for all instances of sort_by not just the
(previously) hard-coded title -> title_sort.
=> Fix collection management title sorting

frontend/app/assets/javascripts/tree_toolbar.js.erb
In some situations reordered components don't remain reordered.  If the active component prior to the user enabling/using reorder mode is then saved after reorder mode is exited (either with or without active changes), then the json that is sent via the update posts an old/pre-reorder logical position value.  The form/page needs to be reloaded to update this position after exiting reorder mode so that the form does not contain stale data.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1156
Existing tests passed, confirmed db and json values persist/change as expected when using the UI's reorder mode.
=> ANW-1156: Don't undo reordering when saving selected component

backend/app/converters/lib/marcxml_base_map.rb, backend/app/exporters/examples/marc/at-tracer-marc-1.xml, backend/spec/lib_marcxml_converter_spec.rb
Fix for ANW-1002, MARC 245$g should import into a bulk date field
[ANW-1002](https://archivesspace.atlassian.net/browse/ANW-1002)
Tested with the Columbia example MARC record set https://github.com/ASpace-Metadata-Standards/marc-examples/tree/master/ColumbiaUniversityMARC
=> ANW 1002:  Map MARC 245$g to bulk dates on import

backend/app/lib/background_job_queue.rb, backend/app/lib/job_runners/batch_import_runner.rb, backend/app/lib/streaming_import.rb, backend/app/model/ASModel_crud.rb, backend/app/model/backend_enum_source.rb, backend/app/model/db.rb, backend/app/model/job.rb, backend/app/model/mixins/relationships.rb, backend/tests/integration.rb, common/aspace-rails/compressor.rb, common/jsonmodel.rb, common/jsonmodel_i18n_mixin.rb, common/jsonmodel_type.rb, common/locales/en.yml, indexer/app/lib/index_batch.rb, indexer/app/lib/indexer_common.rb, indexer/spec/indexer_common_spec.rb, solr/schema.xml
Includes 18 commits from the larger #1896 funded by Queensland State Archives and written by:
- @marktriggs
- @jambun
- @payten
- acf37cdc79453a8f9643882481ada16b2a8f6fba: Reduce JSON parsing by storing extra data about records in a batch
- 1d330d6c84b9225075ab789ea67b4de729b45cbb: Ensure that realtime-indexing always sees up-to-date records
- 676120f5d49908cb3449fe422db42dc6d9dddb08: Don't require URI patterns with placeholders to end in a slash
- 05abccbd0606cc9b65d7f02bfe3425d551d41c95: Don't blow up when indexing an accession with no title or date
- 498b8ecee90f437e0582c19d9e7be6e9eecfbe0e: Bugfix: Don't mark failed jobs as "completed"
- eed06fc26e63a217bf363f02b98a005aeded1cc2: Document a strange sequence of events that caused imports to silently rollback.
- …
=> Hm qsa 110620

frontend/app/views/agent_contact_details/_show.html.erb, frontend/app/views/agent_functions/_show.html.erb, frontend/app/views/agent_genders/_show.html.erb, frontend/app/views/agent_occupations/_show.html.erb, frontend/app/views/agent_places/_show.html.erb, frontend/app/views/agent_topics/_show.html.erb, frontend/app/views/agents/show.html.erb, frontend/app/views/notes/_show.html.erb, frontend/app/views/related_agents/_show.html.erb, frontend/app/views/used_languages/_show.html.erb, frontend/config/locales/en.yml
Ensures that all subrecords' subrecords (e.g. notes, dates, telephones, etc.) display in the view-only views of a new/full agent record.
=> Confirm all notes, dates, etc. appear in view only display of subrecords

backend/spec/model_agent_corporate_entity_spec.rb, backend/spec/model_agent_family_spec.rb, backend/spec/model_agent_person_spec.rb, backend/spec/model_agent_software_spec.rb, common/db/migrations/002_missing_date_foreign_keys.rb, common/locales/enums/en.yml, frontend/app/assets/javascripts/utils.js, frontend/app/assets/stylesheets/archivesspace/sidebar.less, frontend/app/helpers/sidebar_helper.rb, frontend/app/views/agents/_sidebar.html.erb, frontend/app/views/agents/show.html.erb, frontend/app/views/shared/_sidebar_entry.html.erb
The sidebar for the new/full agents records can be quite long.  This adds the following:
- Indents subrecord sidebar entries under the proper sidebar heading;
- Shades headings in the sidebar in light gray and removes the `>` on the right side of the entry;
- Only adds the blue pill/record count in edit mode to subrecords (not to subrecord headings);
- Only displays sidebar entries/headings if there is record content for those entries/headings while in view mode;
- Only shows form headings/anchors in the view-only form if there are subrecords to display under that heading;
- Adds a bottom margin to the sidebar as a first pass/start of a fix for https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1152
Just a general note that there are a lot of whitespace changes in …
=> Staff sidebar enhancements for agents

common/locales/enums/en.yml, frontend/app/views/agent_alternate_sets/_show_fields.html.erb, frontend/app/views/agent_conventions_declarations/_show.html.erb, frontend/app/views/agent_conventions_declarations/_show_fields.html.erb, frontend/app/views/agent_genders/_show.html.erb, frontend/app/views/agent_maintenance_histories/_show.html.erb, frontend/app/views/agent_maintenance_histories/_show_fields.html.erb, frontend/app/views/agent_record_controls/_show.html.erb, frontend/app/views/agent_record_controls/_show_fields.html.erb, frontend/app/views/agent_resources/_show.html.erb, frontend/app/views/agent_resources/_show_fields.html.erb, frontend/app/views/agent_sources/_show_fields.html.erb, frontend/app/views/used_languages/_show.html.erb
Accomplishes three primary items:
- Fixes "translation missing" errors for the default (only) gender option of `not_specified` by adding a translation for not_specified;
- Removes the other existing gender translations (male, female, not known); and,
- Ensures the new agents-related staff-side forms all default to raw values in cases where translations are missing for those values (as is done elsewhere in the application).
Also updates forms to only use `"` when doing string interpolation in keeping with general ArchivesSpace practice.
Frontend tests passing.  Visually confirmed.
Helps avoid these types of translation missing errors (whether items are added via "Manage Controlled Value Lists" or whether items are added via an import job):
=> Missing enumeration translations should default to the value

common/config/config-defaults.rb, frontend/app/helpers/application_helper.rb, frontend/app/views/agents/_sidebar.html.erb, frontend/app/views/shared/_sidebar_entry.html.erb, frontend/app/views/system_info/_info.html.erb, frontend/spec/selenium/spec/agents_spec.rb
Remove AppConfig handbrake. Full agent view access determined
by permission only.
Update agent sidebar to add lightmode toggle class where needed.
Clean up tests to remove AppConfig specific handling.
=> Lightmode updates

frontend/app/views/agents/_form_required.html.erb, frontend/app/views/agents/_merge_selector.html.erb, frontend/app/views/related_agents/_template.html.erb
Resolves:
```
[java] F, [2021-01-22T09:14:39.578161 #2738] FATAL -- : ActionView::Template::Error (No such template: "structured_date_label"):
[java] F, [2021-01-22T09:14:39.578323 #2738] FATAL -- :     52:   <div class="subrecord-form-container">
[java]     53:     <% if cardinality === :zero_to_one && list_limited_to_one == false %>
[java]     54:       <%= form.list_for([form[name]].compact, name) do |item| %>
[java]     55:         <% form.emit_template(template, item) %>
[java]     56:       <% end %>
[java]     57:     <% else %>
[java]     58:       <%= form.list_for(form[name], "#{name}[]") do |item| %>
```
=> Fix structured date templates to use type

backend/app/converters/lib/marcxml_auth_agent_base_map.rb, backend/spec/lib_marcxml_auth_agent_converter_spec.rb
Addressing a number of issues with MARC imports discovered during initial ANW-429 user testing, including: 
- MARCXML 008/040 importing content to single Record Info and/or repeating Other Agency Codes as needed
- MARCXML 001/010/016/024/035 fields importing into repeating Record IDs with appropriate types/sources/authorized flags as necessary
- MARCXML 040 field subfield e no longer generates citation field
- MARCXML 046 field subfields s, t, q, and r importing both standardized (if parseable) and expression dates
- MARCXML 100/110 field @ind1 value correctly setting Direct/Indirect name order
- MARCXML 100/110 repeating subfields all now import
- MARCXML 110 field @ind1 value not importing correctly
- MARCXML 37x fields no longer always generating date records
- MARCXML 37x subfields s, …
=> Anw 429 MARC import enhancements

frontend/app/assets/javascripts/locations.location_holdings.js, frontend/app/views/locations/_linker.html.erb, frontend/app/views/locations/_location_holdings_cell.html.erb, frontend/app/views/locations/index.html.erb, frontend/app/views/top_containers/bulk_operations/_location_linker.html.erb
This PR is the third of 3 proposed solutions to #1920 (see there for info about all 3 PRs).
This fixes both the duplicated imports and the synchronous request warning by listening for the "Browse Locations" modal to open after a totally arbitrary amount of time I made up (300ms).
This is the solution to #1920 that I recommend, but it may be brittle at 300ms? The server is waiting for a response with modal DOM from itself, is it possible for it to take longer than this?
#1920 
See #1920
=> GH-1920 --C-- Fix bugs, listen for modal

reports/custom/extent_subreport.rb
MariaDB adds 'portion' as a new keyword. This conflicts with is use in one (or more?) of the reports. 
Quoting 'portion' fixes the problem so the report doesn't blow up. 
Without this fix, running resource_list_report using MariaDB blow up in extent_subreport.
After fix it works. It's just a more strict SQL syntax, so it should not affect anything else.
=> mariadb fix for resource_list_report + extent_subreport

public/app/controllers/repositories_controller.rb, public/app/controllers/search_controller.rb, public/app/services/archives_space_client.rb
Cambridge University Library asked me for help with slow performance in their PUI. They have a similar number of records in their ArchivesSpace system, but they have 32 public repositories, whereas in the Bodleian we only have one.
The parts of their PUI which are the slowest are the main keyword search and displaying repository pages. Looking for commonalities, I found the controllers which handle those routes both call `get_types_counts()` in the `ArchivesSpaceClient` class. They do so to populate a variable called `@counts` with a hash of the numbers of records for each record type. That instance variable is used when displaying repository pages, in the template for rendering badges for each record type in the repository. <strike>But I cannot find any other use of `@counts` in the PUI …
=> Fix for PUI slowness caused by unnecessary counting of record types

backend/app/converters/lib/marcxml_base_map.rb
Account for call numbers/identifiers in the MARC 099 tag, as some collection/resource identifiers are stored there as compared to the 090, and export/import doesn't often include 852 tags from a separate holdings record.  The suggested change merely copies an existing subroutine that is focused on the 090, but the copied subroutine is focused on the 099.
None (Zendesk ticket was created)
We are a hosted instance, so I am unable to confirm the code change effect as I don't have a testing environment at my disposal.  The suggested change is merely a copy of an existing code block, but targeted toward a different MARC tag.
=> Update marcxml_base_map.rb to account for 099

frontend/app/controllers/application_controller.rb, frontend/app/views/agents/_form.html.erb, frontend/app/views/notes/_template.html.erb, frontend/spec/selenium/factories.rb, frontend/spec/selenium/spec/restricted_properties_spec.rb
If a user without permission to view agent contact details updates
a record containing contact record/s then that data is lost.
This fix adds a generic restricted properties check to ensure
that sections of a record a user does not have access to are
preserved on update.
=> Prevent loss of agent contact details, fixes #2110

backend/app/converters/ead_converter.rb
This bug was introduced in 2.7.0, when it became compulsory for resources to have at least one language code. To comply, [a new handler](https://github.com/archivesspace/archivesspace/blob/85965cead1451d1b1cddc3d8283c6035d2333c97/backend/app/converters/ead_converter.rb#L268-L282) was added to the EAD importer so that, if there are no _langmaterial_ elements inside the _archdesc/did_, the "und" code is set, to explicitly declare the language of materials to be "Undetermined". However, in doing so it means the `lang_material` object created is added to the `@batch.working_area` queue, in a different context than when they are created in the _langmaterial_ handler. Hence the `lang_material` object is subsequently returned by calls to the [context_obj …
=> Fix for EAD import bug when top-level descriptive identification has container info but no langmaterial

backend/app/converters/lib/eac_base_map.rb, backend/app/converters/lib/marcxml_auth_agent_base_map.rb, backend/app/model/agent_relationship_associative.rb, backend/app/model/agent_relationship_earlierlater.rb, backend/app/model/agent_relationship_family.rb, backend/app/model/agent_relationship_hierarchical.rb, backend/app/model/agent_relationship_identity.rb, backend/app/model/agent_relationship_parentchild.rb, backend/app/model/agent_relationship_subordinatesuperior.rb, backend/app/model/agent_relationship_temporal.rb, backend/app/model/mixins/related_agents.rb, backend/spec/controller_enumeration_spec.rb, backend/spec/model_related_agents_spec.rb, common/db/migrations/145_update_agent_rlshps.rb, common/locales/en.yml, common/locales/enums/en.yml, common/schemas/abstract_agent_relationship.rb, common/schemas/agent_family.rb, common/schemas/agent_relationship_parentchild.rb, frontend/app/views/related_agents/_template.html.erb, frontend/app/views/related_agents/_template_merge.html.erb, frontend/app/views/related_agents/_template_merge_target.html.erb, frontend/app/views/related_agents/_template_required.html.erb
First pass of additional related agents enhancements, including the following:
- Add two new form fields for `specific_relator` (optional editable controlled value list with no default) and `relationship_uri` (optional text string);
- Update marc_auth import map and eac import map to send appropriate content to those new fields;
- Update staff form fields to incorporate new fields;
- Update relationships models to point to an existing db table;
- Update new db migration (145) to add new fields, migrate relator term from a string to an id (inline with prior refactoring work https://github.com/archivesspace/archivesspace/commit/e2f2cdb5d94cd79123d464f1d74ad2a8b95b5911), and make existing relator term values readonly;
- Update some tests and add new test to confirm specific relator …
=> ANW-429 related agents enhancements

_yard/API.erb
Currently, the API docs lack information covering the use of SOLR-backed search routes, which has been a persistent source of confusion among API connsumers.  As part of the Ad-Hoc API Docs subgroup, I've written some generic info covering these routes and added it to the API docs. 
This is at "rough draft" stage, I would expect feedback and to rework and improve it before submission.
=> Add generic search route docs to API docs

backend/app/converters/lib/marcxml_auth_agent_base_map.rb, backend/spec/lib_marcxml_auth_agent_converter_spec.rb
Adds additional cleaning of trailing characters to the new MARC auth import, including removing the unnecessary comma at the end of the $a when a $d is present.
In comparing the new auth imported to the old/shared bib importer, I noticed several other areas where trailing punctuation was previously being cleaned up.  I copied over these changes to keep the new importer as close as possible to the old/road tested importer, though more work will likely be necessary in the future.
https://archivesspace.atlassian.net/browse/ANW-1225
=> ANW-1225: Clean trailing characters from MARC auth import

backend/app/converters/lib/eac_base_map.rb, backend/app/converters/lib/marcxml_auth_agent_base_map.rb
Resubmission of #2141 
Minor tweak to EAC and MARC auth import to ensure newly created/imported related agents aren't set to publish by default.  Rather, related agents newly imported via MARC/EAD will follow publication user/repo/global preferences.
=> ANW-429: Don't publish rel agents by default

frontend/app/views/agents/_linker.html.erb, frontend/app/views/agents/_merge_dropdown.html.erb
Agents of different types cannot be merged, so the typeahead should only show agents of the same type.
Also discovered that the `creatable_types` block was running even when `hide_create` was set due to the position of the `<%end%>`.  Moved the closure down so `creatable_types` doesn't choke when an single `allowable_types` is sent via the merge_dropdown.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1217
=> ANW-1217 Only show same type agents in merge dropdown

public/app/controllers/agents_controller.rb
map will return `nil` for all values in `RETAINED_PARAMETERS` that are not keys in `params`, which makes `Hash` emit a warning:
```
webapp/WEB-INF/app/controllers/agents_controller.rb:100: warning: this causes ArgumentError in the next release
webapp/WEB-INF/app/controllers/agents_controller.rb:100: warning: wrong element type NilClass at 1 (expected array)
webapp/WEB-INF/app/controllers/agents_controller.rb:100: warning: ignoring wrong elements is deprecated, remove them explicitly
```
Using the array's `compact` method  before casting eliminates `nil` values and the warning.
Confirmed fix in irb and ran the public:test suite to completion.
=> avoid passing nil elements to Hash

frontend/app/assets/javascripts/related_agents.crud.js, frontend/spec/selenium/spec/agents_spec.rb
Load related agents on demand when editing an agent record when there are more than four relationships.
Added the "tooMany" check to the agents.crud.js initializer following the pattern used in notes.crud.js
https://archivesspace.atlassian.net/browse/ANW-1210
Added two tests to the agent selenium spec.
=> ANW-1210 hide related agent subrecords when there are more than 4

frontend/app/helpers/search_helper.rb, frontend/app/views/assessment_attributes/edit.html.erb, frontend/app/views/groups/index.html.erb, frontend/app/views/locations/batch.html.erb, frontend/app/views/oai_config/edit.html.erb, frontend/app/views/users/index.html.erb, frontend/config/locales/en.yml, frontend/config/locales/es.yml, frontend/config/locales/fr.yml, frontend/config/locales/ja.yml, frontend/vendor/assets/javascripts/bootstrap-tagsinput.js, plugins/lcnaf/frontend/locales/en.yml, plugins/lcnaf/frontend/locales/fr.yml, plugins/lcnaf/frontend/views/lcnaf/index.html.erb
Several small accessibility improvements to issues discovered during post-2.8.1 release scanning.
Fixes several instances of the following types of issues:
- Adds sr-only table headings to several "Action" columns;
- Ensures translation values are used instead of hardcoded English (incidentally discovered during other work);
- Ensures "Close" buttons have sr-only text (not just a conveying their purpose through a "close" gif);
- Adds appropriate alt-text to spinner/loading gif;
- Adds some aria-labels to complex form fields (assessment attributes); and,
- Adds a fieldset/legend to LCNAF plugin import source selection.
Also includes a small change to `frontend/vendor/assets/javascripts/bootstrap-tagsinput.js` to ensure the resulting `input` has an id available for label assignment.  (This …
=> Staff UI accessibility enhancements

public/app/views/agents/_related_agents.html.erb
Small tweak to the sidebar display of related agents in the PUI.  If an (optional) `specific_relator` is present, show that, else use the (required) `relator` term.  Also, remove the agent type from the parens.
https://archivesspace.atlassian.net/browse/ANW-1215
=> ANW-1215: Show specific relator if present in PUI

backend/app/converters/lib/eac_base_map.rb
When parsing a person related agent name, strip the space after a comma so there is (hopefully) no leading whitespace in 'rest_of_name'.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1228
=> ANW-1228 Related agents rest of name whitespace fix

backend/app/exporters/serializers/eac.rb, backend/spec/export_eac_spec.rb
Update EAC export to do the following:
- Map ArchivesSpace `relator` term to a valid `cpfRelationType` attribute;
- Export `relationship_uri` to `xlink:arcrole` attribute if available; and, 
- Export `description` to `descriptiveNote/p` if available.
https://archivesspace.atlassian.net/browse/ANW-1226
New tests added, existing tests passing.
=> ANW-1226: EAC export related agents tags/attributes

backend/app/exporters/serializers/marc_auth.rb, backend/spec/agent_spec_helper.rb, backend/spec/export_marc_auth_agent_spec.rb
Updates MARC authority record exports to match the following:
For 500/510/511 subfield 'i':
- if specific_relator, value of specific relator;
-  if no specific_relator, but description, value of description;  otherwise, 
- value of relator
For 500/510/511 subfield 'w':
-   if relator = is_earlier_form_of, `a`;
-  if relator = is_later_form of, `b`;
-  if specific_relator = Acronym, `d`;
-  if specific_relator = Musical composition, `f`;
-  if specific_relator = Broader term , `g`;
-  if specific_relator = Narrower term, `h`;   otherwise, 
- `r`
Also, corrected bug wherein subfields 'w' and 'i' were being created for 100/110/111 and 400/410/411 tags. 
https://archivesspace.atlassian.net/browse/ANW-1227
Several new tests added, including a helper method to setup some enumeration values for …
=> ANW-1227: MARC export related agents 'w' and 'i' subfs

backend/app/converters/ead_converter.rb, backend/app/exporters/examples/ead/at-tracer.xml, backend/spec/lib_ead_converter_spec.rb
Modifies EAD importer to support `<langmaterial>`s that include multiple `<language>` elements.  Previously, all but the first `<language>` was skipped on import.  This resolves an issue wherein numerous ASpace language_and_script records with a language value of 'undetermined' were improperly created.
Also modifies/adds backend tests.
https://archivesspace.atlassian.net/browse/ANW-1173
Existing tests passing, new tests added.
=> ANW-1173 EAD import should support multiple <langmaterial> <language>s

frontend/app/views/shared/_lightmode_toggle.html.erb
The new lightmode toggle button on an existing agent's toolbar was missing a label.  This updates the existing `<span>` to a `<label>` for accessibility purposes.
https://archivesspace.atlassian.net/browse/ANW-1246
WAVE tool demonstrating missing label:
=> ANW-1246 Assign label to lightmode toggle button

reports/accessions/accession_names_subreport/accession_names_subreport.rb
1 line chang in accession_name_subreport to quote new reserved word 'function'  
simple syntactically valid change that should have no effect in environments that don't display the problem. 
accession reports fail running under MySQL 8.0 + 
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1200
Tested under MariaDB 10.x, which does not have that reserved word, but change is still proper SQL syntax so it works. Waiting for confirmation from users with MySQL 8.0 who reported the issue. But from the error message ( and experience with past SQL errors ) I'm certain this is the issue. 
- [x ] My change requires a change to the documentation.
- [x ] I have …
=> anw-1200  : function became reserved word in MySQL 8.0.1

backend/app/controllers/search.rb, backend/app/model/search.rb, backend/app/model/solr.rb, public/app/controllers/concerns/searchable.rb
Hey there,
This is a shot at addressing https://archivesspace.atlassian.net/browse/ANW-1240, where a "Search within results" query would end up returning more hits than the original query.
As described in that ticket, the root cause seems to be that ANDing these extra restrictions onto the main query flips it back to the standard query parser, which behaves quite differently to the original one.  This patch extends the search API to let you provide additional queries to be used as filters (which are parsed with edismax in the usual way), then uses those to express the search within results restrictions.
=> ANW-1240 Add a new `filter_query` search parameter and use it for "Search within results"

frontend/app/controllers/agents_controller.rb, frontend/config/locales/en.yml, frontend/spec/selenium/spec/agents_spec.rb
This fix adds a check and cleanly fails with an error on screen if the user tries to merge agents that have a relationship.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-913
Manual testing and added selenium test.
=> ANW-913: Show warning when trying to merge 2 agents that have a relationship

public/app/models/archival_object.rb
Adds back resource title and identifier to PUI archival object citations (accidentally removed during #1830 ).
https://archivesspace.atlassian.net/browse/ANW-1219
=> ANW-1219 Add resource title and identifier to ao citations

frontend/app/helpers/aspace_form_helper.rb, frontend/spec/selenium/spec/accessions_spec.rb, frontend/spec/selenium/spec/classifications_spec.rb, frontend/spec/selenium/spec/notes_spec.rb, frontend/spec/selenium/spec/resources_spec.rb, frontend/vendor/assets/javascripts/bootstrap-combobox.js
Minor changes to `aspace_form_helpers` and `bootstrap-combobox` to provide accessibility enhancements to staff side comboboxes (e.g. language and script subrecords).  Ultimately, this ensures a label is provided to both the typeahead text input as well as the dropdown, with some aria elements demonstrating the link between the input and dropdown  loosely modeled off of the recommendations at https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html 
While I generally wouldn't want to make changes to vendor assets like this, these additions merely add aria attributes and should be more or less noncontroversial/low risk.
Additional enhancements - most notably changing focus to the dropdown values/dropdown menu to enable screenreader use - are still …
=> ANW-1248: Improve combobox accessibility

backend/app/converters/ead_converter.rb
Very minor addition to #2168 to ensure that markup such as:
`<langmaterial><language langcode="eng"/> <language langcode="ger"/></langmaterial>`
doesn't fail on import because it tries to create a note with whitespace-only content.
https://archivesspace.atlassian.net/browse/ANW-1151
https://archivesspace.atlassian.net/browse/ANW-1173
Able to import EAD with the above snippet without receiving:
```ValidationException: {:errors=>{"lang_materials/2/notes/0/content"=>["At least 1 item(s) is required"]}, :import_context=>"<c class=\"cdata\" id=\"ref37\" level=\"file\"> ... </c>"}>```
=> ANW-1151, ANW-1173 Don't try to create empty langmaterial note

.github/workflows/backend.yml, .github/workflows/build.yml, .github/workflows/codescan.yml, .github/workflows/frontend.yml, .github/workflows/indexer.yml, .github/workflows/public.yml, Dockerfile, docker-compose.yml
Extend test workflows to include Java 11 and update Docker image to 11.
Have been using Java 11 with ArchivesSpace for at least a couple of months, without problems, so seems like a good next step is to incorporate it into the test workflows and Docker for the test server deployments. Can build and run ArchivesSpace (`docker-compose build && docker-compose up`).
=> Bump Docker to java 11 and include java 11 in tests

common/db/migrations/utils.rb
Specifically: if the name_source enumeration already had the value snac then the migration would fail.
=> Fixes 140 migration by checking for existing enum value before insert

frontend/app/assets/javascripts/jobs.show.js
We really only need to append a new <div> when there's something to show.  Otherwise we keep adding blank lines and scroll away from the real action.
(This is a tiny bug that's been around for ever.  Finally annoyed me enough to fix...)
=> Avoid adding blank lines on each poll loop in job output display

backend/app/converters/ead_converter.rb
Fixes non-display in the public user interface of _dimensions_ elements when imported from EAD into a dimensions note. For example:
```
<physdesc>
<dimensions>16 1/2 × 12 in.</dimensions>
</physdesc>
```
Because the _physdesc_ has no _extent_ child, the `make_nested_note()` method is called. There is no  `audience="internal"` attribute, so the multi-part note created will have its publish property set to true. But not the publish property of the subnote containing the actual content. This pull request sets the publish property on both, as is the case in the other instances in ead_converter.rb where multi-part notes are created.
The `make_nested_note()` method is only called when creating dimensions notes. Possibly it shouldn't be creating multi-part notes, because in EAD 2002 the …
=> Set publish on subnotes the same as parent multi-part note in EAD importer

backend/app/model/mixins/rights_restriction_notes.rb, backend/spec/model_restriction_spec.rb, common/locales/en.yml, common/locales/es.yml, common/locales/fr.yml, common/locales/ja.yml, common/validations.rb
Currently, if a user supplies a restriction start/end date that doesn't conform to yyyy-mm-dd pattern the staff interface throws an unhelpful Server Error.  To be machine actionable, these dates need to be entered in yyyy-mm-dd format, but there is no validation present to relay this to the user.  This adds such a validation to `validations.rb`.
Also includes error translations for all languages (google translate) and 2 new tests.
https://archivesspace.atlassian.net/browse/ANW-251
Before fix:
After fix:
=> ANW-251 Provide error for invalid restriction date

backend/app/converters/lib/marcxml_bib_base_map.rb
When importing MARCXML the current import map looks for a 300$a that looks something like `100 linear feet`.  It should also support $a's that only include numbers such as `100` or, even, `1,000`.  This minor change to the existing regex does that.
https://archivesspace.atlassian.net/browse/ANW-1174
=> ANW-1174 Import MARC extents that include only numbers and commas

backend/app/converters/lib/marcxml_bib_base_map.rb
This change fixes an issue where MARC 730 field (Added Entry, Uniform Title) was being silently ignored during MARCXML bib record import. It implements field 730 import according to the same logic as 130 and 630, as specified in the JIRA ticket.
* https://archivesspace.atlassian.net/browse/ANW-1083
* Backend unit tests passed on Ubuntu 20.04.2
- Ideally, the [MARCXML Import / Export Map](https://archivesspace.org/wp-content/uploads/2016/08/MARCXML-Import-Export-Mapping-20130715.xlsx) spreadsheet (linked from the [Migration Tools and Data Mapping](https://archivesspace.org/using-archivesspace/migration-tools-and-data-mapping) page) would be updated: it currently includes field 630, but is missing 130 and 730. I'm happy to make this change if anyone has guidance on the best means to update …
=> ANW-1083: MARCXML import field 730

backend/app/model/mixins/relationships.rb, backend/spec/controller_merge_request_spec.rb, common/db/migrations/146_tc_link_cleanup.rb
#1764 introduced a bug wherein a user that merged one or many top containers linked to archival records (accessions, resources, aos) into another top container that was unassociated/unlinked to any archival records, the archival record(s) that were linked to the now deleted top container(s) were left with `top_container_link_rlshp` records that were corrupt (no top container present in the db) making it impossible for users to view those previously linked records in the staff UI and/or API.  
This PR fixes the underlying code that created the corrupt relationship records (change to `mixins/relationships.rb`), adds tests to confirm the fix, and adds a db migration to attempt to resurrect the records that became un-viewable/editable as a result of these silently failing merges.  
The 146 …
=> ANW-1253: Bugfix for merging linked top containers into unassociated top container

frontend/app/assets/stylesheets/archivesspace/form.less, frontend/app/views/notes/_template.html.erb
Hi there,
This is just a minor thing, but I notice the "Raw" view of notes text doesn't show blank lines, which has the effect of merging multi-paragraph text (like bioghist) into one giant block of text.  "Formatted" does look better, but since "Raw" is the default I thought it might be nice to improve it a little.
I've just added a CSS class to note text in the read-only view, and added a `white-space: pre-line` to get those line breaks back.  Here's the before shot:
and the after:
=> Show line breaks in the read-only raw view for note text

backend/app/model/mixins/sort_name_processor.rb, backend/spec/model_agent_corporate_entity_spec.rb, backend/spec/model_agent_family_spec.rb, backend/spec/model_agent_person_spec.rb, backend/spec/model_agent_software_spec.rb
agents
Adding dates field from name form to sort name string for software agents. This is the behavior for the other agent types so this brings.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1036
Manual testing, unit tests
=> ANW-1036: Adding dates field from name form to sort name string for software

backend/app/converters/lib/marcxml_auth_agent_base_map.rb, backend/app/exporters/examples/marc/authority_john_davis_2.xml, backend/spec/lib_marcxml_auth_agent_converter_spec.rb
If the 035 starts with `(DLC)` then the MARCXML Auth importer should set the source to `naf` and type to `loc`.
https://archivesspace.atlassian.net/browse/ANW-1259
=> ANW-1259 MARCXML Auth import 035 prepended with (DLC) source and type

backend/spec/controller_agent_software_spec.rb, backend/spec/controller_exports_spec.rb, backend/spec/factories.rb, backend/spec/model_agent_software_spec.rb, common/locales/en.yml, common/validations.rb
Software agents shouldn't have some of the subrecords the other agents have. These validation changes back up the removal of certain forms from the public interface.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1232
Manual and unit testing.
=> ANW-1232: JSON validations for software agents excised fields

backend/app/converters/ead_converter.rb, backend/app/exporters/examples/ead/at-tracer.xml, backend/spec/lib_ead_converter_spec.rb
Updates EAD importer to map <persname>, <famname>, or <corpname> role attribute to ArchivesSpace's linked agent relator field.
Also updates tests (including a little cleanup) and makes on minor tweak to EAD example file to support test changes.
Note: EAD import/export map will need to be updated to reflect this change.
https://archivesspace.atlassian.net/browse/ANW-814
Tests updated and passing.
=> ANW-814 Map EAD role attribute to linked agent relator

backend/app/exporters/models/marc21.rb, backend/spec/export_marc_spec.rb
For the purposes of MARC export, if an agent linked to a resource is linked as a subject (600/610) and if it has certain types of terms provided with that linkage, then $0 should not be exported.
Note: Existing MARC export mappings will need to be updated.
https://archivesspace.atlassian.net/browse/ANW-825
Tests reworked, new test provided.
=> ANW-825: Don't include $0 in MARC export if $v, $x, $y, or $z

backend/app/model/rights_restriction_type.rb, indexer/app/lib/indexer_common.rb
1. Conversion of set to array in indexer when the field value was
an array led to a nested array with contents put into a string.
Fixed by ensuring the array is flattened.
2. Update to use correct schema prop: local_access_restriction_type
Create a record with a note type "Conditions Governing Access" and select one or more "Local Access Restriction Type" options. Go to controlled value lists "Local Access Restriction Type" and confirm that there are related items.
=> Fix local access restriction enum search

backend/app/exporters/serializers/eac.rb, backend/spec/export_eac_spec.rb
The existing agent date map for EAC exports doesn't include support for standardized dates. This updated map adds this.
https://archivesspace.atlassian.net/browse/ANW-1264
=> ANW-1264: Implementing updated EAC export map for agent dates

backend/app/converters/accession_converter.rb, backend/spec/lib_accession_converter_spec.rb
Update to the accessions CSV importer to map `agent_contact_fax`, `agent_contact_telephone`, and `agent_contact_telephone_ext` to repeating  agent contact telephone subrecords.
When telephones were removed from the agent_contact subrecord into their own repeating subrecords the accessions CSV importer wasn't updated to reflect this change.  This PR remedies that.
Note: The existing import mapping will need to be updated to reflect this change.
https://archivesspace.atlassian.net/browse/ANW-90
Existing tests pass, new test added.
=> ANW-90 Map telephone and fax to agent contact telephones subrecord

frontend/app/assets/javascripts/jquery.tokeninput.js, frontend/app/assets/javascripts/linker.js, frontend/app/views/accessions/_linker.html.erb, frontend/app/views/agents/_linker.html.erb, frontend/app/views/classification_terms/_linker.html.erb, frontend/app/views/classification_terms/_record_linker.html.erb, frontend/app/views/classifications/_linker.html.erb, frontend/app/views/classifications/_record_linker.html.erb, frontend/app/views/container_profiles/_linker.html.erb, frontend/app/views/digital_objects/_linker.html.erb, frontend/app/views/events/_record_linker.html.erb, frontend/app/views/location_profiles/_linker.html.erb, frontend/app/views/locations/_linker.html.erb, frontend/app/views/repositories/_linker.html.erb, frontend/app/views/resources/_linker.html.erb, frontend/app/views/shared/_linker.html.erb, frontend/app/views/subjects/_linker.html.erb, frontend/app/views/top_containers/_linker.html.erb
Continuation of work started in #2182 to improve accessibility of staff side comboboxes, specifically linker boxes.  Includes small fixes to accomplish the following:
- identifying/labeling the comboboxes and component parts (listbox, combobox, options);
- ensuring the dropdown/autocomplete options are selectable by the keyboard;
- indicating when the combobox dropdown is expanded/collapsed; 
- indicating which dropdown option is currently selected; and,
- indicating which option is selected and, when selected, that screenreaders do not trip over the text highlighting (`<b>`) used in the option text.
https://archivesspace.atlassian.net/browse/ANW-1265
Fully expanded empty accession record before:
Fully expanded empty accession record after:
=> ANW-1265 Improve linker box accessibility

backend/app/exporters/models/marc21.rb, backend/spec/export_marc_spec.rb
Updates MARC XML export for 1xx, 6xx, and 7xx to do the following:
- $e --> translated value of `relator` if `relator` and a translation is available;
- $4 --> code/key value of `relator` if `relator`
Also includes some changes to tests to reflect the above changes.  Also, fixes the fact that existing tests were looking for `name['relator']` which is always going to be `nil` because a relator is not part of a name record, but instead the `linked_agents` record.
Note: MARC XML map will need to be updated to reflect this change.
https://archivesspace.atlassian.net/browse/ANW-1047
New tests added, tests updated.
=> ANW-1047 Update 1xx, 6xx, and 7xx to export both $e and $4 if relator

public/app/models/record.rb, public/spec/factories.rb, public/spec/features/resources_spec.rb
Adding date certainty to date display in PUI for clarity
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-861
In browser manual testing and integration testing
=> ANW-861: Show date certainty in parens next to date in PUI

public/app/models/record.rb, public/app/models/request_item.rb
Location information may be sensitive and shouldn't appear in the
PUI request form or emails. The top container uris can be used to
find the location w/o exposing it outside of the ArchivesSpace SUI.
=> ANW-853 Remove location info from PUI request form / emails

frontend/app/views/custom_report_templates/_form.html.erb, frontend/app/views/custom_report_templates/index.html.erb
Just placeholders for help links. 
**NOTE**: Had to use an existing link to make the question mark show up so I used `accession_basic_information`.
=> ANW-1069-help-links

backend/app/converters/accession_converter.rb
Small addition to #2223 in response to testing feedback.  When using the Accession CSV importer, don't attempt to import a telephone subrecord when only a telephone extension, but no number, is provided.  Telephone number is a required element in the telephone subrecord.
=> ANW-90 don't attempt to import extension without telephone number

frontend/app/assets/javascripts/rde.js, frontend/spec/selenium/spec/rde_templates_spec.rb
Changes the way RDE.JS applies column order and visibility, so that the first pass on order happens before any visibility state is loaded. Also appends destruction / reinit of the multiselect widget to the template loader, so the multiselect state matches the loaded template.
ANW-194 AND-206
Added explicit test for ANW-194. Tested the ANW-206 could not be reproduced.
=> ANW-194 ANW-206 synchronize RDE templates and multiselect

backend/app/model/enumeration.rb, backend/app/model/extent.rb, backend/app/model/mixins/active_association.rb, backend/app/model/mixins/touch_records.rb, backend/spec/mixin_active_association_spec.rb, backend/spec/mixin_touch_records_spec.rb
Related items relies on search, however the indexer was not being
updated for records "related" to the referenced extents. An active
association mixin has been added to make it convenient to determine
the parent record of the extent and bump the mtime for re-indexing.
The mixin could also be applied to other records types and used for
refactoring in the future where if / case statements are being used
to find an associated record by non-null id.
There is more detail on use cases: ANW-1278
There is also some cleanup for the gnarly touch records mixin spec.
=> ANW-147 Merging extent controlled values loses related items

backend/app/exporters/models/marc21.rb, backend/spec/export_marc_spec.rb
ANW-820 pinpoints two problems with the punctuation of 110/610/710 MARCXML exports:
- Punctuation should not be added to 610$a when $v, $x, $y, or $z are next, and,
- Double punctuation (`,.`) should not be added to 610$a when $e comes next and the only punctuation should be a comma.
However, because so much of this code is shared (and so much of it really deserved some consolidation/refactoring), some additional changes are made in this PR, including:
- Removing the terms variable from the 7xx constructor (7xx's don't get terms);
- Breaking duplicative bits of code out into new methods (`handle_agent_terms`, `apply_terminal_punctuation`, and `prepare_role_subfields`);
- Reordering 100/600/700 $g and $q and wrapping them in parens (per pdf attached to the JIRA); and,
- Updates to tests …
=> ANW-820 MARCXML export 1xx, 6xx, 7xx punctuation updates

backend/app/exporters/models/marc21.rb, backend/spec/export_marc_spec.rb
Previously, the MARC exporter would only set position 6 of 008 to `s` if the resource had a level of "item" AND a date type of single.  This change updates it so that `s` is set based only on the date type of single, and removes the resource level check, per the JIRA ticket.
https://archivesspace.atlassian.net/browse/ANW-143
=> ANW-143 MARCXML 008 position 6 should be 's' when date type is single

public/app/views/shared/_skipnav.html.erb
The shared skipnav partial was attempting to show skiplinks to search actions since the classifications terms show pages do have `@search` defined, however, like archival objects, no search actually appears on this page.  As such, the skipnav was linking to a broken link.  This had previously been handled for archival objects  by checking for `action_name == 'inventory'`, so I just extended this to include `action_name == term` as well.  (This is unambiguous as term isn't defined in any other controllers.) 
https://archivesspace.atlassian.net/browse/ANW-1277
Before:
After:
=> ANW-1277 Don't display skiplinks on classification terms pages

public/app/assets/javascripts/search.js.erb, public/app/views/shared/_search.html.erb, public/spec/features/search_spec.rb
instead of submitting when pressing enter key in focus
Bugfix for unexpected UI behavior
https://archivesspace.atlassian.net/browse/ANW-665
=> ANW-665: Bugfix for public interface search additional fields disappearing

backend/app/model/archival_object.rb, backend/spec/model_archival_object_spec.rb
Include date certainty in display string for archival objects
https://archivesspace.atlassian.net/browse/ANW-861
=> ANW-861: Include date certainty in display string for archival objects

backend/app/model/large_tree.rb, backend/app/model/large_tree_resource.rb, common/config/config-defaults.rb, frontend/app/assets/javascripts/tree_renderers.js.erb, frontend/spec/selenium/spec/resources_spec.rb, public/app/assets/javascripts/tree_renderer.js.erb, public/config/locales/en.yml, public/config/locales/es.yml, public/config/locales/fr.yml, public/config/locales/ja.yml, public/spec/rails_helper.rb, public/spec/spec_helper.rb
These changes resolve the issue raised in JIRA issue ANW-1196 - a desire to be able to view resource and archival object identifiers in the PUI collection organisation tree. This allows for easier navigation within large collections, especially where runs of sibling archival objects have similar (or even identical) titles. The approach used was inspired by the University of Denver's tree_component_id plugin (https://github.com/duspeccoll/tree_component_id), so I have also added the option to put resource and archival object identifiers into the staff interface tree (in their own section, rather than being added to the container summary). This should mean that there is no need for this plugin in the future. As suggested by @cdibella in the JIRA issue, this identifier display in the PUI and …
=> ANW-1196: optional display of identifiers in record trees

backend/spec/export_marc_spec.rb
Part of the reason backend tests seem to be failing more often.  #2246 changed how the 008 handled date strings, but this test wasn't fully updated to reflect that change.  Rather, since the test data `@marc1` didn't have a particular type of date explicitly assigned to it, it was sometimes inclusive/bulk and sometimes single, which led to randomly failing tests.  This fixes it by ensuring `@marc1` always has an inclusive date attached.
=> Ensure @marc1 always has an inclusive date

public/app/models/resource.rb, public/app/views/shared/_request_hiddens.html.erb
forms as well
HTML entities are not being escaped properly in the PUI in the citation and request forms.
https://archivesspace.atlassian.net/browse/ANW-980
https://archivesspace.atlassian.net/browse/ANW-1011
=> ANW-1011, ANW-980: Updated fix to resolve ANW-980 and escape tags in request and citation

frontend/app/controllers/top_containers_controller.rb
Prepends columns for resource / accession & series links && removes
the title field which packs all the column data into a single field..
=> ANW-695 top container csv links

plugins/lcnaf/frontend/spec/lcnaf_client_spec.rb
I've wanted to do this for a while, so finally took the chance to update these.  This fixes all lcnaf plugin tests so that they are now passing (and actually testing things) in a post-3.0 world.  
TO-DO: We should probably discuss adding a github workflow to run `frontend:test:plugin` so that these continue to get tests regularly if plugins (or at least this plugin) is going to remain in core for any period of time.  Currently, the lcnaf plugin is the only plugin in the core code that includes tests.
=> Post-3.0 updates to LCNAF plugin tests

frontend/app/controllers/application_controller.rb, frontend/spec/selenium/spec/instances_and_containers_spec.rb
#1764 added the ability to batch merge top containers from the manage top containers page.  Based on the existing `handle_merge` method in application_controller, this meant a successful merge resulted in a redirect to the surviving top container page.  ANW-1119 requested this be changed to redirect back to the Manage Top Containers screen post-merge.
https://archivesspace.atlassian.net/browse/ANW-1119
Updated existing test to confirm redirect to Manage Top Containers.
=> ANW-1119 Redirect to top containers index page post merge

.gitignore, build/build.xml, build/solr_home/collection1/conf/_rest_managed.json
Set appconfig data directory separately for dev / test
Added pointers for parts to update when embedded solr removed
Removed reset task (shouldn't be needed now tasks are more consistent)
Remove committed file (_rest_managed.json) added pre gitignore
Minor bonus: keeps the build directory better organized and consistent
```txt
build/dev/
├── archivesspace_demo_db
│   ├── log
│   ├── seg0
│   └── tmp
├── indexer_pui_state
├── indexer_state
├── solr_home
│   └── collection1
│       ├── conf
│       └── lib
└── solr_index
└── index
build/test
├── archivesspace_demo_db
│   ├── log
│   ├── seg0
│   └── tmp
├── indexer_pui_state
├── indexer_state
├── solr_home
│   └── collection1
│       ├── conf
│       └── lib
└── solr_index
└── index
```
=> Updates for isolating dev / test env build files

common/aspace_i18n.rb, frontend/config/application.rb
Rather than risk breaking anything by refactoring load path loading, just tack on a reorder at the end. But they should be refactored and normalized between frontend and public. 
Solves the problem of local locale overrides not affecting the staff application.
https://archivesspace.atlassian.net/browse/ANW-1222
It is hard to test this - perhaps we need a separate build task for testing plugins.
=> force plugin load paths to the back

common/db/migrations/142_update_existing_tables_for_agents.rb
Corrects issues introduced in original 142 migration wherein `notes` that contained data were dropped from the `agent_contact` table instead of being migrated to the `notes` tables.
=> Don't drop agent contact notes on migration

frontend/app/assets/javascripts/agents.crud.js
Don't hide the 'title' field when the linked agent is a subject.
https://archivesspace.atlassian.net/browse/ANW-530
Manually
=> allow a title field if the agent is a subject or creator

public/config/initializers/locales.rb
Make sure any frontend paths in the public I18n path are at the front of the I18n load path.
Ensures that frontend translation will not clobber public translation. 
https://archivesspace.atlassian.net/browse/ANW-1222
Tested conflicting translation in plugin/local frontend and public directories.
=> push frontend locales to the front of the public I18n stack

public/app/views/objects/show.html.erb
This is a fix for a bug I introduced in #1831. I thought, because I was adding code inside this existing if statement...
```
<% if !@result.instance_of?(DigitalObject) || @has_children %>
```
...that I didn't need to test that the object being rendered is not a digital object. But, because we don't use digital object components where I work, I had forgotten that if those are present then `@has_children` is true. In which case, it will cause ``undefined method `resource_uri'`` errors.
It only occurs when `AppConfig[:pui_search_collection_from_archival_objects]` is set to true in config.rb (by default it is false) which is probably why it wasn't picked up in testing.
To fix this, I have added an extra check that the object is an archival object, thus ensuring `@result.resource_uri` is …
=> Ensure object being viewed is an archival object

common/config/config-defaults.rb, frontend/app/views/agents/_merge_dropdown.html.erb, frontend/spec/selenium/spec/agents_spec.rb
These changes are backwards compatible with the embedded Solr.
1. Use q.op for default AND behavior.
Prefer default `'q.op' => 'AND"` to `'mm' => '100%'` because latter can "override" the outcome of generated queries (with Solr > 4) causing them to fail.
For example, using Solr 8.8, suppose that accession id 1 & 2 exist (query generated by the PUI):
```txt
http://localhost:8984/solr/archivesspace/select?q=(id%3A(%22\%2Frepositories\%2F2\%2Faccessions\%2F1%22)+OR+id%3A(%22\%2Frepositories\%2F2\%2Faccessions\%2F2%22))&wt=json&csv.escape=\&csv.encapsulator=%22&csv.header=true&start=0&rows=500&fq=-exclude_by_default%3Atrue&fq=-types%3Apui_only&fq=suppressed%3Afalse&facet=true&mm=100%25
{
"responseHeader":{
"status":0,
"QTime":0,
"params":{
"mm":"100%", …
```
=> Updates to pass tests with external Solr (v8)

frontend/app/views/agents/_contact_details.html.erb, frontend/app/views/notes/_form.html.erb
Following changes in #2276 and proposed changes in #2277, return note subrecord to the agent contact section of a repository page.
This required updating the `nested_note_jsonmodel` name so that the disabled remove button on the top-level agent contact, wasn't also incorrectly being applied to the embedded notes as well.
Continuation of https://archivesspace.atlassian.net/browse/ANW-1191
Existing tests pass.
=> ANW-1191 Returns contact notes to repository records

reports/assessments/assessment_linked_records_subreport/assessment_linked_records_subreport.rb
This minor pull request adjusts the output of the assessment linked records subreport to resolve an apparent bug. Previously, if an archival object appeared in the assessment record list report, its record id would be given as `archival_object_{root_record_id}` rather than `archival_object_{id}`, and its identifier would be given as its root record's identifier. This meant that the identifier didn't match up with the title given, and the record id was inevitably for a completely different record.
This issue was spotted during local testing and hasn't been submitted as a JIRA Ticket or GitHub issue.
Locally tested and backend and frontend test suites run (though this functionality didn't appear to be covered by any tests).
=> Refer to archival object's id and identifier instead of root record's

public/app/assets/stylesheets/archivesspace/aspace.scss
Sets the a:hover and a:focus color on the PUI to ensure adequate color contrast in the footer (and other non-white background areas).  Contrast is now 8:1 in the footer.
https://archivesspace.atlassian.net/browse/ANW-1321
=> ANW-1321 Ensure color contrast in PUI footer on hover/focus

public/app/assets/stylesheets/application.scss, public/app/assets/stylesheets/archivesspace/variables.scss
Overrides the default `$input-color-placeholder` to darken the PUI placeholder text to achieve desired color contrast on Firefox.  To accomplish this without altering bootstrap files themselves, the load order of the sass files in `application.scss` had to be corrected so that our overrides come first.  This required some additional cleanup and reorganization, namely removing unnecessary/previously unused styling that was in `variables.scss`, in order to only change/update the placeholder text (and not additional elements).
Note: The "4.5:1 contrast ratio on hover or focus" issues attached to this JIRA were previously resolved with #2317 .
https://archivesspace.atlassian.net/browse/ANW-1311
=> ANW-1311 Darken placeholder text on PUI

solr/Dockerfile, solr/_default-schema-8.8.min.xml, solr/_default-schema-8.8.xml, solr/_default-solrconfig-8.8.min.xml, solr/_default-solrconfig-8.8.xml, solr/minify.sh, solr/schema-8.8.min.xml, solr/schema-8.8.xml, solr/solrconfig-8.8.min.xml, solr/solrconfig-8.8.xml
Probably not the final form but this puts everything together in one place while we review. This just:
- Adds reference config defaults from Solr v8
- Updates `luceneMatchVersion`
- Resolves deprecations reported by Solr log
Tests are passing. No impact on embedded Solr so this is just for devs.
=> Solr cfg upd 8

common/asutils.rb
The default value for the `AppConfig[:plugins_directory]` is:
but if you uncomment that line in the standard config.rb, it fails to
find your plugins.  Someone hit that here:
https://groups.google.com/g/archivesspace/c/22bOn1sou0s
The `ASUtils.plugin_base_directory` method was mistakenly interpreting
relative paths against the backend directory, rather than the
ArchivesSpace base directory.
=> Handle relative paths for `AppConfig[:plugins_directory]`

backend/app/model/mixins/agent_manager.rb, backend/spec/model_agent_person_spec.rb, frontend/app/views/linked_agents/_show.html.erb, frontend/spec/selenium/spec/accessions_spec.rb, frontend/spec/selenium/spec/resources_spec.rb
The `linked_agent_roles` method in `backend/app/model/mixins/agent_manager.rb` behaved differently when run in mysql vs. Derby.  In Derby, the method returned a `nil` leading to the error reported in JIRA when creating/saving/viewing a record (resource, accession, etc.) with a rights_statement that included one or many linked agents since agents linked through rights statements subrecords will (rightly) never have a role.  The resolves the reported issue when running in Derby.
Also:
- Added several tests;
- Corrected a minor issue with the show-only view of linked agents in rights statements so that a translation missing error wasn't provided for role-less linked agents.
https://archivesspace.atlassian.net/browse/ANW-1317
New tests run under Derby and MySql, as well as existing tests.
=> ANW-1317 Ensure rights statements linked agents work in Derby

frontend/app/assets/javascripts/tree.js.erb, frontend/app/assets/javascripts/tree_resizer.js, frontend/app/assets/stylesheets/archivesspace/largetree.less, frontend/config/locales/en.yml, frontend/config/locales/es.yml, frontend/config/locales/fr.yml, frontend/config/locales/ja.yml, frontend/spec/selenium/common/tree_helper.rb
Accessibility enhancements to staff and PUI trees, including:
- labels, darkens, assigns aria-expanded and aria-labels, and makes keyboard accessible the staff-side expand/collapse tree toggle;
- transitions expand/collage tree toggle from an empty <a> to a <button>; and, 
- CSS and yml changes as needed.
Not, this does not address the missing table headings noted in the accessibility audit as #2322 altered the largetree to employ `<div>s` instead of a `<table>`.
https://archivesspace.atlassian.net/browse/ANW-1328
=> ANW-1328 Staff interface tree labels, contrast, headings

backend/app/lib/bulk_import/digital_object_handler.rb
#2147 inadvertently introduced old/outdated code (refactored in #2027) back into `backend/app/lib/bulk_import/digital_object_handler.rb`, which effectively broke the linking of digital objects to archival objects when dos were added to the bulk import spreadsheet.  This re-removes the improper code.
https://archivesspace.atlassian.net/browse/ANW-1353
=> ANW-1353 Fix spreadsheet DO importer

frontend/app/views/users/index.html.erb
Since manage users and manage user access share a view, elements were being displayed on both pages. This separates them so managing groups is only possible from manage user access, and all other functions are only possible from manage users.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-97
=> ANW-97: Separate UI elements on the manage_users and manage_user_access pages

common/aspace_i18n_enumeration_support.rb, frontend/app/controllers/application_controller.rb
I18n cache optimization did not include the locale, resulting in
cache hits irrespective of the locale, based on first encountered.
This prefixes the cache entries with the locale to restore the
original functionality. Also supports resetting the cache which
may be useful in the future and updates the locale switching code
to mirror Rails documentation (around_action and with_locale).
=> ANW-1347 Fix setting language preferences in staff interface

public/app/assets/javascripts/resizable_sidebar.js, public/app/assets/stylesheets/archivesspace/aspace.scss, public/app/views/resources/_resource_tab.erb, public/app/views/shared/_accordion_panel.html.erb, public/spec/features/accessibility_spec.rb
The drag to resize functionality of the PUI sidebar is presently only usable with a mouse.  For accessibility purposes, this functionality should be extended to allow for the same user experience with keyboard commands alone.  This is a first pass at accomplishing that primary goal.
Additional unrelated issues also noted in ANW-1316 are also addressed here, including programmatically providing information on the expanded/collapsed and active state of some features (including on initial page load).
https://archivesspace.atlassian.net/browse/ANW-1316
https://archivesspace.atlassian.net/browse/ANW-1323
Tested in Edge, Firefox, and Chrome, though additional testing would be ideal.
https://user-images.githubusercontent.com/15144646/126833447-975c984c-9e1b-45d1-bb47-ac1a5fd33da2.mov
=> ANW-1316, ANW-1323 Provide keyboard-only resizing of PUI sidebar

backend/spec/model_agent_topics_spec.rb, common/db/migrations/157_fk_constraints_for_agent_subrecords.rb, frontend/app/controllers/subjects_controller.rb, frontend/config/locales/en.yml
Agent subrecord tables were created in migration 141, but lacked foreign key constraints for their parent agents. 4 of the agent sub record types can link to subjects through a 'place' or 'topic' relationship, so it cannot be possible to delete a subject while it is being used in one of the relationships (See JIRA). 
https://archivesspace.atlassian.net/browse/ANW-1381
=> ANW-1381 resolve agent sub records pointing to deleted subjects

backend/app/exporters/serializers/ead.rb, backend/spec/export_ead_spec.rb, stylesheets/as-ead-pdf.xsl
Changes add_xlink_prefix in EAD serializer to only prefix those attributes that exist in XLink 1.1.
Additionally, alters the stylesheet used for PDF generation to allow
for incorrect xlink (or arbitrary namespace) on target attribute.
Note that this still does not make PDF generation correct for all
permitted EAD constructs: ref is legal without any attributes, though
I have no idea what the use of such a thing would be.
This allows resources with refs (with valid targets) in mixed content to successfully generate PDFs.
https://archivesspace.atlassian.net/browse/ANW-1376
Made changes in local ASpace, generated PDF from a record with an AO having a ref in its related materials note.
=> Fixes ANW-1376 and handles incorrectly NSed @target permissively

backend/app/lib/bulk_import/import_archival_objects.rb
The arguments passed to `DigitalObjectHandler.create` were out of order in the XSLX AO importer, which resulted in the wrong values being assigned to attributes upon import.  This PR fixes the order, which will straighten out the attributes.
The `DigitalObjectHandler.create` call in the DO importer was already in the correct order, so no changes were needed there.
https://archivesspace.atlassian.net/browse/ANW-1383
=> ANW-1383 - xlink attributes for imported DOs are swapped

public/app/assets/stylesheets/archivesspace/aspace.scss, public/app/views/repositories/_repository_details.html.erb, public/app/views/shared/_accordion_panel.html.erb, public/app/views/shared/_agents_list.html.erb, public/app/views/shared/_multi_notes.html.erb, public/app/views/shared/_record_innards.html.erb, public/app/views/shared/_single_note.html.erb, public/spec/features/accessibility_spec.rb
Reworking several PUI partials to provide logical/unskipped heading order on PUI record pages (specifically resources and digital objects, but this work also touches also several shared subrecords such as repository details and linked agents).  
Also include a substantive update to `public/spec/features/accessibility_spec.rb`.  The new "Accessibility 2.0" suite of tests is no more, as the older (falsely passing) original PUI accessibility tests have been updated and incorporated into the 2.0 tests, organized roughly by record area.
https://archivesspace.atlassian.net/browse/ANW-1322
=> ANW-1322 PUI heading levels and accessibility tests

public/app/assets/stylesheets/archivesspace/aspace.scss
#2311 and #2243 implemented fixes to ensure digital object captions in the PUI would wrap on small devices/screen sizes.  However, as https://archivesspace.atlassian.net/browse/ANW-1338 explains, this issue wasn't specifically related to device/screen size, but, rather, happened whenever the screen size was too small OR the caption length too long (regardless of screen size).  These CSS changes extend/update the prior fixes to work regardless of device size, while also addressing some regressions that were introduced in prior fixes (namely, subrecord text was no longer wrapping around DO images). 
https://archivesspace.atlassian.net/browse/ANW-1338
Larger screen:
Mobile device:
=> ANW-1338 Ensure PUI DO captions will wrap regardless of device size

common/config/config-aliases.rb, common/config/config-distribution.rb
This just turns off custom report configurability for the time being.
=> prevent enabling custom reports for now

frontend/app/helpers/application_helper.rb, frontend/spec/selenium/spec/agents_spec.rb
As described in ANW-1390, edit view of non-person agents was throwing errors for users without full record permissions.  The `has_agent_subrecords?` method in `frontend/app/helpers/application_helper.rb` was throwing an undefined method error on non_person agents that didn't have (and will never have) `agent_gender` subrecords.  I modified the method to check whether the subrecord method exists for a given agent type, before moving on to check for the subrecords.  
This was a somewhat difficult thing to spot since it wasn't erroring out on records that _had_ subrecords (the new functionality that would logically be tested), but on records that didn't have subrecords.  So, I added tests as well.
https://archivesspace.atlassian.net/browse/ANW-1390
New tests added and confirmed passing.
=> ANW-1390 Don't error when light mode users edit corp/software/fam records

public/app/views/request_mailer/request_received_staff_email.html.erb
I have created a one-character change that fixes the output of the request_mailer staff email.
When a request for a resource gets processed, emails are sent out to the requester and the staff. The staff email template loops through the request object to output fields, but then at the bottom of the email, it outputs the same information, formatted as a Ruby list.
https://archivesspace.atlassian.net/browse/ANW-1379?atlOrigin=eyJpIjoiMjAyYjM0MGI2NzAxNDY5NTk2MzQyZmFlNzc2ODdkZGMiLCJwIjoiaiJ9
I have a local instance of Aspace on WSL (Windows Subsystem for Linux). All of my testing has been manual. I'm new to ArchivesSpace, Rails, and Ruby, otherwise I would have included it already. If this change requires testing, please let me know.
=> Fix request_mailer staff email

backend/app/model/sequence.rb
One of the changes contributed from the Queensland State Archives project was this reworking of the `Sequence` class.  Although it's not used in the core code anymore, various plugins do make use of it, and we addressed some issues with concurrency and deadlocking as as part of that project.
The new implementation relies on a queue, but @pobocks noticed that the line that defines that seems to have been dropped accidentally along the way, so I'm just adding it back in here (this gets rid of the warning message on startup too).
I also took out the raise of `SequenceError`, since our new version doesn't do that either--it's just a relic from the original implementation.
=> Add the missing definition of QUEUE

common/locales/enums/en.yml, frontend/app/views/metadata_rights_declarations/_show.html.erb, frontend/app/views/metadata_rights_declarations/_show_fields.html.erb
Adds a default "unspecified" language when the license is not selected.
Corrects a translation missing error when the metadata subrecord is collapsed in view mode.
https://archivesspace.atlassian.net/browse/ANW-1282?focusedCommentId=37775
No testing changes
=> ANW-1282-fix-translation-errors-for-collapsed-license-view

.env.docker.release, docker-compose-dist.yml, proxy/default.conf
This is for illustrative purposes -- running multiple aspace instances via a single proxy with MySQL and external Solr (does not address duplicative indexer state).
=> Docker distributed aspace cfg example (aspace N instances)

backend/app/converters/ead_converter.rb, backend/app/converters/lib/sax_xml_reader.rb, backend/app/converters/lib/xml_sax.rb
I noticed that importing certain EAD files would take a long time.  Two in particular, both exported from Smithsonian's ArchivesSpace instance, ran for over an hour before I gave up.
The thing common to the slow files was that both used unnumbered component tags (i.e. `<c>` instead of `<c01>`).  The profiler showed all of the CPU time in this method:
https://github.com/archivesspace/archivesspace/blob/3663176be821028007b5cdae2c5b01b4ea550e21/backend/app/converters/ead_converter.rb#L28-L38
which is the overridden version of this one:
https://github.com/archivesspace/archivesspace/blob/3663176be821028007b5cdae2c5b01b4ea550e21/backend/app/converters/lib/xml_sax.rb#L124-L136
the EAD converter version has been modified to short-circuit the check for common tags--including numbered …
=> Improve EAD import performance for unnumbered components

public/app/assets/stylesheets/archivesspace/aspace.scss
Windows users are seeing unwanted scroll bars in the badge-and-identifier section of the PUI, likely stemming from #2372 and the related quirk with overflow styling noted here: https://stackoverflow.com/questions/51250934/chrome-scrollbar-is-showing-on-windows-but-not-mac
I can't directly test this, but I *think* it should resolve the bug.  (It certainly doesn't hurt or change anything for the worse on Mac).
=> Don't show scrollbars on Windows in badge-and-identifier

backend/app/model/implied_publication_calculator.rb
The `repository_published?` method gets called heavily when fetching records that are a part of large collections.  To reduce the overhead of looking up the current repository's publication status, the method keeps a result cache that lives for the duration of the request.
When the repository isn't published, this cache is currently not working.  The construction:
@repository_published_status[repo_id] ||= (Repository[repo_id].publish == 1)
always evaluates the RHS when the LHS is falsey which, for unpublished repositories, it is, because it's false!  What was intended was to do the lookup if the cache has no entry for `repo_id`.
This would only be an issue for people with large collections in unpublished repositories, so maybe that use case is rare.  I see halved response times in such …
=> Cache the negative lookup result in ImpliedPublicationCalculator

launcher/plugin_gems/initialize-plugin.sh
Plugins with attached gemfiles could not find JRuby to install the needed gems. This PR switches out the hardcoded path to use ASPACE_LAUNCHER_BASE as the default base path to JRuby and gem files
https://github.com/archivesspace/archivesspace/issues/2392
Tested by enabling plugins using the changes in this PR
- [x ] I have added tests to cover my changes.
=> Use aspace base to determine location of gem files

public/spec/features/accessibility_spec.rb
Adds a single color-contrast test to confirm that the PUI skiplink is appropriate contrast when given focus.  The actual contrast problem was resolved for this (and other PUI link elements) in #2317
=> Add basic color contrast test

.yamllint, frontend/config/help.yml, frontend/config/locales/en.yml, frontend/config/locales/help/en.yml
Small changes to `frontend/config/locales/en.yml` to enable importing these translations into Weblate.  As it stands now, Weblate won't import this set of translations due to the duplicate `dates_of_existence` keys (removed below).
=> Frontend locale cleanup

.yamllint, common/locales/en.yml, common/locales/es.yml, common/locales/fr.yml, common/locales/ja.yml
Cleanup of the common locales, primarily to enable adding the file to Weblate.  In addition to removing actual accidentally duplicated keys (e.g. `time_submitted`), this also involves changing multiple aliases used in one context from this:
```
<<: *section_tooltips
<<: *slug_attributes
```
to a list like:
```
<<: [*section_tooltips, *slug_attributes]
```
This keeps weblate from identifying the repeated `<<:` as a duplicate key, and has no negative impact in the application.
With these changes merged, I'll be able to finish setting up common translations in weblate.
=> Common locales cleanup

backend/app/model/ark_name.rb, backend/spec/model_ark_name_spec.rb
I don't know why, probably some subtlety of Ruby semantics, but the _case/when/else_ in the `ArkName.ark_name_exists?()` method only ever executed the _else_ condition, regardless of the _Class_ object passed to it in the _type_ parameter. Hence the calling code in ASModel_crud.rb always got a false response, so created a new ARK every time the record was updated.
Replacing with the logically-identically _if/elsif/else_ equivalent, but which does allow the first two conditions to evaluate to true when the _type_ passed to the method is either _Resource_ or _ArchivalObject_. This fixes the bug of multiple ARKs being generated for the same record.
If an ArchivesSpace system already has multiple ARKs for some or all of its records, this won't change that. …
=> ANW-1060: Fix for multiple ARKs generated for the same record

_yard/API.erb, backend/app/controllers/classification.rb, backend/app/controllers/digital_object.rb, backend/app/controllers/resource.rb
I was trying to help someone use the various `/tree` API endpoints, and found them to be a little cryptic.  Additionally problematic because these may find increased usage as we deprecate the now outdated `/tree` endpoints in favor of `tree/root`, `tree/waypoint`, and `tree/node`. I decided to add some API examples to the controllers, but then was frustrated by how bad they looked in Slate.  So, I also decided to (slightly) improve the way parameters and JSON payloads are represented in the Slate docs (screenshots below).
Before: 
After:
=> Add API tree examples and improve parameters/data styling

backend/app/controllers/custom_report_template.rb, backend/app/controllers/reports.rb
Adds API example blocks to the two reports controllers.  Also incidentally noticed that no permissions were assigned to the custom report endpoint in `backend/app/controllers/reports.rb` so added a permission there.  We may want to update this (as well as the `custom_report_template.rb`) permissions once ANW-1400 is complete.
https://archivesspace.atlassian.net/browse/ANW-1305
=> ANW-1305 API examples and permissions

backend/app/controllers/reports.rb
In #2431 I decided to be "helpful" and remedy the fact that the `reports/custom_data` endpoint didn't have any permissions attributed to it.  I added a `create_job` permission.  Turns out that was a bad idea.  `create_job` is a repo-scoped permission, but to work the `custom_data` endpoint has no repo assigned in it.  
This reverts that permission back to nothing until we can do further review/make decisions about what the permissions should be here.
=> Temporary fix to reports permissions

frontend/app/assets/javascripts/merge_dropdown.js.erb, frontend/app/views/resources/_linker.html.erb, frontend/spec/features/accessibility_spec.rb
Element inside of the merge dropdown is missing aria-expanded attribute.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1370
Manual and in browser testing
=> ANW-1370: Expand / collapse state of the element is incorrect

public/app/controllers/resources_controller.rb, public/spec/controllers/resources_controller_spec.rb
made changes so that linked digital objects would show up as a thumbnail on the collections / resources PUI page -- the same way the linked digital objects do for archival objects
Our institution was interested in it-- and there was an existing Jira issue archivesspace/ANW-810
ANW-810
I tested it where a resource could have zero to many linked digital objects and it would display accordingly.
- [x ] New feature (non-breaking change which adds functionality)
sorry-- i need to figure out how to get these running as when i tried it gave me errors
=> ANW-810 add thumbnails of linked digital objects to collections / resources in the PUI-- the same way it does for archival objects

.devcontainer/Dockerfile, .devcontainer/README.md, .devcontainer/aliases, .devcontainer/devcontainer.json, .devcontainer/setup, .gitignore
For development only.
Allows integration with vscode for running a batteries included dev environment for aspace  in Docker. Used locally this is only really practical on Linux, WSL and faster Intel Macs (latter is a maybe, haven't actually tried it). But in the future this can be used with [codespaces](https://github.com/features/codespaces) to run aspace on GitHub infrastructure with a local or browser based vscode.
=> Add devcontainer cfg

backend/app/lib/job_runners/print_to_pdf_runner.rb
Incidentally discovered this while reviewing #2446 .  For no apparent reason, the generate pdf job adds some modified uris, though generating a PDF is never going to actually modify a record.  This can go away (with the added benefit that this means that, once #2446 is in, the "New & Modified Records Section" won't display following the completion of a generate PDF job).
=> ANW-1303_cont Minor tweak to pdf export job runner

frontend/spec/features/accessibility_spec.rb, frontend/vendor/assets/javascripts/bootstrap-datepicker.js
Bootstrap datepicker tags are missing role=button on the day, month, year elements.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1395
=> ANW-1395: Add button role to date picker span tags for month, day, year

backend/app/controllers/custom_report_template.rb
#2448 removed `narrow_by` from the list of data keys used in custom report templates.  This updates the API docs to match the current state of the code.
https://archivesspace.atlassian.net/browse/ANW-1305
=> ANW-1305 update: Remove narrow_by

frontend/app/controllers/bulk_import_templates_controller.rb, frontend/config/warble.rb
I confess to not being entirely sure why public was not already part of the `config.dirs` list in the warble config. But I suspect it is just because there are some assumptions about `public/assets` in the warble gem.
=> add public directory to frontend warble config

frontend/app/controllers/custom_report_templates_controller.rb, frontend/app/views/custom_report_templates/show.html.erb
Recent changes to the custom report templates edit pages, weren't reflected in the show/view pages.  This updates the view only page, primarily fixing translation missing errors (ANW-1432) and all fields incorrectly being shown as displayed (ANW-1439).
While working on this, I also discovered that changes to the frontend controller to handle the new user form fields, broke the enumeration based fields (can be replicated on test if you attempt to save a template with any values selected in controlled value fields).  This fixes that as well.
https://archivesspace.atlassian.net/browse/ANW-1432
https://archivesspace.atlassian.net/browse/ANW-1439
=> ANW-1439 and ANW-1432 Improve custom report template show page

frontend/app/assets/javascripts/custom_report_templates.crud.js, frontend/app/assets/javascripts/form.js, frontend/app/views/custom_report_templates/_toolbar.html.erb, frontend/app/views/custom_report_templates/show.html.erb
Adds standard toolbar elements (Save, Edit, Revert, etc.) to the custom report templates toolbar, which includes typical change tracking and prompts to save when changes are made to the form.
This change tracking conflicted with the record type selection functionality already in `frontend/app/assets/javascripts/custom_report_templates.crud.js` so I changed that up some, but realize it's probably still a little wonky (my js is not great).  So that could probably be tightened up a little more.
Also added the ability to apply a `no-change-tracking` class to toolbar buttons so that they won't be disabled by the change tracking lock.  In this case, for custom report templates, the check all/uncheck all button needs to work even when edits are happening to the form, but I could envision this …
=> ANW-1402 Add change tracking/standard toolbar to custom report templates

backend/app/exporters/serializers/ead.rb, backend/spec/export_ead_spec.rb
Minor update to ead export to ensure that the label attribute for an abstract note is retained, which results in the label persisting into the staff-side PDF export.
Also includes updates to the ead export tests to ensure that the sample notes created are actually valid notes.  Previously, the sampling method used could create notes with mismatching types/note_types (e.g. an abstract note that has a multipart note type, when it is a singlepart note).  Also ensures enough notes are created so that tests are actually testing data, and not just being skipped because a relevant note type (e.g. an abstract note) doesn't exist in this run of the test.
Note: Since this was scoped to the ticket which only concerns staff-side PDF output, this only impacts EAD 2002 export.  No changes have been …
=> ANW-1243 Retain label attribute for abstract note

backend/app/controllers/merge_request.rb
Adds shell and python examples to the API documentation for the merge subjects endpoint.  The python example is directly copied from what was supplied in JIRA.
https://archivesspace.atlassian.net/browse/ANW-1388
=> ANW-1388 Add subject merge api examples

frontend/app/assets/stylesheets/archivesspace/largetree.less
So, I still haven't quite figured out how this was working as it was prior to #2322 moved from the tree using a table to divs, but that's probably unimportant.  This sets the title columns in both resource and do staff side trees to 46% (100 -the sum of all the other already defined columns), and returns the tree widths to what they were prior to v3.1.  (Compare to sandbox which as of now is still on 3.0.2).  Also, widened the last column in the do tree since there was no reason for it to be squished like that (more real estate was available).
https://archivesspace.atlassian.net/browse/ANW-1441
=> ANW-1441 Widen title area in staff side tree

frontend/app/assets/stylesheets/archivesspace/search.less
Fixes a regression in staff-side advanced search drop-down styling that resulted from the linting done via #2441 
This returns to using calculation - which has to be escaped in less so that the calculation isn't done by less - as it was prior to #2441   However, it's slightly different than what was originally contributed via #2356 because this now satisfies stylelint and prettier.
https://archivesspace.atlassian.net/browse/ANW-1429
=> ANW-1429 Fix staff side advanced search width

_yard/API.erb, backend/spec/documentation_spec.rb
As noted in the JIRA ticket, the API documentation has long been wrong in generating examples for parameters that expect an array.  This corrects the automatically generated docs to accommodate situations where the parameter should take the form of:
`param_name[]=string_value`
https://archivesspace.atlassian.net/browse/ANW-1335
=> ANW-1335 Fix API examples for arrays

public/app/models/record.rb, public/spec/models/record_spec.rb
Correct the display of untitled objects in the PUI, ensuring that the display string is PARENT RECORD, DATE EXPRESSION.
https://archivesspace.atlassian.net/browse/ANW-1431
public/spec/models/record_spec.rb
=> ensure untitled object display strings in PUI use date for display

frontend/app/assets/stylesheets/archivesspace/buttons.less, frontend/vendor/assets/stylesheets/bootstrap/mixins/buttons.less
#2461 led to a regression in button styling across the staff UI.  This moves part of that PR from `vendor` to the archivesspace stylesheets, and more narrowly scopes the change to only address the reported issue in Deque (see issue #521639).
https://archivesspace.atlassian.net/browse/ANW-1438
=> ANW-1438 Color contrast fixes

frontend/app/assets/javascripts/header.js, frontend/app/views/shared/_advanced_search.html.erb
#2356 likely negatively impacted keypress functionality within the staff-side advanced search dropdown/form.  This ensures that hitting return while in the advanced search text field will submit the search (and not trigger the "remove row" button).
This is probably a bit ham-fisted as far as a solution goes, but it works? 🤷‍♀️ 
https://archivesspace.atlassian.net/browse/ANW-1449
=> ANW-1449 Return key should submit advanced search form

backend/Gemfile, backend/Gemfile.lock, common/test_utils.rb, frontend/Gemfile, frontend/Gemfile.lock, frontend/spec/rails_helper.rb, public/Gemfile, public/Gemfile.lock
We want to use the same network layer in development as we do in production. For some time, this want has prevented us from making the move to Jetty 9 due to the abandonment of the [mizuno gem](https://github.com/matadon/mizuno), which is what we use to wrap jetty up like a typical rack development server.  But the time has come to take action, so I [forked mizuno](https://github.com/archivesspace/mizuno) and tweaked it to use Jetty 9. 
There is probably some discussion to be had about licensing metadata and where this should live, but I can't think of any reason to bother pushing it through rubygems.
=> Use Jetty 9 for the development webservers

backend/app/exporters/models/marc21.rb, backend/spec/export_marc_spec.rb
Adding subject authority_id to MARC export
https://archivesspace.atlassian.net/browse/ANW-1415
=> ANW-1415: include subject authority_id 65X field, $0

docker-startup.sh
fails with 
```
[2021-12-06T08:58:11-05:00] (name)   inflating: /archivesspace/tmp/stylesheets/fonts/Bitter-Italic.ttf
[2021-12-06T08:58:11-05:00] (name) cp: -r not specified; omitting directory '/archivesspace/tmp/stylesheets/fonts'
```
=> stylesheets should be cp -r too

backend/app/model/authentication_manager.rb
A few people on the listserv commented that they were seeing this message a lot, due to integrations that were logging in as system users multiple times concurrently.
The log message isn't really helpful anyway: it doesn't indicate a problem and there's nothing to be done about it.  The comment in the code explains what's happening, so I've dropped the logging.
=> Remove unnecessary warning log triggered on concurrent logins

common/config/config-defaults.rb, public/spec/features/cite_spec.rb
This PR adds the following changes to #2488
- Remove PUI citation modal default tab config option
- update cite_spec test to check for platform when running keyboard commands
=> ANW-1337: Addendum to PR GH-2488 re: PUI citation modal

backend/app/lib/bulk_import/digital_object_handler.rb, backend/spec/model_bulk_import_job_spec.rb
Assign a random identifier to digital objects rather than using the ref_id of the associated archival object.
=> ANW-1459 assign a random identifier to bulk import digital objects

common/config/preference_defaults.rb, common/locales/en.yml, common/schemas/defaults.rb, frontend/app/views/defaults/_template.html.erb, frontend/app/views/resources/_toolbar.html.erb, frontend/spec/controllers/resource_controller_spec.rb, frontend/spec/selenium/spec/resources_spec.rb, frontend/spec/spec_helper.rb
Allows user to set whether the "include unpublished" checkbox is on or off by default
https://archivesspace.atlassian.net/browse/ANW-1177
Manual in-browser testing. Added an automated test stub as I haven't been able to figure out how to have the menu (which requires a mouseover to appear) to show programmatically.
=> ANW-1177: Add a user preference to include unpublished in exports

frontend/app/assets/javascripts/tree_toolbar.js.erb, frontend/spec/features/largetree_toolbar_tooltip_spec.rb
This PR fixes [ANW-1448](https://archivesspace.atlassian.net/browse/ANW-1448).
Archival object view:
Resource view:
Fixed the jquery function used in generating the Staff tree toolbar help icon.
ANW-1448
=> ANW-1448 Fix tooltip bug in staff tree toolbar

.gitignore, frontend/app/controllers/bulk_import_templates_controller.rb, frontend/app/controllers/custom_report_templates_controller.rb, frontend/app/views/custom_report_templates/_listing.html.erb
Use JSONModel sort functionality for custom report templates.
Sort bulk import templates by name.
Also smuggled in .gitignore on frontend/docs.
=> ANW-1456 Sort templates

backend/Gemfile, backend/Gemfile.lock, frontend/Gemfile, frontend/Gemfile.lock, public/Gemfile, public/Gemfile.lock
As the title says, mizuno now from ruby gems (and free of log4j)
=> mizuno-aspace is now a proper rubygem

proxy/default.conf
Need this tip-off when nginx itself is behind an SSL terminating access point.
=> Proxy default conf will always be https enabled

backend/app/model/advanced_query_string.rb, backend/spec/model_advanced_query_string_spec.rb, backend/spec/model_solr_spec.rb, common/advanced_query_builder.rb, common/schemas/date_field_query.rb
This PR builds on the work from #2400 after user feedback that the advanced search date query was still not working as expected.
Month- and year-precision searches weren't providing the expected results.
[ANW-573](https://archivesspace.atlassian.net/browse/ANW-573)
=> ANW-573: Fine tune advanced search date query

frontend/app/assets/javascripts/tree_toolbar.js.erb, frontend/app/views/shared/_templates.html.erb, frontend/spec/features/tree_toolbar_import_help_link_spec.rb
After #2546 was merged, [user feedback](https://archivesspace.atlassian.net/browse/ANW-1448?focusedCommentId=38035&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-38035) found a pre-existing bug where the 'load via spreadsheet' help button was still showing while in tree reorder mode. This PR solves this by refactoring the help button and tooltip logic. This also fixes the tooltip layout position discrepancies that existed between resource and archival object tree views.
[ANW-1448](https://archivesspace.atlassian.net/browse/ANW-1448?focusedCommentId=38035&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-38035)
See frontend/spec/features/largetree_toolbar_import_help_link_spec.rb.
See above.
=> ANW-1448: Refactor staff tree load-via-spreadsheet help-tooltip to fix reorder render bug

common/config/config-defaults.rb, public/app/assets/javascripts/handle_accordion.js, public/app/views/agents/show.html.erb, public/app/views/shared/_record_innards.html.erb, public/app/views/subjects/show.html.erb, public/spec/features/record_accordion_spec.rb
This PR solves [ANW-730](https://archivesspace.atlassian.net/browse/ANW-730) by adding a global PUI config option for toggling on/off the "expand all information blocks" by default at the bottom of record pages.
⚠️ **The expand all option has been set to `true` by default.** ⚠️
1. Add new config option to common/config/config-defaults.rb
2. Add new parameter to `initialize_accordion()`, clean up handle_accordion.js
3. Pass new arguments to uses of `initialize_accordion()`
4. Add tests
ANW-730
See [public/spec/features/record_accordion_spec.rb](https://github.com/brianzelip/archivesspace/blob/ANW-730-pui-expand-all-config/public/spec/features/record_accordion_spec.rb)
See above
=> ANW-730: Add PUI expand/collapse all config option

public/app/lib/xml_cleaner.rb
Since #1745, the HTML which is generated in order to be converted into a PDF has been run through a [third-party library](https://github.com/threedaymonk/htmlentities) which converts most entity references (but maybe not all) into UTF-8 characters. That is fine for numerical entities like `&#246;` and named entities like `&nbsp;` defined by the HTML schema (although the latter would be invalid if exported to EAD, but that's a different matter). But it also converts the five [predefined entities in XML](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML), which can create non-well-formed XHTML, which will break PDF generation. The case of `&amp;` has been handled by regex searching for unescaped-& in the strings returned by the …
=> Fix for PDF failure when predefined XML entities are unescaped

common/db/db_migrator.rb, common/db/migrations/158_ark_generalization.rb
Adds 2 small modifications to the ARK migration adopted here: https://github.com/archivesspace/archivesspace/pull/2472
1. Ensure that duplicate "zombie" rows are deleted before and after the first big transaction.
2. Ensure that the user is warned and the migration is aborted if legacy data contains a one-to-many ARK-to-Resource relation.
=> Migration 158 Legacy Data Issues

frontend/app/controllers/date_calculator_controller.rb, frontend/spec/controllers/date_calculator_controller_spec.rb
bugfix for 500 error in date calculator
https://archivesspace.atlassian.net/browse/ANW-1182
=> ANW-1182: bugfix for 500 error thrown in date calculator

backend/app/controllers/archival_object.rb
Add SHELL and Python examples to API
I added SHELL and Python examples to all the endpoints in the archival_objects.rb file. This is to update the examples found on the API and make it easier for people to understand and use those endpoints for their own needs. Additionally, I edited 2 of the descriptions to make them easier to understand.
No tests. This *shouldn't* affect anything.
=> Add examples to archival_objects.rb

frontend/app/views/deaccessions/_show.html.erb
adding default value for extent type in deaccession show page
https://archivesspace.atlassian.net/browse/ANW-1342
=> ANW-1342: adding default value for extent type in deaccession show page

frontend/app/views/site/_footer.html.erb, frontend/config/locales/en.yml, public/app/views/shared/_footer.html.erb, public/config/locales/en.yml
Footers of public and frontend interface were not ready for i18n. I have changed that and added three new translation keys each to the `en.yml` files of frontend and public components. They live under `footer`. This was inspired by the already existing `header` in the frontend component.
I'm unsure if relevant keys need to be added to other languages as well. If so, please point this out.
I'm unsure why I had to use the `I18n.t().html_safe` in the public footer. This was not necessary in the frontend footer. If this is a problem, please tell me.
Fixes #2583 
Visual testing by running the frontend and public interfaces locally.
Could not run automated tests locally because of `You have already activated nokogiri 1.12.4, but your Gemfile requires nokogiri 1.12.3`. Not sure what I'm doing …
=> add i18n to frontend and public interface footers

frontend/app/assets/stylesheets/archivesspace/notes.less, frontend/app/views/notes/_template.html.erb
Ease of use, so that adding more items doesn't require scrolling up so much.
https://archivesspace.atlassian.net/browse/ANW-699
=> ANW-699: moving 'add item' button to bottom for defined lists

frontend/app/views/repositories/_toolbar.html.erb, frontend/spec/selenium/spec/repositories_spec.rb
Single quotes are not being escaped properly by translations and JS layers, so trying to delete a repo with a single quote in the name leads to an unexpected string in the confirmation. This removes quptes from the confirmation to bypass this issue while still allowing for single quotes in repo names.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1168
Manual in browser and unit testing
=> ANW-1168: strip out quotes from the confimration when deleting a repo

public/config/routes.rb
Re-implemention of #2436 because the change in public/config/routes.rb was lost when #2437 was merged.
=> Do not set up PUI route for handling ARK URLs if arks_enabled is false

backend/app/controllers/users.rb
Previously, if you tried to send a curl request with expiring=false, it would return successful regardless of if the param was successful. For example `curl -s -F password="admin" expiring=false "http://localhost:8089/users/admin/login"` would return successfully, but the token would expire because it should be `curl -s -F password="admin" "http://localhost:8089/users/admin/login?expiring=false"
Now, when you send the expiring param the correct way, the response will include a expire_after_seconds field which shows the number of seconds until the token expires. This is set by `AppConfig[:session_nonexpirable_force_expire_after_seconds]`
N/A
ran it in devserver mode and gave it curl requests to the backend.
Not sure if there should tests for this, but just let me know if so and I'll try to …
=> API login request with expiring=false now returns feedback

public/app/assets/stylesheets/archivesspace/aspace.scss
CSS fix for block paragraph tags being converted to inline when expanding/contracting with the show less/more function in the PUI. CSS fix also solves the carriage return issue in the same request.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1242
=> ANW-1242: bugfix for lost formatting when expanding notes in PUI

common/config/config-defaults.rb, frontend/app/controllers/accessions_controller.rb, frontend/app/controllers/application_controller.rb, frontend/app/controllers/resources_controller.rb, frontend/app/views/linked_events/_show.html.erb
Implements the fetch_resolved refactoring mentioned in the comment,
by consolidating the method in application controller.
Also adds an excludes option to the method signature which allows for
an optimized way of loading accession & resource records by being more
selective about the data that is retrieved (vs. everything in find_opts).
Applies an exclusion for linked events (and their linked records) in
edit & update mode as that data is not required and can have a large
impact on performance when many linked event records are associated.
Adds an AppConfig setting for max_linked_events_to_resolve. When
the max is exceeded (> no. of linked events) then the events and
linked records are not resolved in view mode and a simplified
display is presented (excludes titles). This keeps memory …
=> Performance improvement for loading of linked event records in SUI

backend/app/controllers/merge_request.rb
Better detail for the python example - comments to help people understand the code
#2519 
No testing necessary
=> Update merge subject api python example for #2519

public/app/views/shared/_record_innards.html.erb
UI tweak to display all creators instead of just one
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1095
=> ANW-1095: display all creators in public interface

common/aspace_i18n.rb
Fixing a small typo re German language select. ger = Deutsch while gem = Germanic Languages.
- [x Bug fix (non-breaking change which fixes an issue)
=> fix typo for German language select

common/config/config-defaults.rb, common/db/migrations/158_ark_generalization.rb
It seems like sometime prior to 3.2.0 ArchivesSpace was creating additional rows in the ark_name table, maybe without the user's knowledge when they edited a resource or archival object. If that is the case, and all ark_names after the first one created for a resource or archival_object should be pruned, app admins can set this before running `setup-database`:
`AppConfig[:prune_ark_name_table] = true`
=> add config option to make migration 158 prune the ark_name table

common/config/config-defaults.rb, public/app/views/shared/_only_facets.html.erb, public/spec/features/resources_spec.rb, public/spec/spec_helper.rb
Allow administrator to choose to display facet lists in PUI in alphabetical order instead of relevance order
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-340
manual in browser testing, unit tests
=> ANW-340: adding support for sorting facets in alpha order

backend/app/lib/bulk_import/digital_object_handler.rb, backend/app/model/digital_object.rb, backend/app/model/file_version.rb, backend/spec/model_digital_object_spec.rb, common/schemas/digital_object.rb
- Adds `representative_file_version` field to `digital_object` schema
- Adds `representative_file_version` computed property to `digital_object` model per business logic
- Adds `validate` method to `file_version` model per business logic
- Adds tests per business logic
[ANW-1493](https://archivesspace.atlassian.net/browse/ANW-1493)
See backend/spec/model_digital_object_spec.rb
=> ANW-1493 Representative File Version: Backend Rules

frontend/app/assets/javascripts/representativemembers.js, frontend/app/views/file_versions/_template.html.erb, frontend/spec/selenium/spec/digital_objects_spec.rb
update frontend so setting representative and published are linked
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1498
=> ANW-1498: update frontend so setting representative and published are linked

public/app/models/concerns/tree_nodes.rb
display full record ID in PUI breadcrumb
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1422
=> ANW-1422: display full record ID in PUI breadcrumb

public/app/assets/javascripts/infinite_scroll.js
Javascript code in the InfiniteScroll js library is breaking search on the collection organization page of the PUI. Spacebar keypress events are being intercepted. This changes code to use CTRL key instead of spacebar.
https://archivesspace.atlassian.net/browse/ANW-1430
Manual, in browser testing
=> ANW-1430: changing shortcut key from space to control for infinite scroll library

backend/app/lib/job_runners/ns2_remover_runner.rb, backend/spec/model_ns2_remover_job_spec.rb, common/db/migrations/160_persistent_ids_for_notes_created_during_migrations.rb, common/locales/en.yml, common/schemas/ns2_remover_job.rb, common/spec/lib/factory_bot_helpers.rb, frontend/app/helpers/resolver_helper.rb, frontend/app/views/jobs/_form.html.erb, frontend/app/views/jobs/_job_records.html.erb, frontend/config/locales/en.yml, frontend/spec/helpers/resolver_helper_spec.rb
Re-submission of https://github.com/archivesspace/archivesspace/pull/2627 (see that PR for original description).
While testing, I realized that certain previous migrations (088, 142) that transformed legacy data into notes failed to populate the `note_persistent_id` table while populating the `note` table. This is a fairly obscure omission, but could break the note-referencing functionality that supports index notes.
=> Note persistent id issue

frontend/app/assets/javascripts/representativemembers.js, frontend/spec/selenium/spec/digital_objects_spec.rb
Tweaking UI so that make representative is disabled when published is unchecked for file versions
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1498
=> ANW-1498: change UI so make representative is disabled unless publish is checked

public/app/assets/stylesheets/archivesspace/aspace.scss, public/app/assets/stylesheets/archivesspace/helpers.scss, public/app/controllers/objects_controller.rb, public/app/controllers/resources_controller.rb, public/app/views/objects/show.html.erb, public/app/views/resources/show.html.erb, public/app/views/shared/_digital.html.erb, public/app/views/shared/_representative_file_version.erb, public/spec/controllers/digital_objects_controller_spec.rb
This PR closes [ANW-1506](https://archivesspace.atlassian.net/browse/ANW-1506) by displaying a digital object's representative file version in the public interface.
- Render image file uri in PUI digital object record
- Add representative_file_verson to objects controller
- Update locals passed to digital partial in objects show template
- Add representative_file_version template
- Refactor digital template around new rep fv template
- Add representative fv helper to resource controller
- Pass representative fv local in resource show view
- Add tests to digital_objects_controller_spec.rb
=> ANW-1506 Display representative file version in PUI

frontend/app/views/jobs/_form.html.erb
prevent create custom template button for showing unless permissions
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1478
=> ANW-1478: prevent create custom template button for showing unless permissions

frontend/app/views/jobs/_job_records.html.erb
bugfix for non-repo records not linking properly when imported
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1519
Manual, in browser testing. Did a MARC import of the following files:
backend/spec/examples/marc/at-tracer-marc-1.xml
backend/spec/examples/marc/authority_john_davis.xml 
And confirmed that the subjects and agents imported were created properly and directly linked to after import
=> ANW-1519: bugfix for non-repo records not linking properly when imported

backend/app/lib/bulk_import/import_digital_objects.rb
A user noticed that bulk importing digital objects via spreadsheet failed after upgrading from v2.8.1 to v3.2.0 due to an unexpected requirement for a value in either the `digital_object_link` or `thumbnail` columns in the [bulk_import_DO_template.xlsx file](https://github.com/archivesspace/archivesspace/blob/master/templates/bulk_import_DO_template.xlsx).
The link or thumbnail requirement was added on March 27, 2021 via [this commit](https://github.com/archivesspace/archivesspace/commit/12074a6914d360706a6eb6e0609201e56904b5ab#diff-47db1a1ae37a9ba74a43d2236a1dd232e35c44aac073775df1300672288c30a4R85-R94). (Indeed after v2.8.1 release.)
This PR removes the requirement, essentially resetting the code back to the [v2.8.1 state](https://github.com/archivesspace/archivesspace/blob/db5f2c3e34e7e …
=> ANW-1548 Unexpected digital object bulk import requirement of DO uri or thumbnail

backend/app/controllers/id_lookup_controller.rb
Provides shell and python examples for endpoints in the id_lookup_controller.rb file.
Adds examples to the 4 endpoints in the file, as well as updates the description of the :resolve parameter to better clarify usage. /repositories/:repo_id/find_by_id/resources still needs a shell example and an example searching via ARK for python.
This change is required to help users reference the API for examples when building their own code to access and take advantage of the API.
N/A*
* Will add JIRA ticket to add shell and ARK example to /repositories/:repo_id/find_by_id/resources
N/A
=> Update id_lookup_controller.rb API Examples

common/spec/lib/factory_bot_helpers.rb, frontend/app/controllers/accessions_controller.rb, frontend/app/controllers/application_controller.rb, frontend/app/controllers/resources_controller.rb, frontend/app/models/accession.rb, frontend/app/models/resource.rb, frontend/app/views/accessions/_toolbar.html.erb, frontend/spec/aspace_helper.rb, frontend/spec/controllers/resource_controller_spec.rb
=> ANW-725 Spawn with default values

backend/app/model/db.rb
Sometimes the real content of a MySQL connection failure is several wrapped exceptions deep.  For example, socket-level errors like Connection Refused/Reset and SSL version errors report a fairly bland "Communications link failure", without giving any real clues about the problem.
This commit walks the nested exceptions on a DB connection failure and logs them all out.
=> Print more diagnostic information on a DB connection failure

common/config/search_browse_column_config.rb, frontend/config/locales/en.yml
adding URI to list of fields that can be displayed in search/browse
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1360
in browser testing
=> ANW-1360: adding URI to list of fields that can be displayed in search/browse

backend/app/model/accession.rb, backend/app/model/archival_object.rb, backend/spec/model_accession_spec.rb, common/db/migrations/163_accession_component_links.rb, common/schemas/accession.rb, common/schemas/archival_object.rb, frontend/app/assets/javascripts/archival_objects.crud.js, frontend/app/controllers/application_controller.rb, frontend/app/models/archival_object.rb, frontend/app/views/accession_links/_accession_linker.html.erb, frontend/app/views/accession_links/_show.html.erb, frontend/app/views/accession_links/_template.html.erb, frontend/app/views/accessions/_form.html.erb, frontend/app/views/accessions/_sidebar.html.erb, frontend/app/views/accessions/show.html.erb, frontend/app/views/archival_objects/_form_container.html.erb, frontend/app/views/archival_objects/_show_inline.html.erb, frontend/app/views/archival_objects/_sidebar.html.erb, frontend/app/views/component_links/_component_linker.html.erb, frontend/app/views/component_links/_show.html.erb, frontend/app/views/component_links/_template.html.erb, frontend/config/locales/en.yml, frontend/spec/features/spawning_spec.rb
Porting the [Accession / Component link plugin](https://github.com/hudmol/as_accession_links) into core. 
Added is the auto-population of the linked accession field when a component is spawned from an accession.
=> ANW-287 move HM accession / component link plugin to core

common/asconstants.rb
`git symbolic-ref -q --short HEAD` gives a fatal error on detached HEAD.
so let's try a little harder to get something useful - by giving the checked out tag.
=> fix git version fail when head is detached

indexer/app/lib/indexer_common.rb
Nakanoshima Museum of Art couldn't get their Japanese titles to sort correctly. They identified that the primary culprit was `clean_for_sort` stripping out everything which isn't an ASCII world character. It isn't as noticeable in a primarily English-speaking institution, although it does make a small difference when there are accented characters or Greek letters, for example, near the start of a title.
The fix is to replace `\w`, which is equivalent to `[a-zA-z0-9_]`, with `\p{L}`, which should match anything deemed by Unicode to be a letter. This will allow non-English titles to be sorted correctly. Although it might require some adjustment to the Solr schema by individual ArchivesSpace users.
http://lyralists.lyrasis.org/pipermail/archivesspace_users_group/2022-May/009290.html
On a …
=> Fix sorting of records with titles containing non-ASCII characters

backend/app/controllers/repository_transfer.rb
I've been trying to understand how permissions work, and noticed this very small issue, but one that could confuse people searching the API docs. The other "transfer" endpoints move individual records, but this one moves all records in a repository to another repository.
N/A
N/A
=> Fix inaccurate API endpoint description

frontend/app/views/shared/_view_published_button.html.erb
Currently, the 'View Published' toolbar button in the staff interface is hidden for unpublished records. However, it is still visible for records (resources, archival objects, digital objects, accessions) which belong to a repository which isn't published. Clicking the button in such cases returns a 404 page, as it should, but the presence of the button could make people incorrectly think they are published. It is a minor issue, but can cause confusion, if using an unpublished repository as a staging area.
This change fixes that, by adding a new condition that must be met for the button to be displayed:
```
if current_repo.publish || !record.repository
```
The second clause is needed to allow global records (e.g. agents) that don't belong to the repository the staff user has currently …
=> Hide 'View Published' for published records in unpublished repositories

frontend/app/views/assessments/_toolbar.html.erb
Fixes visibility of delete button on assessment views for users without delete permission
Minor change to view for below issue.
The delete button on the assessment edit/view was visible to users without the correct permissions (delete_assessment_record)
Manual testing in local dev instance
Mac O/S running the packaged docker containers with dev db.
=> Assessment View Delete Button Visibility

public/app/views/shared/_record_innards.html.erb, public/spec/controllers/resources_controller_spec.rb, public/spec/controllers/search_controller_spec.rb, public/spec/features/agents_spec.rb, public/spec/features/resources_spec.rb, public/spec/spec_helper.rb
Rework for ANW-1095: don't show creators in two places on PUI show page
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1095
=> ANW-1095: don't show creators in two places on PUI show page

backend/app/model/search_resolver.rb, common/config/config-defaults.rb, public/app/controllers/agents_controller.rb, public/app/controllers/repositories_controller.rb, public/app/controllers/search_controller.rb
Remove 'top_container_uri_u_sstr:id' from default search opts in
controllers where it isn't required / used.
Not only is it unnecessary but it can wreak havoc in general
searches where the search returns records containing many
instances, resulting in "too many boolean clauses".
For the latter issue we now pre-check for subqueries that
exceed our defined limit (default 1024) and drop the excess
conditions with a warning, equivalent to the max resolve warning.
=> ANW-1134: Avoid resolving top_containers where it's unnecessary

frontend/app/assets/javascripts/archival_objects.crud.js, frontend/app/assets/javascripts/largetree.js.erb, frontend/app/views/archival_objects/_form_container.html.erb, frontend/app/views/archival_objects/new.html.erb, frontend/config/locales/en.yml, frontend/spec/features/spawning_spec.rb
Revised the 2nd modal ("Select Parent") in the spawn resource component from accession workflow. New design uses tree view rather than a search pane, and has a 3 option menu for selecting location (before, child, after) similar to the reorder mode in the resource edit view (but without the drag and drop handles).
=> revise tree position selection when spawning component

frontend/app/assets/javascripts/archival_objects.crud.js, frontend/app/controllers/archival_objects_controller.rb
Fix a bug that put the resource uri into the parent param when inserting before a top-level object
=> make sure not to accidentally set resource as a parent

frontend/app/assets/stylesheets/archivesspace.less, frontend/app/assets/stylesheets/archivesspace/print.less
This PR closes [ANW-28](https://archivesspace.atlassian.net/browse/ANW-28) and [ANW-949](https://archivesspace.atlassian.net/browse/ANW-949) by adding a print stylesheet for the staff interface.
Screenshots  of PDFs printed from Firefox at 100% scale, not stretched to fit width, then converted to JPG:
=> ANW-28, ANW-949: Staff print styles

backend/app/exporters/models/marc21.rb
Update MARC exports to use the MARC country code, not ISO 3166 country codes
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1416
Manual testing
=> ANW-1416: Use MARC country codes instead of ISO-3166 codes in marc exports

frontend/app/views/shared/_toolbar_new_records.html.erb
This simple PR causes the lightmode toggle button to appear when creating new Agent records. It does this by adding the button code to the new records toolbar, conditionally scoping it to the `agents` controller.
I have submitted this PR because it was a change requested by our archivists; having added it to our local plugin, they thought it likely that other institutions could make use of it too.
N/A
Manual testing carried out in a development environment, frontend test suite run. Identical code currently running in a plugin with no apparent issues in our production system.
=> Allow the light mode toggle to appear when creating new Agents

public/app/controllers/subjects_controller.rb
When a subject has been linked to from enough records that its representation in the PUI has multiple pages, any filters which a user applies (e.g. to narrow to a record type) are lost when they navigate to the second page.
This does not happen for agents which have similar numbers of linked records. So, comparing the controller code, I found the same problem had previously been fixed for agents by @marktriggs here:
https://github.com/archivesspace/archivesspace/commit/e51f4e96c11bda594bbb7acf953a7ac650f9a24c
So I have simply replicated exactly the same change in the subjects controller. Which seems to have the desired effect. Filters are now retained as you browse through the multiple pages of records matching both the subject and a filter. …
=> ANW-1584: fix for filters being dropped after first page of subject pages on PUI

frontend/spec/features/bulk_import_spec.rb, frontend/spec/features/jobs_spec.rb, frontend/spec/rails_helper.rb
[Recent work](https://github.com/archivesspace/archivesspace/pull/2776) exposed an existing problem with tests using `sleep` and a bit of hope to check page elements that appear after a backend job completed. This attempts to remove the guesswork and uses the backend API to wait for confirmation the job is in completed status.
=> add a helper so feature specs can await backend job completion

frontend/app/helpers/search_helper.rb, frontend/app/views/repositories/index.html.erb, frontend/app/views/shared/_header_repository.html.erb
I've noticed a few small discrepancies between the permissions on endpoints in the backend and permissions controlling whether corresponding menus/buttons are displayed in the frontend:
- The backend API requires the "create_repository" global permission to create new repositories or edit the details (name, publish y/n, OAI settings, etc) of an existing one. Whereas "manage_repository" is a repository-level permission for controlling access to the current repository. This pull request hides buttons in the staff interface which lead to the form for editing a repository, but unless the user is a system admin they'll get a error if they try to save changes.
- In the staff interface, non-admin users can only see the Create menu if they have permissions to create records (resources, …
=> Some small fixes to SUI permissions

public/app/lib/xml_cleaner.rb, public/app/models/finding_aid_pdf.rb
The existing code, which is run per PDF finding aid generation on the
PUI, will run up to 10,000 times before failing in the face of invalid
XML with an error it doesn't understand, which is most XML errors.
This can take tens of minutes or more on large XML output.
The replacement code fixes all the same issues, and will fail early
and gracefully on the XML issues the previous code groveled over.
https://archivesspace.atlassian.net/browse/ANW-1550
Run in production on Harvard's instance for lo these many fortnights now.
=> Fixes ANW-1550 - replaces broken XMLCleaner with Nokogiri PushParser

backend/app/exporters/serializers/ead3.rb
The `EAD3Serializer` class [defines its own](https://github.com/archivesspace/archivesspace/blob/4940708b2f2fc64669acef4689a87e196661f011/backend/app/exporters/serializers/ead3.rb#L127-L141) `add_serialize_step` and `run_serialize_step` methods, but when it comes to actually running the export, it calls the `EADSerializer` parent class's version of `run_serialize_step`. Hence, currently, if a plug-ins sets up different hooks to output EAD3 versions of whatever elements they are adding, those will never be called.  To fix this, I have searched and replaced `EADSerializer` with `EAD3Serializer` in ead3.rb.
It is possible there are plug-ins that have been created to add an element that is unchanged between EAD 2002 and EAD3, which haven't added a specific EAD3 hook, hence this change will …
=> Enable plug-ins to customize EAD3 export differently to EAD 2002

common/db/migrations/160_persistent_ids_for_notes_created_during_migrations.rb
Upon testing of v3.3.0-RC1 a flaw was discovered in [migration 160](https://github.com/archivesspace/archivesspace/commit/281cb0377f7e164a3668d4135c98c2da3b9cfe64).
It seems that in the wild there are orphaned notes which exist entirely free of context. 
This remedy will make sure that the last populated column in the row looks like a foreign key before attempting to update the persistent id table.
=> skip orphaned notes when remediating note persistent ids

frontend/app/assets/stylesheets/archivesspace/form.less, frontend/app/models/mixins/record_children.rb, frontend/app/views/archival_objects/_rde_templates.html.erb, frontend/app/views/digital_object_components/_rde_templates.html.erb, frontend/spec/selenium/spec/rde_templates_spec.rb
This PR adds 3 new columns to both the Archival Object and Digital Object Component RDE forms for staff to explicitly set the publish status for each of the 3 notes.
Here is the Archival Objects RDE:
Here is the Digital Objects RDE:
=> ANW-996: Add Publish columns to RDE Notes section

reports/digital_objects/digital_object_file_versions_list_subreport/digital_object_file_versions_list_subreport.rb, reports/digital_objects/digital_object_file_versions_report/digital_object_file_versions_report.rb
Rewrote report queries to show file version information
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1526
Manual testing:
Created 3 digital object records:
- one with no subrecords at all
- one with a date subrecord
- one with a file_version subrecord and a digital object component with a file_version subrecords, both with different file version URLs
Created a Digital Object custom report linking file versions and date subrecords
The result of the custom report is that all 3 digital object records show in report, with the URIs for both file versions (for the DO and it's DOC child that have one) and the date subrecord data for the DO that has that. Screenshot below.
The result of the file version report is that only rows for the DO and it's DOC child with …
=> ANW-1526: Fix for file version URIs not appearing when linked in file version and custom report where FV is linked

indexer/app/lib/indexer_common.rb
The cause of the missing identifier value was simply that it was not
being indexed.
Include the "identifier" value for classification records in the indexer. The value not being indexed is the cause of it being missing from CSV exports.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1503
=> ANW-1503: bugfix for identifier value not appearing in CSV download

backend/app/converters/lib/marcxml_bib_base_map.rb, backend/spec/lib_marcxml_bib_converter_spec.rb
Support ind1 = 1 for corp names in MARC importer
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1410
=> ANW-1410: Support ind1 = 1 for corp names in MARC importer

frontend/Gemfile, frontend/Gemfile.lock, public/Gemfile, public/Gemfile.lock, public/config/environments/production.rb
Upgrade uglifier so ES6 syntax will not break asset precompilation in the public app.
=> Upgrade Uglifier / Fix Docker Build

indexer/app/lib/indexer_common.rb, indexer/app/lib/indexer_common_config.rb
Resolves: repository address is indexed in all searches (SUI and PUI) skewing search results.
Skip indexing of repository and top_container record properties in the fullrecord field for all record types.
This results in repository and top container (including location) data not influening search for other record types.
https://archivesspace.atlassian.net/browse/ANW-901
Using the dev data set perform a general SUI search:
http://localhost:3000/search?utf8=%E2%9C%93&q=Your+Name+Here+Special+Collections+%28YNHSC%29
Before:
448 results, ~10 record types
After:
10 results, 6 record types
http://localhost:3000/search?utf8=%E2%9C%93&q=Overly+Gothic+Library
Before:
614 results, ~11 record types
After:
172 results, 3 record types: location, top container, repository
The repository / location …
=> ANW-901: Update full record exclusions

backend/app/model/authentication_manager.rb, backend/spec/model_authentication_manager_spec.rb, common/config/config-defaults.rb, common/schemas/user.rb, frontend/app/views/users/_form.html.erb, frontend/app/views/users/index.html.erb, frontend/config/locales/en.yml
Option to restrict existing users to only attempt authentication
against their set source. Without this there are loopholes for
bypassing the "intended" authentication backend if only a single
source of authentication is expected.
Also:
Use more screen real estate for users table
Display source in users table
Display source in user record
Development server confirms single source restriction when config
applied.
=> Stricter authentication source check

public/app/assets/stylesheets/archivesspace/print.css
This PR follows up on [QA feedback](https://archivesspace.atlassian.net/browse/ANW-950?focusedCommentId=38584) on [previous work](https://github.com/archivesspace/archivesspace/pull/2683) on PUI print styles.
- 'See more' text is expanded, and the associated ellipses are removed
- More borders have been hidden
In the screenshots below, the 'See more' expander has been removed, and the content has been expanded under Scope and Content, and the Finding Aid borders have been removed.
=> ANW-950: Show See more text and hide borders for PUI print

frontend/spec/features/datepicker_plugin_spec.rb, frontend/vendor/assets/javascripts/bootstrap-datepicker.js
⚠️ THIS PR MODIFIES A VENDOR PLUGIN ⚠️
This PR addresses [QA feedback from previous ANW-170 work](https://archivesspace.atlassian.net/browse/ANW-170?focusedCommentId=38512) that was concerned about the datepicker behavior when pasting year or month values with the datepicker toggled on. Previously the datepicker would force year and month values into the current day's date. This PR modifies the datepicker vendor plugin to allow pasting year, month, or day values into a datefield when the datepicker is toggled on.
https://archivesspace.atlassian.net/browse/ANW-170
See frontend/spec/features/datepicker_plugin_spec.rb
=> ANW-170: Modify datepicker plugin to allow pasting year, month, or day

backend/app/model/large_tree.rb, backend/spec/controller_archival_object_spec.rb, backend/spec/controller_resource_spec.rb, frontend/app/assets/javascripts/largetree.js.erb, public/app/assets/stylesheets/archivesspace/aspace.scss, public/spec/controllers/resources_controller_spec.rb, public/spec/controllers/search_controller_spec.rb, public/spec/features/classifications_spec.rb, public/spec/features/resources_spec.rb, public/spec/features/tree_spec.rb, public/spec/spec_helper.rb
Addresses ANW-1206 Collection Organization tree linked digital object indicator.
This adds an icon to items in the tree that have associated digital objects.
This is only 1 part of the issue. The other will be addressed separately to make
implementation / review simpler.
https://archivesspace.atlassian.net/browse/ANW-1206
Manually & with specs.
=> ANW-1206: visual cue for digitized materials (tree)

backend/app/converters/lib/marcxml_bib_base_map.rb, backend/spec/lib_marcxml_bib_converter_spec.rb
Adds 583 to MARC XML bib importer map as requested by Metadata Standards subgroup of TAC.
Maps 583 $a, b, c, d, e, f, h, i, j, k, l, n, o, u, x, z, 3, 5 to note_multipart; note_type='processinfo'; label=Processing Note with a format of (if subfield exists): `Action: $a--Action Identification: $b--Time/Date of Action: $c--Action interval: $d--Contingency for Action: $e--Authorization: $f--Jurisdiction: $h--Method of action: $i--Site of Action: $j--Action agent: $k--Status: $l--Extent: $n--Type of unit: $o--URI: $u--Non-public note: $x--Public note: $z--Materials specified: $3--Institution: $5`
(Note: The JIRA ticket repeats $j for both method of action and site of action, but I believe this is a typo.  I've mapped $i to Method of Action and $j to Site of Action per: …
=> ANW-1567 MARCXML import add 583

backend/app/converters/lib/marcxml_bib_base_map.rb, backend/spec/lib_marcxml_bib_converter_spec.rb
Adds 584 to MARC XML bib importer map as requested by Metadata Standards subgroup of TAC.
Maps 584 $a, b, 3, 5 to note_multipart; note_type='accruals'; label='Accruals' with a format of (if subfield exists): `Accumulation: $a--Frequency of use: $b--Materials specified: $3--Institution: $5`.
https://archivesspace.atlassian.net/browse/ANW-1568
New test added.
=> ANW-1568 MARCXML import add 584

frontend/app/views/digital_object_components/_show_inline.html.erb, frontend/app/views/digital_objects/_show_inline.html.erb, frontend/app/views/file_versions/_image.html.erb, frontend/app/views/file_versions/_show.html.erb, frontend/spec/selenium/spec/digital_objects_spec.rb
This PR addresses [ANW-1518](https://archivesspace.atlassian.net/browse/ANW-1518) by fixing a bug in the logic for computing the `alt` text of a Digital Object Component's file version image. DO and DOC file version images use the file version caption to populate the `alt` attribute text on the corresponding `<img>` element in the object's view page. When a DOC file version had no caption set, the attempt was made to derive the alt text from data that was only available to DO.
See frontend/spec/selenium/spec/digital_objects_spec.rb
=> ANW-1518: Fix alt text logic for staff Digital Object Component file version image

package.json, public/app/assets/stylesheets/archivesspace/aspace.scss, public/app/assets/stylesheets/archivesspace/helpers.scss, public/app/views/shared/_digital.html.erb, public/config/locales/de.yml, public/config/locales/en.yml, public/config/locales/es.yml, public/config/locales/fr.yml, public/config/locales/ja.yml, public/config/locales/pt.yml, public/spec/features/file_version_link_spec.rb
This PR addresses [ANW-907](https://archivesspace.atlassian.net/browse/ANW-907) and [ANW-1626](https://archivesspace.atlassian.net/browse/ANW-1626).
It also provides npm lint fix scripts for developer convenience.
ANW-907 refers to the digital object links not being recognizable as such. This PR adds a visual button to the object's link box with an icon denoting the link leads to an external resource. This PR builds on [an earlier branch](#2843). In that branch the link color was changed to black, but here I kept the color red which denotes digital objects as defined in the [stylesheets](https://github.com/archivesspace/archivesspace/blob/master/public/app/assets/stylesheets/archivesspace/colors.scss#L44). The color could of course be easily changed if the color for digital objects is …
=> ANW-907, ANW-1626: Refactor PUI digital object links

frontend/spec/selenium/common/driver.rb, frontend/spec/selenium/spec/digital_objects_spec.rb
This PR improves the test from #2847. It updates the frontend selenium driver helpers `get_view_page()` and `get_edit_page()` to get archival object and digital object component pages.
[ANW-1518](https://archivesspace.atlassian.net/browse/ANW-1518)
See frontend/spec/selenium/spec/digital_objects_spec.rb.
=> ANW-1518 Refactor test for image alt text for rep file versions

backend/app/converters/lib/marcxml_bib_base_map.rb, backend/spec/lib_marcxml_bib_converter_spec.rb
Adds 264$c to MARC XML bib importer map as requested by Metadata Standards subgroup of TAC, when the following are absent:
- controlfield position 6 is not 'i', 'k', or 's' (not in JIRA, but a necessary condition);
- 245$f;
- 245$g; and
- 260$c.
**Note**: In working on this, I noticed that one of the assumptions inherent in the ticket and that seems to be [attempted in the code](https://github.com/archivesspace/archivesspace/blob/master/backend/app/converters/lib/marcxml_bib_base_map.rb#L867-L875), currently does not work.  If you attempt to upload a MARCXML file that contains no dates in:
- controlfield;
- 245$f; and
- 245$g
a date subrecord **does not** get created from the value in 260$c.  (In fact, if the only place date content is available is 260$c the import will fail with the …
=> ANW-1565 MARCXML import conditionally add 264$c

backend/app/converters/lib/marcxml_bib_base_map.rb, backend/spec/lib_marcxml_bib_converter_spec.rb
Adds 852$j to MARC XML bib importer map as requested by Metadata Standards subgroup of TAC.
https://archivesspace.atlassian.net/browse/ANW-1557
New test added to `backend/spec/lib_marcxml_bib_converter_spec.rb`.
=> ANW-1557 MARCXML import add 852$j

frontend/app/assets/javascripts/agents.crud.js, frontend/app/assets/javascripts/representativemembers.js, frontend/app/assets/javascripts/utils.js, frontend/app/assets/stylesheets/archivesspace/form.less, frontend/app/helpers/aspace_form_helper.rb, frontend/app/views/agents/name_forms/_agent_corporate_entity.html.erb, frontend/app/views/agents/name_forms/_agent_family.html.erb, frontend/app/views/agents/name_forms/_agent_person.html.erb, frontend/app/views/agents/name_forms/_agent_software.html.erb, frontend/app/views/file_versions/_template.html.erb, frontend/config/locales/en.yml
Adds tooltips to action buttons at the top of some subrecords in ASpace frontend forms to aid in adding user documentation
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1521
=> ANW-1521: support for tooltips in subrecord header buttons

backend/app/lib/background_job_queue.rb, backend/spec/model_job_spec.rb
Prevents a bad reference from foiling `rescue` when a `BackgroundJobQueue` tries to cancel a job that no longer exists.
https://github.com/archivesspace/archivesspace/issues/2821
I added a test for this functionality as well.
=> resolve https://github.com/archivesspace/archivesspace/issues/2821

frontend/app/helpers/application_helper.rb, frontend/app/views/shared/_header_global.html.erb, frontend/app/views/shared/_header_repository.html.erb, frontend/spec/features/help_tooltip_default_placement_spec.rb
This PR fixes [ANW-1589](https://archivesspace.atlassian.net/browse/ANW-1589) by moving the default placement of the help tooltip from left of to underneath the help icon.
=> ANW-1589: Change staff help tooltip default location to underneath icon

public/app/assets/stylesheets/application.scss, public/app/assets/stylesheets/archivesspace/result-linked-instances.scss, public/app/views/digital_objects/_search_result_breadcrumbs.html.erb, public/app/views/shared/_result.html.erb, public/app/views/shared/_result_breadcrumbs.html.erb, public/app/views/shared/_result_breadcrumbs_ancestor.html.erb, public/app/views/shared/_result_breadcrumbs_repo.html.erb
This PR provides an update to [ANW-961](https://archivesspace.atlassian.net/browse/ANW-961) PR #2877 that:
1. renders breadcrumbs for each linked instance of a digital object in a PUI search result
2. makes consistent the use of icons in breadcrumbs of all PUI search results
=> ANW-961: Refactor PUI search results breadcrumbs

frontend/app/controllers/digital_objects_controller.rb
Of course, the lack of any record passed in to copy from is not an error; it just means that we don't need to copy anything and should proceed with a blank digital object as usual.
I will look into adding an appropriate test for this case. (The test previously added for this feature only checks the affirmative case where we are creating on top of an resource.)
=> DO spawn error check was just plain wrong

.devcontainer/devcontainer.json, .vscode/README.md, .vscode/settings.json
This PR isn't related to any existing issue.
It improves the auto-fixing of lint errors for contributors who use VS Code _before_ they push to GitHub. VS Code plugin activity can be hard to debug and inefficient. This PR improves the existing config by being more explicit about which plugin does what. It also turns on a key setting by default that was previously left to the contributor to initiate (`"source.fixAll": true`).
The VS Code settings should probably be added to the @archivesspace/tech-docs , since it's essentially ArchivesSpace's official recommendation for VS Code tooling config, and requires any contributor using VS Code to manually add the related plugins to their editor.
@mark-cooper I wanted to get your OK to change the rubocop plugin. As the name suggests …
=> [Chore] Improve VS Code editor config

frontend/app/views/enumerations/_list.html.erb
In the staff interface, in _System > Manage Controlled Value Lists_, if the enumeration being displayed has no relationships, then it won't be possible to suppress individual values in that list. The reason is that, since 4efc80f4e51c88f01383b16d1fb6e34f5c0ac772, the "Suppress" buttons are initially disabled, and then JavaScript in _enumerations.index.js.erb_ re-enables them for values that aren't used in any records. But that won't work if the enumeration has no relationship (i.e. isn't used to populate drop-downs in any records.) So this pull request adds an extra condition so that the "Suppress" buttons aren't disabled in the first place for such enumerations.
Admittedly, this is a very niche issue, as I think all the stock enumerations do have relationships. It only really affects …
=> Fix for inability to suppress controlled value list values if the enumeration has no relationships to records

.github/workflows/release.yml
This PR updates the releases.yml CI workflow file to make use of the latest workflow syntax and to get rid of deprecation warnings we keep getting in our CI tests.
Warning message:
> The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.
This PR replaces #2863 which experienced merge conflicts after #2879.
=> ANW-1637: Update release workflow `set-output` env vars

common/config/search_browse_column_config.rb, frontend/app/assets/stylesheets/archivesspace/search.less, frontend/app/views/search/_representative_file_version_cell.html.erb, frontend/config/locales/en.yml, frontend/spec/controllers/search_controller_spec.rb
Use the `representative_file_version` data to construct a thumbnail image for search results in the staff ui:
Note: to test this you will need to go to your repository or global preferences and select "Thumbnail image" for one of the browse columns for the record type you are going to test. Example:
=> ANW-1530 show representative image as thumbnail in staff search results

public/app/assets/stylesheets/archivesspace/aspace.scss, public/app/views/digital_objects/_additional_file_versions.html.erb, public/app/views/shared/_record_innards.html.erb, public/config/locales/en.yml, public/spec/controllers/digital_objects_controller_spec.rb, public/spec/controllers/objects_controller_spec.rb
This PR solves [ANW-1506](https://archivesspace.atlassian.net/browse/ANW-1506) which correlates to Req3.3 of [ANW-1209](https://archivesspace.atlassian.net/browse/ANW-1209).
It adds an "Additional File Versions" accordion to digital object and digital object component pages in the PUI if there are additional file versions not marked as representative.
See public/spec/controllers/objects_controller_spec.rb.
=> ANW-1506: Add additional file versions accordion to PUI digital object and digital object component pages

backend/app/lib/bulk_import/bulk_import_mixins.rb, backend/app/lib/bulk_import/cv_list.rb, backend/spec/lib_bulk_import_container_instance_handler_spec.rb, backend/spec/lib_bulk_import_cvlist_spec.rb
add missing values for instance_type when running a bulk import
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1296
=> ANW-1296: add missing values for instance_type when running a bulk import

frontend/app/assets/javascripts/locations.location_holdings.js.erb
Should now properly select the location linker Browse button to add the click handler to set up observers to populate the holdings counts cells both when the modal is displayed and when the pagination controls are used. MutationObservers are used both for ensuring we wait until the modal is present and for detecting when new rows appear (on initial display and on page change).
=> ANW-1501: fix locations list holdings count cells

backend/app/exporters/lib/export_helpers.rb, backend/app/exporters/models/ead.rb, backend/app/exporters/serializers/ead.rb, backend/app/exporters/serializers/ead3.rb, backend/spec/custom_matchers.rb, backend/spec/export_ead_representative_file_version_spec.rb, backend/spec/export_spec_helper.rb
Adds `Xlink:role` and `linkrole` attributes to EAD and EAD3 export respectively when representative digital object instances are attached to resources and archival objects per specification in ANW-1209.
=> ANW-1532 add representative @role attributes to EAD and EAD3 exports

frontend/app/assets/javascripts/representativemembers.js, frontend/app/assets/stylesheets/archivesspace/form.less, frontend/app/helpers/aspace_form_helper.rb, frontend/app/views/agents/_contact_details.html.erb, frontend/app/views/file_versions/_template.html.erb, frontend/app/views/instances/_template.html.erb, frontend/spec/features/is_representative_toggle_spec.rb
This PR addresses [ANW-1498](https://archivesspace.atlassian.net/browse/ANW-1498). It allows the 'make representative' button found in the staff app to be toggled on and off on click. (Previously the button only turned the 'is-representative' state on but not off.) The button is found in the resource instances form, digital object file versions form, and agent contact details form.
This PR maintains the status quo of how this feature works -- using two buttons (to do the work of one) in conjunction with JavaScript and a hidden `<input type="text">`, thus recreating the native HTML `<input type="radio">` . In the future this feature should be refactored into a radio button input group, as the nature of the is-representative data model maps well to the radio button use case.
See …
=> ANW-1498: Allow staff is-representative buttons to be toggled off on click

public/app/controllers/concerns/searchable.rb, public/spec/controllers/search_controller_spec.rb
Removes a method that was running `ActionView::Helpers::SanitizeHelper.sanitize` over search controller params, and garbling search queries with an '&' in the query string.
=> search queries are not html!

public/app/controllers/objects_controller.rb, public/app/controllers/resources_controller.rb, public/app/views/accessions/show.html.erb, public/app/views/objects/show.html.erb, public/app/views/resources/show.html.erb, public/app/views/shared/_digital.html.erb, public/app/views/shared/_record_innards.html.erb, public/spec/controllers/accessions_controller_spec.rb, public/spec/controllers/objects_controller_spec.rb, public/spec/controllers/resources_controller_spec.rb, public/spec/features/accessions_spec.rb, public/spec/features/file_version_link_spec.rb, public/spec/features/record_innards_spec.rb
This PR solves [ANW-1531](https://archivesspace.atlassian.net/browse/ANW-1531) by displaying a representative file version image on public record pages for resources, archival objects, and accessions.
⚠️ As-is, the ANW-1209/representative_file_version spec results in possibly attempting to render unsupported file formats as images (mp3, pdf, etc) when a file version with such a file format is identified as representative. This PR works in tandem with #2920, which limits what is considered a representative file version by file format, by disabling the tests in public/spec/features/file_version_link_spec.rb. Once the ANW-1209 spec dust settles, either the tests in public/spec/features/file_version_link_spec.rb should be refactored, or the spec file should be removed entirely.
- cleaned up …
=> ANW-1531: Show representative file version for PUI resources, arch objs, and accessions

common/config/preference_defaults.rb, common/locales/en.yml, common/locales/ja.yml, common/schemas/defaults.rb, frontend/app/assets/javascripts/digital_object_spawning.js.erb, frontend/app/controllers/digital_objects_controller.rb, frontend/app/helpers/digital_object_helper.rb, frontend/app/views/defaults/_template.html.erb, frontend/app/views/digital_objects/_linker.html.erb, frontend/spec/features/spawning_spec.rb
Resources and Archival Objects use this LargeTree Javascript
component for navigating and viewing. Since this happens entirely on
the client side, the record object that was provided to the view when
the user initially clicked Edit is no longer valid if the user clicks a
different record in the tree.
As a result, we needed some JavaScript that grabs the ID of the
"current" record (from the Tree) and tacks it on to the parameters
that are submitted by the linker's Create button. Now the controller
can copy fields from the correct record into the new Digital Object.
Also went back and fixed the name of the preference - not sure why
I had  "_description" on it.
=> ANW-1615: account for LargeTree client-side interactions

backend/app/lib/job_runners/print_to_pdf_runner.rb
PDF export runner was trying to resolve "digital_objects" instead of "digital_object", so the export helper ended up trying to access a nil _resolved value
=> Fix resolultion of digital_object reference

frontend/app/views/search/_listing.html.erb, frontend/spec/features/representative_file_version_spec.rb
This PR fixes [ANW-1677](https://archivesspace.atlassian.net/browse/ANW-1677), hides broken thumbnail images in staff search listings when the URL for a record's `representative_file_version` resolves to a [non-supported image format](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#supported_image_formats).
It works by listening for the loading error event on each thumbnail `<img>`.
See frontend/spec/features/representative_file_version_spec.rb
[ANW-1677]: https://archivesspace.atlassian.net/browse/ANW-1677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-1677: Hide broken representative file version thumbnail images in staff search listing

public/app/assets/stylesheets/archivesspace/aspace.scss, public/app/helpers/view_helper.rb, public/app/views/accessions/show.html.erb, public/app/views/objects/show.html.erb, public/app/views/resources/show.html.erb, public/app/views/shared/_digital.html.erb, public/spec/controllers/resources_controller_spec.rb
Adds a link to view all digital objects that are related to the resource record being viewed below the representative file version.
=> ANW-1534: Link to image search in PUI

public/app/views/objects/show.html.erb, public/app/views/resources/show.html.erb, public/app/views/shared/_digital.html.erb
The need for this PR came from the Program Team standup, 2023-02-20, where we observed that the older, "generic" blue icon representing linked instances, was showing up on some PUI Resource and Archival Object record pages that did not have a representative instance. This was viewed by the team as work from ANW-1209 that is unintentionally "leaking" into unrelated parts of the application.
This PR stops the leakage by constraining the use of the public/app/views/shared/_digital.html.erb template.
[ANW-1209](https://archivesspace.atlassian.net/browse/ANW-1209)
[ANW-1209]: https://archivesspace.atlassian.net/browse/ANW-1209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-1209: Limit use of the PUI shared/_digital.html.erb template*

public/app/assets/stylesheets/archivesspace/helpers.scss, public/app/controllers/resources_controller.rb, public/app/views/resources/show.html.erb, public/app/views/shared/_digital.html.erb, public/app/views/shared/_representative_file_version_record.html.erb, public/config/locales/en.yml, public/config/locales/ja.yml
This is a follow up from #2934 regarding [ANW-1534](https://archivesspace.atlassian.net/browse/ANW-1534) that implements the language from the spec regarding the link to the list of linked instances for Resources and AObjs.
[ANW-1534]: https://archivesspace.atlassian.net/browse/ANW-1534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-1534 Implement spec link text

public/app/views/pdf/_archival_object.html.erb, public/app/views/pdf/_digital_object_links.html.erb, public/app/views/pdf/_header.html.erb, public/app/views/pdf/_resource.html.erb, public/app/views/pdf/_titlepage.html.erb, public/app/views/welcome/show.html.erb
- allow plugins to add content to PUI views without overriding those views
- adds hooks for header, titlepage, archival_objects, digital_object_links, and resources for pdfs
- adds hook for welcome view
Local testing with custom plugin. Public tests passed (`./build/run public:test`)
This functionality uses the same mechanism & pattern found in [public/app/views/shared/_record_innards.html.erb](https://github.com/archivesspace/archivesspace/blob/master/public/app/views/shared/_record_innards.html.erb#L57)
=> Feature - PUI View Hooks for Plugins

backend/app/model/mixins/representative_file_version.rb, backend/spec/mixin_representative_file_version_spec.rb, common/schemas/file_version.rb, frontend/spec/selenium/spec/resources_spec.rb, public/app/views/digital_objects/_additional_file_versions.html.erb, public/app/views/shared/_digital.html.erb, public/app/views/shared/_representative_file_version_record.html.erb, public/spec/features/representative_file_version_spec.rb
This PR  solves [ANW-1700](https://archivesspace.atlassian.net/browse/ANW-1700) by providing a `derived_from` property on the `representative_file_version` hash for Resources, Archival Objects, and Accessions. This property is the URI for the DO (or child DOC) record that provides the representative file version, from the representative linked instance of the archival record. This property is then used to link to the DO (or child DOC) from the representative file version image shown on PUI archival record pages.
This PR also addresses [ANW-1705](https://archivesspace.atlassian.net/browse/ANW-1705) by limiting a DO's representative file version to its own file versions, and only looking to a DO's children for purpose of showing a representative file version image on a Resourse/AO/Accession …
=> ANW 1700, ANW-1705: Link to DO from rep file version img; adjust logic for determing a DO's rep file version

public/app/assets/stylesheets/archivesspace/helpers.scss, public/app/controllers/resources_controller.rb, public/app/views/digital_objects/_search_result_breadcrumbs.html.erb, public/app/views/shared/_result_breadcrumbs_ancestor.html.erb, public/spec/controllers/resources_controller_spec.rb
This PR addresses [ANW-1699](https://archivesspace.atlassian.net/browse/ANW-1699) by showing the tree-like breadcrumbs ("treecrumbs") for results on the "View Digital Materials" pill section of a PUI resource record.
- Resolve linked_instances for /digitized results
- Add test
- Minor: fix class name interpolation bug in template
- Minor: swap out inline styles for classes in markup
See public/spec/controllers/resources_controller_spec.rb.
[ANW-1699]: https://archivesspace.atlassian.net/browse/ANW-1699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-1699: Add tree-view breadcrumbs to a PUI resource's digitized list results

backend/app/model/file_version.rb, backend/app/model/mixins/representative_file_version.rb, backend/spec/mixin_representative_file_version_spec.rb, backend/spec/model_digital_object_component_spec.rb, backend/spec/model_digital_object_spec.rb
This PR addresses [ANW-1701](https://archivesspace.atlassian.net/browse/ANW-1701) by changing the logic of the rep file version spec's REQ-3.2. This PR significantly cuts down on the number of possible broken images that will be shown as representative file versions.
The original REQ-3.2 is too aggressive in defining a representative file version by _any_ published file version.
> **REQ-3.2**: If no published File Version is designated as representative, and there is no entry with a Use-Statement value of "Image-Thumbnail", the system shall display the first available linked, published File Version subrecord. 
This PR replaces the _any_ published file version catch-all with the older `xlink_attribute_show` method for showing an image, which is [defined …
=> ANW-1701: Add xlink method for determining a representative file version

public/app/assets/stylesheets/archivesspace/aspace.scss, public/app/views/shared/_representative_file_version_record.html.erb
[ANW-1707](https://archivesspace.atlassian.net/browse/ANW-1707)
[ANW-1707]: https://archivesspace.atlassian.net/browse/ANW-1707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ANW-1707]: https://archivesspace.atlassian.net/browse/ANW-1707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-1707: Tweak representative file version image CSS

frontend/app/controllers/locations_controller.rb
This just makes sure an instance variable that the translation depends on is present.
=> ANW-1692 fix create button label after error

backend/app/model/digital_object.rb, public/spec/features/record_digital_materials_spec.rb, public/spec/spec_helper.rb
The digital object "collection" property should only be added to from an archival object when that object is published.
This will prevent digital objects linked to unpublished archival objects from appearing in the Digital Materials list / total for a resource (aka the "collection") in the PUI.
https://archivesspace.atlassian.net/browse/ANW-1703
=> ANW-1703: scope d.obj collection to published a.objs

public/app/views/digital_objects/_search_result_breadcrumbs.html.erb, public/spec/controllers/search_controller_spec.rb, public/spec/features/digital_objects_spec.rb, public/spec/features/record_innards_spec.rb
[ANW-1706](https://archivesspace.atlassian.net/browse/ANW-1706)
This PR includes a digital object's linked accessions in its search result bread crumbs. See the "Aldo S. Leopold Papers" breadcrumbs in the screenshot below.
[ANW-1706]: https://archivesspace.atlassian.net/browse/ANW-1706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-1706: Add accessions to digital object search result breadcrumbs

frontend/app/assets/javascripts/largetree_dragdrop.js.erb, frontend/app/assets/javascripts/tree_renderers.js.erb, frontend/app/assets/stylesheets/archivesspace/largetree.less
This PR addresses [ANW-1024](https://archivesspace.atlassian.net/browse/ANW-1024) via the following changes:
- the a11y color contrast violation of the Staff reorder mode drag and drop handle (to the far left of each child row shown below) has been solved by replacing the existing handle image with inline svg
- each row in a reorder mode tree can now be dragged, whereas the current reorder mode only allows dragging of the drag-handle at the far left of each row
[ANW-1024]: https://archivesspace.atlassian.net/browse/ANW-1024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-1024: Staff reorder mode improvements

frontend/app/assets/javascripts/linker.js
When you click "Browse" from a Top Container linker, there's some JS in linker.js that prepopulates the "Resource" field in the browse (to show you top containers linked to the current Resource record).
This code relies on a regex on window.location.pathname to work out whether it's running in the context of a resource record, but that regex didn't account for the possibility of a URL prefix.  Modify that regex to work when running under a prefix too.
=> Ensure prefilled collection in "browse top containers" works with a URL prefix

backend/app/model/mixins/representative_file_version.rb, backend/spec/mixin_representative_file_version_spec.rb, common/schemas/file_version.rb, public/app/views/shared/_digital.html.erb, public/app/views/shared/_record_innards.html.erb, public/app/views/shared/_representative_file_version_record.html.erb, public/spec/features/representative_file_version_spec.rb
This PR addresses [ANW-1721](https://archivesspace.atlassian.net/browse/ANW-1721), which is feedback from the first round of user testing after the initial representative file version work related to ANW-1209.
This PR brings the app into backwards compatibility with regard to how a representative file version, or an 'embedded thumbnail' in the pre-ANW-1209 parlance, can be clicked.
Since before ANW-1209, an embedded thumbnail could have a link wrapped around it. The link was defined by _the `file_uri` of the proceeding file version_ to the file version which provides the thumbnail for embedding. While there weren't any tests covering this behavior, the [user manual](https://archivesspace.atlassian.net/wiki/spaces/ArchivesSpaceUserManual/pages/894566839/Publishing+Digital+Objects+and+Embedd …
=> ANW-1721: Add `link_uri` to `representative_file_version` based on proceeding file version

public/app/controllers/concerns/result_info.rb, public/spec/controllers/objects_controller_spec.rb
This PR addresses [ANW-1719](https://archivesspace.atlassian.net/browse/ANW-1719). It removes the rule that the file_uri must start with 'http' for showing what we've termed the 'generic icon' that shows on a digital object's PUI record page.
[ANW-1719]: https://archivesspace.atlassian.net/browse/ANW-1719?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-1719: Remove PUI file_uri 'http' rule for showing icon

public/app/views/digital_objects/_additional_file_versions.html.erb, public/spec/controllers/objects_controller_spec.rb
This PR addresses [ANW-1722](https://archivesspace.atlassian.net/browse/ANW-1722) by updating the logic of how file versions in addition to a DO's/DOC's representative file version are shown on the DO/DOC record page.
Before this PR the ANW-1209 spec was implemented as written, which tried to show each additional file version as an image, a la the representative file version.
This new work changes the display logic according to the following rules via the issue ticket:
1. If there's a caption only, display text of caption and link to URI
2. If there's a use statement only - display text of use statement and link to URI
3. If there's both a caption and a use statement, display text of caption and link to URI (_same as rule \# 1_)
4. If there's no use statement or caption - display text of …
=> ANW-1722 Add PUI additional file version display logic

common/config/search_browse_column_config.rb, frontend/config/locales/en.yml, frontend/spec/controllers/search_controller_spec.rb
Allows user to select "Thumbnail Image" as a browse column for general search results in staff interface.
=> ANW-1723 Thumbnail Column in Search Results

public/app/views/objects/show.html.erb, public/app/views/resources/show.html.erb, public/spec/features/file_version_link_spec.rb
This PR addresses [ANW-1735](https://archivesspace.atlassian.net/browse/ANW-1735).
This PR undoes the work from #2939 to show the 'generic icons' for each eligible file version of each of a Resource's or AO's linked digital objects, when there is no eligible representative file version for the Resource or AO.
See public/spec/features/file_version_link_spec.rb
[ANW-1735]: https://archivesspace.atlassian.net/browse/ANW-1735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-1735: Undo the removal of generic icons from PUI Resource and Archival Object pages

public/app/controllers/concerns/result_info.rb, public/app/views/digital_objects/_additional_file_versions.html.erb, public/config/locales/en.yml, public/spec/controllers/objects_controller_spec.rb
This PR addresses the updated [ANW-1719](https://archivesspace.atlassian.net/browse/ANW-1719).
We have pivoted (from #2976) and decided to keep the http rule since removing it increases the chances for showing broken images.
We also need to accommodate base64 encoded [data urls](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs), so add the data: rule too.
This also updates the markup for additional file versions, so that the full data url (which can be very long!) isn't shown as the text of links where there are no caption or use statement. The text chosen to be displayed can be changed to something else, currently set to "URL-encoded data".
See public/spec/controllers/objects_controller_spec.rb
[ANW-1719]: …
=> ANW-1719: Allow file version file_uri to start with 'http' or 'data:'

public/app/controllers/concerns/result_info.rb, public/spec/features/file_version_link_spec.rb
This change modifies ArchivesSpace to check the publish flag of a digital object before selecting a file version to display as part of an archival object.
In `process_digital_instance`, digital objects are selected for display but do not check their `publish` flags.  There is a very similar piece of code in `get_rep_image` from the same file that does check this flag.  I think this change is required because without it, the public view displays published file versions for digital objects that are not published.
We noticed this when users attempted to hide digital objects by unchecking their `publish` checkboxes, but their file versions were still displayed with the archival object in the public view.
https://archivesspace.atlassian.net/browse/ANW-1738
I tested this by toggling the …
=> ANW-1738: respect digital object publish flag when selecting a representative digital object for an archival object

frontend/app/assets/javascripts/tree.js.erb, frontend/app/assets/javascripts/tree_renderers.js.erb, frontend/app/assets/stylesheets/archivesspace/largetree.less, frontend/app/views/layouts/application.html.erb, frontend/spec/features/resource_tree_spec.rb, public/app/assets/javascripts/tree_renderer.js.erb, public/app/views/layouts/application.html.erb, public/spec/controllers/objects_controller_spec.rb, public/spec/features/resource_tree_spec.rb
This will allow admins to configure both staff and public apps to show record identifiers in trees.
Toggle these config values:
```ruby
AppConfig[:display_identifiers_in_largetree_container] = true
AppConfig[:pui_display_identifiers_in_resource_tree] = true
```
You should see the identifiers thusly:
=> ANW-1196 rework appconfig for optional tree identifier display

public/app/views/layouts/application.html.erb
Allows plugins to add content directly to top of the body of the page in the PUI
Adds another plugin hook to layout to allow plugins to directly add content to the top of the body of PUI pages. Use case example: adding `<noscript>` content for things like Google Tag Manager.
Local testing Mac OS
=> Plugins can add to top of body in PUI

frontend/app/controllers/events_controller.rb, frontend/app/views/events/new.html.erb, frontend/spec/features/events_spec.rb
Adds the record URI and type to the "plus 1" button parameters so the record will again be linked automatically on the new event form.
=> ANW-1690 ensure record link after +1 event

public/app/controllers/search_controller.rb, public/app/services/archives_space_client.rb, public/config/locales/en.yml, public/spec/controllers/search_controller_spec.rb
Adds validation for `from_year` and `to_year`. 
This was done in response to: https://github.com/archivesspace/archivesspace/issues/1691#issuecomment-1671345291
I was not able to reproduce an actually XSS event, but in any case it doesn't make sense to let arbitrary content in those fields get carried over in url params and in the `input` tag's `value` field.
Queries with invalid params will just redirect and show a flash error:
=> validate search params for from_year and to_year

common/db/migrations/160_persistent_ids_for_notes_created_during_migrations.rb
Migration 160 currently fails for us, but probably produces incorrect results for everyone due to using an incorrect field, see issue #3022 for details
Fixes #3022 
I've built a release from the fix branch, installed it on our test system and was able to run the migration successfully.
=> use correct field in migration

backend/app/model/db.rb, build/scripts/migrate_db.rb, common/db/sequel_mysql_timezone_workaround.rb
Workaround MySQL/Sequel Daylight Savings Time hiccups
When serverTimezone=UTC, timestamps coming out of MySQL will return a correct
epoch time when `.getTime()` is called, but will otherwise be expressed in the
JVM's default timezone.  For example, if your timestamp was midnight UTC,
`timestamp.getHour()` might return 20 if you were in New York (and four hours
behind UTC).
Sequel is configured to use the UTC timezone too, but
`to_application_timestamp` is expecting to get
year/month/day/hour/mins/seconds in UTC values, not in local time values.
To make these things line up, get a Calendar instance corresponding to `v` in
the UTC timezone and then read off the UTC values.
Fun note: you might think you could just set serverTimezone to match your
JVM's timezone and avoid this whole mess, and …
=> ANW-1229 Sequel DST timestamp fix

build/scripts/export_config.rb, scripts/tasks/doc.thor
Some config options were being filtered out when the distribution gets built
PRs merged with squash commits were not getting titles in generated release notes
=> Fix release notes and release config export

backend/app/model/search_resolver_compact_resource.rb, public/app/views/shared/_result_breadcrumbs.html.erb
Not all records have (or require) titles. However the PUI breadcrumbs for search were expecting a title, which when absent results in an error.
This is resolved by including the display string in compact results and using that as a fallback when title is not present.
Before (ao has no no title, display string not included):
```
"_resolved_ancestors": {
"/repositories/2/archival_objects/2684": [
{
"publish": true,
"level": "other level",
"uri": "/repositories/2/archival_objects/2684"
}
]
}
```
After (ao has no title, includes display_string):
```
"_resolved_ancestors": {
"/repositories/2/archival_objects/2684": [
{
"publish": true,
"level": "other level",
"uri": "/repositories/2/archival_objects/2684",
"display_string": "1909, 1919, undated"
}
]
}
```
Create published records: `resource -> …
=> Return display string in compact resource respresentations

backend/app/controllers/users.rb, backend/app/lib/user_mailer.rb, backend/spec/controller_user_spec.rb, common/locales/en.yml, frontend/app/controllers/users_controller.rb, frontend/app/models/user.rb, frontend/app/views/users/password_form.html.erb, frontend/config/locales/en.yml
This addresses an issue and discussion on #2979
The view path setup for ActionMailer was not correct for release builds running on Jetty (via archivesspace.sh). This should take care of that. We now don't indicate to the user that an email address was not found for password reset, instead stating that if the account exists, and email will be sent. Also removes "recover" terminology in favor of "reset" for clarity/consistency.
=> ANW-1477 Password reset fixes/updates

frontend/app/helpers/plugin_helper.rb, frontend/app/views/agents/_form.html.erb, frontend/app/views/agents/_form_required.html.erb, frontend/config/initializers/plugin.rb
This addresses the following problems I have encountered while developing a plug-in that adds new sections to agent forms in the staff interface:
* If you add individual agent types (e.g. "agent_person") to the "parents" list in the plug-in's config.yml, that adds new sections in read-only mode, and links in the sidebar, but the new sections are missing in edit mode.
* If you add "agent" to the "parents" list in config.yml, then new sections are added to edit mode, but they don't appear in the sidebar or read-only mode.
* You can work around this by adding both to config.yml, but the sidebar links don't jump to the new sections.
* That workaround also means plug-ins cannot add sections to only some of the agent types, or different ones to different types.
To fix this, I have changed the …
=> Fix agents plugin support in staff interface

backend/app/model/agent_person.rb, backend/spec/model_deletion_spec.rb, frontend/config/locales/de.yml, frontend/config/locales/en.yml, frontend/config/locales/es.yml, frontend/config/locales/fr.yml, frontend/config/locales/ja.yml
Replacement for #3030 submitted from a fresh fork, which doesn't have commits from GitHub Actions automatically run on the other fork.
Check whether an agent is linked to a user before deleting, rather than letting it fail if it violates a foreign key constraint.
https://archivesspace.atlassian.net/browse/ANW-1341
1. Log in to staff interface.
2. Find an agent which corresponds to a user.
3. Click the delete button.
It correctly fails to delete, as before, but the message displayed is, in English...
> Record cannot be deleted as it is linked to a user
...rather than...
> Record deletion failed: Java::JavaSql::SQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`archivesspace`.`user`, CONSTRAINT `user_ibfk_1` FOREIGN KEY …
=> ANW-1341: Display user-friendly message when trying to delete an agent linked to a user

docker-compose-dist.yml, docker-compose-release.yml
The file ./proxy/Dockerfile holds an ARG "DEFAULT_CFG"
The files ./docker-compose-release.yml and ./docker-compose-dist.yml have been passing an arg to that Dockerfile above.  But the name of the ARG they are sending is "default" instead of "DEFAULT_CFG".
As such, the Dockerfile will always use "ARG DEFAULT_CFG=default.conf" 
when running "docker compose -f docker-compose-release.yml build" or
when running "docker-compose -f docker-compose-dist.yml build".
Those docker-compose seem to intend to use "./proxy/default.conf.release" and "./proxy/default.conf.dist" respectively.
Either that Dockerfile or docker-compose*.yml files can be changed so that the ARG is successfully passed.
This pull request chooses the second option, but either is valid.
=> fixing mismatch between docker-compose & ./proxy/Dockerfile ARG

backend/app/lib/user_mailer.rb
By default it is equivalent to frontend_url but is more typically used to record the proxy addressable url that a user uses to access the staff ui in line with the config.rb and tech docs recommendation:
- https://archivesspace.github.io/tech-docs/provisioning/https.html
- https://archivesspace.github.io/tech-docs/provisioning/prefix.html
Without this, when using a proxy (url) with the default frontend_url, you'll receive a reset link like:
http://localhost:8080/users/$USERNAME/$TOKEN
=> Use frontend proxy url for password reset

frontend/config/initializers/plugin.rb
Don't assume plugin config.yml has a parent key as it's not required (and for example lcnaf does not).
Do something like:
```bash
git clone --recurse-submodules https://github.com/archivesspace/archivesspace aspace-with-submodules
cd aspace-with-submodules
./build/run build-dist
```
As above and locally updated the `hello_world` example plugin to test the conditions (no `parents` and with `parents.agent`).
=> Fix frontend plugin initializer

frontend/app/helpers/search_helper.rb, frontend/app/views/search/_context_cell.html.erb
This PR addresses 2 issues we encountered with "search" adjacent performance rendering the context cell (particularly with larger page sizes).
1. Currently a call to `get_ancestor_title` is made at least twice per "ancestor". Once to see if there's a value, then again to get the value. The PR updates this to just happen once and use the result.
2. Requests for ancestors are repeated per result (record). If a result shares ancestors the same request is being made without reference to any previous lookups for the same "ancestor". To help with this this PR goes with a minimally intrusive approach of introducing a local variable per controller action. It's simple, can be easily replaced or updated in the future for something more sophisticated (it may eventually be better to do something that …
=> Dedupe ancestor title requests and lookup once per field

.env.docker.release, docker-compose-dist.yml, docker-startup.sh
This enables running > 1 container instances safely (i.e. without overlapping and potentially conflicting db migrations).
Example is provided in docker-compose-dist.yml.
=> Make dockerfile db migrate conditional

docker-compose-fake-smtp.yml, frontend/config/routes.rb
Usernames containing periods get a 404.
There's a good explanation here:
https://prathamesh.tech/2020/06/15/allowing-dots-in-rails-routes/
For testing, without the PR, start the dev servers and visit:
http://localhost:3000/users/username/123456789 - ok, redirected to error
When the username contains a period (for example, an email address):
http://localhost:3000/users/my.email@example.org/123456789 - 404, routing not working
With the PR, for the latter you'll get the error (for the non-existing user) but routing is working.
An alternative implementation would be to `Base64.urlsafe_encode64(username)` on the way out and `Base64.urlsafe_decode64(username)` on the way in (as is being done during the authentication process).
I've also included the fake-smtp compose file previously referenced …
=> Fix route not found for password reset

public/app/views/resources/_finding_aid.html.erb
bug fix addressing the change item of order in the Finding Aid & Administrative Information section of the PUI introduced by adding the selectable status feature in ANW-312
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-312
Manual testing
=> ANW-312: restore original item order in PUI Finding Aid & Administrative Information section

common/schemas/defaults.rb, frontend/app/views/top_containers/bulk_operations/_results.html.erb
Stops "no value" columns from showing up in top container management table, and stop "score" field from showing up in sort column options. (This is a special case because "top container management" is not actually a record type, so whatever is hiding that option in the other preference sections seems to not be applying to this one.)
=> ANW-1101 small fixes for top container mgmt column prefs

frontend/spec/spec_helper.rb, indexer/app/lib/indexer_common.rb, indexer/app/lib/pui_indexer.rb, indexer/spec/indexer_common_spec.rb, solr/schema.xml
I have observed the following side-effects of #3006:
- Archival objects match keywords in their parent resource when searching in the PUI. That is because the PUI indexer retrieves ancestors in order to do inheritance of selected fields, but *all* the fields in those ancestors are now being included in the new “fullrecord_published” index.
- Indexing is slower, because each record is being scanned for fields to include in the new “fullrecord_published” and “notes_published” indexes. It only adds hundredths of a second per record, but for very large institutions that could add hours to a full re-index.
This pull request contains a possible approach to fixing these issues:
- Change the _extract_string_values_ method to extract both published and unpublished strings at the same time.
- …
=> Indexer efficiency improvements and fixes for side-effects of #3006

frontend/app/controllers/application_controller.rb, frontend/app/helpers/search_helper.rb, frontend/app/views/search/_context_cell.html.erb
This updates: https://github.com/archivesspace/archivesspace/pull/3025
Additional testing has been done to ensure the instance variable is valid in all views (hence initted in application controller).
=> Use instance variable to speedup context cell (lookup ancestor titles)

indexer/app/lib/periodic_indexer.rb, indexer/app/lib/pui_indexer.rb
This is an efficiency improvement in the indexer. There is no need for the PUI Indexer to index individual archival objects (or anything else) belonging to a private repository. Currently it does, and on the production system I run that adds half an hour to a full re-index, because there is a very large private repository used for staging new records prior to publishing. Maybe that is an niche case, but the principle remains that it should just skip such repositories, not retrieve every record from the database, then individually determine that each one should not be published.
The one scenario when PUI Indexer needs to do something is the first time the PUI Indexer runs after a public repository is unpublished. That one time, it needs to delete all the "pui only" documents from Solr (the …
=> Do not re-index records in private repositories unnecessarily

frontend/spec/features/representative_file_version_spec.rb
This PR bandaids over a notoriously flaky test by replacing an image url hardcoded in a spec.
The old url that pointed to an image on an ArchivesSpace domain was not resolving after Lyrasis made some server changes, which resulted in the spec failing.
This PR just changes the image url, pointing to an image hosted on another ArchivesSpace domain.
While this sets us up for possible test failures down the line if the hardcoded image does not persist, it makes this spec _less_ of a flaky test in  the short term, since the test was flaky _before_ Lyrasis made the recent server changes.
[ANW-1884](https://archivesspace.atlassian.net/browse/ANW-1884) is a general catch-all ticket for current flaky tests. As such this PR does not close ANW-1884.
[ANW-1884]: …
=> ANW-1884: Fix representative file version thumbnail spec image url

frontend/app/assets/javascripts/extent_calculator.js, frontend/app/views/extent_calculator/_show_calculation.html.erb, frontend/config/locales/en.yml, frontend/config/locales/ja.yml, frontend/spec/selenium/spec/resources_spec.rb
There were a couple of issues with the extent calculator "form" javascript. There were no checks to ensure required fields were filled in before creating the calculated extent, so they were added (ANW-1691) as well as a test for it.  It was also failing to recognize that it might be running on top on an archival object, so that check has been added in order to construct the appropriate selectors in that case (ANW-1771). Also had to update a test due to required fields being enforced.
=> ANW-1691 ANW-1771 fixes small extent calculator bugs

public/app/views/pdf/_resource.html.erb, public/config/locales/en.yml
PUI PDF tweaks/fixes for issues raised by testers: Specific Issues fixed:
- Arrangement note is duplicated in PUI PDF
- Preferred citation note is duplicated in PUI PDF. One is immediately after the abstract, and the other is above processing information
- ID [ark] is hyperlinked on SUI PDF whereas it appears as ark:/99999/1 on PUI PDF
- Date [bulk] has additional language in PUI PDF (e.g. “1998-2005” vs “Majority of material found within 1998-2005”)
- Language of material is in the SUI PDF, but not the PUI PDF.
- Line breaks are not retained in processing information note in PUI PDF (I’m guessing this is not isolated in the processing information note)
https://archivesspace.atlassian.net/browse/ANW-1848
Manual testing using this record: …
=> ANW-1848: PUI PDF tweaks

frontend/app/assets/javascripts/largetree_dragdrop.js.erb
The drag and drop functionality from "reorder mode" in an Archival Object's largetree is available when reorder mode is not enabled. This PR checks for reorder mode on mousedown inside the largetree.
Closes GH #3108 
https://archivesspace.atlassian.net/browse/ANW-1896
=> ANW-1896 Fix always-on largetree reorder mode drag and drop

.github/actions/bootstrap/action.yml, .github/workflows/accessibility.yml, .github/workflows/backend.yml, .github/workflows/codescan.yml, .github/workflows/frontend.yml, .github/workflows/indexer.yml, .github/workflows/public.yml, .github/workflows/release.yml, .github/workflows/stats.yml, common/config/config-defaults.rb
Upgrade github actions to latest version
We have been getting deprecation messages on our github runners such as: 
https://github.com/archivesspace/archivesspace/actions/runs/7717059494/attempts/1?pr=3097
https://archivesspace.atlassian.net/browse/ANW-1887
I did an irrelevant change on common just to trigger a whole spec run
=> ANW-1887: upgrade github actions to use updated node

indexer/app/lib/index_state.rb
This is a small step towards improving support for multi-instance deployments of ArchivesSpace. We need to check the file exists as one instance may already have processed the file before another attempts to act on it, creating a race condition.
=> Check index tmp file exists before mv

backend/app/model/db.rb, common/config/config-defaults.rb
In cases where the db pool becomes full it can be helpful in some cases to increase the pool timeout to give the db connections addtl. time to complete before throwing pool timeout errors.
The default timeout is 5 which preserves the current cfg / behavior.
=> Provide cfg to enable setting db pool timeout

frontend/app/controllers/users_controller.rb
This PR fixes the broken sort-by-username on the [Manage user Access](https://test.archivesspace.org/staff/users/manage_access) page by copying the `@search_data` logic from the `index` action to the `manage_access` action in the User controller.
The [original sort feature](https://github.com/archivesspace/archivesspace/pull/2278/files#diff-b3bb499ec4138704e3d81f0e4c634917fb6fc3c882d69c18cde288b943e7b084) was only added to `index`.
https://archivesspace.atlassian.net/browse/ANW-1830
There is already a [backend test for the server functionality](https://github.com/archivesspace/archivesspace/pull/2273/files#diff-0cb2908732454ffe0930555ae8611dd9ec468f576118551adf25586b73266fb6).
=> ANW-1830 Fix sort by username on the Manage User Access page

frontend/app/assets/javascripts/tree_renderers.js.erb, frontend/app/assets/stylesheets/archivesspace/common.less, frontend/app/assets/stylesheets/archivesspace/largetree.less
This PR fixes the vertical jank/movement that happens in the Staff app in record reorder mode when an individual row is selected. It does so by rewriting the styles related to the row's drag handle. It also updates the drag handle grip icon svg to that which is used in the upcoming [Softserv Staff fixes](https://github.com/archivesspace/archivesspace/pull/3090).
The need for this work was observed while working on the related [ANW-1447](https://archivesspace.atlassian.net/browse/ANW-1447) although it doesn't directly solve the issues in ANW-1447. Since work on ANW-1447 was halted via a recent staff meeting, this quick fix was pushed up.
Manual in-browser
[ANW-1447]: https://archivesspace.atlassian.net/browse/ANW-1447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
=> Fix vertical jank in reorder mode row selection

frontend/app/views/accession_links/_accession_linker.html.erb, frontend/app/views/component_links/_component_linker.html.erb, frontend/config/locales/de.yml, frontend/config/locales/en.yml, frontend/config/locales/es.yml, frontend/config/locales/fr.yml, frontend/config/locales/ja.yml
The title and the label on the "add link action" button are missing on:
- /staff/accessions/<accession id>/edit#accession_component_links_
- /staff/resources/<resource id>/edit#archival_object_accession_links_
https://archivesspace.atlassian.net/browse/ANW-1879
=> ANW-1879 fix title and action button label on accessions and component linkers

public/app/views/digital_objects/_linked_instances.html.erb, public/app/views/digital_objects/_search_result_breadcrumbs.html.erb, public/app/views/shared/_result_breadcrumbs_ancestor.html.erb
Users expect mixed content in titles to be rendered properly in the breadcrumbs shown on the "found in" section for the digital materials in a collection. This was not previously accounted for. Two things needed to be done:
1. handle unprocessed `emph` tags in collection titles
2. move the resulting`span` tags used for the formatting outside of the breadcrumb links so they render properly
before:
after:
=> ANW-1869 support emphasis styling in PUI breadcrumbs

indexer/app/lib/periodic_indexer.rb, indexer/app/lib/pui_indexer.rb
This is a small update to the indexer to only set the mtimes for repositories, deletes and pui record types when "some work was done", which is the case for all other record types.
The primary reason for doing this is to get rid of unnecessary i/o operations when the indexer state is running on non-local storage such as EFS or S3, where there can be additional costs or performance overhead from this when running many instances of ArchivesSpace (that may also have many repositories each).
Fire up ArchivesSpace and let it reindex. Check:
- `ls -l build/dev/indexer_state/`
- `ls -l build/dev/indexer_pui_state/`
Note the last modified times and / or check the mtimes. Allow the indexer to run for a minute or 2 (in excess of the indexer frequency cfg) and note that no mtimes have been updated. …
=> Indexer update (all) mtimes only when needed

.github/workflows/frontend.yml, frontend/Gemfile, frontend/Gemfile.lock, frontend/config/environments/test.rb, frontend/spec/rails_helper.rb
This is partly implemented in https://github.com/archivesspace/archivesspace/tree/ANW-1727-softserv-upgrades-final-build but without the configuration that uploads the artifacts when a capybara spec fails in CI. 
I thought adding just this functionality could help us debug the capybara specs that are currently flakky as well as the ones I am porting over from selenium as part of: https://archivesspace.atlassian.net/jira/software/c/projects/ANW/boards/46?selectedIssue=ANW-1825
I will also create an accompanying PR on tech-docs to document this functionality. 
https://archivesspace.atlassian.net/browse/ANW-1906
=> ANW-1906 add functionality to take screenshots every time a spec fails

public/app/views/digital_objects/_additional_file_versions.html.erb
This will match the thumbnail images links and open the file version text links in a new tab or window. Also gives them a title to match the same.
I don't think there is one, at least not one I could find for just this little thing
Ran local
=> Set additional file version links to target=new

.github/workflows/frontend.yml, frontend/spec/rails_helper.rb
This is a fix for the uploading of saved pages when capybara specs test fail.
There needs to be a difference in the name of the uploaded zip file for the Java 11 and Java 8 runs, otherwise the one that ends second fails to upload the file because of name collision.
=> ANW-1906 fix uploaded artifact name

frontend/app/views/layouts/application.html.erb, public/app/views/layouts/application.html.erb
Fixes HTML Language Declarations
The html `lang` attribute had been set to the default locale without regard for the current session settings. This corrects that and sets the language accordingly for both the staff frontend and the PUI.
Local Testing.
=> HTML Language Declaration

public/app/assets/javascripts/InfiniteTree.js, public/app/assets/javascripts/MixedContent.js, public/app/views/resources/infinite.html.erb, public/spec/features/collection_organization_spec.rb
This PR fixes [ANW-1971](https://archivesspace.atlassian.net/browse/ANW-1971) by handling mixed content in record titles listed in the Collection Organization sidebar tree appropriately.
- A new JS class is introduced - `MixedContent` - that checks for mixed content in a string and provides some useful getters.
- A new spec is added to test the functionality.
This PR represents a quicker client side solution, since the InfiniteTree sidebar is empty on page load and populated later via a fetch. However, a more robust and longer term solution would entail sending HTML down the wire instead of the current JSON on fetch, which is not very common in ArchivesSpace if present at all.
[ANW-1971]: https://archivesspace.atlassian.net/browse/ANW-1971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …
=> ANW-1971 Fix mixed content rendering in PUI Collection Organization sidebar tree

common/config/config-defaults.rb, frontend/app/controllers/application_controller.rb, frontend/spec/features/system_information_spec.rb
Allow users with admin privs to access system_information page
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-799
=> ANW-799: allow users with admin privs access to system_information page

frontend/spec/features/agents_spec.rb
https://archivesspace.atlassian.net/browse/ANW-1919
=> ANW-1919 port agents specs to capybara

public/app/models/finding_aid_pdf.rb, public/config/locales/en.yml
Instead of the app returning a generic 500 error page when a PDF fails to generate, this returns a PDF with a better description of the error, including what went wrong, what part of the PDF the error occurred in, etc.
https://archivesspace.atlassian.net/jira/software/c/projects/ANW/issues/ANW-1075
Manual testing
=> ANW-1075: Better error messages for PUI PDF errors

.github/workflows/accessibility.yml, .github/workflows/all_specs_dispatch.yml, .github/workflows/backend.yml, .github/workflows/codescan.yml, .github/workflows/common-frontend.yml, .github/workflows/frontend.yml, .github/workflows/indexer.yml, .github/workflows/public.yml
set a default java version when github action variables are not available (fork PRs) see also: https://github.com/orgs/community/discussions/44322
I have noticed this as soon as we got a PR from a fork:
https://github.com/archivesspace/archivesspace/pull/3190
Because also no secrets are available when running github actions on a fork PR, it is not possible (for now) to run our frontend specs (running on AWS workers and requiring secrets to start them) on PRs from forks
I tried to use env variables within the workflows but it is not possible to use them as input arguments to call other workflows (such as the frontend.yml calling the common-frontend.yml workflows)
I tried to use a job that just sets the Java version as an output variable and define that job as a prerequisite for all java …
=> ANW-2022 variables not available on PRs from forks

frontend/app/assets/stylesheets/archivesspace/common.scss, frontend/app/assets/stylesheets/archivesspace/help.scss, frontend/app/helpers/application_helper.rb, frontend/app/views/agents/new.html.erb, frontend/app/views/archival_objects/_new_inline.html.erb, frontend/app/views/assessments/new.html.erb, frontend/app/views/classifications/new.html.erb, frontend/app/views/container_profiles/new.html.erb, frontend/app/views/custom_report_templates/new.html.erb, frontend/app/views/digital_objects/new.html.erb, frontend/app/views/instances/_subrecord_form_action.html.erb, frontend/app/views/jobs/new.html.erb, frontend/app/views/location_profiles/new.html.erb, frontend/app/views/repositories/new.html.erb, frontend/app/views/resources/new.html.erb, frontend/app/views/shared/_subrecord_form.html.erb, frontend/app/views/subjects/new.html.erb, frontend/app/views/top_containers/new.html.erb, frontend/app/views/users/new.html.erb
This PR:
- Repositions the tooltip generated via `link_to_help()`, and hacks around tightly coupled surbform heading markup and form behavior
- Fixes the tooltip generated via `wrap_with_tooltip()`
- Brings spacing around some .form-actions button groups inline with the rest of the app
[ANW-1977](https://archivesspace.atlassian.net/browse/ANW-1977)
[ANW-1977]: https://archivesspace.atlassian.net/browse/ANW-1977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-1977: Fix Staff tooltip bugs

backend/app/exporters/serializers/dc.rb, backend/app/exporters/serializers/eac.rb, backend/app/exporters/serializers/ead.rb, backend/app/exporters/serializers/marc21.rb, backend/app/exporters/serializers/marc_auth.rb, backend/app/exporters/serializers/mets.rb, backend/app/exporters/serializers/mods.rb
Fix for ANW-2025, partially reverting ANW-1671
This rolls back the replacement of http with https in serializer XML namespaces, but leaves the updates to the schema locations intact.
Tested locally by doing exports of EAD, EAC, MARCXML, DC, MODS, and METS and making sure that the changes were reverted properly.
- [X ] My code follows the code style of this project.
=> ANW-2025 Replace https in XML namespaces with http

_yard/Gemfile.lock, backend/Gemfile.lock, backend/spec/export_dc_spec.rb, backend/spec/export_eac_spec.rb, backend/spec/export_marc_spec.rb, backend/spec/export_mets_spec.rb, frontend/Gemfile.lock, indexer/Gemfile.lock, oai/Gemfile.lock, public/Gemfile.lock
Fix failing specs as a result of merging [pull request](https://github.com/archivesspace/archivesspace/commit/72386801d1679277eb458429d8f84814664d9dfb) https://github.com/archivesspace/archivesspace/pull/3194 [from abbistani/ANW-2025](https://github.com/archivesspace/archivesspace/commit/72386801d1679277eb458429d8f84814664d9dfb)
Support Java 17 on development environment
=> Fix specs for merged pull request #3194 from abbistani/ANW-2025

frontend/app/assets/javascripts/ajaxtree.js.erb, frontend/app/assets/javascripts/tree_toolbar.js.erb, frontend/app/controllers/archival_objects_controller.rb, frontend/config/locales/de.yml, frontend/config/locales/en.yml, frontend/config/locales/es.yml, frontend/config/locales/fr.yml, frontend/config/locales/ja.yml, frontend/spec/controllers/archival_objects_controller_spec.rb, frontend/spec/features/trees_spec.rb
https://archivesspace.atlassian.net/browse/ANW-1757
=> ANW-1757 duplicate a full resource record

stylesheets/as-ead-pdf.xsl
This makes the Digital Objects reappear on the staff pdf by only applying changes in the xsl transformation.
[ANW-1909]
[ANW-1909]: https://archivesspace.atlassian.net/browse/ANW-1909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-1909 Fix digital objects on staff pdf

frontend/app/assets/stylesheets/archivesspace/submenu.scss, frontend/app/views/shared/_header_repository.html.erb
Fix the positioning and improve markup for the plugins dropdown submenu under the repo settings dropdown menu in the global header of the Staff app.
[ANW-2037](https://archivesspace.atlassian.net/browse/ANW-2037)
[ANW-2037]: https://archivesspace.atlassian.net/browse/ANW-2037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2037: Fix staff plugins dropdown submenu in repo settings

frontend/app/assets/javascripts/archival_objects.crud.js, frontend/spec/features/spawning_spec.rb
This PR fixes the broken modal work flow for spawning an Archival Object from an Accession.
It also re-enables the related spec.
[ANW-2030](https://archivesspace.atlassian.net/browse/ANW-2030)
[ANW-2030]: https://archivesspace.atlassian.net/browse/ANW-2030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2030: Fix archival obj spawn from accession

backend/app/controllers/exports.rb, frontend/app/assets/javascripts/export_dropdown.js.erb, frontend/app/controllers/exports_controller.rb, frontend/app/views/resources/_toolbar.html.erb, frontend/config/locales/de.yml, frontend/config/locales/en.yml, frontend/config/locales/es.yml, frontend/config/locales/fr.yml, frontend/config/locales/ja.yml
The pdf export for a resource used to be in a checkbox inside the Export -> Download EAD menu, and we could directly download the EAD using a backend controller.
At some point, the print pdf was moved inside a job, in a separate section in the Export menu, so the controller on the backend and anything related to directly printing pdf on the frontend is not used anymore.
=> Remove unused print pdf backend controller and ead xml export frontend

frontend/app/assets/stylesheets/archivesspace.scss, frontend/app/assets/stylesheets/archivesspace/common.scss, frontend/app/assets/stylesheets/archivesspace/custom_reports.scss, frontend/app/assets/stylesheets/archivesspace/form.scss, frontend/app/views/custom_report_templates/_form.html.erb, frontend/app/views/custom_report_templates/index.html.erb, frontend/app/views/groups/_form.html.erb, frontend/app/views/groups/edit.html.erb, frontend/app/views/shared/_ark_editor.html.erb
This PR fixes:
- the "Edit ARKs" dropdown toolbar button (under the "More" dropdown)
- the edit ARKs modal
- the Groups _form view
- Custom Report views
This PR is a follow up from the Softserv upgrades.
[ANW-2048](https://archivesspace.atlassian.net/browse/ANW-2048)
S
[ANW-2048]: https://archivesspace.atlassian.net/browse/ANW-2048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2048 Fix ARKs, Groups, and Custom Report views

frontend/app/assets/stylesheets/archivesspace/form.scss, frontend/app/views/jobs/_show_templates.html.erb, frontend/app/views/jobs/new.html.erb, frontend/app/views/shared/_templates.html.erb
This PR fixes the layout for Jobs status sections.
This is part of [ANW-2048](https://archivesspace.atlassian.net/browse/ANW-2048), outstanding Softserv updates fixes.
[ANW-2048]: https://archivesspace.atlassian.net/browse/ANW-2048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2048 Fix Jobs status layouts

backend/app/exporters/serializers/ead.rb, backend/spec/export_ead_spec.rb
For fields in revision statements and finding_aid_language_note in  a resource
I was unable to reproduce the issue on the PUI pdf. 
I was able to reproduce the issue only on the pdf generated on the staff UI by including ampersands in fields:
- Finding Aid Status 
- the fields inside Revision Statements.
[ANW-1340]
[ANW-1340]: https://archivesspace.atlassian.net/browse/ANW-1340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-1340 Escape ampersand characters on pdf export

.github/workflows/accessibility.yml, build/build.xml, public/app/assets/javascripts/InfiniteRecords.js, public/app/assets/javascripts/InfiniteTree.js, public/app/views/resources/infinite.html.erb, public/spec/rails_helper.rb, public/spec/spec_helper.rb
Passes in the public app proxy url to InfiniteTree/InfiniteRecords so they can properly fetch nodes/waypoints when a proxy is in use.
This also ends up involving some changes so that the public URL can be defined at the top level in build.xml and passed to rspec so that AppConfig can be set appropriately and various tests involving the collection organization pages will run successfully.
=> ANW-2000 account for potential app proxy prefix in IR code

public/config/locales/de.yml, public/config/locales/en.yml, public/config/locales/es.yml, public/config/locales/fr.yml, public/config/locales/ja.yml
This is a follow up from #3239 that adds missing translations.
=> ANW-2073 Add search result highlighting translations

public/app/assets/javascripts/more_facets.js, public/app/assets/stylesheets/archivesspace/aspace.scss, public/app/views/shared/_facet_description.html.erb, public/app/views/shared/_only_facets.html.erb, public/config/locales/de.yml, public/config/locales/en.yml, public/config/locales/fr.yml, public/config/locales/pt.yml, public/spec/features/more_facets_spec.rb
This PR fixes a bug from the Softserv updates that broke the "more" / "less" buttons on the PUI sidebar of search results that expanded/collapsed a long list of facets to use for filtering.
This work also improves the more facets template, which mistakenly nested facets of different types in the markup despite the correct visual organization on the page.
*It should be noted that this was a light editing of the more facets code, and preserves the fully-JavaScript based approach. In the future this feature could be brought in line with the "read more notes" work from #3234 which is an HTML-first approach.*
[ANW-2069](https://archivesspace.atlassian.net/browse/ANW-2069)
[ANW-2069]: https://archivesspace.atlassian.net/browse/ANW-2069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
=> ANW-2069: Fix search result filter "read more facets" feature

public/spec/features/more_facets_spec.rb
Running the individual spec associated with #3238 passed, but it failed in aggregate with the rest of the specs since the number of repos eventually grew beyond 5, causing the spec here to fail. This PR passes the buck by, instead of figuring out how to control the creation of facets, relies on the aggregate tests _not_ creating more than 5 Subject facets, just like the earlier reliance on the aggregate not creating more than 5 repository facets. The author of this PR needs more understanding of how facets get created in order to provide a more robust solution to this issue.
=> ANW-2069 Shift PUI More Facets negative assertion

frontend/app/views/shared/_pagination_summary.html.erb
This PR fixes the pagination summary "sort by" dropdown menus that appear at the top of search result tables. This is one of the last remaining fixes of the Softserv updates (#3090).
[ANW-1986](https://archivesspace.atlassian.net/browse/ANW-1986)
[ANW-1986]: https://archivesspace.atlassian.net/browse/ANW-1986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-1986: Fix the Softserv pagination summary dropdown menus

frontend/app/assets/stylesheets/archivesspace/largetree.scss, frontend/app/assets/stylesheets/bootstrap-overrides.scss, frontend/app/assets/stylesheets/vendor/glyphicons.scss, public/app/assets/javascripts/tree_renderer.js.erb, public/app/assets/stylesheets/application.scss, public/app/assets/stylesheets/archivesspace/aspace.scss, public/app/views/resources/infinite.html.erb
This PR lightly refactors the use of external Glyphicons that get imported at runtime via a network request, to depending on only local assets.
- In all of the public cases, Glyphicons were replaced with Font Awesome icons
- in the staff app, the external glyphicons.css file was copied locally, which imports the font binaries located at frontend/vendor/assets/fonts/
The Softserv updates upgraded Bootstrap from v3 to v4. v3 had a built in icon library (Glyphicons), which were deprecated in v4. Yet the v3 icons were still depended on via [an external source](https://github.com/archivesspace/archivesspace/blame/master/frontend/app/assets/stylesheets/bootstrap-overrides.scss#L3-L4) at run time.
This PR continues to "pass the buck" onto the future of not refactoring out the use of deprecated …
=> ANW-1997: Make all icons local

frontend/app/assets/javascripts/export_dropdown.js.erb
The Export dropdown menu with download buttons for EAD, MARC, MODS, etc, changed inadvertently with the Softserv upgrades. Whereas the download buttons could be clicked multiple times to initiate multiple downloads without page refresh, after Softserv the download action only happened on first click and not on any subsequent clicks.
The culprit may be some change in the markup? I'm not sure exactly, but this quick change solves the issue nicely.
[ANW-2046](https://archivesspace.atlassian.net/browse/ANW-2046)
[ANW-2046]: https://archivesspace.atlassian.net/browse/ANW-2046?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2046: Undo change to Staff "Export" dropdown download buttons

frontend/app/assets/stylesheets/vendor/glyphicons.scss
PR #3241 worked in development mode but not in production.
This is a WIP commit to be merged into master for the purposes of seeing if this unbreaks the icons on the test server.
=> ANW-2078: Unbreak Staff icons running in production

common/config/config-defaults.rb, public/app/assets/javascripts/resizable_sidebar.js, public/app/assets/stylesheets/archivesspace/aspace.scss, public/app/assets/stylesheets/archivesspace/infinite-scroll.scss, public/app/views/resources/infinite.html.erb, public/app/views/shared/_only_facets.html.erb, public/spec/features/collection_organization_spec.rb
This PR:
- Moves (only) the Collection Organization sidebar to the left of the content by default
- Provides a (backend) config option for showing the Collection Org sidebar on the right or left of the content
- Changes the DOM order of the sidebar and content, where now the sidebar comes first in the DOM regardless of the backend configuration via CSS, which benefits screen readers as mentioned in the User Survey feedback report
- Improves keyboard control of the resizable sidebar when it has focus according to the following rules:
- sidebar is increased when `Up` is pressed or `Right` when positioned on the left or `Left` when positioned on the right
- sidebar is decreased when `Down` is pressed or `Left` when positioned on the left or `Right` when positioned on the right
- Fixes a bug …
=> ANW-769: Allow PUI Collection Organization sidebar to be positioned to the left or right of content; display it to the left by default

public/app/assets/stylesheets/archivesspace/aspace.scss, public/app/assets/stylesheets/archivesspace/helpers.scss, public/app/views/resources/infinite.html.erb, public/app/views/resources/show.html.erb, public/app/views/shared/_record_innards.html.erb, public/spec/features/accessibility_spec.rb, public/spec/features/collection_organization_spec.rb
This PR moves a Resource's sidebar on the show/Collection Overview view to the left by default, following ANW-769 (#3254) which moved the sidebar for a Resource's infinite/Collection Organization view.
[ANW-2091](https://archivesspace.atlassian.net/browse/ANW-2091)
[ANW-2091]: https://archivesspace.atlassian.net/browse/ANW-2091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2091: Move Collection Overview sidebar to the left by default via config option

public/app/assets/javascripts/InfiniteRecords.js
An extra `'/'` was added to the infinite records waypoint URL during the [recent app proxy prefix work](https://github.com/archivesspace/archivesspace/commit/753ba2d17e5749e1a0b3c55696a123eb6bfa7002#diff-aaa915a88594ef3b73cbcf501c58d26cdde05fb8b93d500e398cf6479c1c93b8R166). However this did not break the PUI Collection Org infinite view from fetching waypoints both in local development and in production on the test server.
More recently on the test server fetching now throws an error and the PUI Collection Org loading spinner hangs ([see here for example](https://test.archivesspace.org/repositories/2/resources/32/collection_organization)), while local development still works as expected.
It may have something to do with the recent jruby updates (#3271).
This fix can be tested on the test …
=> ANW-2014: Remove InfiniteRecords waypoint url extra slash

public/app/views/objects/show.html.erb, public/spec/features/collection_organization_spec.rb
This PR moves the Collection Org sidebar to the left by (a configurable) default for the children of Resources and Digital Objects. This is a follow up from ANW-2091 (#3258) and ANW-769 (#3254), and completes the moving of the Collection Org sidebar.
[ANW-2099](https://archivesspace.atlassian.net/browse/ANW-2099)
[ANW-2099]: https://archivesspace.atlassian.net/browse/ANW-2099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2099: Move Collection Org sidebar for Archival Objs and Digital Obj Components

frontend/app/controllers/search_controller.rb, frontend/app/helpers/export_helper.rb, frontend/spec/helpers/export_helper_spec.rb
The "Found In" column in the search results table in the Staff UI is generated by the frontend, and unlike the other columns is not indexed so it doesn't show up in CSV exports. This is because the CSV export helper actually has to re-run the search in order to get the full results set (not just the currently displayed page), and is just given the field names displayed in the results table to include in the search. Since "context" is not an actual field in any record, it comes back blank.
I've added a class to the ExportHelper that mimics the way the "Found In" column results are constructed. Since the various fields that indicate the ancestors for different record types only provide URI refs, they need to be grabbed from the backend in order to get the actual title string. This …
=> ANW-1509 reproduce search "Found In" column in CSV exports

scripts/tasks/doc.thor
It seems that around v1.15.0 the git library client methods got changed up a bit and the log method now takes different arguments. This should hopefully restore the ability for the release process to automatically pull PRs for the release notes.
=> ANW-2074 update for git client lib log changes

public/app/assets/javascripts/InfiniteRecords.js, public/app/assets/javascripts/infiniteRecordsWorker.js, public/app/assets/stylesheets/archivesspace/infinite-records.scss, public/app/views/resources/_infinite_records.html.erb, public/config/environments/development.rb, public/config/locales/pt.yml, public/spec/features/collection_organization_spec.rb
This PR adds minor tweaks to the recent PR #3257:
- accounts for the proxy prefix when fetching from the web worker
- updates the loading spinner css
- updates the Portuguese translation file
- removes a console.log() debugger from the spec
=> ANW-1836: Add minor tweaks to load all records

frontend/app/views/archival_objects/_form_container.html.erb
This PR fixes a Softserv bug where the "Publish?" field label text not right-aligned when editing Archival Objects.
=> ANW-2041: Re-align archival object 'Publish' label text

frontend/app/controllers/top_containers_controller.rb
Jetty 10 apparently decided to start complaining about "empty segments" in URIs and returning 400 errors when they are encountered. It often happens that URIs end up with double slashes in them when being constructed via string interpolation, and this is one spot where that was happening. We'll need to be more careful about that going forward.
reference: https://github.com/jetty/jetty.project/commit/b4d7e5117db6bc4ef0cb7a16eab589b83dcf0e21
=> ANW-2122 fix empty path segment in top containers search

public/app/assets/stylesheets/archivesspace/bootstrap-overrides.scss, public/app/views/search/search_results.html.erb, public/app/views/shared/_cite_page_action.html.erb
This PR fixes a minor Softserv styling bug for the "New Search" and "Refine Search" buttons in the top banner of a keyword search result page.
[ANW-2125](https://archivesspace.atlassian.net/browse/ANW-2125)
[ANW-2125]: https://archivesspace.atlassian.net/browse/ANW-2125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2125 Fix public search statement buttons

frontend/app/views/location_profiles/edit.html.erb, frontend/app/views/location_profiles/new.html.erb, frontend/app/views/location_profiles/show.html.erb
This PR fixes minor Softserv bugs where the staff location profile badge was not properly resized, and multiple view layouts were misaligned.
[ANW-2126](https://archivesspace.atlassian.net/browse/ANW-2126)
[ANW-2126]: https://archivesspace.atlassian.net/browse/ANW-2126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2126 Fix location profile badge and layout issues

backend/app/model/location.rb
The location model is stored in a non-hierarchical fashion, with any
variation in field values resulting in a new database row. The only
required field is Building, so users can input locations that have only
a Building and a Room, among other permutations.
However, the location model's building_data method was organizing the
flat rows from the database into a hierarchy of building->floor->
room->area. If a floor did not have any rooms defined for it, it would
move on to the next location row, thus not allowing for rooms without
floors (same for areas without rooms).
Since all buildings have at least one floor, it would be ideal for the
location creation form to require the floor field as well. However,
as a free text field, this could result in some users entering "1" while
others enter …
=> ANW-2127 allow for lack of floor or room in a location's building data

frontend/app/views/agents/show.html.erb
This PR fixes a minor Softserv layout bug that misaligned the Agent Type label and value in the staff interface.
[ANW-2084](https://archivesspace.atlassian.net/browse/ANW-2084)
[ANW-2084]: https://archivesspace.atlassian.net/browse/ANW-2084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2084: Fix Agent Type label layout

frontend/app/assets/stylesheets/themes/default/default.scss, frontend/app/views/extent_calculator/_show_calculation.html.erb, frontend/app/views/jobs/_job_records.html.erb, frontend/app/views/linked_agents/_show.html.erb, frontend/app/views/search/_title_cell.html.erb, frontend/app/views/shared/_header_repository.html.erb, frontend/app/views/shared/_header_user.html.erb
This PR provides two commits:
- Fix the unpublished repo warning label by quick and dirty copying of Bootstrap styles instead of addressing the underlying order of SCSS imports in frontend/app/assets/stylesheets/archivesspace.scss, which awards higher specificity for frontend/app/assets/stylesheets/themes/default/default.scss over Bootstrap
- Remove a conventional `.dropdown-item` class on the select repo menu to remove unintentional padding and hover effect
[ANW-2149](https://archivesspace.atlassian.net/browse/ANW-2149)
All of Bootstrap's bade styles are overridden due to the problem listed above. This commit "fixes" the problem by copying more Bootstrap styles into default.scss, and updating the badge markup across multiple files.
The problems above stem from the fact that Softserv kept …
=> ANW-2149, ANW-2148: Fix frontend missing badge styles

public/app/assets/stylesheets/archivesspace/helpers.scss, public/app/assets/stylesheets/archivesspace/infinite-records.scss, public/app/views/resources/_infinite_load_all.html.erb, public/spec/features/collection_organization_spec.rb
This PR fixes the accessibility errors reported by Wave in the PUI load all records feature:
- color contrast violation
- multiple labels on an input
[ANW-2166](https://archivesspace.atlassian.net/browse/ANW-2166)
[ANW-2166]: https://archivesspace.atlassian.net/browse/ANW-2166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2166: Fix PUI load-all-records accessibility errors reported by Wave

frontend/app/views/bulk_archival_object_updater_job/_form.html.erb, frontend/spec/features/resources_spec.rb
This PR updates the bulk updater file input's design and behavior by making it consistent with the load via spreadsheet file input.
[ANW-2154](https://archivesspace.atlassian.net/browse/ANW-2154)
[ANW-2154]: https://archivesspace.atlassian.net/browse/ANW-2154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2154: Bring bulk updater file input component into parity with load via spreadsheet

frontend/app/views/file_versions/_file_uri.html.erb, public/app/assets/javascripts/ReadMoreNotes.js, public/app/assets/stylesheets/archivesspace/bootstrap-overrides.scss, public/app/assets/stylesheets/archivesspace/read-more-notes.scss, public/app/views/shared/_navigation.html.erb, public/app/views/shared/_note_content.html.erb, public/config/locales/de.yml, public/config/locales/en.yml, public/config/locales/es.yml, public/config/locales/fr.yml, public/config/locales/ja.yml, public/config/locales/pt.yml, public/spec/features/read_more_notes_spec.rb
[ANW-2168](https://archivesspace.atlassian.net/browse/ANW-2168)
This PR fixes some PUI accessibility errors reported in the following Wave report: https://app.pope.tech/organization/lyrasis/accessibility/f14898cf-9345-4c9b-aea1-69282315e524
This PR should solve all of the reported errors except the image-related† errors:
- Color contrast: solution is to override Bootstrap
- Empty button: solution is to add i18n text
- Form labels: solution is to adjust the markup
This PR also fixes a minor frontend Softserv layout bug
† The image-related errors are arbitrary and dependent on whether or not a caption is provided for a digital object's file version in the frontend.
[ANW-2168]: https://archivesspace.atlassian.net/browse/ANW-2168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
=> ANW-2168: Fix PUI accessibility errors

frontend/app/views/repositories/index.html.erb, frontend/spec/features/repositories_spec.rb
This PR conditionally shows the "Set Order in Public Interface" button in the Staff app when managing repositories if `AppConfig[:pui_repositories_sort] == :position`.
[ANW-2172](https://archivesspace.atlassian.net/browse/ANW-2172)
[ANW-2172]: https://archivesspace.atlassian.net/browse/ANW-2172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2172: Show the set repo order button conditionally according to `AppConfig[:pui_repositories_sort]`

frontend/app/views/accessions/_toolbar.html.erb, frontend/spec/features/accessions_spec.rb
This PR solves [ANW-2183](https://archivesspace.atlassian.net/browse/ANW-2183) by aligning the Accessions toolbar "More" dropdown menu to the right of the "More" button. Previously it was left-aligned, which would hide menu text off to the right of the viewport when the "More" button was the right-most button in the toolbar.
[ANW-2183]: https://archivesspace.atlassian.net/browse/ANW-2183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2183 Right-align accessions 'more' dropdown menu

frontend/app/views/digital_objects/_form_container.html.erb, frontend/app/views/digital_objects/_show_inline.html.erb, frontend/app/views/digital_objects/_sidebar.html.erb
This PR solves [ANW-2173](https://archivesspace.atlassian.net/browse/ANW-2173) by fixing the `id` of the Digital Object Notes section in both `show` and `edit` views, and the corresponding `sidebar` anchor link.
[ANW-2173]: https://archivesspace.atlassian.net/browse/ANW-2173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2173: Fix digital object notes id and anchor links

frontend/app/controllers/agents_controller.rb, frontend/spec/controllers/agents_controller_spec.rb
When an agent is merged into another one, it is deleted after its
information is added to the destination agent. As a result, any resource
or archival object would lose any role linked to that agent. This update
preserves those roles by re-linking them to the destination agent for
affected resources/AOs.
=> ANW-2064 preserve roles from merged agents

frontend/app/helpers/plugin_helper.rb, frontend/app/views/layouts/application.html.erb, public/app/views/layouts/application.html.erb, public/app/views/pdf/_archival_object.html.erb, public/app/views/pdf/_digital_object_links.html.erb, public/app/views/pdf/_header.html.erb, public/app/views/pdf/_resource.html.erb, public/app/views/pdf/_titlepage.html.erb, public/app/views/shared/_record_innards.html.erb, public/app/views/welcome/show.html.erb
- properly render plugin layouts inline for both staff and public frontends and public pdf exports
- allow plugins to add their own shared/templates equivalents - due to changes in `ActionView::PartialRenderer render` method
- fix public pdf locals for digital object links
Some plugin partials were not rendering inline properly. Additionally, changes to `ActionView::PartialRenderer` necessitated the inclusion of an additional plugin file (`frontend/views/_shared_templates.html.erb`) to allow plugins to add their own templates for the frontend.
Also fixes local variable for plugins which use a plugin supplied `_pdf_digital_object_links` partial
Local tests. Mac OS 14, MariaDB 10.11.4, Solr 8.11.2
=> Core Code Plugin Support - Changes for 4.0

public/app/views/shared/_favicon.html.erb
This PR is a follow up from #3331, it fixes the deprecation warning in the logs about the PUI favicons not being part of the asset pipeline:
```
[java] DEPRECATION WARNING: The asset "favicon-AS.png" is not present in the asset pipeline.
[java] Falling back to an asset that may be in the public folder.
[java] This behavior is deprecated and will be removed.
[java] To bypass the asset pipeline and preserve this behavior,
[java] use the `skip_pipeline: true` option.
```
See eg, this log from a CI run before this PR: https://github.com/archivesspace/archivesspace/actions/runs/11501086583/job/32012868739#step:8:184.
=> ANW-2157: Skip the asset pipeline for PUI favicon

frontend/app/views/linked_agents/_show.html.erb, frontend/app/views/users/edit_groups.html.erb
This PR fixes two similar bugs related to rendering tables in Safari:
- [ANW-2193](https://archivesspace.atlassian.net/browse/ANW-2193) reported "squished" columns in the Agent Links subform table in, ie: a Resource view page
- [ANW-2194](https://archivesspace.atlassian.net/browse/ANW-2194) reported "squished" columns in the user Edit Groups view
[ANW-2193]: https://archivesspace.atlassian.net/browse/ANW-2193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ANW-2194]: https://archivesspace.atlassian.net/browse/ANW-2194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2193, ANW-2194: Fix Safari rendering of table column widths for Agent Link subform and Edit Group page

backend/app/converters/converter.rb, backend/app/converters/location_converter.rb, backend/app/lib/job_runners/batch_import_runner.rb, backend/spec/lib_location_converter_spec.rb, common/locales/en.yml, common/schemas/import_job.rb, frontend/app/assets/javascripts/jobs.crud.js, frontend/app/views/jobs/_form.html.erb
Adds a checkbox to the location CSV importer that allows for the imported location(s) to be linked to the current repo.
Allows for locations to be imported with an associated repo from the start, rather than requiring additional steps after import.
https://archivesspace.atlassian.net/browse/ANW-2107
Some tests added to the backend test suite, as well as manually testing.  Happy to add additional tests based off the guidance/review of the dev team.
Adds the following checkbox:
=> ANW-2107 Allow owner repo to be imported via CSV

backend/app/exporters/serializers/ead.rb, backend/spec/export_ead_spec.rb
If the Description of a Revision Description note starts with `<`, the entire note will bypass the `<change>` wrapper when exported as EAD.  This makes sense if the leading XML is specifically `<change>` or `<list>` (the only two valid children of `<revisiondesc>`).  However, other XML tags are allowed in `change/item`; for example, `<change><item><name>Alex</name> revised this</item>[..]` is valid EAD.  The current exporter would just drop `<name>Alex</name> revised this` directly under `revisiondesc`, which makes the document invalid.
This PR makes the check for `<change>` and `<list>` in Revision Description more explicit, so other leading mixed content won't invalidate the document.
https://archivesspace.atlassian.net/browse/ANW-2015
I added a new unit test to the EAD specs to verify …
=> ANW-2015 export leading mixed content in revisiondesc

public/app/assets/stylesheets/archivesspace/infinite-records.scss
This PR adds to #3352 which fixes Wave-reported accessibility errors. This PR fixes the contrast error on the load-all-records feature's toggle switch. The error relates to the color of the toggle `<input>`'s hidden text used as an input label for screen readers but which is hidden visually. Instead of ignoring the error in Wave, let's just fix the error in the code.
=> ANW-2168 Change hidden text color for valid contrast

frontend/app/views/search/_representative_file_version_cell.html.erb, frontend/spec/features/representative_file_version_spec.rb
This PR fixes [ANW-1770](https://archivesspace.atlassian.net/browse/ANW-1770) which reports that the images in the Image Thumbnail column of the Staff Digital Object search listing table does not provide the image caption as `alt` text as happens in the PUI.
The accompanying spec is ignored due to the representative file version spec being a common flaky test in CI but not locally. The spec was unignored to test locally, which passed. The test was then re-ignored for this PR.
[ANW-1770]: https://archivesspace.atlassian.net/browse/ANW-1770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-1770: Add alt text to images in Digital Object search listing

frontend/app/views/bulk_archival_object_updater_job/_form.html.erb, frontend/spec/features/resources_spec.rb
This PR fixes [ANW-2154](https://archivesspace.atlassian.net/browse/ANW-2154) which [reports](https://archivesspace.atlassian.net/browse/ANW-2154?focusedCommentId=40857) that the Bulk AO Updater job can be submitted before a valid file has been selected for the job.
This PR disables the "Start Job" button until a valid file has been selected via the file input, which is consistent with the way the "Load via Spreadsheet" input works.
[ANW-2154]: https://archivesspace.atlassian.net/browse/ANW-2154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2154 Bulk AO Updater job disable submit button until valid file input

frontend/app/helpers/jobs_helper.rb, frontend/app/views/jobs/_job_records.html.erb
Treats locations the same as other repository-less resources like agents and subjects and does not display the external_repo warning on csv import.
Even though #3275 allowed locations to be imported with an "owner repo", location records still don't actually belong to/exist within any specific repo.  Whether or not they are linked to an owning repository, they still can be viewed by all authenticated users.  Even though the issue described in ANW-2206 predates #3275, this new functionality will make the bug more visible and confusing.  So I've addressed it here.
https://archivesspace.atlassian.net/browse/ANW-2206
I've taken a stab at adding e2e tests for this and I'll PR those separately to that repo.
ℹ️ PRed separately: https://github.com/archivesspace/e2e-tests/pull/21
=> ANW-2206 Do not show external repo warning for global records

frontend/app/helpers/aspace_form_helper.rb, frontend/app/views/accession_links/_accession_linker.html.erb, frontend/app/views/agents/_linker.html.erb, frontend/config/locales/de.yml, frontend/config/locales/en.yml, frontend/config/locales/es.yml, frontend/config/locales/fr.yml, frontend/config/locales/ja.yml, frontend/spec/features/resources_spec.rb, frontend/vendor/assets/javascripts/bootstrap-combobox.js, frontend/vendor/assets/javascripts/codemirror/codemirror.js
This PR is a step towards fixing [ANW-2169](https://archivesspace.atlassian.net/browse/ANW-2169) which reports frontend accessibility errors reported by Wave.
Fixing all of the errors gets into the territory of having to modify the old libraries we depend on like CodeMirror, the tooltips, etc. The same errors existed _before_ v4, so this PR stops short of a complete fix in favor of punting on the outstanding issues in favor of fixing more urgent v4 specific bugs to get the release out.
[ANW-2169]: https://archivesspace.atlassian.net/browse/ANW-2169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2169: Fix frontend accessibility errors reported by Wave

frontend/app/controllers/events_controller.rb, frontend/app/views/events/new.html.erb, frontend/spec/features/events_spec.rb
The previous change to fix the event +1 button causing a crash when
coming from the main menu Create->Event button was erroneously
redirecting to editing the newly created event; it should redirect to
a blank new event page.
This should be cleaned up now, and I've left copious comments
because this was frustratingly confusing to me and I'd like to spare
future developers from that.
=> ANW-2175 fix event +1 redirecting to edit new event

frontend/app/assets/stylesheets/archivesspace/form.scss, frontend/app/views/agents/_form.html.erb
This PR fixes [ANW-2215](https://archivesspace.atlassian.net/browse/ANW-2215) which reports on Softserv-related janky tooltips related to only some of the subform headings on the Agent form.
[ANW-2215]: https://archivesspace.atlassian.net/browse/ANW-2215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2215: Fix Agent form headings with janky tooltips

frontend/app/assets/javascripts/utils.js
This PR addresses [ANW-2162](https://archivesspace.atlassian.net/browse/ANW-2162) which observes extraneous "add-as-you-go" buttons, while in record edit mode, at the bottom of staff subforms with zero-to-many cardinality and with nested Note suberecords.
Note data structures are different than most other structures in that they can be a top-level structure or be nested inside other structures. The problem reported by ANW-2162 stems from a bug where Note subforms duplicate HTML `id`s (ie: `rights_statement_notes`) instead of incrementing them (ie: `resource_rights_statements__0__acts_`).
⚠️ This PR does not fix the underlying problem of duplicate Note ids, rather it hacks around the underlying issue in the interest of getting the next v4 release candidate out. ⚠️
Tests are forthcoming in …
=> ANW-2162: Filter out extra add-as-you-go buttons caused by the duplicate Note subform id bug

public/app/models/classification.rb, public/app/views/classifications/show.html.erb, public/spec/features/classifications_spec.rb
Display clickable hyperlinks in the Classifications Description field on PUI
https://archivesspace.atlassian.net/browse/ANW-1780
=> ANW-1780: Display hyperlinks in classification description on PUI

backend/app/model/date_calculator.rb, backend/spec/model_date_calculator_spec.rb
https://archivesspace.atlassian.net/browse/ANW-1799
=> ANW-1799: Modify date calculator to handle child OA

frontend/spec/features/add_as_you_go_spec.rb
This PR adds tests for the add-as-you-go feature across all record types, which is (unnecessarily) assembled wholly in JavaScript at run time instead of template markup at build time, and was not tested prior to this PR.
This PR is a follow up from the recent #3397 which fixed a problem related to the add-as-you-go feature but did not include any tests in favor of getting out a release candidate for v4.
=> ANW-2221: Add tests for the staff add-as-you-go javascript feature

frontend/app/assets/javascripts/utils.js, frontend/app/controllers/application_controller.rb, frontend/app/models/user.rb, frontend/config/initializers/session_store.rb, public/config/initializers/session_store.rb
Set secure when in production (requires https).
Set SameSite lax (Rails default from v6 and the browser default when not set).
Set httponly when not js consistently.
For js set cookies just follow the url protocol.
Before:
After:
=> Update aspace cookies

build/.bundle/.keep, build/build.xml
I noticed that the `v4.0.0-RC1` zip contains all the test and development gems (pry, rspec, ladle etc.). I think what happened is that after bundler was upgraded and the `--without` flag replaced with the newer `bundle config` statements, the gem group exclusions broke because in a case like this:
`bundle config set ...` 
Bundler assumes the working directory is the place to write the `config` file.
But then a command like: `bundle install --gemfile=../backend/Gemfile` causes Bundler to look for the config in `backend/.bundle`. Apparently Bundler does not look in parent directories when the config isn't there, so it ends up with nothing. 
This commit just sets the location of the config file to always be `build/.bundle`
I just did some manual testing to confirm that …
=> Ensure Gem Group Exclusion Works By Setting BUNDLE_APP_CONFIG

backend/app/converters/lib/marcxml_auth_agent_base_map.rb, backend/spec/lib_marcxml_auth_agent_converter_spec.rb
The problem is described in ANW-2113. The fix proposed in that issue is implemented. 
https://archivesspace.atlassian.net/browse/ANW-2113
I added a test to the spec file modified in this PR to verify that "09" will get treated as 2009 and not 1909. I verified that an existing test covered that "89" gets treated as 1989.
I verified that my new test failed before implementing the change. 
I worked in a development environment set up using [these instructions](https://docs.archivesspace.org/development/dev/#_top) and I ran the entire backend specs. There were no failures.
=> ANW-2113: Don't create pre-1970 authority record creation event_dates in authority maintenance events

.gitignore, build/build.xml
Noticed clean builds are failing since PR: https://github.com/archivesspace/archivesspace/pull/3422 (Docker latest is out of date). Also replicated with fresh clone of ASpace and `./scripts/build_release -t`.
I made the `:war` tasks uniformly consistent with `frontend:war` (because deleting the `dist` bundle cfg seems reasonable) and removed the failing copy ref in `frontend`, which appears ok (the bundler setup is pretty complex). Local fresh builds are working (tested both standard and Docker builds & also ran the dev servers).
=> Cleanup build dist bundle config

frontend/app/assets/javascripts/tree_toolbar.js.erb, frontend/app/assets/stylesheets/archivesspace/tree.scss, frontend/app/views/shared/_rde.html.erb
This PR fixes Softserv related bugs in the Staff reorder mode and RDE features:
- Fix reorder mode loading spinner
- Fix 'disable reorder mode' btn bg color
- Fix RDE 'fill column' nav tabs and various cancel btns
[ANW-2238](https://archivesspace.atlassian.net/browse/ANW-2238)
[ANW-2238]: https://archivesspace.atlassian.net/browse/ANW-2238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2238: Fix Softserv bugs in Staff reorder mode and RDE

frontend/app/assets/javascripts/utils.js, frontend/spec/features/help_tooltips_spec.rb
This PR fixes a Softserv-related bug where "help tooltips" attached to subrecord form headings in the Staff app, which remain visible if the heading is clicked (as opposed to disappearing from the user moving their mouse off of the heading), would have their number of close buttons incremented each time another heading's tooltip was shown by click.
The bug does not appear to have occurred as a result of the Softserv manual code changes, but rather merely by virtue of updating the underlying versions of jQuery and/or Bootstrap. It appears that earlier versions of jQuery and/or Bootstrap were more lenient than the versions introduced by the Softserv upgrades in allowing the tooltip object's `tip` key to be accessed via `$tip` 🤦🏼
=> ANW-2215 Fix Softserv help tooltip multi close button bug

frontend/app/assets/stylesheets/bootstrap-overrides.scss
This PR fixes a minor Softserv-related bug when a combobox item was selected and the dropdown button did not show the `⨉`, to represent "clear selection".
[ANW-2241](https://archivesspace.atlassian.net/browse/ANW-2241)
[ANW-2241]: https://archivesspace.atlassian.net/browse/ANW-2241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2241: Fix Sofstserv combobox dropdown button's 'clear selection' state

frontend/app/views/enumerations/_list.html.erb, frontend/spec/controllers/enumerations_controller_spec.rb
This reverts commit 204c48109a994c6a99ef743b2c6d0abf5197b712.
The commit was submitted in [PR 301](https://github.com/archivesspace/archivesspace/pull/301)
There was no explanation other than supporting I18n keys
with '.' in the string. I could find no examples with a '.'
in the key in any of the enumerations in the ArchivesSpace
repository, and this alternate way of calling `translate`
appears not to work in current versions of I18n. So while
previous versions of ArchivesSpace do show translated values
correctly in the controlled value list table, v4.0.0-RC1 does
not. 
Translated labels are not appearing on Controlled Value List table in 
v4.0.0.-RC1
See first commit in this PR, which includes a new Rails controller test for the `EnumerationsController`
=> Fixing controlled value lists translation column

frontend/app/assets/stylesheets/archivesspace/common.scss, frontend/app/views/enumerations/_list.html.erb
This PR adjusts the enumerations, or the "controlled value list", table formatting, including:
- Improve column widths
- Improve the positions column content layout
- Make each row's action button group border color consistent with the border on the edit record toolbar
=> ANW-2248: Adjust enumerations table formatting

frontend/app/views/classifications/_form_container.html.erb
This PR fixes the duplicate "too many records alert" for the record links linker, when there are more than 4 links, on the Classifications form. This bug was found when reviewing #3471.
[ANW-2272](https://archivesspace.atlassian.net/browse/ANW-2272)
[ANW-2272]: https://archivesspace.atlassian.net/browse/ANW-2272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2272: Fix duplicate too-many-records alert for the record link linker on the Classifications form

frontend/app/controllers/preferences_controller.rb, frontend/config/locales/de.yml, frontend/config/locales/en.yml, frontend/config/locales/es.yml, frontend/config/locales/fr.yml, frontend/config/locales/ja.yml, frontend/spec/controllers/preferences_controller_spec.rb
Fix error when accessing preferences page on Staff UI when there is no repository
https://archivesspace.atlassian.net/browse/ANW-1351
Before
After
=> ANW-1351: Handle error on preference page without a repository

public/config/locales/de.yml, public/config/locales/en.yml, public/config/locales/es.yml, public/config/locales/fr.yml, public/config/locales/ja.yml
As seen on the mailing list last week, this enum throws an error in search results like this one https://test.archivesspace.org/search?utf8=%E2%9C%93&op%5B%5D=&q%5B%5D=books&limit=&field%5B%5D=&from_year%5B%5D=&to_year%5B%5D=&commit=Search
=> fixes missing enum instance_type_enum_s on highlighting

public/app/assets/javascripts/InfiniteRecords.js, public/app/assets/javascripts/InfiniteTree.js, public/app/assets/javascripts/InfiniteTreeFetch.js, public/app/assets/javascripts/InfiniteTreeMarkup.js, public/app/assets/javascripts/MixedContent.js, public/app/assets/stylesheets/archivesspace/infinite-tree.scss, public/app/views/resources/infinite.html.erb, public/app/views/shared/_infinite_tree.html.erb, public/spec/aspace_helper.rb, public/spec/features/collection_organization_spec.rb, public/spec/rails_helper.rb
This PR fixes a bug in the PUI "Collection Organization" page where collapsing a parent in the `InfiniteTree` only hid the first "waypoint" of children and left any remaining waypoints of children showing in the tree. The solution here is to rewrite the underlying HTML and CSS layers of the tree. An [earlier PR for this ticket](#3469) did not fully solve the bug.
Writing more JavaScript to hide all children was chosen against due to a [broader development goal](https://archivesspace.atlassian.net/browse/ANW-2251) of refactoring the `largetree` for drag-and-drop purposes and more, including rewriting the tree's underlying HTML and CSS.
While [ANW-425](#3014) introduced InfiniteTree.js, which replaced the `largetree` used in the PUI resources `infinite` view, its structure mimicked the …
=> ANW-2259: Refactor InfiniteTree HTML and CSS layers

public/app/assets/stylesheets/archivesspace/aspace.scss, public/app/views/shared/_idbadge.html.erb, public/app/views/subjects/_terms.html.erb, public/app/views/subjects/show.html.erb, public/spec/features/idbadge_spec.rb
This PR solves a regression bug in v4.0.0 that, in the PUI, did not show text in record titles wrapped in mixed content `<title>` tags. This bug did not exist in v3.5.1. I'm not sure where the break happened, the files changed herein were the first I checked and it appears to be fixed, even though the file bits hadn't been updated in 3+ years. Possibly related to recent mixed content work, or softserv?
[ANW-2316](https://archivesspace.atlassian.net/browse/ANW-2316)
[ANW-2316]: https://archivesspace.atlassian.net/browse/ANW-2316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2316: Handle mixed content in titles especially the title tag

public/vendor/assets/stylesheets/font-awesome/scss/_variables.scss
This PR is attempting to fix a problem where the PUI Font Awesome font assets are not being found when the app has a url prefix.
[ANW-2333](https://archivesspace.atlassian.net/browse/ANW-2333)
[ANW-2333]: https://archivesspace.atlassian.net/browse/ANW-2333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2333 Adjust PUI font-awesome path for url prefix

indexer/app/lib/indexer_common.rb, solr/schema.xml
Many moons ago there was a PR which introduced some PUI functionality which apparently depended or was thought to depend on being able to sort a record's related agents by their role.
https://github.com/archivesspace/archivesspace/pull/429 None of this appears to be in use or ever to have been in use in the public app, but the indexer is still creating dynamic fields with keys like:
_agents_corporate_entities_102_relator_sort
_agents_corporate_entities_103_relator_sort
_agents_corporate_entities_104_relator_sort
In fact, for an instance with 1000 agent records - each appearing in at least 1 related_agents relationship - the Solr schema will contain 1000 of these unused, unnecessary fields in the dynamic schema. (Try it by looking at the "Schema" pane in the Solr admin panel after indexing …
=> Remove Dynamic _relator_sort Fields from Solr Schema

public/app/assets/stylesheets/application.scss, public/app/assets/stylesheets/archivesspace/print.scss, public/app/views/resources/_infinite_load_all.html.erb, public/app/views/resources/infinite.html.erb, public/app/views/shared/_children_tree.html.erb, public/app/views/shared/_note_content.html.erb
This PR is a holdover from the Softserv updates and brings the PUI print styles inline with the new v4 environment.
This PR also adds back the missing fixed-height for the `largetree`.
[ANW-2349](https://archivesspace.atlassian.net/browse/ANW-2349)
[ANW-2349]: https://archivesspace.atlassian.net/browse/ANW-2349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2349: Update PUI print styles for the Softserv updates

frontend/app/assets/stylesheets/archivesspace/print.scss, frontend/app/views/shared/_largetree.html.erb
This PR improves the frontend app's print styles, paying particular attention to Accessions, but improving most if not all record types. This change was a holdover from the softserv updates.
[ANW-2336](https://archivesspace.atlassian.net/browse/ANW-2336)
[ANW-2336]: https://archivesspace.atlassian.net/browse/ANW-2336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2336: Improve frontend print styles

common/locales/en.yml, common/locales/es.yml
This help text "e.g." reads more like a suggestion when it's actually required to be exactly that format. I think this change makes that more clear.
=> changes user_defined date help wording

public/app/views/pdf/_resource.html.erb, public/app/views/pdf/_toc.html.erb, public/config/locales/de.yml, public/config/locales/en.yml, public/config/locales/es.yml, public/config/locales/fr.yml, public/config/locales/ja.yml, public/config/locales/pt.yml
This PR adds any existing bibliography notes that a resource might have to the to the pdf generated by the PUI.
[ANW-2334](https://archivesspace.atlassian.net/browse/ANW-2334)
Here are 2 relevant pages exported from https://test.archivesspace.org/repositories/2/resources/32:
[ANW-2334]: https://archivesspace.atlassian.net/browse/ANW-2334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2334: Add bibliography notes to PUI pdf generation

frontend/app/views/shared/_templates.html.erb, frontend/config/locales/de.yml, frontend/config/locales/es.yml
There are a few places where it looks like a find and replace for "target" (or equivalent) incorrectly replaced that word with the new merge terminology. I did not see this in the Japanese yml (someone may need to check) and had previously corrected the French one.
https://archivesspace.atlassian.net/browse/ANW-2361
=> ANW-2361 - Put back intended uses of the word "target"

public/app/views/shared/_modal_actions.html.erb, public/app/views/shared/_request_page_action.html.erb, public/spec/features/request_spec.rb
This PR fixes [ANW-1844](https://archivesspace.atlassian.net/browse/ANW-1844) by not adding the PUI request modal to the DOM when `AppConfig[:pui_page_actions_request]` is `false`.
The following screenshot shows that the "Request" button is not present in the toolbar towards the top of the page. It also shows the browser dev tools confirming that `#request_modal`, the CSS selector for the modal element containing the request form, is not present in the DOM.
[ANW-1844]: https://archivesspace.atlassian.net/browse/ANW-1844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-1844: Render request modal conditionally based on `pui_page_actions_request`

frontend/app/views/agents/_form_required.html.erb, frontend/app/views/shared/_required_subrecord_form.html.erb
This PR adds appropriate `for` attributes to `<label>`s in the shared agent required subforms. It also fixes Softserv-related layout bugs for subform headings and label+checkbox alignment.
[ANW-2355](https://archivesspace.atlassian.net/browse/ANW-2355)
[ANW-2355]: https://archivesspace.atlassian.net/browse/ANW-2355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2355 Fix agents required forms

frontend/app/views/agents/_form_required.html.erb, frontend/app/views/agents/_required_sidebar.html.erb, frontend/app/views/agents/required.html.erb, frontend/app/views/shared/_required_subrecord_form.html.erb
This PR fixes a bug (going back to at least v3.5.1) where lightmode didn't work when editing Agent Required Fields.
[ANW-2363](https://archivesspace.atlassian.net/browse/ANW-2363)
The spec is forthcoming and will be included with the PR for [ANW-2366](https://archivesspace.atlassian.net/browse/ANW-2366) which will focus on the sidebar structure and will finalize the subforms that show/hide for lightmode.
[ANW-2363]: https://archivesspace.atlassian.net/browse/ANW-2363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ANW-2366]: https://archivesspace.atlassian.net/browse/ANW-2366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2363: Enable lightmode on Agent Required Fields form

frontend/app/controllers/application_controller.rb, frontend/app/helpers/plugin_helper.rb, frontend/app/views/layouts/application.html.erb, public/app/controllers/application_controller.rb, public/app/helpers/view_helper.rb, public/app/views/layouts/application.html.erb, public/app/views/pdf/_archival_object.html.erb, public/app/views/pdf/_digital_object_links.html.erb, public/app/views/pdf/_header.html.erb, public/app/views/pdf/_resource.html.erb, public/app/views/pdf/_titlepage.html.erb, public/app/views/shared/_record_innards.html.erb, public/app/views/welcome/show.html.erb
- adds new helper methods for frontend and public
- adds plugin base directory to Rails view path(s)
- changes `render :inline` to `render :template` for plugin partials
As discovered by @marktriggs, the `render :inline` used in the initial release of ArchivesSpace 4.0 creates a memory leak for instances that are running plugins with specific partials.
See #3508 for full explanation, discussion, and resolution
Local testing. Mac OS 15, mariadb, solr 9.8.0 and local containerized dev environment. Tested with local (not public) custom plugins and the following public plugins
- https://github.com/dartmouth-dltg/local_contexts_projects
- https://github.com/dartmouth-dltg/aspace_content_warnings
- https://github.com/dartmouth-dltg/aspace_custom_restrictions_and_context
- …
=> Fixes Plugin Partial Render Memory Leak

frontend/app/views/agents/_form_required.html.erb, frontend/app/views/agents/_required_sidebar.html.erb, frontend/spec/features/agents_required_fields_spec.rb
This PR fixes a long standing bug where the Agent Required Fields forms were inconsistent with their Agent forms counterpart with respect to the page's sidebar and sub forms:
- updates the required fields sidebar to look just like their agent form counterpart with regard to sidebar items present and visual hierarchy
- updates subforms to match the subforms had by their agent counterpart
⚠️⚠️ This PR keeps the status quo of the Agent Required Fields form NOT providing a "Notes" or "Related Agent" section, due to possible unsolved implementations of making notes and/or related agents required. ⚠️⚠️
[ANW-2366](https://archivesspace.atlassian.net/browse/ANW-2366)
[ANW-2366]: https://archivesspace.atlassian.net/browse/ANW-2366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …
=> ANW-2366 Make Agent Required Fields form consistent with their counterpart Agent form

frontend/app/assets/javascripts/linker.js, frontend/app/assets/stylesheets/archivesspace/tables.scss, frontend/app/helpers/application_helper.rb, frontend/app/views/accessions/show.html.erb, frontend/app/views/assessments/_assessment_records_cell.html.erb, frontend/app/views/classification_terms/_show_inline.html.erb, frontend/app/views/classifications/_show_inline.html.erb, frontend/app/views/digital_object_components/_show_inline.html.erb, frontend/app/views/digital_objects/_show_inline.html.erb, frontend/app/views/instances/_show.html.erb, frontend/app/views/shared/_templates.html.erb, frontend/app/views/terms/_show.html.erb, frontend/spec/features/mixed_content_in_title_fields_spec.rb, public/app/assets/stylesheets/archivesspace/aspace.scss
This PR finalizes [ANW-2353](https://archivesspace.atlassian.net/browse/ANW-2353) by fixing more bugs related to displaying titles that contain EAD mixed content, and adds a spec to cover all of the recent work relating to this ticket (see #3534, #3509).
[ANW-2353]: https://archivesspace.atlassian.net/browse/ANW-2353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2353: Fix more mixed content display bugs and add spec

frontend/app/views/accessions/_toolbar.html.erb, frontend/app/views/agents/_merge_dropdown.html.erb, frontend/app/views/agents/_toolbar.html.erb, frontend/app/views/classifications/_toolbar.html.erb, frontend/app/views/shared/_component_toolbar.html.erb, frontend/app/views/shared/_merge_dropdown.html.erb, frontend/app/views/shared/_resource_toolbar.html.erb, frontend/app/views/shared/_templates.html.erb, frontend/app/views/subjects/_toolbar.html.erb, frontend/spec/features/mixed_content_in_title_fields_spec.rb
This PR continues to fix display of mixed content in title fields across record types on the frontend, including:
- toolbar merge dropdowns
- toolbar Delete button modals
[ANW-2353](https://archivesspace.atlassian.net/browse/ANW-2353)
[ANW-2353]: https://archivesspace.atlassian.net/browse/ANW-2353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2353 Fix mixed content display in toolbars across record types

frontend/app/helpers/aspace_form_helper.rb
Required fields for the agent form were originally implemented by appending the string "_REQ" to values in the form and somehow tracking required fields that way. It was refactored a while back, but it looks like some code stuck around in the form helper. See: https://github.com/archivesspace/archivesspace/pull/2703
=> Remove stranded code from old required field system.

frontend/app/views/shared/_required_subrecord_form.html.erb, frontend/spec/features/agents_required_fields_spec.rb
This PR fixes an erroneously hardcoded `for` attribute in a partial used for many `<label>`s in the Agent Required Fields forms. This bug caused many mismatches between checkbox `id` values and their related `<label>`'s `for` attribute which should match.
[ANW-2355](https://archivesspace.atlassian.net/browse/ANW-2355)
[ANW-2355]: https://archivesspace.atlassian.net/browse/ANW-2355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-2355: Fix label `for` attributes in Agent required fields forms

frontend/app/assets/javascripts/tree_renderers.js.erb, frontend/app/assets/stylesheets/archivesspace/largetree.scss, frontend/spec/features/reorder_mode_spec.rb
This PR solves [ANW-1998](https://archivesspace.atlassian.net/browse/ANW-1998) by making the Classifications Reorder Mode tree visually consistent with that of Digital Objects and Resources.
This PR closes #3546 
[ANW-1998]: https://archivesspace.atlassian.net/browse/ANW-1998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ANW-1998: Make Classifications Reorder Mode consistent with others

common/schemas/archival_object.rb, common/schemas/resource.rb, frontend/app/controllers/archival_objects_controller.rb, frontend/app/controllers/resources_controller.rb
Updates controllers to spawn the new record with the default title or an empty title in the titles list, which will cause the subrecord form to show an empty title subrecord. Also updated titles list in the schema to match other fields by overriding the abstract schema and specifying a minimum of 1 item, though this did not fix the problem on its own.
=> ANW-2392 ensure empty title subrecord appears on new record

backend/app/controllers/merge_request.rb, common/schemas/revision_statement.rb
Revision Statements appear to be basic subrecords like extents, dates, etc. It appears that 'uri' was added to the json schema in error. This causes an obscure bug where if a job creates a revision statement, it will try to register it as a top-level record and will error when trying to display the list of job-created records.
=> Delete URI from Revision Statement Schema

public/app/assets/javascripts/InfiniteCoordinator.js, public/app/assets/javascripts/InfiniteRecords.js, public/app/assets/javascripts/InfiniteTree.js, public/app/views/resources/infinite.html.erb, public/spec/features/collection_organization_coordinator_spec.rb
This PR is related to the larger #3490 which is concerned with improving the way finding in the PUI Collection Organization's tree sidebar.
This PR adds a feature/fixes a bug where, when there is a "tree node" whose "batch" has not yet been fetched (it's not yet in the DOM), and who matches the "current record" (the top-most record viewable in the scrollable records container), then the tree node will be shown as the "current node" when its batch is fetched (either when its parent is expanded for the first time, or via the tree's `batchObserver`).
Before this PR, the current node wouldn't show up in a newly fetched batch until the user started to scroll the records container.
The solution here implements an `InfiniteCoordinator` class that sits above the `InfiniteTree` and …
=> ANW-2412 Show the current `InfiniteTree` node when its batch is initially rendered

frontend/app/assets/javascripts/notes.crud.js.erb, frontend/app/assets/javascripts/utils.js, frontend/app/views/notes/_template.html.erb, frontend/app/views/shared/_templates.html.erb, frontend/spec/features/notes_spec.rb
This PR fixes a bug where note summaries containing mixed content were not being handled properly. The readonly summaries are present in both show and edit views.
The fix here is a bit different than most mixed content fixes. In particular the edit view creates a "truncated note summary" at run time via JS code and the outdated JS templating system. This solution adds a global helper for escaping HTML to the `AS` utility object, which the template can then use. This helper was essentially copied from the [bootstrap-select.js plugin's code](https://github.com/archivesspace/archivesspace/blob/0ff3a67c323450766360d8840f0deb3c3edca0d5/frontend/vendor/assets/javascripts/bootstrap-select.js#L176-L192) which provides a similar helper.
In the case of the show view, where the notes are shown in …
=> ANW-2417: Fix staff readonly display of notes with mixed content

frontend/spec/features/enumeration_management_spec.rb, frontend/spec/features/trees_spec.rb
The frontend feature specs trees_spec.rb and enumeration_management_spec.rb have been particularly flaky of late.
This PR fixes the enumeration spec by refactoring the entire test to prefer `let`s over instance vars, changing how the repo is set, preferring `before(:each)` over `before(:all)`.
This PR "fixes" the trees_spec by adding `wait_for_ajax` to some key moments.
=> Fix the flaky enumerations_spec and "fix" the flaky trees_spec

frontend/app/assets/stylesheets/archivesspace/tables.scss
This PR fixes a layout bug in the Safari browser where, when viewing a table like the resources index view, the table scrolled horizontally outside of the page container. Switching from `width: max-content` to `width: fit-content` works cross browser as expected.
=> Fix frontend Safari table column horizontal scroll bug

indexer/app/lib/indexer_common.rb, solr/solrconfig.xml
Hi there,
We at Hudson Molonglo have been working with Mary Kidd at Yale and @Blake- to troubleshoot some issues around indexing performance.
We ended up discovering a performance issue with deletes.  There's more detail below (and in the comments of the commit), but the gist is that deletes are applied during the commit process, and when they take a long time they lock out everyone else who is trying to write to the Solr index.  When large numbers of deletes are happening (for example, when the PUI indexer is working through a large tree), all other index update activity ends up stalled waiting for the commit to finish.
This commit ensures that deletes are applied somewhat regularly, and also rewrites the delete queries to be around 500x faster.
------------------------------
Solr stores …
=> Optimize handling of deletes against Solr

indexer/app/lib/index_state.rb, indexer/app/lib/index_state_s3.rb, indexer/app/lib/pui_indexer.rb, indexer/spec/index_state_spec.rb
- adds a `state_type` argument to the indexer state management
- this separates the indexer state of trees and the standard objects to prevent PUI indexer misses in some cases
Essentially, the PUI indexer runs two types of indexes per index round - a standard object index and a tree index. The two currently share the state files that flag whether a round is complete and provide the timestamp by which to request new/changed objects.
What can happen is that a race condition develops when an index round is running and another set of objects is changed. That second set of objects will get picked up by the tree index round, and the tree indices associated with those objects will be updated, but the standard indices will not because the tree index round will update the state files with a …
=> Indexer State files for Trees

frontend/app/views/resources/_toolbar.html.erb, frontend/spec/features/resources_spec.rb
This PR fixes a Softserv-related bug that hardcoded the value for the `include-unpublished` search param in the URL that generates the PDF for a Resource in the frontend app via the record toolbar's "Export" dropdown menu. The search param value was harcoded to "false", which meant that, on page load, unpublished children would not be included in the PDF, regardless of the user's repository preferences settings. (The correct behavior was forced by JS once the user started to check/uncheck the "include unpublished" checkbox in the toolbar's dropdown menu after page load.)
The URL should change accordingly on page load based on the user's repository preferences ("Include Unpublished Records in Exports?"), as well as by toggling the "include unpublished" checkbox that appears when the …
=> ANW-2365: Fix the hardcoded `include-unpublished` search parameter in the url that generates a pdf for a resource in the frontend

public/app/views/pdf/_archival_object.html.erb, public/spec/models/finding_aid_pdf_spec.rb
The code assumed that Indicator doesn't contain semicolon and thus it was just splitting a `:`. This diff makes sure that pdf  export will preserve top container tiles containing semicolon
https://archivesspace.atlassian.net/browse/ANW-2217
=> ANW-2217: pdf export preserve top container tile containing semicolon

build/build.xml, frontend/app/assets/javascripts/representativemembers.js, frontend/app/views/linked_agents/_template.html.erb, frontend/spec/factories.rb, frontend/spec/features/accessions_spec.rb, frontend/spec/features/archival_objects_spec.rb, frontend/spec/features/digital_objects_spec.rb, frontend/spec/features/events_spec.rb, frontend/spec/features/resources_spec.rb, frontend/spec/rails_helper.rb, frontend/spec/shared/linked_agents_is_primary_examples.rb
[ANW-1874](https://archivesspace.atlassian.net/browse/ANW-1874) was originally reported based on seeing multiple linked agents under the Rights Statement subform on an Accession record being marked as primary after a save attempts was made on an invalid Accession form.
Work on this PR uncovered an additional bug that marking a Rights Statement linked agent as "primary" did not "stick", meaning, the record wasn't actually saved with `is_primary` set to true for the given Rights Statement linked agent.
The PRs related to [ANW-504](https://archivesspace.atlassian.net/browse/ANW-504) introduced the feature of allowing a linked agent to be marked as primary. But this was only intended for Accessions, Resources and AOs, Digital Objects and DOCs. However, the same agent linker was used for all …
=> ANW-1874: Constrain the use of `is_primary` for top-level linked agents to Accessions and abstract Archival Objects only
